UID = "A78B9534"
Name = "92F29531"
TriggerScript = """
setCamera.1000
label.1
say.<По неизвестной причине книга о {4*Занзаре}, которую ты читала, теперь парит в воздухе...>.1
choice.2.<Прочесть>
choice.0.<Уйти>
waitForUser
label.2
playAnimation.14.-1
say.<...Возможно, ты просто заснула и не заметила этого?>.3
choice.4.<Выбор главы>
choice.3.<Назад>
waitForUser
label.3
goto.1
label.4
say.<Выбери необходимую главу.>.3
choice.7.<
    Глава 1.
    {4*История Занзары}
>
choice.46.<
    Глава 3.
    {4*Конец истории}
>
choice.1000.<Не нажимай это!>
choice.5.<Назад>
waitForUser
label.5
goto.2
label.46
ifPlayerHasCards.1.0.113
setTalkLabels.47.48.1
talk.<
    Ты уверена, что хочешь закончить своё путешествие?
    (Ты можешь вернуться к нему в любой момент, начав с того места, где остановилась в предыдущий раз.)
>
waitForUser
endIf
setTalkLabels.-1.-1.0
talk.<Ты открываешь книгу на указанной странице, но все они абсолютно пустые.>
waitForUser
goto.4
label.48
goto.4
label.7
say.<Страницы книги могут рассказать больше о {4*мире Занзары}.>.3
choice.11.<
    1.
    {4*Тайный Мир}
>
choice.10.<
    2.
    {4*Карта Природы}
>
choice.9.<
    3.
    {4*Царство Облаков}
>
choice.8.<Далее>
waitForUser
label.8
say.<Страницы книги могут рассказать больше о {4*мире Занзары}.>.3
choice.14.<
    4.
    {4*Карта Воздуха}
>
choice.13.<
    5.
    {4*Страж}
>
choice.12.<Назад>
waitForUser
label.12
goto.4
label.11
playVideo.1
waitForUser
goto.7
label.10
playVideo.2
waitForUser
goto.7
label.9
playVideo.5
waitForUser
goto.7
label.14
playVideo.3
waitForUser
goto.8
label.13
playVideo.4
waitForUser
goto.8
label.2
goto.0
label.0
playAnimation.0.-1
exit
label.47
playVideo.6
endGame
label.1000
setNpcModifier.2401.42.1
setNpcModifier.2420.9.1
setNpcModifier.2420.16.1
setNpcModifier.2420.18.1
setNpcModifier.0210.46.1
setNpcModifier.0231.55.1
setNpcModifier.0231.28.1
setNpcModifier.1243.37.1
setNpcModifier.1243.38.1
setNpcModifier.1243.24.1
setNpcModifier.1244.85.1
setNpcModifier.1244.84.1
setNpcModifier.1244.88.1
setNpcModifier.1244.63.1
setNpcModifier.3450.7.1
setNpcModifier.3455.32.1
setNpcModifier.3455.21.1
setNpcModifier.3454.18.1
setNpcModifier.2610.39.1
setNpcModifier.1422.67.1
setNpcModifier.1432.52.1
setNpcModifier.1432.45.1
setNpcModifier.1432.43.1
setNpcModifier.1413.17.1
setNpcModifier.1401.18.1
setNpcModifier.1402.24.1
setNpcModifier.1404.46.1
setNpcModifier.2223.70.1
setNpcModifier.1223.81.1
setNpcModifier.1031.25.1
setNpcModifier.1031.26.1
setNpcModifier.1032.51.1
setNpcModifier.1032.52.1
setNpcModifier.1050.58.1
setNpcModifier.1050.49.1
setNpcModifier.1050.65.1
setNpcModifier.1050.66.1
setNpcModifier.1050.68.1
setNpcModifier.1410.12.1
setNpcModifier.1060.59.1
setNpcModifier.1060.60.1
setNpcModifier.1060.61.1
setNpcModifier.0203.58.1
setNpcModifier.0203.59.1
setNpcModifier.0203.60.1
setNpcModifier.0203.61.1
setNpcModifier.0203.62.1
setNpcModifier.0840.86.1
setNpcModifier.0840.87.1
setNpcModifier.0830.63.1
setNpcModifier.0623.48.1
setNpcModifier.3406.41.1
setNpcModifier.3406.46.1
setNpcModifier.3406.49.1
exit"""
InitScript = """
setNpcType.4
setModel.i001si01"""
UpdateScript = "lookAtPlayer.0.0"
