UID = "A78B9534"
Name = "92F29531"
TriggerScript = """
beginIf_global.1.1
say.<First time talking>.0
setGlobal.1.2
waitForUser
exit
endIf
beginIf_global.1.2
say.<Second time talking>.0
setGlobal.1.3
waitForUser
exit
endIf
beginIf_global.1.3
say.<Third time talking>.0
setGlobal.1.3
waitForUser
exit
endIf
say.<Last time talking>.0
waitForUser
InitScript = """
setNpcType.4
setModel.i001si01
setGlobal.1.1"""
UpdateScript = "lookAtPlayer.0.0"
