UID = "9023B1A4"
Name = "79110B91"
#Tadana (4), Nils (25), Goops (48)
#From 19 to 16
InitScript = """
setNpcType.3
gotoRandomLabel.15.0
label.0
defaultWizForm.8.0.20
goto.15
label.1
defaultWizForm.21.0.20
goto.15
label.2
defaultWizForm.23.0.20
goto.15
label.3
defaultWizForm.8.0.19
goto.15
label.4
defaultWizForm.21.0.19
goto.15
label.5
defaultWizForm.23.0.19
goto.15
label.6
defaultWizForm.8.0.18
goto.15
label.7
defaultWizForm.21.0.18
goto.15
label.8
defaultWizForm.23.0.18
goto.15
label.9
defaultWizForm.8.0.17
goto.15
label.10
defaultWizForm.21.0.17
goto.15
label.11
defaultWizForm.23.0.17
goto.15
label.12
defaultWizForm.8.0.16
goto.15
label.13
defaultWizForm.21.0.16
goto.15
label.14
defaultWizForm.23.0.16
goto.15
label.15"""
