UID = "5AC06084"
Name = "3FB16991"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Что ты забыла здесь, человеческое отродье?>.0
waitForUser
ifPlayerHasCards.1.0.208
goto.0
else
setTalkLabels.-1.-1.0
talk.<
    Я не знаю, кто позволил тебе попасть в этот мир, женщина, и поэтому я советую тебе убраться в ту вонючую дыру, откуда ты вылезла, вместе со всеми {4*Тёмными Эльфами}. 
	Это было величайшей ошибкой позволить людям настолько долго влачить своё жалкое существование в {4*Занзаре}, будто бы паразитам, отравляющим всё живое вокруг себя.
	И, теперь, кто-то хочет повторить эту ошибку снова.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Никто не хочет иметь дел с твоим мерзким человеческим миром, и мы терпим твоё присутствие только из-за нашего глубокого великодушия. 
	Как только мы сотрём все следы существования {4*Тёмных Эльфов} с этой земли, мы наконец восстановим изначальный порядок. 
	Убирайся с моих глаз, ведьма, ты уже натворила достаточно зла, посмев явиться в нашу {4*Занзару}!
>
waitForUser
exit
label.0
say.<Хорошо, я сделаю исключение, и из жалости потерплю твоё присутствие немного дольше.>.3
choice.4.<Диалог>
choice.2.<Торговля>
choice.1.<До встречи>
waitForUser
label.4
setTalkLabels.-1.-1.0
talk.<
	Я могу тебе предложить базовые атакующие заклинания любой стихии, - если ты, конечно, знаешь, зачем они вовсе нужны. 
	Не думаю, что они способны сделать из тебя что-то лучшее, чем убогую тень {4*Коллекционера}; но, может, так ты быстрее поймёшь, что тебе нечего делать в нашем мире.
>
waitForUser
goto.0
label.2
setupGambling.1.1.0
setupGambling.1.1.5
setupGambling.1.1.10
setupGambling.1.1.15
setupGambling.1.1.20
setupGambling.1.1.25
setupGambling.1.1.30
setupGambling.1.1.35
setupGambling.1.1.40
setupGambling.1.1.45
setupGambling.1.1.50
setupGambling.1.1.55
waitForUser
goto.1
label.1
setTalkLabels.-1.-1.0
talk.<
    Да, проваливай, женщина, и оставь в покое наш мир. 
	С каждой секундой, пока я стою рядом с тобой, я чувствую, как становлюсь всё более глупым. 
	Поэтому уходи, пока я окончательно не превратился в такую же безмозглую куклу, как ты.
>
waitForUser
exit"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
