UID = "5AC06084"
Name = "F42E8491"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Ты что-то ищешь?>.0
waitForUser
ifPlayerHasCards.1.0.208
setTalkLabels.-1.-1.2
talk.<
    Извини, но ты не являешься членом нашей {4*Гильдии}.
    Я предоставляю услуги только тем, кто заслужил наше доверие.
>
goto.1
endIf
label.0
ifPlayerHasSpecials.1.1
say.<Похоже, у тебя есть наш знак. Тебе нужна моя помощь?>.3
choice.3.<Диалог>
choice.1.<До встречи>
waitForUser
else
say.<Похоже, у тебя есть наш знак. Тебе нужна моя помощь?>.3
choice.4.<Диалог>
choice.2.<Обмен>
choice.1.<До встречи>
waitForUser
label.4
setTalkLabels.-1.-1.0
talk.<
    Я могу отдать тебе одну из моих {4*диких фей}, раз уж у тебя до сих пор нет никакой феи.
	Но какая именно фея тебе достанется известно лишь удаче.
>
waitForUser
goto.0
label.3
setTalkLabels.-1.-1.2
talk.<
    Я очень скучаю по морю. 
	Ты знаешь, что оно все ещё здесь? 
	Я это чувствую. 
	С тех пор, как оно ушло, прошло очень много времени.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Всё, что теперь есть на его месте - это грязное и вонючее болото {4*Данмора}, простирающееся до горизонта. 
	Но оно всё равно остаётся морем, правда? 
	Ты можешь его увидеть, если закроешь глаза и вспомнишь, что оно когда-то там было.
>
goto.0
label.2
givePlayerCards.1.2.0
givePlayerCards.1.0.88
gotoRandomLabel.90.100
label.100
tradeWizform.0
goto.1
label.101
tradeWizform.1
goto.1
label.102
tradeWizform.2
goto.1
label.103
tradeWizform.3
goto.1
label.104
tradeWizform.4
goto.1
label.105
tradeWizform.5
goto.1
label.106
tradeWizform.6
goto.1
label.107
tradeWizform.7
goto.1
label.108
tradeWizform.8
goto.1
label.109
tradeWizform.9
goto.1
label.110
tradeWizform.10
goto.1
label.111
tradeWizform.11
goto.1
label.112
tradeWizform.12
goto.1
label.113
tradeWizform.13
goto.1
label.114
tradeWizform.14
goto.1
label.115
tradeWizform.15
goto.1
label.116
tradeWizform.16
goto.1
label.117
tradeWizform.17
goto.1
label.118
tradeWizform.18
goto.1
label.119
tradeWizform.19
goto.1
label.120
tradeWizform.20
goto.1
label.121
tradeWizform.21
goto.1
label.122
tradeWizform.22
goto.1
label.123
tradeWizform.23
goto.1
label.124
tradeWizform.24
goto.1
label.125
tradeWizform.25
goto.1
label.126
tradeWizform.26
goto.1
label.127
tradeWizform.27
goto.1
label.128
tradeWizform.28
goto.1
label.129
tradeWizform.29
goto.1
label.130
tradeWizform.30
goto.1
label.131
tradeWizform.31
goto.1
label.132
tradeWizform.32
goto.1
label.133
tradeWizform.33
goto.1
label.134
tradeWizform.34
goto.1
label.135
tradeWizform.35
goto.1
label.136
tradeWizform.36
goto.1
label.137
tradeWizform.37
goto.1
label.138
tradeWizform.38
goto.1
label.139
tradeWizform.39
goto.1
label.140
tradeWizform.40
goto.1
label.141
tradeWizform.41
goto.1
label.142
tradeWizform.42
goto.1
label.143
tradeWizform.43
goto.1
label.144
tradeWizform.44
goto.1
label.145
tradeWizform.45
goto.1
label.146
tradeWizform.46
goto.1
label.147
tradeWizform.47
goto.1
label.148
tradeWizform.48
goto.1
label.149
tradeWizform.49
goto.1
label.150
tradeWizform.50
goto.1
label.151
tradeWizform.51
goto.1
label.152
tradeWizform.52
goto.1
label.153
tradeWizform.53
goto.1
label.154
tradeWizform.54
goto.1
label.155
tradeWizform.55
goto.1
label.156
tradeWizform.56
goto.1
label.157
tradeWizform.57
goto.1
label.158
tradeWizform.58
goto.1
label.159
tradeWizform.59
goto.1
label.160
tradeWizform.60
goto.1
label.161
tradeWizform.61
goto.1
label.162
tradeWizform.62
goto.1
label.163
tradeWizform.63
goto.1
label.164
tradeWizform.64
goto.1
label.165
tradeWizform.65
goto.1
label.166
tradeWizform.66
goto.1
label.167
tradeWizform.67
goto.1
label.168
tradeWizform.68
goto.1
label.169
tradeWizform.69
goto.1
label.170
tradeWizform.70
goto.1
label.171
tradeWizform.71
goto.1
label.172
tradeWizform.72
goto.1
label.173
tradeWizform.73
goto.1
label.174
tradeWizform.74
goto.1
label.175
tradeWizform.75
goto.1
label.176
tradeWizform.76
goto.1
label.177
tradeWizform.77
goto.1
label.178
tradeWizform.78
goto.1
label.179
tradeWizform.79
goto.1
label.180
tradeWizform.80
goto.1
label.181
tradeWizform.81
goto.1
label.182
tradeWizform.82
goto.1
label.183
tradeWizform.83
goto.1
label.184
tradeWizform.84
goto.1
label.185
tradeWizform.85
goto.1
label.186
tradeWizform.86
goto.1
label.187
tradeWizform.87
goto.1
label.188
tradeWizform.88
goto.1
label.189
tradeWizform.89
goto.1
label.1
exit"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
