UID = "B0DC5C14"
Name = "53CAF221"
TriggerScript = """
setCamera.1003
playAnimation.13.-1
say.<
    Опять ты, эльф...
    эльф-переросток...
>.0
waitForUser
label.0
say.<
	Никто не понимает...
	мы видим мир не при помощи глаз...
>.1
choice.1.<Диалог>
choice.2.<Обмен>
choice.3.<До встречи>
waitForUser
label.1
say.<Ты тоже... не видишь?.. Эльфы никогда ничего не видят...>.1
choice.6.<Неизвестный Толлан>
choice.5.<Невосполнимая Утрата>
choice.4.<Назад>
waitForUser
label.6
setTalkLabels.-1.-1.2
talk.<
    Эх, эльф...
	Толлан...
	Ты когда-нибудь слышала о Толлане?
	Нет?
	А зря...
	Это... это как капля росы на лепестке оранжевого мака, только больше.
	Параллельный мир, понимаешь?..
	Там... там трава цвета безумного карнавала, небо – как лоскутное одеяло, сшитое из перьев ярких птиц и жёлтых облаков...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    И живут там... человечки.
	Зеленые, как сорванные с кустов твёрдые изумруды.
	Маленькие, как бусинки в твоей голове, но мудрые...
	Мудрые, как мшистые пни, исписанные рунами и знаками прошлого.
	Они собирают утром звёзды под тенью гигантских крыльев, и знают ответы...
	на вопросы, которые ты ещё не успела придумать.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Толлан... это не место, это манящий влагой мираж.
	Когда реальность высушивается до ломкой соломы, ты видишь... истину.
	Или просто иллюзию.
	Кто ж разберет...
	Толлан всегда ждет.
	Он всегда ждет...
	с распростёртыми, зелёными, мерцающими объятиями...
>
waitForUser
goto.0
label.5
setTalkLabels.-1.-1.2
talk.<
    Опять эти эльфы…
	Не видите вы, что вокруг...
	Не видите того, что вижу я, ну, или видел... раньше.
	Зелёные человечки, знаешь, из Толлана.
	Прилетали ко мне, прямо в огород, бывало...
	Ну, не то чтобы прямо вот на грибах, а так… прорывались.
	Сначала как рябь в воздухе, потом – оп! – и летают, светятся...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Они говорили...
	на языке, но я понимал их...
	Учили, как мир устроен...
	про смыслы жизни...
	Вот ты знаешь, в чём смыслы жизни?
	А они в Толлане...
	Я просил их забрать меня с собой...
	Но они сказали...
	я должен быть в перьях, а то разобьюсь при перелёте...
	или летательный порошок...
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Что случилось?..
	Сделал ли я что-то не так?..
	Моё тело мертво, я ничего не вижу...
	где мой плащ из перьев серых птиц...
	Моё сердце помнит, как они светились...
	Это всё потеряно...
	как язык в красном доме...
	Но я помню о них... 
	они не оставят меня одного, пока у нас есть крылья и перья...
>
waitForUser
goto.0
label.2
setTalkLabels.8.4.1
talk.<
    Тебе нужна помощь {4*зелёного человечка}?
	Я могу позволить одному из них отправиться с тобой в путешествие...
	если ты принесёшь мне такой же {4*зелёный камушек}...
	Есть ли у тебя один такой?..
>
waitForUser
label.8
ifPlayerHasCards.1.0.53
removePlayerCards.1.0.53
givePlayerCards.1.2.91
exit
else
setTalkLabels.-1.-1.0
talk.<
    Нет, у тебя нет этого прекрасного {4*зелёного камушка}...
	или ты хочешь меня обмануть, эльф?!
	{4*Зелёные человечки} не лгут...
	они не видят, что у тебя есть {4*зелёный камушек}...
>
waitForUser
exit
label.4
goto.0
label.3
exit"""
InitScript = """
setNpcType.4
setModel.g011s05m"""
