UID = "3243CA14"
Name = "A4DA3291"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Добро пожаловать в наш прекрасный сад!>.0
waitForUser
ifTriggerIsEnabled.27
setTalkLabels.-1.-1.0
talk.<
    Ты видишь этот восхитительный {4*Эволюционный Камень Природы}?
    Хотелось бы его взять, но прямо за ним живет довольно агрессивная фея...
>
waitForUser
exit
else
setTalkLabels.-1.-1.2
talk.<
    Ты всё же смогла забрать {4*Эволюционный Камень Природы}?
    Я уверена, {4*Болотный Гоблин} неподалеку отсюда готов обменять его на одного из {4*Тайнфолов}, редкую фею, которую невозможно найти в дикой природе.
    Но если ты хочешь услышать мой совет...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Иногда гораздо выгоднее сражаться обычными {4*дикими феями}, чем феями, получаемыми через {4*Эволюционные Камни Стихий}.
    У диких фей {4*меньше здоровья}, но они {4*быстрее набирают опыт и получают новые слоты заклинаний}, а у фей, эволюционирующих через {4*Камни Стихий}, всё с точностью до наоборот!
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Опытные {4*Коллекционеры} зачастую используют фей, получаемых при помощи {4*Эволюционных Камней Стихий}, так как они имеют доступ к {4*большему количеству заклинаний}.
    Так что ты должна подбирать свою команду с умом, если не хочешь оказаться в невыгодном для себя положении...
>
waitForUser
exit"""
InitScript = """
setModel.g205s21m
defaultWizForm.123.0.1"""
UpdateScript = """
ifTriggerIsEnabled.27
lookAtTrigger.-1.27
else
lookAtPlayer.-1.1
endIf"""
