UID = "36C11DB4"
Name = "9574B621"
#label 33 for Adventure Guild Badge
TriggerScript = """
setCamera.1003
say.<Приветствую, человеческое существо.>.0
playAnimation.13.-1
waitForUser
label.0
say.<Чем я могу тебе помочь?>.3
choice.3.<Диалог>
choice.2.<Почта>
choice.1.<До встречи>
waitForUser
label.3
setTalkLabels.-1.-1.0
talk.<
    Я представляю услуги особенной магической почты.
	Если ты назовёшь {4*номер заказа}, и на твоё имя будет посылка, то я с радостью отдам её тебе.
	За это не нужно никакой оплаты: все расходы остаются за отправителем.
>
waitForUser
goto.0
label.2
say.<Выбери первую цифру>.3
choice.15.<1>
choice.15.<2>
choice.15.<3>
choice.16.<Далее>
waitForUser
label.16
say.<Выбери первую цифру>.3
choice.15.<4>
choice.15.<5>
choice.18.<6>
choice.17.<Далее>
waitForUser
label.17
say.<Выбери первую цифру>.3
choice.15.<7>
choice.15.<8>
choice.15.<9>
waitForUser
label.18
say.<Выбери вторую цифру>.3
choice.19.<1>
choice.19.<2>
choice.19.<3>
choice.20.<Далее>
waitForUser
label.20
say.<Выбери вторую цифру>.3
choice.19.<4>
choice.19.<5>
choice.19.<6>
choice.21.<Далее>
waitForUser
label.21
say.<Выбери вторую цифру>.3
choice.19.<7>
choice.19.<8>
choice.22.<9>
waitForUser
label.22
say.<Выбери третью цифру>.3
choice.23.<1>
choice.23.<2>
choice.23.<3>
choice.24.<Далее>
waitForUser
label.24
say.<Выбери третью цифру>.3
choice.25.<4>
choice.23.<5>
choice.23.<6>
choice.26.<Далее>
waitForUser
label.26
say.<Выбери третью цифру>.3
choice.23.<7>
choice.23.<8>
choice.23.<9>
waitForUser
label.25
say.<Выбери четвёртую цифру>.3
choice.27.<1>
choice.27.<2>
choice.27.<3>
choice.28.<Далее>
waitForUser
label.28
say.<Выбери четвёртую цифру>.3
choice.27.<4>
choice.29.<5>
choice.27.<6>
choice.30.<Далее>
waitForUser
label.30
say.<Выбери четвёртую цифру>.3
choice.27.<7>
choice.27.<8>
choice.27.<9>
waitForUser
label.29
say.<Выбери пятую цифру>.3
choice.31.<1>
choice.31.<2>
choice.31.<3>
choice.32.<Далее>
waitForUser
label.32
say.<Выбери пятую цифру>.3
choice.33.<4>
choice.31.<5>
choice.31.<6>
choice.34.<Далее>
waitForUser
label.34
say.<Выбери пятую цифру>.3
choice.31.<7>
choice.31.<8>
choice.31.<9>
waitForUser
label.15
say.<Выбери вторую цифру>.3
choice.19.<1>
choice.19.<2>
choice.19.<3>
choice.35.<Далее>
waitForUser
label.35
say.<Выбери вторую цифру>.3
choice.19.<4>
choice.19.<5>
choice.19.<6>
choice.36.<Далее>
waitForUser
label.36
say.<Выбери вторую цифру>.3
choice.19.<7>
choice.19.<8>
choice.19.<9>
waitForUser
label.19
say.<Выбери третью цифру>.3
choice.23.<1>
choice.23.<2>
choice.23.<3>
choice.37.<Далее>
waitForUser
label.37
say.<Выбери третью цифру>.3
choice.23.<4>
choice.23.<5>
choice.23.<6>
choice.38.<Далее>
waitForUser
label.38
say.<Выбери третью цифру>.3
choice.23.<7>
choice.23.<8>
choice.23.<9>
waitForUser
label.23
say.<Выбери четвёртую цифру>.3
choice.27.<1>
choice.27.<2>
choice.27.<3>
choice.39.<Далее>
waitForUser
label.39
say.<Выбери четвёртую цифру>.3
choice.27.<4>
choice.27.<5>
choice.27.<6>
choice.40.<Далее>
waitForUser
label.40
say.<Выбери четвёртую цифру>.3
choice.27.<7>
choice.27.<8>
choice.27.<9>
waitForUser
label.27
say.<Выбери пятую цифру>.3
choice.31.<1>
choice.31.<2>
choice.31.<3>
choice.41.<Далее>
waitForUser
label.41
say.<Выбери пятую цифру>.3
choice.31.<4>
choice.31.<5>
choice.31.<6>
choice.42.<Далее>
waitForUser
label.42
say.<Выбери пятую цифру>.3
choice.31.<7>
choice.31.<8>
choice.31.<9>
waitForUser
label.31
setTalkLabels.-1.-1.0
talk.<
	На твоё имя нет никакой посылки с подобным номером.
	Проверь ещё раз, правильно ли ты назвала цифры.
>
waitForUser
goto.0
label.33
ifPlayerHasSpecials.1.1
setTalkLabels.-1.-1.2
talk.<
    У меня действительно была посылка с таким номером, но, к сожалению, ты опоздала.
	Если бы ты пришла ко мне раньше, то я смог бы передать её тебе.
	Теперь она была возвращена обратно отправителю, и я не могу больше ничем помочь.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    {4*Подсказка}: ты можешь использовать данный пароль только в начале новой игры.
	И при этом у тебя не должно быть ни одной взятой феи.
	Ты можешь узнать больше об этом, если почитаешь {4*книгу в Лондоне}.
>
waitForUser
goto.0
else
givePlayerCards.1.0.208
exit
label.1
exit"""
InitScript = "setModel.w004s04m"
UpdateScript = "lookAtPlayer.0.1"
