UID = "008C94A4"
Name = "0648ACA1"
TriggerScript = """
setCamera.1000
ifNpcModifierHasValue.1
goto.0
else
say.<У тебя должны быть сильные феи, чтобы осмелиться прийти в такое место, человеческий детёныш.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Моё имя Зендея, и я хранительница этой священной рощи.
	Давным-давно в этом месте {4*Друидам} была ниспослана {4*Карта Земли} — особое заклинание, дарующее власть над стихией Камня.
	Но с тех пор, как твой вид был изгнан из {4*Занзары}, все остальные расы отказались от использования {4*Магических Карт} во имя восстановления баланса.
>
waitForUser
setNpcModifier.-1.-1.1
label.0
setTalkLabels.1.2.1
talk.<
    Если ты хочешь получить {4*Карту Земли}, тебе придётся сразиться со мной и моими друзьями.
	И, в случае твоей победы, я даже расскажу тебе о способе, как разрушить {4*магический барьер}, защищающий {4*Карту Земли}.
    Ты готова сражаться?
>
waitForUser
label.1
setCamera.3001
fight.225.1
label.2
exit"""
InitScript = """
ifNpcModifierHasValue.0
setNpcType.3
defaultWizForm.210.2.38
endIf
ifNpcModifierHasValue.1
setNpcType.3
defaultWizForm.210.2.16
endIf"""
UpdateScript = """
lookAtPlayer.5.0"""
DefeatedScript = """
setTalkLabels.-1.-1.2
talk.<
    Ты самый сильный коллекционер фей из всех, которых я когда-либо встречала.
    Ты заслужила доступ к {4*Карте Земли}.
	Однако, тебе всё ещё нужно найти способ разрушить {4*магический барьер}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я слышала, что существует {4*особое заклинание}, которое способно разрушать такие препятствия.
	Однако, как и в случае с другими {4*Магическими Картами}, оно спрятано в труднодоступном месте.
	Но я уверена, оно должно быть где-то среди {4*гор, окружающих Монагам, деревню гномов}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Теперь, когда моя миссия исполнена, я помогу тебе в твоём путешествии.
	Но тебе всё ещё стоит быть осторожной — {4*Тёмные Эльфы} ищут способ завладеть {4*Картами Магии}.
	Мы не должны позволить им этого сделать, иначе {4*Занзару} окончательно поглотит эпоха хаоса!
>
waitForUser
changeWaypoint.-1.-1
givePlayerCards.1.2.210
startEffect.1.-1
removeNpcAtTrigger.59
removeNpcAtTrigger.60
removeNpcAtTrigger.61
removeNpcAtTrigger.62
removeNpc"""
