UID = "008C94A4"
Name = "0648ACA1"
TriggerScript = """
setCamera.1000
say.<У тебя должны быть сильные феи, чтобы осмелиться прийти в такое место, человеческий детёныш.>.0
waitForUser
setTalkLabels.0.1.0
talk.<
    Если ты победишь меня и моих друзей в честной схватке, я открою тебе портал в тайное место!
    Ты готова сражаться?
>
waitForUser
setCamera.3001
fight.225.1
exit"""
InitScript = """
setNpcType.3
defaultWizForm.210.0.29"""
UpdateScript = """
lookAtPlayer.5.0"""
DefeatedScript = """
setTalkLabels.-1.-1.0
talk.<
    Ты самый сильный коллекционер фей из всех, которых я когда-либо встречала.
    Ты заслужила доступ к {4*Карте Камня}.
>
waitForUser"""
