UID = "1836E654"
Name = "910B1179"
TriggerScript = """
deployNpcAtTrigger.36.1
setTalkLabels.-1.-1.0
talk.<Счастливого путешествия, хе-хе!>
waitForUser
startEffect.0.-1
removeNpc"""
InitScript = """
setNpcType.3
defaultWizForm.9.0.37"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
