UID = "FDA543F4"
Name = "E48E8DA1"
TriggerScript = """
setCamera.1003
say.<Ты тот самый человек, о котором говорит весь Тиралин?>.0
playAnimation.13.-1
waitForUser
label.0
say.<
    Я продаю лучшие зелья, которые можно найти во всём {4*Тиралине}...
    если у тебя хватит на это денег.
>.3
choice.1.<Диалог>
choice.2.<Торговля>
choice.3.<До встречи>
waitForUser
label.1
say.<
    Хорошо, но только спрашивай обо всём быстро.
    Иначе {4*Текла} снова будет ворчать, словно я отлыниваю от работы...
>.3
choice.4.<Искусство Трансмутации>
choice.5.<Волшебное Озеро>
choice.6.<Семейное дело>
choice.7.<Назад>
waitForUser
label.4
setTalkLabels.-1.-1.2
talk.<
    {4*Алхимия} имеет несколько дисциплин, одинаково важных для того, чтобы быть успешным.
    Но самая сложная из них — это {4*трансмутация}.
    Это знание, позволяющее превращать одно зелье в другое, изменяя его внутреннюю структуру и баланс {4*стихий}.
    Я полагаю, это сложно понять кому-то далекому от {4*алхимии}...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Проще говоря, у каждого зелья существует своя основа, — мы называем их {4*стихиями}.
    Они представляют собой сумму свойств, определённое состояние или качества, которые эффективно влияют на друг друга, ослабляя или усиливая потенциал сущности {4*стихии}.
    Каждая из {4*пяти стихий} имеет свою пару, с которой она взаимодействует, и важно понимать, как именно это работает.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    К примеру, {4*Жизнь} не сочетается с {4*Огнём}.
    В теории, этот антагонизм возможно разрешить, если добавить в эту пару третью стихию, а именно {4*Землю}.
    Таким образом {4*Жизнь} усилит эффект {4*Земли}, а {4*Земля} усилит эффект {4*Огня}.
    Увы, на практике это работает не так просто...
    если не рассчитать точные пропорции всех {4*стихий} в зелье, то {4*трансмутация} не сработает.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    И даже зная точные пропорции {4*стихий}, ты всё ещё рискуешь сделать всё неправильно.
    Любое действие, необходимое для варки зелий — даже выбор силы огня — моментально меняет соотношение и силы {4*стихий}.
    Поэтому {4*трансмутация} практически не изучена...
    Если, конечно, ты однажды не обнаружишь в себе такой же удивительный талант к {4*алхимии}, как у меня, и тогда нам будет что обсудить.
>
waitForUser
goto.1
label.5
setTalkLabels.-1.-1.2
talk.<
    В {4*Занзаре} существует очень много легенд и мифов, и в них всегда главную роль играет {4*магия}.
    Именно благодаря магии мы можем взаимодействовать с феями, а также изучать свойства волшебных предметов.
    Сила {4*магии} настолько велика, что когда-то давно она была способна менять {4*стихийную принадлежность фей}, но с тех пор мы сами научились управлять этими силами.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    В детстве мне часто рассказывали легенду о {4*Циритее} — легендарном алхимике, которая однажды бесследно исчезла.
    История гласит, что {4*Циритея} могла слышать голоса деревьев и цветов, и поэтому они сами рассказывали ей о своих лечебных свойствах.
    Как итог, она отправилась жить в одиночестве в лесу, посвятив себя изучению природы и поиску гармонии с ней.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Всё изменилось, как взошло {4*Чёрное Солнце}...
    оно уничтожило всё, что было ей так дорого, а именно её друзей, — деревья, растения, цветы.
    Она долго оплакивала их потерю, что из её слёз образовалось целое озеро, а сама она превратилась в прекрасное белое древо: так сильно она хотела помочь несчастным феям обрести хоть какое-то убежище и исцелить их душевные раны.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    И когда {4*феи Природы} узнали об этом, они ринулись все вместе в озеро.
    Обезумевшие от горя потери не только своего дома, но и той, кого они практически считали одной из них, {4*феи} отдали все свои магические силы озеру, наделяя его волшебными свойствами.
    Их души всё ещё можно увидеть даже сейчас, они весело смеются и резвятся рядом со своей любимой {4*Циритеей}...
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Ох, извини, каждый раз, когда я вспоминаю об этой истории, я начинаю плакать и вспоминать о своём детстве...
    Мы часто играли у этого озера в {4*Зачарованном Лесу}, даже несмотря на опасных {4*диких фей} поблизости, и никогда не понимали, почему у этой истории не могло быть счастливого конца.
    Ну вот, я уже начинаю говорить, как {4*Эмили}, она просто обожает слушать сказки, подобные этой.
>
waitForUser
goto.1
label.6
setTalkLabels.-1.-1.2
talk.<
    Ты даже не представляешь, как тяжело содержать этот огромный магазин! Мой муж, {4*Ларс}, занимается изготовлением и продажей магических сфер для ловли фей, а я алхимических зелий.
    А ещё есть {4*Текла}...
    она, ну, здесь самая главная, хотя на самом деле мы с мужем считаем, что я самая главная в нашем магазине, а {4*Текле} мы просто подыгрываем в этом вопросе.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    По правде говоря, этот магазин никогда не приносил большой прибыли...
    основным её источником всегда была торговля с {4*Данмором} и {4*Монагамом}, а также редкие крупные заказы.
    В последнее время мы едва сводим концы с концами, и {4*Ларс} не хочет заставлять волноваться свою мать и рассказывать ей об этом.
    Поэтому я начала искать альтернативы...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Знаешь, что самое удивительное в алхимии?
    Это бесконечное поле для экспериментов! Я думала о том, чтобы попробовать устроить представления для детей и их родителей, показывая им простые фокусы...
    это смогло бы привлечь новых клиентов и возможно мы начали бы изготавливать не только зелья, но и другие виды товаров.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Но {4*Текла} ничего не хочет даже слышать об этом! Она говорит, что я только буду отпугивать таким образом покупателей! Однако я подозреваю, что она просто не любит детей, которые постоянно приходят сюда...
    но что может быть лучше их радостных улыбок?
    Только деньги их родителей, правда?
    Но это всего лишь шутка, не подумай ничего такого.
>
waitForUser
goto.1
label.2
ifPlayerHasCards.15.0.106
tradingCurrency.C564B4A3
tradingItem.20.9ED19693
tradingItem.40.20510203
tradingItem.50.069C5F03
tradingItem.45.0B8C6603
tradingItem.30.2825B8A3
waitForUser
goto.0
else
ifPlayerHasCards.7.0.106
tradingCurrency.C564B4A3
tradingItem.25.9ED19693
tradingItem.45.20510203
tradingItem.55.069C5F03
tradingItem.50.0B8C6603
tradingItem.35.2825B8A3
waitForUser
goto.0
else
tradingCurrency.C564B4A3
tradingItem.50.20510203
tradingItem.55.0B8C6603
tradingItem.35.2825B8A3
waitForUser
goto.0
label.7
goto.0
label.3
exit"""
InitScript = """
setModel.b000s21m
defaultWizForm.168.0.0"""
UpdateScript = "lookAtPlayer.0.1"
