UID = "E985B6B4"
Name = "A59D61A1"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
ifNpcModifierHasValue.0
goto.30
else
goto.32
endIf
label.30
ifNumberOfNpcsIs.1.75ED2A94
say.<
    Благослови всех эльфов этого мира! Я спасён!
>.0
waitForUser
talk.<
    В моем подвале ужасный монстр! Ты мне можешь помочь?
    С твоими размерами будет легко поймать это отвратительное существо!
>
waitForUser
exit
else
setNpcModifier.-1.-1.1
talk.<
    Спасибо тебе за избавление от этого чудища, теперь я снова могу вернуться к своим {4*магическим предметам}.
    Если хочешь, я продам тебе несколько!
>
waitForUser
exit
label.32
say.<Рад тебя снова видеть, человеческий детеныш.>.0
waitForUser
label.0
say.<
    Ещё раз благодарю, что спасла меня от этого пикси.
    И как он только сюда попал...
>.1
choice.100.<Диалог>
choice.1.<Торговля>
choice.2.<Обмен>
choice.3.<До встречи>
waitForUser
endIf
exit
label.100
say.<
    Ты можешь научиться многому, обратившись к опыту прошлого.
    О чём ты хочешь знать?
>.1
choice.101.<История Эволюционных Камней>
choice.102.<Загадочные Руины>
choice.103.<Основание Тиралина>
choice.104.<Назад>
waitForUser
label.104
goto.0
label.101
setTalkLabels.-1.-1.2
talk.<
    {4*Эволюционные Камни} прошли долгий путь развития.
    Впервые их совместно изобрели {4*гномы} и {4*эльфы}, используя специально зачарованные камни и энергию лавовой магмы: они назывались {4*стихийными камнями}.
    Однако процесс их создания был крайне трудоёмок, и даже так шанс проведения успешной эволюции оставался очень случайным.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    После того, как {4*Друиды} появились на землях {4*Занзары}, они создали первые {4*Эволюционные Камни}.
    Но изначально они использовались для восстановления земель после событий {4*Чёрного Солнца} и не были предназначены для самих фей.
    Прошло много лет, пока их свойства стали полностью изучены, но, вновь, они работали на небольшом количестве фей.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Сейчас мы способны создавать {4*Эволюционные Камни} всех стихий, но, конечно, методика их создания останется секретом моей семьи.
    Алхимики стараются хранить знания среди своих учеников и редко посвящают в них посторонних.
    Но, не беспокойся, о технике созданий {4*Камней} также знает один из моих учеников, и поэтому подобные знания никогда не пропадут бесследно.
>
waitForUser
goto.100
label.102
setTalkLabels.-1.-1.2
talk.<
    За железными вратами, которые ты можешь найти напротив моего дома, находится путь к таинственным руинам.
    Они являются свидетельством когда-то великой {4*эпохи Друидов}, наследия которой практически не осталось во всей {4*Занзаре}.
    Это очень грустно видеть, что теперь в этих местах обитают лишь только дикие феи.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я не знаю точного предназначения этих строений, и у меня не было достаточно времени, чтобы лучше их изучить.
    Моё предположение состоит в том, что некогда это был храм, построенный людьми, чтобы поддерживать магию {4*Друидов} для произрастания {4*Зачарованного Леса}.
    Конечно, после {4*Раскола} и исчезновения {4*Друидов} от некогда величественных строений не осталось практически ничего.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Если ты захочешь посетить это место, то я советую быть осторожной, там обитают очень опасные {4*феи Света и Энергии}.
    Возможно, руины хранят в себе немало секретов, но без каких-либо подсказок о том, где их найти, всё, что нам остаётся, так это надеяться, что когда-то мы узнаем о них что-либо.
    Или пока не найдётся тот, кто сможет найти {4*сокровище}, о котором ходят легенды.
>
waitForUser
goto.100
label.103
setTalkLabels.-1.-1.2
talk.<
    {4*Тиралин} обладает весьма богатой историей, уходящей далеко в старые времена.
    Изначально это было всего лишь небольшое поселение, основанное людьми, но, к сожалению, оно было полностью разрушено во время событий {4*Чёрного Солнца}.
    Тогда один из огромных вулканов, существующих в {4*Занзаре}, внезапно проснулся, и он уничтожил часть земель, полностью изменив их облик.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Когда-то богатые зелёные луга, окружающие эти горы, исчезли и стали выжженной пустошью.
    Реки полностью пересохли, а гигантское море, из которого они происходили, постепенно превратилось в болото, где сейчас обитают {4*Болотные Гоблины}.
    Это была огромная трагедия для всех, включая {4*фей}, которые тоже потеряли свои дома.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Вместе с этим закончилась {4*эпоха Драконов} и началась {4*эпоха Друидов}.
    Тем, кто был магически одарён, {4*феи} дали возможность помочь им в восстановлении природы, и таким образом появились {4*Карты Стихий}.
    За долгие годы своей непрерывной работы {4*Друиды} смогли превратить эти пепельные степи в {4*Зачарованный Лес}, удивительное и волшебное место.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    {4*Тиралин} был отстроен заново объединёнными усилиями людей и эльфов, чтобы стать центром новой жизни для всех жителей {4*Сада фей} и их окрестностей.
    Но мы практически ничего не знаем, что происходило после этого, — множество документов и книг было уничтожено людьми во время {4*Раскола}, и всё, что осталось, до сих пор хранится в {4*архиве Тиралина}, вдали от большинства посторонних глаз.
>
waitForUser
goto.100
label.1
say.<
    У меня богатый выбор {4*Эволюционных Камней}.
    Какие именно тебя интересуют?
>.1
choice.4.<Эволюционные камни за {4*Медный Редис}>
choice.5.<Эволюционные камни за {4*Серебрянный Лук}>
choice.6.<Эволюционные камни за {4*Золотую Морковь}>
waitForUser
label.4
tradingCurrency.99613EA3
tradingItem.3.30B30713
tradingItem.3.43927E13
tradingItem.3.29617F13
tradingItem.3.5A642513
waitForUser
goto.0
label.5
tradingCurrency.2E2FB8A3
tradingItem.2.523D6413
tradingItem.2.28114F13
tradingItem.2.88157013
tradingItem.2.0C356C13
waitForUser
goto.0
label.6
tradingCurrency.709DB4A3
tradingItem.2.AAEB4603
tradingItem.2.32114213
tradingItem.2.91714603
waitForUser
goto.0
label.2
say.<Я могу обменять твои {4*Эволюционные Камни} на другие такой же ценности, если тебе это действительно нужно.>.1
choice.7.<Обмен {4*Эволюционного Камня Природы}>
choice.8.<Обмен {4*Эволюционного Камня Воздуха}>
choice.9.<Обмен {4*Эволюционного Камня Воды}>
choice.10.<Далее>
waitForUser
label.7
tradingCurrency.30B30713
tradingItem.1.43927E13
tradingItem.1.29617F13
tradingItem.1.5A642513
waitForUser
goto.0
label.8
tradingCurrency.AAEB4603
tradingItem.2.32114213
tradingItem.2.91714603
waitForUser
goto.0
label.9
tradingCurrency.43927E13
tradingItem.1.30B30713
tradingItem.1.29617F13
tradingItem.1.5A642513
waitForUser
goto.0
label.11
say.<Я могу обменять твои {4*Эволюционные Камни} на другие такой же ценности, если тебе это действительно нужно.>.1
choice.12.<Обмен {4*Эволюционного Камня Света}>
choice.13.<Обмен {4*Эволюционного Камня Энергии}>
choice.14.<Обмен {4*Эволюционного Камня Пси}>
choice.15.<Далее>
waitForUser
label.12
tradingCurrency.523D6413
tradingItem.2.28114F13
tradingItem.2.88157013
tradingItem.2.0C356C13
waitForUser
goto.0
label.13
tradingCurrency.32114213
tradingItem.2.AAEB4603
tradingItem.2.91714603
waitForUser
goto.0
label.14
tradingCurrency.29617F13
tradingItem.1.30B30713
tradingItem.1.43927E13
tradingItem.1.5A642513
waitForUser
goto.0
label.15
say.<Я могу обменять твои {4*Эволюционные Камни} на другие такой же ценности, если тебе это действительно нужно.>.1
choice.16.<Обмен {4*Эволюционного Камня Земли}>
choice.17.<Обмен {4*Эволюционного Камня Льда}>
choice.18.<Обмен {4*Эволюционного Камня Огня}>
choice.19.<Далее>
waitForUser
label.16
tradingCurrency.5A642513
tradingItem.1.30B30713
tradingItem.1.43927E13
tradingItem.1.29617F13
waitForUser
goto.0
label.17
tradingCurrency.28114F13
tradingItem.2.523D6413
tradingItem.2.88157013
tradingItem.2.0C356C13
waitForUser
goto.0
label.18
tradingCurrency.91714603
tradingItem.2.AAEB4603
tradingItem.2.32114213
waitForUser
goto.0
label.20
say.<Я могу обменять твои {4*Эволюционные Камни} на другие такой же ценности, если тебе это действительно нужно.>.1
choice.21.<Обмен {4*Эволюционного Камня Тьмы}>
choice.22.<Обмен {4*Эволюционного Камня Хаоса}>
choice.23.<Назад>
waitForUser
label.21
tradingCurrency.88157013
tradingItem.2.523D6413
tradingItem.2.28114F13
tradingItem.2.0C356C13
waitForUser
goto.0
label.22
tradingCurrency.0C356C13
tradingItem.2.523D6413
tradingItem.2.28114F13
tradingItem.2.88157013
waitForUser
goto.0
label.10
goto.11
label.15
goto.16
label.19
goto.20
label.23
goto.0
label.3
exit"""
InitScript = "setModel.b006s23m"
UpdateScript = "lookAtPlayer.-1.1"
