UID = "399C7404"
Name = "05360321"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Приветствую, путешественница.>.0
waitForUser
label.0
say.<Надеюсь, ты наслаждаешься своим пребыванием здесь. Достаточно уютное и тихое место, не правда ли?>.1
choice.4.<Диалог>
choice.3.<Торговля>
choice.2.<Обмен>
choice.1.<До встречи>
waitForUser
label.4
setTalkLabels.-1.-1.2
talk.<
    В Книге фей перечислены только дикие феи, встречающиеся в {4*Занзаре}.
    Причина этому — многообразие эволюционных форм, которые можно получить экспериментальным путём.
    Никто не знает, насколько их много и какие феи ещё могут существовать.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Немногие селекционеры фей пытаются понять закономерности, при которых возможно появление новых форм, но пока что никто в этом не преуспел.
    Поэтому мы больше занимаемся сохранением тех видов, что нам удалось найти, например, {4*cемейства Орнеллы}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Нет универсального способа для выведения новых форм фей: гномы пытаются проводить эксперименты на феях, используя посторонние {4*источники энергии}.
    Также этим занимаются и {4*Тёмные Эльфы}, но, полагаю, ты сможешь узнать подробности, только если встретишь одного из них.
    И если он согласится рассказать об этом.
>
waitForUser
goto.0
label.3
tradingCurrency.BAA9B8A3
tradingItem.5.82FE2C03
waitForUser
goto.0
label.2
setTalkLabels.10.11.1
talk.<
    Если ты хочешь, я могу обменять {4*три Детали Инструментов} на уникальную {4*фею Металла}.
    Ты хочешь сделать это?
>
waitForUser
label.10
ifPlayerHasCards.3.0.108
removePlayerCards.3.0.108
givePlayerCards.1.2.146
exit
else
setTalkLabels.-1.-1.0
talk.<
    Я не вижу, что у тебя есть {4*Детали Инструментов}.
    Возвращайся, как у тебя будет их достаточно.
>
waitForUser
goto.0
label.11
goto.0
label.1
exit"""
InitScript = """
setModel.x002s02
defaultWizForm.153.0.4"""
UpdateScript = "lookAtPlayer.0.1"
