UID = "56EA89B4"
Name = "E792AC31"
TriggerScript = """
setCamera.3001
say.<Добро пожаловать в мой магазин.>.0
waitForUser
ifPlayerHasCards.1.0.15
label.0
say.<Теперь, когда {4*Тёмные Эльфы} исчезли с болот, я могу продать тебе самые разнообразные травы.>.1
choice.6.<Диалог>
choice.7.<Торговля>
choice.3.<Обмен>
choice.4.<До встречи>
waitForUser
label.7
tradingCurrency.C564B4A3
tradingItem.10.2825B8A3
tradingItem.110.4F9DDBA3
tradingItem.125.EA16B5A3
tradingItem.135.238AFCA3
tradingItem.200.B437E9A3
waitForUser
goto.0
label.99
say.<
    Извини, мне практически нечего тебе предложить.
    {4*Тёмные Эльфы} скрываются повсюду на болотах, и все опасаются покидать деревню.
>.1
choice.5.<Торговля>
choice.3.<Обмен>
choice.4.<До встречи>
waitForUser
label.5
tradingCurrency.C564B4A3
tradingItem.10.2825B8A3
waitForUser
goto.99
label.3
setTalkLabels.10.11.1
talk.<
    Если тебе нужна помощь с опознанием алхимических зелий или трав, то я могу помочь с этим.
    У тебя есть что-то для меня?
>
waitForUser
label.10
ifPlayerHasCards.1.0.162
removePlayerCards.1.0.162
goto.12
else
ifPlayerHasCards.1.0.224
removePlayerCards.1.0.224
goto.13
else
setTalkLabels.-1.-1.0
talk.<У тебя нет никаких предметов, с оценкой которых я могу тебе помочь.>
waitForUser
goto.0
label.11
ifPlayerHasCards.1.0.15
goto.0
else
goto.99
label.12
setTalkLabels.-1.-1.2
talk.<Ты открываешь {4*Мешочек Трав}...>
waitForUser
gotoLabelByRandom.70.50
gotoLabelByRandom.70.51
gotoLabelByRandom.70.52
goto.53
label.50
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пучок Солнцелиста} (х1)!>
waitForUser
givePlayerCards.1.0.141
goto.10
label.51
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Сумеречный Корень} (х1)!>
waitForUser
givePlayerCards.1.0.142
goto.10
label.52
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Бутон Луноцвета} (х1)!>
waitForUser
givePlayerCards.1.0.143
goto.10
label.53
gotoRandomLabel.3.54
label.54
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Лесные Травы} (х3)!>
waitForUser
givePlayerCards.3.0.5
goto.10
label.55
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Лесные Травы} (х4)!>
waitForUser
givePlayerCards.4.0.5
goto.10
label.56
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Лесные Травы} (х5)!>
waitForUser
givePlayerCards.5.0.5
goto.10
label.13
setTalkLabels.-1.-1.2
talk.<Ты изучаешь {4*Неизвестное Зелье}...>
waitForUser
gotoRandomLabel.11.60
label.60
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Природы} (х1)!>
waitForUser
givePlayerCards.1.0.215
goto.10
label.61
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Воздуха} (х1)!>
waitForUser
givePlayerCards.1.0.213
goto.10
label.62
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Воды} (х1)!>
waitForUser
givePlayerCards.1.0.218
goto.10
label.63
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Света} (х1)!>
waitForUser
givePlayerCards.1.0.219
goto.10
label.64
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Энергии} (х1)!>
waitForUser
givePlayerCards.1.0.220
goto.10
label.65
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Пси} (х1)!>
waitForUser
givePlayerCards.1.0.223
goto.10
label.66
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Земли} (х1)!>
waitForUser
givePlayerCards.1.0.216
goto.10
label.67
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Льда} (х1)!>
waitForUser
givePlayerCards.1.0.217
goto.10
label.68
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Огня} (х1)!>
waitForUser
givePlayerCards.1.0.214
goto.10
label.69
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Тьмы} (х1)!>
waitForUser
givePlayerCards.1.0.221
goto.10
label.70
setTalkLabels.-1.-1.2
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Эликсир Хаоса} (х1)!>
waitForUser
givePlayerCards.1.0.222
goto.10
label.4
exit"""
InitScript = "setModel.g002s02m"
UpdateScript = "lookAtPlayer.-1.1"
