UID = "5EC643A4"
Name = "E55CBB91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Человек, за которым следуют феи?>.0
waitForUser
label.0
say.<В твоих путешествиях тебе непременно понадобятся новые феи, и я могу помочь тебе с этим.>.1
choice.4.<Диалог>
choice.3.<Торговля>
choice.2.<Обмен>
choice.1.<До встречи>
waitForUser
label.4
say.<Ты хочешь узнать больше о {4*Магических Сферах} или о чём-то другом?>.1
choice.8.<Магические Шары>
choice.7.<Одичавшие Феи>
choice.6.<Семейное Дело>
choice.5.<Назад>
waitForUser
label.8
setTalkLabels.-1.-1.2
talk.<
    Как ты знаешь, самый распространённый способ получения новых фей — это их ловля при помощи {4*магических шаров}.
    В зависимости от уровня феи, тебе понадобятся подходящая для её поимки сфера: и чем сильнее фея, против которой ты сражаешься, тем более дорогая сфера для неё потребуется.
    Всего существует три вида сфер: {4*серебряные}, {4*золотые} и {4*хрустальные}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    {4*Серебряные сферы} используются для поимки фей до 20 уровня, и в основном их используют для ловли {4*слабых фей Природы, Камня и Хаоса}.
    Ты можешь найти их на территории {4*Сада фей, Зачарованного Леса и болот Данмора}, но для {4*фей Хаоса} тебе возможно потребуется попросить помощи у {4*Руфуса, Хранителя пикси из Эндевы}, он один из немногих, кто знает об этих неприятных созданиях.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    {4*Золотые сферы} используются для поимки фей до 40 уровня, и это большинство диких фей различных стихий.
    Они обитают в {4*горах, окружающих Монагам, тёмных пещерах, отдалённых уголках Зачарованного Леса, а также заброшенном Царстве Облаков}.
    Если ты сможешь найти способ попасть в закрытую область {4*Подземелий Тиралина}, я думаю, ты найдёшь там фей {4*Тьмы и Хаоса}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    {4*Хрустальные сферы} используются для поимки фей до 60 уровня, и к ним относятся редкие феи {4*Огня, Энергии, Света и Тьмы}.
    Я не могу посоветовать, где стоит искать этих фей, но ты можешь спросить об этом у других {4*Коллекционеров}.
    В {4*Занзаре} немногие могут похвастаться, что могут ловить настолько сильных фей.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Напоследок позволь мне дать пару советов.
    Ты можешь использовать более дорогие сферы для ловли слабых фей, если у тебя нет подходящей для их уровня.
    И ещё одно — если ты сражаешься с двумя и более дикими феями, это будет очень сложным делом поймать одну из них...
    и поэтому лучше ловить фей, когда они нападают на тебя в одиночестве.
>
waitForUser
goto.0
label.7
setTalkLabels.-1.-1.2
talk.<
    Путешествуя по {4*Занзаре}, ты уже не раз сталкивалась с тем, как на тебя нападали {4*дикие феи}.
    Однако так было не всегда.
    Древние легенды рассказывают о временах, когда феи и все расы, населяющие эти земли, жили в согласии между собой.
    И те немногие, кто заслуживал доверие фей, мог удостоиться чести стать {4*Коллекционером}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Именно феи даровали {4*магические карты}: волшебные предметы, созданные с целью раскрыть потенциал магической природы определённой стихии.
    Вместе с новыми силами пришла и ответственность по поддержанию гармонии во всей {4*Занзаре}, которую взяли на себя {4*Друиды}.
    Но всё изменилось, как люди начали завидовать силам и безграничным возможностям фей.
    
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Действия людей и их охота на магических существ нанесли незаживляющие раны на теле мира, поэтому {4*Белый Друид} закрыл порталы в человеческий мир.
    Вместе с этим использование {4*Карт Магии} ушло в прошлое, а сами феи стали враждебными.
    Таким образом эльфы придумали {4*Магические Сферы}, чтобы стараться поддерживать мир среди фей и остальных рас.
>
waitForUser
goto.0
label.6
setTalkLabels.-1.-1.2
talk.<
    Семейный магазин — это очень утомительное занятие, и оно забирает всё свободное время.
    Если ты уже успела познакомится с моей женой {4*Агатой} и матерью {4*Теклой}, уверен, что ты и сама поняла, в чём главная проблема.
    Они постоянно ссорятся друг с другом, всё время спорят по пустякам, а мне приходится подбирать нужные слова, чтобы успокоить их обеих!
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Мы знакомы с {4*Агатой} ещё с самого детства, и поэтому она была лучшим кандидатом для работы здесь.
    Единственной проблемой было то, что она не была гражданкой {4*Тиралина}, поэтому мы решили заключить брак.
    И всё шло просто идеально, пока они не начали обсуждать, как лучше вести торговлю.
    В этих вопросах мама достаточно консервативна, а {4*Агата} — её полная противоположность!
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Буквально на днях они опять поссорились и снова не разговаривают друг с другом.
    Знаешь, я ведь тоже не просто так стою у самого выхода: я всё чаще и чаще думаю о том, чтобы просто сбежать от всего этого...
    Когда-то я мечтал стать {4*Коллекционером}, но сейчас у меня едва есть свободное время, чтобы посетить {4*Эндеву} и обучиться основам дуэлей между феями.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я восхищаюсь сестрой {4*Агаты} — {4*Люцерной}, её свободой, стремлением делать то, что хочешь... Может когда-нибудь я тоже стану коллекционером фей, как она?
    Когда у меня будут собственные дети, которым я смогу доверит магазин, и я перестану каждый день беспокоиться о пустяках! Только, пожалуйста, не рассказывай об этом моей жене и матери, я не хочу расстраивать кого-либо из них...
>
waitForUser
goto.0
label.3
tradingCurrency.C564B4A3
tradingItem.60.8E0E9503
tradingItem.150.62689503
tradingItem.300.ADB09503
waitForUser
goto.0
label.2
say.<Если тебе не нужны {4*магические овощи}, то я с радостью их обменяю на {4*сферы для ловли фей}.>.1
choice.11.<Обмен {4*Медного Редиса}>
choice.10.<Обмен {4*Серебрянного Лука}>
choice.9.<Обмен {4*Золотой Моркови}>
waitForUser
label.11
tradingCurrency.99613EA3
tradingItem.3.8E0E9503
tradingItem.6.62689503
tradingItem.12.ADB09503
waitForUser
goto.0
label.10
tradingCurrency.2E2FB8A3
tradingItem.2.8E0E9503
tradingItem.3.62689503
tradingItem.6.ADB09503
waitForUser
goto.0
label.9
tradingCurrency.709DB4A3
tradingItem.1.8E0E9503
tradingItem.1.62689503
tradingItem.2.ADB09503
waitForUser
goto.0
label.1
exit"""
InitScript = """
setModel.b023s23m
defaultWizForm.7.0.0"""
UpdateScript = "lookAtPlayer.0.1"
