UID = "96837434"
Name = "7B2D8F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Добро пожаловать в мой скромный магазин!>.0
waitForUser
label.10
say.<Чем могу помочь?>.1
choice.0.<Торговля>
choice.2.<До встречи>
waitForUser
label.0
ifPlayerHasCards.5.0.106
tradingCurrency.BAA9B8A3
tradingItem.10.20510203
tradingItem.12.069C5F03
tradingItem.13.0813C113
tradingItem.20.5762C113
tradingItem.15.252A4FA3
waitForUser
goto.10
else
ifPlayerHasCards.3.0.106
tradingCurrency.BAA9B8A3
tradingItem.12.20510203
tradingItem.16.0813C113
tradingItem.25.5762C113
tradingItem.15.252A4FA3
waitForUser
goto.10
else
tradingCurrency.BAA9B8A3
tradingItem.15.20510203
tradingItem.20.0813C113
tradingItem.15.252A4FA3
waitForUser
goto.10
label.2
exit"""
InitScript = "setModel.d003s03m"
UpdateScript = "lookAtPlayer.-1.1"
