UID = "9FB22894"
Name = "10A990A1"
TriggerScript = """
setCamera.1003
say.<Путешественница из Тиралина?>.0
playAnimation.13.-1
waitForUser
label.2
say.<
    Ты тоже заметила, что на болотах так много {4*Терновых Кустов}?
    Может, это из-за влажного климата?
>.3
choice.3.<Диалог>
choice.4.<Торговля>
choice.5.<Обмен>
choice.10.<До встречи>
waitForUser
label.3
say.<
    Я не уверен, что я интересный собеседник...
    но я попробую.
>.3
choice.6.<Потерянная связь>
choice.7.<Исчезнувшие виды>
choice.8.<Алхимик Большого Дерева>
choice.9.<Назад>
waitForUser
label.6
setTalkLabels.-1.-1.2
talk.<
    Прошло уже несколько недель с тех пор, как {4*Данмор} оказался в осаде.
    Ещё хуже другое: единственный путь в {4*Тиралин} заблокировали {4*Тёмные Эльфы}, и если бы не {4*госпожа Кардеа}, - мне страшно представить, что с нами сделали бы {4*Тёмные Эльфы}...
    Она единственная, кто достаточно сильна, чтобы дать отпор этим непрошенным гостям.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Обычно я просил проходящих здесь путешественников передать письма моим сёстрам в {4*Тиралине}.
    С тех пор, как наши пути разошлись, я единственный поддерживаю наши семейные отношения.
    И без нужных мне материалов, которые мне присылала {4*Люцерна}, я чувствую себя беспомощным, — по сравнению с {4*Агатой}, я совершенно лишён практической жилки...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Люцерна занимается {4*тренировками фей}, и порою мне кажется, что она относится к этому слишком серьёзно.
    Ей удалось обнаружить метод обработки пыльцы фей, позволяющий многократно усилить эффект получаемого опыта.
    Но {4*Люцерна} отказывается экспериментировать на своих феях; для неё важно не нарушать природный баланс вещей...
    по крайней мере, она объясняет это так.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Моя другая сестра, {4*Агата}, работает алхимиком в {4*Тиралине}.
    Она слишком упрямо шла к своей цели, и такой же была {4*Люцерна}, но я не виню их в этом.
    После того, как наши родители погибли в процессе неудачного эксперимента с лечебным эффектом одного ядовитого растения, мои сёстры совершенно разделились во мнениях относительно нашего общего будущего.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Это было сложное решение, но я не выбрал сторону ни одной из моих сестёр.
    Я отказался продолжить нашу алхимическую династию, но в то же время продолжил заниматься {4*алхимией} здесь, в {4*Данморе}.
    И я не полностью оборвал свою жизнь с {4*алхимией}, как того желала {4*Люцерна}, я решил искать знания травничества у {4*Болотных Гоблинов} и методы совершенствования их знаний.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Тебе знакомо это чувство, когда ты хочешь познакомить вместе солнце и луну?
    Но они никогда не смогут увидеть друг друга.
    И они настолько далеко, что ты можешь смотреть на них на небе, но твои руки не дотягиваются до них, и тебе остаётся лишь обнимать себя.
    Я представляю себя горизонтом, объединяющим их вместе...
    постоянно надеясь, что они всё ещё считают друг друга семьёй.
>
waitForUser
goto.3
label.7
setTalkLabels.-1.-1.2
talk.<
    {4*Феи} — одни из самых удивительных и загадочных созданий, которых только можно встретить во всей {4*Занзаре}.
    Они всегда были неотъемлимой частью этого мира, поэтому тяжело представить, что некоторые из них могли в один момент просто исчезнуть.
    Пускай мы и можем предполагать причины этого, но зато мы точно знаем, какие именно это были феи.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Некоторые из них были прародителями тех фей, которых ты можешь найти сейчас в дикой природе.
    Природа других же кажется настолько уникальной, что их было всего несколько штук во всём мире.
    И часть из них появилась в процессе появления уникальных адаптационных механизмов, связанных с резким изменением климата или образа их жизни.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Долгое время мы могли изучать их только по рисункам, оставшимся в древних книгах.
    Но мне удалось найти способ получения этих фей! 
	Это {4*Камень Регрессии} — моё уникальное изобретение, позволящее возвращать утраченные в глубине веков формы фей.
    Ты всегда можешь купить его в обмен на {4*пыльцу} или найти у других торговцев в {4*Занзаре}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Но я должен тебя предупредить об одной вещи: {4*регрессивные феи} имеют очень странные {4*слоты заклинаний}, и поэтому они могут быть не такими эффективными в бою, как большинство других.
    Возможно, опытные {4*Коллекционеры} могут найти для них применение в бою, а также эти феи всё ещё являются ценными экземплярами для любой коллекции.
>
waitForUser
goto.3
label.8
setTalkLabels.-1.-1.2
talk.<
    На юге от {4*Данмора} находится ещё одно поселение {4*Болотных Гоблинов}, {4*Большое Дерево}.
    К алхимику, живущему там, стекаются со всех концов света — говорят, что он способен вылечить любую известную хворь.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Из-за особого климата на болотах {4*гоблины} вынуждены дополнительно заботиться о состоянии своей кожи, поэтому они, как и {4*эльфы}, изучают алхимию.
    Но, в отличие от эльфов, {4*гоблины} исследуют свойства различных растений на себе самих или добровольцах из других рас, в то время как {4*лесные эльфы} в большей степени изучают травы на феях.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Таким образом, гоблины стали одними из лучших, кто разбирается в медицине.
    Они также активно торгуют полезными растениями, и {4*болотные травы} — единственное средство для восстановления {4*фей} после поражения в битве.
    Сейчас я не могу представить, как мы могли бы жить без ценных знаний гоблинов.
>
waitForUser
goto.3
label.4
tradingCurrency.AD58B4A3
tradingItem.5.AC718B13
tradingItem.3.79064393
tradingItem.20.EAD36213
tradingItem.40.B99EF113
waitForUser
goto.2
label.9
goto.2
label.5
say.<Я приму любые {4*магические овощи} для моих экспериментов.>.3
choice.11.<Обмен {4*Медного Редиса}>
choice.12.<Обмен {4*Серебрянного Лука}>
choice.13.<Обмен {4*Золотой Моркови}>
choice.14.<Назад>
waitForUser
label.11
tradingCurrency.99613EA3
tradingItem.3.79064393
waitForUser
goto.2
label.12
tradingCurrency.2E2FB8A3
tradingItem.2.79064393
tradingItem.20.EAD36213
waitForUser
goto.2
label.13
tradingCurrency.709DB4A3
tradingItem.1.79064393
tradingItem.7.EAD36213
tradingItem.15.B99EF113
waitForUser
goto.2
label.14
goto.2
label.10
exit"""
InitScript = "setModel.b003s01m"
UpdateScript = """
label.0
idle
moveSystem.1.3
gotoRandomLabel.2.0
goto.0
label.1
playAnimation.0.90
goto.0"""
