UID = "DEC0BEA4"
Name = "24E3A591"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<О, это снова ты.>.0
waitForUser
label.0
say.<Возможно, нам стоит взять перерыв от экспериментов, это слишком небезопасно...>.1
choice.3.<Торговля>
choice.2.<Обмен>
choice.1.<До встречи>
waitForUser
label.4
setTalkLabels.-1.-1.2
talk.<
    В Книге фей перечислены только дикие феи, встречающиеся в {4*Занзаре}.
    Причина этому — многообразие эволюционных форм, которые можно получить экспериментальным путём.
    Никто не знает, насколько их много и какие феи ещё могут существовать.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Немногие селекционеры фей пытаются понять закономерности, при которых возможно появление новых форм, но пока что никто в этом не преуспел.
    Поэтому мы больше занимаемся сохранением тех видов, что нам удалось найти, например, {4*cемейства Орнеллы}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Нет универсального способа для выведения новых форм фей: гномы пытаются проводить эксперименты на феях, используя посторонние {4*источники энергии}.
    Также этим занимаются и {4*Тёмные Эльфы}, но, полагаю, ты сможешь узнать подробности, только если встретишь одного из них.
    И если он согласится рассказать об этом.
>
waitForUser
goto.0
label.3
tradingCurrency.BAA9B8A3
tradingItem.30.DA63F5A3
tradingItem.30.CFF793A3
tradingItem.40.4D4A9913
tradingItem.40.CD73C313
tradingItem.30.9DAC42B3
waitForUser
goto.0
label.2
setTalkLabels.10.11.1
talk.<
    Если ты хочешь, я могу продать тебе уникальную {4*фею Металла} всего за {4*тридцать кристаллов}.
    Ты хочешь сделать это?
>
waitForUser
label.10
ifPlayerHasCards.30.0.6
removePlayerCards.30.0.6
givePlayerCards.1.2.146
exit
else
setTalkLabels.-1.-1.0
talk.<
    Я не вижу, что у тебя достаточное количество {4*Кристаллов}.
	Возвращайся, когда они у тебя появятся.
>
waitForUser
goto.0
label.11
goto.0
label.1
exit"""
InitScript = """
setModel.b014s00m
defaultWizForm.209.0.4"""
UpdateScript = "lookAtPlayer.0.1"
