UID = "9023A7A4"
Name = "79110B91"
#Sillia (8), Boneria (9), Gummy (23), Phoe (37), Mykori (40)
#From 19 to 16
InitScript = """
setNpcType.3
gotoRandomLabel.25.0
label.0
defaultWizForm.8.0.20
goto.25
label.1
defaultWizForm.9.0.20
goto.25
label.2
defaultWizForm.23.0.20
goto.25
label.3
defaultWizForm.37.0.20
goto.25
label.4
defaultWizForm.40.0.20
goto.25
label.5
defaultWizForm.8.0.19
goto.25
label.6
defaultWizForm.9.0.19
goto.25
label.7
defaultWizForm.23.0.19
goto.25
label.8
defaultWizForm.37.0.19
goto.25
label.9
defaultWizForm.40.0.19
goto.25
label.10
defaultWizForm.8.0.18
goto.25
label.11
defaultWizForm.9.0.18
goto.25
label.12
defaultWizForm.23.0.18
goto.25
label.13
defaultWizForm.37.0.18
goto.25
label.14
defaultWizForm.40.0.18
goto.25
label.15
defaultWizForm.8.0.17
goto.25
label.16
defaultWizForm.9.0.17
goto.25
label.17
defaultWizForm.23.0.17
goto.25
label.18
defaultWizForm.37.0.17
goto.25
label.19
defaultWizForm.40.0.17
goto.25
label.20
defaultWizForm.8.0.16
goto.25
label.21
defaultWizForm.9.0.16
goto.25
label.22
defaultWizForm.23.0.16
goto.25
label.23
defaultWizForm.37.0.16
goto.25
label.24
defaultWizForm.40.0.16
goto.25
label.25"""
