UID = "9023A8A4"
Name = "79110B91"
#Grem (6), Gummi (23), Mykory (40), JumJum (81)
#From 19 to 16
InitScript = """
setNpcType.3
gotoRandomLabel.16.0
label.0
defaultWizForm.6.0.20
goto.20
label.1
defaultWizForm.23.0.20
goto.20
label.2
defaultWizForm.40.0.20
goto.20
label.3
defaultWizForm.81.0.20
goto.20
label.4
defaultWizForm.6.0.19
goto.20
label.5
defaultWizForm.23.0.19
goto.20
label.6
defaultWizForm.40.0.19
goto.20
label.7
defaultWizForm.81.0.19
goto.20
label.8
defaultWizForm.6.0.18
goto.20
label.9
defaultWizForm.23.0.18
goto.20
label.10
defaultWizForm.40.0.18
goto.20
label.11
defaultWizForm.81.0.18
goto.20
label.12
defaultWizForm.6.0.17
goto.20
label.13
defaultWizForm.23.0.17
goto.20
label.14
defaultWizForm.40.0.17
goto.20
label.15
defaultWizForm.81.0.17
goto.20
label.20"""
