UID = "9023BBA4"
Name = "79110B91"
#Phaleon (88), Gremor (7), Gamelin (24)
#From 35 to 29
InitScript = """
setNpcType.3
gotoLabelByRandom.75.21
gotoRandomLabel.21.0
label.0
defaultWizForm.88.0.36
goto.100
label.1
defaultWizForm.7.0.36
goto.100
label.2
defaultWizForm.24.0.36
goto.100
label.3
defaultWizForm.88.0.35
goto.100
label.4
defaultWizForm.7.0.35
goto.100
label.5
defaultWizForm.24.0.35
goto.100
label.6
defaultWizForm.88.0.34
goto.100
label.7
defaultWizForm.7.0.34
goto.100
label.8
defaultWizForm.24.0.34
goto.100
label.9
defaultWizForm.88.0.33
goto.100
label.10
defaultWizForm.7.0.33
goto.100
label.11
defaultWizForm.24.0.33
goto.100
label.12
defaultWizForm.88.0.32
goto.100
label.13
defaultWizForm.7.0.32
goto.100
label.14
defaultWizForm.24.0.32
goto.100
label.15
defaultWizForm.88.0.31
goto.100
label.16
defaultWizForm.7.0.31
goto.100
label.17
defaultWizForm.24.0.31
goto.100
label.18
defaultWizForm.88.0.30
goto.100
label.19
defaultWizForm.7.0.30
goto.100
label.20
defaultWizForm.24.0.30
goto.100
label.21
gotoRandomLabel.21.22
label.22
defaultWizForm.88.0.36
goto.50
label.23
defaultWizForm.7.0.36
goto.50
label.24
defaultWizForm.24.0.36
goto.50
label.25
defaultWizForm.88.0.35
goto.50
label.26
defaultWizForm.7.0.35
goto.50
label.27
defaultWizForm.24.0.35
goto.50
label.28
defaultWizForm.88.0.34
goto.50
label.29
defaultWizForm.7.0.34
goto.50
label.30
defaultWizForm.24.0.34
goto.50
label.31
defaultWizForm.88.0.33
goto.50
label.32
defaultWizForm.7.0.33
goto.50
label.33
defaultWizForm.24.0.33
goto.50
label.34
defaultWizForm.88.0.32
goto.50
label.35
defaultWizForm.7.0.32
goto.50
label.36
defaultWizForm.24.0.32
goto.50
label.37
defaultWizForm.88.0.31
goto.50
label.38
defaultWizForm.7.0.31
goto.50
label.39
defaultWizForm.24.0.31
goto.50
label.40
defaultWizForm.88.0.30
goto.50
label.41
defaultWizForm.7.0.30
goto.50
label.42
defaultWizForm.24.0.30
goto.50
label.50
gotoRandomLabel.21.51
label.51
defaultWizForm.88.1.36
goto.100
label.52
defaultWizForm.7.1.36
goto.100
label.53
defaultWizForm.24.1.36
goto.100
label.54
defaultWizForm.88.1.35
goto.100
label.55
defaultWizForm.7.1.35
goto.100
label.56
defaultWizForm.24.1.35
goto.100
label.57
defaultWizForm.88.1.34
goto.100
label.58
defaultWizForm.7.1.34
goto.100
label.59
defaultWizForm.24.1.34
goto.100
label.60
defaultWizForm.88.1.33
goto.100
label.61
defaultWizForm.7.1.33
goto.100
label.62
defaultWizForm.24.1.33
goto.100
label.63
defaultWizForm.88.1.32
goto.100
label.64
defaultWizForm.7.1.32
goto.100
label.65
defaultWizForm.24.1.32
goto.100
label.66
defaultWizForm.88.1.31
goto.100
label.67
defaultWizForm.7.1.31
goto.100
label.68
defaultWizForm.24.1.31
goto.100
label.69
defaultWizForm.88.1.30
goto.100
label.70
defaultWizForm.7.1.30
goto.100
label.71
defaultWizForm.24.1.30
goto.100
label.100"""
