UID = "9053C5A4"
Name = "79110B91"
#Pyphia (17), Sirella (47), Sirael (65), Gorael (66), Grace (70), Driane (75)
#From 35 to 29
InitScript = """
setNpcType.3
gotoLabelByRandom.50.43
gotoRandomLabel.42.0
label.0
defaultWizForm.17.0.36
goto.900
label.1
defaultWizForm.47.0.36
goto.900
label.2
defaultWizForm.65.0.36
goto.900
label.3
defaultWizForm.66.0.36
goto.900
label.4
defaultWizForm.70.0.36
goto.900
label.5
defaultWizForm.75.0.36
goto.900
label.6
defaultWizForm.17.0.35
goto.900
label.7
defaultWizForm.47.0.35
goto.900
label.8
defaultWizForm.65.0.35
goto.900
label.9
defaultWizForm.66.0.35
goto.900
label.10
defaultWizForm.70.0.35
goto.900
label.11
defaultWizForm.75.0.35
goto.900
label.12
defaultWizForm.17.0.34
goto.900
label.13
defaultWizForm.47.0.34
goto.900
label.14
defaultWizForm.65.0.34
goto.900
label.15
defaultWizForm.66.0.34
goto.900
label.16
defaultWizForm.70.0.34
goto.900
label.17
defaultWizForm.75.0.34
goto.900
label.18
defaultWizForm.17.0.33
goto.900
label.19
defaultWizForm.47.0.33
goto.900
label.20
defaultWizForm.65.0.33
goto.900
label.21
defaultWizForm.66.0.33
goto.900
label.22
defaultWizForm.70.0.33
goto.900
label.23
defaultWizForm.75.0.33
goto.900
label.24
defaultWizForm.17.0.32
goto.900
label.25
defaultWizForm.47.0.32
goto.900
label.26
defaultWizForm.65.0.32
goto.900
label.27
defaultWizForm.66.0.32
goto.900
label.28
defaultWizForm.70.0.32
goto.900
label.29
defaultWizForm.75.0.32
goto.900
label.30
defaultWizForm.17.0.31
goto.900
label.31
defaultWizForm.47.0.31
goto.900
label.32
defaultWizForm.65.0.31
goto.900
label.33
defaultWizForm.66.0.31
goto.900
label.34
defaultWizForm.70.0.31
goto.900
label.35
defaultWizForm.75.0.31
goto.900
label.36
defaultWizForm.17.0.30
goto.900
label.37
defaultWizForm.47.0.30
goto.900
label.38
defaultWizForm.65.0.30
goto.900
label.39
defaultWizForm.66.0.30
goto.900
label.40
defaultWizForm.70.0.30
goto.900
label.41
defaultWizForm.75.0.30
goto.900
label.43
gotoRandomLabel.42.44
label.44
defaultWizForm.17.0.36
goto.86
label.45
defaultWizForm.47.0.36
goto.86
label.46
defaultWizForm.65.0.36
goto.86
label.47
defaultWizForm.66.0.36
goto.86
label.48
defaultWizForm.70.0.36
goto.86
label.49
defaultWizForm.75.0.36
goto.86
label.50
defaultWizForm.17.0.35
goto.86
label.51
defaultWizForm.47.0.35
goto.86
label.52
defaultWizForm.65.0.35
goto.86
label.53
defaultWizForm.66.0.35
goto.86
label.54
defaultWizForm.70.0.35
goto.86
label.55
defaultWizForm.75.0.35
goto.86
label.56
defaultWizForm.17.0.34
goto.86
label.57
defaultWizForm.47.0.34
goto.86
label.58
defaultWizForm.65.0.34
goto.86
label.59
defaultWizForm.66.0.34
goto.86
label.60
defaultWizForm.70.0.34
goto.86
label.61
defaultWizForm.75.0.34
goto.86
label.62
defaultWizForm.17.0.33
goto.86
label.63
defaultWizForm.47.0.33
goto.86
label.64
defaultWizForm.65.0.33
goto.86
label.65
defaultWizForm.66.0.33
goto.86
label.66
defaultWizForm.70.0.33
goto.86
label.67
defaultWizForm.75.0.33
goto.86
label.68
defaultWizForm.17.0.32
goto.86
label.69
defaultWizForm.47.0.32
goto.86
label.70
defaultWizForm.65.0.32
goto.86
label.71
defaultWizForm.66.0.32
goto.86
label.72
defaultWizForm.70.0.32
goto.86
label.73
defaultWizForm.75.0.32
goto.86
label.74
defaultWizForm.17.0.31
goto.86
label.75
defaultWizForm.47.0.31
goto.86
label.76
defaultWizForm.65.0.31
goto.86
label.77
defaultWizForm.66.0.31
goto.86
label.78
defaultWizForm.70.0.31
goto.86
label.79
defaultWizForm.75.0.31
goto.86
label.80
defaultWizForm.17.0.30
goto.86
label.81
defaultWizForm.47.0.30
goto.86
label.82
defaultWizForm.65.0.30
goto.86
label.83
defaultWizForm.66.0.30
goto.86
label.84
defaultWizForm.70.0.30
goto.86
label.85
defaultWizForm.75.0.30
goto.86
label.86
gotoRandomLabel.42.87
label.87
defaultWizForm.17.1.36
goto.900
label.88
defaultWizForm.47.1.36
goto.900
label.89
defaultWizForm.65.1.36
goto.900
label.90
defaultWizForm.66.1.36
goto.900
label.91
defaultWizForm.70.1.36
goto.900
label.92
defaultWizForm.75.1.36
goto.900
label.93
defaultWizForm.17.1.35
goto.900
label.94
defaultWizForm.47.1.35
goto.900
label.95
defaultWizForm.65.1.35
goto.900
label.96
defaultWizForm.66.1.35
goto.900
label.97
defaultWizForm.70.1.35
goto.900
label.98
defaultWizForm.75.1.35
goto.900
label.99
defaultWizForm.17.1.34
goto.900
label.100
defaultWizForm.47.1.34
goto.900
label.101
defaultWizForm.65.1.34
goto.900
label.102
defaultWizForm.66.1.34
goto.900
label.103
defaultWizForm.70.1.34
goto.900
label.104
defaultWizForm.75.1.34
goto.900
label.105
defaultWizForm.17.1.33
goto.900
label.106
defaultWizForm.47.1.33
goto.900
label.107
defaultWizForm.65.1.33
goto.900
label.108
defaultWizForm.66.1.33
goto.900
label.109
defaultWizForm.70.1.33
goto.900
label.110
defaultWizForm.75.1.33
goto.900
label.111
defaultWizForm.17.1.32
goto.900
label.112
defaultWizForm.47.1.32
goto.900
label.113
defaultWizForm.65.1.32
goto.900
label.114
defaultWizForm.66.1.32
goto.900
label.115
defaultWizForm.70.1.32
goto.900
label.116
defaultWizForm.75.1.32
goto.900
label.117
defaultWizForm.17.1.31
goto.900
label.118
defaultWizForm.47.1.31
goto.900
label.119
defaultWizForm.65.1.31
goto.900
label.120
defaultWizForm.66.1.31
goto.900
label.121
defaultWizForm.70.1.31
goto.900
label.122
defaultWizForm.75.1.31
goto.900
label.123
defaultWizForm.17.1.30
goto.900
label.124
defaultWizForm.47.1.30
goto.900
label.125
defaultWizForm.65.1.30
goto.900
label.126
defaultWizForm.66.1.30
goto.900
label.127
defaultWizForm.70.1.30
goto.900
label.128
defaultWizForm.75.1.30
goto.900
label.900"""
