UID = "9023B6A4"
Name = "79110B91"
#Boneria (9), Ottis (62), Adriana (79), Phaleon (88)
#From 35 to 29
InitScript = """
setNpcType.3
gotoLabelByRandom.50.29
gotoRandomLabel.28.0
label.0
defaultWizForm.9.0.36
goto.900
label.1
defaultWizForm.62.0.36
goto.900
label.2
defaultWizForm.79.0.36
goto.900
label.3
defaultWizForm.88.0.36
goto.900
label.4
defaultWizForm.9.0.35
goto.900
label.5
defaultWizForm.62.0.35
goto.900
label.6
defaultWizForm.79.0.35
goto.900
label.7
defaultWizForm.88.0.35
goto.900
label.8
defaultWizForm.9.0.34
goto.900
label.9
defaultWizForm.62.0.34
goto.900
label.10
defaultWizForm.79.0.34
goto.900
label.11
defaultWizForm.88.0.34
goto.900
label.12
defaultWizForm.9.0.33
goto.900
label.13
defaultWizForm.62.0.33
goto.900
label.14
defaultWizForm.79.0.33
goto.900
label.15
defaultWizForm.88.0.33
goto.900
label.16
defaultWizForm.9.0.32
goto.900
label.17
defaultWizForm.62.0.32
goto.900
label.18
defaultWizForm.79.0.32
goto.900
label.19
defaultWizForm.88.0.32
goto.900
label.20
defaultWizForm.9.0.31
goto.900
label.21
defaultWizForm.62.0.31
goto.900
label.22
defaultWizForm.79.0.31
goto.900
label.23
defaultWizForm.88.0.31
goto.900
label.24
defaultWizForm.9.0.30
goto.900
label.25
defaultWizForm.62.0.30
goto.900
label.26
defaultWizForm.79.0.30
goto.900
label.27
defaultWizForm.88.0.30
goto.900
label.28
gotoRandomLabel.28.29
label.29
defaultWizForm.9.0.36
goto.57
label.30
defaultWizForm.62.0.36
goto.57
label.31
defaultWizForm.79.0.36
goto.57
label.32
defaultWizForm.88.0.36
goto.57
label.33
defaultWizForm.9.0.35
goto.57
label.34
defaultWizForm.62.0.35
goto.57
label.35
defaultWizForm.79.0.35
goto.57
label.36
defaultWizForm.88.0.35
goto.57
label.37
defaultWizForm.9.0.34
goto.57
label.38
defaultWizForm.62.0.34
goto.57
label.39
defaultWizForm.79.0.34
goto.57
label.40
defaultWizForm.88.0.34
goto.57
label.41
defaultWizForm.9.0.33
goto.57
label.42
defaultWizForm.62.0.33
goto.57
label.43
defaultWizForm.79.0.33
goto.57
label.44
defaultWizForm.88.0.33
goto.57
label.45
defaultWizForm.9.0.32
goto.57
label.46
defaultWizForm.62.0.32
goto.57
label.47
defaultWizForm.79.0.32
goto.57
label.48
defaultWizForm.88.0.32
goto.57
label.49
defaultWizForm.9.0.31
goto.57
label.50
defaultWizForm.62.0.31
goto.57
label.51
defaultWizForm.79.0.31
goto.57
label.52
defaultWizForm.88.0.31
goto.57
label.53
defaultWizForm.9.0.30
goto.57
label.54
defaultWizForm.62.0.30
goto.57
label.55
defaultWizForm.79.0.30
goto.57
label.56
defaultWizForm.88.0.30
goto.57
label.57
gotoRandomLabel.28.58
label.58
defaultWizForm.9.1.36
goto.900
label.59
defaultWizForm.62.1.36
goto.900
label.60
defaultWizForm.79.1.36
goto.900
label.61
defaultWizForm.88.1.36
goto.900
label.62
defaultWizForm.9.1.35
goto.900
label.63
defaultWizForm.62.1.35
goto.900
label.64
defaultWizForm.79.1.35
goto.900
label.65
defaultWizForm.88.1.35
goto.900
label.66
defaultWizForm.9.1.34
goto.900
label.67
defaultWizForm.62.1.34
goto.900
label.68
defaultWizForm.79.1.34
goto.900
label.69
defaultWizForm.88.1.34
goto.900
label.70
defaultWizForm.9.1.33
goto.900
label.71
defaultWizForm.62.1.33
goto.900
label.72
defaultWizForm.79.1.33
goto.900
label.73
defaultWizForm.88.1.33
goto.900
label.74
defaultWizForm.9.1.32
goto.900
label.75
defaultWizForm.62.1.32
goto.900
label.76
defaultWizForm.79.1.32
goto.900
label.77
defaultWizForm.88.1.32
goto.900
label.78
defaultWizForm.9.1.31
goto.900
label.79
defaultWizForm.62.1.31
goto.900
label.80
defaultWizForm.79.1.31
goto.900
label.81
defaultWizForm.88.1.31
goto.900
label.82
defaultWizForm.9.1.30
goto.900
label.83
defaultWizForm.62.1.30
goto.900
label.84
defaultWizForm.79.1.30
goto.900
label.85
defaultWizForm.88.1.30
goto.900
label.900"""
