UID = "B1B031A4"
Name = "9A878891"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Человеческое существо...>.0
waitForUser
ifNpcModifierHasValue.1
label.10
say.<Ты здесь не для того, чтобы тратить моё время?>.3
choice.26.<Обмен фей>
choice.9.<Удаление фей>
choice.0.<До встречи>
waitForUser
endIf
setTalkLabels.-1.-1.2
talk.<
    Похоже, ты здесь впервые.
    Я объясню тебе правила, и лучше тебе их запомнить с первого раза: я не люблю повторять их заново.
>
waitForUser
setNpcModifier.-1.-1.1
label.13
setTalkLabels.-1.-1.2
talk.<
    Мне нужны любые {4*дикие феи и их эволюционные формы}, но я не принимаю фей, получаемых через {4*Эволюционные Камни или Камни Регрессии}.
    Феи {4*первой или второй эволюционных форм}, а также более {4*редких стихий}, ценятся больше, чем другие феи.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    За каждую из твоих фей, в зависимости от ценности, я дам тебе {4*Рунические Свитки}.
    Ты можешь их обменять на {4*любую фею, существующую в дикой природе}, у {4*Коллекционеров}, живущих в {4*Тиралине} или же в {4*Данморе}.
    Но каждый из них обменивает {4*фей только определённых стихий}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Если тебе не нужны {4*Светлячки}, то я могу освободить твой инвентарь от них в любой момент.
    Но будь внимательна — я могу удалить только фей, которые {4*хранятся у тебя дома}.
    И если ты решишь это сделать, то это также {4*освободит всех фей-Светлячков, кроме тех, что у тебя находятся в колоде}.
>
waitForUser
goto.10
label.9
setTalkLabels.1.2.1
talk.<Я могу убрать всех {4*Светлячков} из твоего инвентаря, ты согласна на это?>
waitForUser
label.1
ifPlayerHasCards.-1.2.143
removePlayerCards.1.2.143
exit
else
setTalkLabels.-1.-1.0
talk.<У тебя нет {4*Светлячков}, которых я мог бы забрать у тебя.>
waitForUser
goto.10
label.2
goto.10
label.12
ifPlayerHasCards.1.2.0
goto.4
else
ifPlayerHasCards.1.2.1
goto.5
else
ifPlayerHasCards.1.2.2
goto.3
else
ifPlayerHasCards.1.2.3
goto.4
else
ifPlayerHasCards.1.2.4
goto.4
else
ifPlayerHasCards.1.2.5
goto.5
else
ifPlayerHasCards.1.2.6
goto.4
else
ifPlayerHasCards.1.2.7
goto.5
else
ifPlayerHasCards.1.2.8
goto.3
else
ifPlayerHasCards.1.2.9
goto.4
else
ifPlayerHasCards.1.2.10
goto.3
else
ifPlayerHasCards.1.2.11
goto.4
else
ifPlayerHasCards.1.2.12
goto.5
else
ifPlayerHasCards.1.2.13
goto.6
else
ifPlayerHasCards.1.2.14
goto.5
else
ifPlayerHasCards.1.2.15
goto.6
else
ifPlayerHasCards.1.2.16
goto.6
else
ifPlayerHasCards.1.2.17
goto.6
else
ifPlayerHasCards.1.2.18
goto.4
else
ifPlayerHasCards.1.2.19
goto.5
else
ifPlayerHasCards.1.2.20
goto.6
else
ifPlayerHasCards.1.2.21
goto.3
else
ifPlayerHasCards.1.2.22
goto.4
else
ifPlayerHasCards.1.2.23
goto.5
else
ifPlayerHasCards.1.2.24
goto.6
else
ifPlayerHasCards.1.2.25
goto.5
else
ifPlayerHasCards.1.2.26
goto.6
else
ifPlayerHasCards.1.2.27
goto.7
else
ifPlayerHasCards.1.2.28
goto.5
else
ifPlayerHasCards.1.2.29
goto.6
else
ifPlayerHasCards.1.2.30
goto.4
else
ifPlayerHasCards.1.2.31
goto.5
else
ifPlayerHasCards.1.2.32
goto.2
else
ifPlayerHasCards.1.2.33
goto.6
else
ifPlayerHasCards.1.2.34
goto.7
else
ifPlayerHasCards.1.2.35
goto.5
else
ifPlayerHasCards.1.2.36
goto.6
else
ifPlayerHasCards.1.2.37
goto.4
else
ifPlayerHasCards.1.2.38
goto.6
else
ifPlayerHasCards.1.2.39
goto.6
else
ifPlayerHasCards.1.2.40
goto.3
else
ifPlayerHasCards.1.2.41
goto.4
else
ifPlayerHasCards.1.2.42
goto.7
else
ifPlayerHasCards.1.2.43
goto.5
else
ifPlayerHasCards.1.2.44
goto.6
else
ifPlayerHasCards.1.2.45
goto.6
else
ifPlayerHasCards.1.2.46
goto.7
else
ifPlayerHasCards.1.2.47
goto.5
else
ifPlayerHasCards.1.2.48
goto.6
else
ifPlayerHasCards.1.2.49
goto.6
else
ifPlayerHasCards.1.2.50
goto.4
else
ifPlayerHasCards.1.2.51
goto.5
else
ifPlayerHasCards.1.2.52
goto.4
else
ifPlayerHasCards.1.2.53
goto.5
else
ifPlayerHasCards.1.2.54
goto.5
else
ifPlayerHasCards.1.2.55
goto.6
else
ifPlayerHasCards.1.2.56
goto.6
else
ifPlayerHasCards.1.2.57
goto.7
else
ifPlayerHasCards.1.2.58
goto.6
else
ifPlayerHasCards.1.2.59
goto.7
else
ifPlayerHasCards.1.2.60
goto.6
else
ifPlayerHasCards.1.2.61
goto.7
else
ifPlayerHasCards.1.2.62
goto.5
else
ifPlayerHasCards.1.2.63
goto.6
else
ifPlayerHasCards.1.2.64
goto.6
else
ifPlayerHasCards.1.2.65
goto.5
else
ifPlayerHasCards.1.2.66
goto.6
else
ifPlayerHasCards.1.2.67
goto.5
else
ifPlayerHasCards.1.2.68
goto.6
else
ifPlayerHasCards.1.2.69
goto.6
else
ifPlayerHasCards.1.2.70
goto.7
else
ifPlayerHasCards.1.2.71
goto.6
else
ifPlayerHasCards.1.2.72
goto.7
else
ifPlayerHasCards.1.2.73
goto.5
else
ifPlayerHasCards.1.2.74
goto.6
else
ifPlayerHasCards.1.2.75
goto.6
else
ifPlayerHasCards.1.2.76
goto.7
else
ifPlayerHasCards.1.2.77
goto.3
else
ifPlayerHasCards.1.2.78
goto.4
else
ifPlayerHasCards.1.2.79
goto.3
else
ifPlayerHasCards.1.2.80
goto.4
else
ifPlayerHasCards.1.2.81
goto.3
else
ifPlayerHasCards.1.2.82
goto.4
else
ifPlayerHasCards.1.2.83
goto.3
else
ifPlayerHasCards.1.2.84
goto.4
else
ifPlayerHasCards.1.2.85
goto.6
else
ifPlayerHasCards.1.2.86
goto.7
else
ifPlayerHasCards.1.2.87
goto.6
else
ifPlayerHasCards.1.2.88
goto.3
else
ifPlayerHasCards.1.2.89
goto.4
else
setTalkLabels.-1.-1.0
talk.<У тебя нет подходящей для обмена феи.>
waitForUser
goto.10
label.3
setTalkLabels.20.10.1
talk.<
    Я готов отдать за твою фею {4*один Рунический Свиток}.
    Ты согласна на моё предложение?
>
waitForUser
label.20
givePlayerCards.1.0.102
tradeWizform.143
exit
else
goto.10
label.4
setTalkLabels.21.10.1
talk.<
    Я готов отдать за твою фею {4*два Рунических Свитка}.
    Ты согласна на моё предложение?
>
waitForUser
label.21
givePlayerCards.2.0.102
tradeWizform.143
exit
else
goto.10
label.5
setTalkLabels.22.10.1
talk.<
    Я готов отдать за твою фею {4*три Рунических Свитка}.
    Ты согласна на моё предложение?
>
waitForUser
label.22
givePlayerCards.3.0.102
tradeWizform.143
exit
else
goto.10
label.6
setTalkLabels.23.10.1
talk.<
    Я готов отдать за твою фею {4*четыре Рунических Свитка}.
    Ты согласна на моё предложение?
>
waitForUser
label.23
givePlayerCards.4.0.102
tradeWizform.143
exit
else
goto.10
label.7
setTalkLabels.24.10.1
talk.<
    Я готов отдать за твою фею {4*пять Рунических Свитков}.
    Ты согласна на моё предложение?
>
waitForUser
label.24
givePlayerCards.5.0.102
tradeWizform.143
exit
else
goto.10
label.26
say.<
    Ты принесла новых фей для меня?
    Я всегда нуждаюсь в них, как никто другой...
>.3
choice.13.<Как это работает?>
choice.12.<Обмен>
choice.11.<Назад>
waitForUser
label.14
goto.10
label.11
goto.10
label.0
exit"""
InitScript = """
setModel.u002s02m
defaultWizForm.143.0.9"""
UpdateScript = "lookAtPlayer.0.1"
