UID = "900FC934"
Name = "389D7EB1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<
    Гном {4*Эйрик} приветствует тебя, чужестранница.
>.0
waitForUser
ifPlayerHasCards.1.0.33
setTalkLabels.-1.-1.0
talk.<
    Я желаю, чтобы тебе в дороге сопутствовала удача, Эми.
>
waitForUser
goto.11
else
setTalkLabels.-1.-1.2
talk.<
	Ты уже знаешь о том, что в нашу {4*Занзару} вторглись {4*Тёмные Эльфы}?
	Не так давно они покинули {4*Царство Тьмы} и заблокировали все дороги, связывающие города между друг другом.
	{4*Монагам}, деревня гномов, оказалась первой, что стала отрезанной от остального мира.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я пришёл в {4*Тиралин} в поисках помощи, но никто не хочет помогать нам, {4*гномам}.
	Кто-то распускает грязные слухи о том, что {4*Квинлин}, один из трёх наших правителей, заключил тайный союз с {4*Тёмными Эльфами}.
	Но, конечно, это всё ложь.
	Он никогда бы не поступил так.
>
waitForUser
setTalkLabels.1.2.1
talk.<
    Итак, я предлагаю тебе сделку, странница.
	Дуэль!
	Если ты победишь меня, то получишь награду, – {4*руну телепортации, которая перенесёт тебя прямо в {4*Монагам}.
	Что скажешь?
	Рискнешь ли своим хрупким телом ради спасения гномьего народа?
>
waitForUser
label.1
setCamera.1006
fight.-1.0
label.2
setTalkLabels.-1.-1.0
talk.<Жаль, я всё ещё жду достойного соперника.>
waitForUser
label.11"""
InitScript = """
ifNpcModifierHasValue.0
setModel.b012s00m
defaultWizForm.4.0.17
defaultWizForm.5.1.13
defaultWizForm.4.2.11
endIf
ifNpcModifierHasValue.1
setModel.b012s00m
defaultWizForm.88.0.8
defaultWizForm.8.1.9
defaultWizForm.4.2.9
defaultWizForm.81.3.7
endIf"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
setCamera.3005
givePlayerCards.1.0.33
givePlayerCards.1.0.107
setTalkLabels.-1.-1.2
talk.<
    Ты выиграла.
	Вот твоя {4*руна Монагама}, - гномы всегда держат своё слово.
	Но будь осторожна, к сожалению ты не сможешь избежать битв с {4*Тёмными Эльфами}.
>
waitForUser
exit"""
VictoriousScript = "killPlayer"
