UID = "9E31E034"
Name = "316DB7A1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<...>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<...>
waitForUser
label.0
say.<...>.1
choice.1.<Диалог>
choice.2.<До встречи>
waitForUser
label.1
say.<...>.1
choice.1.<Книга фей>
choice.1.<Основание Тиралина>
choice.2.<Назад>
waitForUser
label.2
exit"""
InitScript = "setModel.b004s21m"
UpdateScript = "lookAtPlayer.0.1"
