UID = "9E31E034"
Name = "316DB7A1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<...>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<...>
waitForUser
label.0
say.<...>.1
choice.1.<Диалог>
choice.2.<До встречи>
waitForUser
label.1
say.<...>.3
choice.6.<Тиралин, город фей>
choice.5.<Книга Фей>
choice.3.<Назад>
waitForUser
label.5
setTalkLabels.-1.-1.2
talk.<
    Феи всегда были неотъемлемой частью жизни Занзары.
	Они защищали нас от неприятностей, помогали нам в повседневных делах, а также были нашими неразлучными друзьями.
	Взамен мы ухаживали за окружающей нас природой, в которой жили феи, а также противостояли вредным и опасным феям Хаоса, Тьмы, Огня...
	которые всегда искали способ причинить другим неприятности!
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Но так было очень давно.
	Мне грустно об этом говорить, но сейчас это звучит, словно сказочные истории из прошлого, нежели ежедневная реальность.
	Теперь дикие феи стали проявлять агрессию к любому, кто посмеет зайти на их территории, а богатая история союза рас Занзары и фей осталась лишь на страницах книг...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Почему это произошло?
	Это был бы очень долгий разговор, поэтому я просто скажу, что закрытие порталов в человеческий мир было одной из главных причин этого.
	И всё же я считаю, что мы не можем позволить себе забыть о том, какую важную роль феи играют в жизни Занзары.
	Даже если всё сильно изменилось.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    С давних пор Книга фей использовалась для того, чтобы передавать знания и мудрость от одного поколения к другому - или, по крайней мере, я считаю, что это должно быть именно так. 
>
waitForUser
ifPlayerHasCards.1.0.58
goto.7
else
setTalkLabels.-1.-1.0
talk.<
    У тебя даже нет {4*Книги фей}?
	Это ужасно!
	Возьми мою, я её тебе дарю!
	Как только ты узнаешь больше о своих феях, то возвращайся ко мне, и мы сможем обсудить всё подробнее.
>
waitForUser
givePlayerCards.1.0.58
goto.2
label.7
setTalkLabels.8.9.1
talk.<
    Я вижу, что у тебя уже есть собственная Книга фей.
	И поэтому я хотела бы задать тебе один вопрос: ты ведь тоже думаешь, что художественные описания фей намного лучше, чем эти скучные и сухие научные факты об их происхождении?
>
waitForUser
label.8
setTalkLabels.-1.-1.2
talk.<
    Ох, ты не представляешь, как я рада это слышать!
	Сказать по правде, это именно я пишу все эти новые описания феям взамен этих устаревших, чрезвычайно утомительных и совершенно не имеющих ничего с реальностью фактов!
	Не знаю, кто был их автором, но он совершенно не понимает, для чего именно феи должны иметь красивые истории!
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Мир {4*Занзары} населяют очень много рас, - и все они имеют совершенно разные представления о том, как именно возник этот мир.
	Именно поэтому важно, чтобы все узнали о том, что именно думает об этом другие.
	Как мы можем понимать друг друга, если не будем знать, во что именно верят остальные?
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Поэтому я использую мифологию эльфов, гоблинов, гномов и не только.
	Все расы имеют собственные версии о том, кем являются феи, кем были созданы расы, я могу продолжать говорить об этом очень долго.
	Но именно это помогает нам лучше понять наши различия и схожести, чтобы разрешать возможные конфликты.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Вероятно, для тебя всё это крайне запутанным, верно?
	Но разве это не отличная причина начать интересоваться больше историей {4*Занзары}, а также открыть множество забытых тайн, касающихся древних времён?
	Я считаю, что в этом есть скрытая правда, и её понимание зависит целиком от правильной интерпретации...
	поэтому никогда не забывай читать любые книги!
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Извини, я немного увлеклась.
	Мне ещё предстоит много работы, чтобы закончить новую редакцию {4*Книги фей}, и я стараюсь заниматься этим в свободное от работы время.
	Но в один день ты увидишь, что все эти труды были не напрасны, и {4*Книга фей} станет порталом в мир удивительных сказок о прошлом {4*Занзары}.
>
waitForUser
goto.1
label.9
setTalkLabels.-1.-1.2
talk.<
    Так...
	значит, ты из тех, кто предпочитают рассматривать фей как существ для исследований и экспериментов?
	Определённо ты сразу же смогла бы найти общий язык с гномами...
	иногда их приземлённая манера мышления кажется даже в какой-то мере трогательной...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    К сожалению, ты вряд ли найдёшь кого-то, кто мог бы рассказать тебе больше о подобных фактах.
	Конечно, всё ещё можно найти немногочисленных {4*селекционеров фей}, которые занимаются разведением определённых видов, но они знают только о собственных феях.
	Остальные предпочитают думать, что феи являются существами без собственной воли или души, но это лишь отчасти правда.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    В старые времена все феи были способны разговаривать с нами, но всё изменилось, как магия {4*Занзары} начала выходить из-под контроля...
	природные катастрофы, вызванные {4*феями Хаоса, Тьмы и Огня}, навсегда изменили облик этого мира и привели ко многим жертвам.
	Сами феи тоже подверглись влиянию нестабильной магии, теряя рассудок и становясь агрессивными.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Но я всё ещё против экспериментов над феями, - и как таковое "изучение", как это называют гномы, обычно означает именно это.
	Теперь, когда никто не может просить помощи у фей, кроме друидов, мы пожинаем плоды своих ошибок...
	и это не может продолжаться вечно.
	Именно поэтому ты сейчас здесь.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    В любом случае, казна Тиралина не имеет денег на то, чтобы заниматься подобными вещами.
	Более того, я даже думаю, что никому это и не нужно;
	эпоха величественных турниров, где {4*Коллекционеры} сражались с друг другом за право защищать {4*Занзару} от зла, остались в прошлом.
	Мы можем только надеяться, что когда-то это изменится.
>
waitForUser
goto.1
label.3
goto.0
label.2
exit"""
InitScript = "setModel.b004s21m"
UpdateScript = "lookAtPlayer.0.1"
