UID = "E65DD384"
Name = "DEE079A1"
TriggerScript = """
setCamera.1003
playAnimation.13.-1
say.<...>.0
waitForUser
label.0
say.<...>.3
choice.1.<Диалог>
choice.2.<Обмен>
choice.3.<До встречи>
waitForUser
label.2
say.<Используя специальную технику, я могу трансформировать твою пыльцу в более качественную, чем прежде.>.3
choice.6.<Обмен {4*Щепотки Пыльцы фей}>
choice.5.<Обмен {4*Горсти Пыльцы фей}>
choice.4.<Назад>
waitForUser
label.5
tradingCurrency.23173793
tradingItem.2.99D2B4A3
tradingItem.4.AD58B4A3
waitForUser
goto.0
label.6
tradingCurrency.99D2B4A3
tradingItem.2.AD58B4A3
waitForUser
goto.0
label.1
say.<Это место может выглядеть опасным, но здесь тебе ничего не угрожает.>.3
choice.8.<///>
choice.7.<Долгое Путешествие>
choice.4.<Назад>
waitForUser
label.7
setTalkLabels.-1.-1.2
talk.<
    Однажды я решила отправиться в путешествие, — долгое и без конкретного пункта назначения.
	Тогда я не была уверена, чему я должна посвятить свою жизнь...
	и я думала только о том, что не хочу, чтобы остальные узнали о моей растерянности перед этим важным выбором.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Но чем больше я проводила времени наедине с собой, тем сильнее мне казалось, будто бы я трачу свою жизнь впустую.
	Поэтому я решила заняться тренировкой фей, — это помогало мне отвлечься от плохих мыслей и найти мотивацию, которая придавала бы мне сил.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я встретила многих других {4*Коллекционеров}, я обменивалась самыми разнообразными феями, я наблюдала за каждой из них...
	Но основной вопрос всё ещё оставался без ответа: действительно ли это то, чем я хотела бы заниматься всю свою жизнь?
	Или, возможно, есть ещё какой-то путь, о котором я не знаю?
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Через какое-то время я вспомнила про Заповедник Фей — удивительное место, которое было создано для сохранения редких форм фей.
	Когда-то в детстве мои родители водили меня сюда, чтобы показать всевозможных уникальных фей, — и эти воспоминания всегда были одним из самых счастливых моментов моей жизни.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    С тех пор я решила остаться здесь.
	Ты можешь счесть, что это моя нерешительность или страх перед будущим, и ты будешь права.
	Я всё ещё уверена, что я нашла своё место в жизни, просто…
	я думаю, что пока я могу чем-то помогать другим, то это делает твою жизнь не настолько бессмысленной.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    В конце концов, может всё моё путешествие не было таким уж бесцельным?
	Именно это место заставило вспомнить меня о том, что в этом мире живём не только мы, — но и феи тоже.
>
waitForUser
goto.1
label.4
goto.0
label.3
exit"""
InitScript = """
setModel.b002s20m
movementSpeed.10
defaultWizForm.180.0.0"""
UpdateScript = """
label.0
moveSystem.1.0
gotoRandomLabel.3.0
goto.0
label.1
playAnimation.0.30
goto.0
label.2
playAnimation.11.30
goto.0"""
