UID = "9023A1A4"
Name = "79110B91"
#Sillia (8), Phoe (37), Mykori (40)
#From 9 to 6
InitScript = """
setNpcType.3
gotoRandomLabel.12.0
label.0
defaultWizForm.8.0.10
goto.20
label.1
defaultWizForm.37.0.10
goto.20
label.2
defaultWizForm.40.0.10
goto.20
label.3
defaultWizForm.8.0.9
goto.20
label.4
defaultWizForm.37.0.9
goto.20
label.5
defaultWizForm.40.0.9
goto.20
label.6
defaultWizForm.8.0.8
goto.20
label.7
defaultWizForm.37.0.8
goto.20
label.8
defaultWizForm.40.0.8
goto.20
label.9
defaultWizForm.8.0.7
goto.20
label.10
defaultWizForm.37.0.7
goto.20
label.11
defaultWizForm.40.0.7
goto.20
label.20"""
