UID = "9023A5A4"
Name = "79110B91"
InitScript = """
setNpcType.3
gotoRandomLabel.3.0
label.0
defaultWizForm.50.0.20
goto.10
label.1
defaultWizForm.18.0.20
goto.10
label.2
defaultWizForm.38.0.20
goto.10
label.10"""
