UID = "9023A2A4"
Name = "79110B91"
#Keylan (21), Kernunn (22), Gummy (23), Gamelin (24), Phoe (37), Mykori (40), Abery (41), Lana (50), Adriana (79)
#From 35 to 29
InitScript = """
setNpcType.3
gotoLabelByRandom.50.64
gotoRandomLabel.63.0
label.0
defaultWizForm.21.0.36
goto.900
label.1
defaultWizForm.22.0.36
goto.900
label.2
defaultWizForm.23.0.36
goto.900
label.3
defaultWizForm.24.0.36
goto.900
label.4
defaultWizForm.37.0.36
goto.900
label.5
defaultWizForm.40.0.36
goto.900
label.6
defaultWizForm.41.0.36
goto.900
label.7
defaultWizForm.50.0.36
goto.900
label.8
defaultWizForm.79.0.36
goto.900
label.9
defaultWizForm.21.0.35
goto.900
label.10
defaultWizForm.22.0.35
goto.900
label.11
defaultWizForm.23.0.35
goto.900
label.12
defaultWizForm.24.0.35
goto.900
label.13
defaultWizForm.37.0.35
goto.900
label.14
defaultWizForm.40.0.35
goto.900
label.15
defaultWizForm.41.0.35
goto.900
label.16
defaultWizForm.50.0.35
goto.900
label.17
defaultWizForm.79.0.35
goto.900
label.18
defaultWizForm.21.0.34
goto.900
label.19
defaultWizForm.22.0.34
goto.900
label.20
defaultWizForm.23.0.34
goto.900
label.21
defaultWizForm.24.0.34
goto.900
label.22
defaultWizForm.37.0.34
goto.900
label.23
defaultWizForm.40.0.34
goto.900
label.24
defaultWizForm.41.0.34
goto.900
label.25
defaultWizForm.50.0.34
goto.900
label.26
defaultWizForm.79.0.34
goto.900
label.27
defaultWizForm.21.0.33
goto.900
label.28
defaultWizForm.22.0.33
goto.900
label.29
defaultWizForm.23.0.33
goto.900
label.30
defaultWizForm.24.0.33
goto.900
label.31
defaultWizForm.37.0.33
goto.900
label.32
defaultWizForm.40.0.33
goto.900
label.33
defaultWizForm.41.0.33
goto.900
label.34
defaultWizForm.50.0.33
goto.900
label.35
defaultWizForm.79.0.33
goto.900
label.36
defaultWizForm.21.0.32
goto.900
label.37
defaultWizForm.22.0.32
goto.900
label.38
defaultWizForm.23.0.32
goto.900
label.39
defaultWizForm.24.0.32
goto.900
label.40
defaultWizForm.37.0.32
goto.900
label.41
defaultWizForm.40.0.32
goto.900
label.42
defaultWizForm.41.0.32
goto.900
label.43
defaultWizForm.50.0.32
goto.900
label.44
defaultWizForm.79.0.32
goto.900
label.45
defaultWizForm.21.0.31
goto.900
label.46
defaultWizForm.22.0.31
goto.900
label.47
defaultWizForm.23.0.31
goto.900
label.48
defaultWizForm.24.0.31
goto.900
label.49
defaultWizForm.37.0.31
goto.900
label.50
defaultWizForm.40.0.31
goto.900
label.51
defaultWizForm.41.0.31
goto.900
label.52
defaultWizForm.50.0.31
goto.900
label.53
defaultWizForm.79.0.31
goto.900
label.54
defaultWizForm.21.0.30
goto.900
label.55
defaultWizForm.22.0.30
goto.900
label.56
defaultWizForm.23.0.30
goto.900
label.57
defaultWizForm.24.0.30
goto.900
label.58
defaultWizForm.37.0.30
goto.900
label.59
defaultWizForm.40.0.30
goto.900
label.60
defaultWizForm.41.0.30
goto.900
label.61
defaultWizForm.50.0.30
goto.900
label.62
defaultWizForm.79.0.30
goto.900
label.63
gotoRandomLabel.63.64
label.64
defaultWizForm.21.0.36
goto.127
label.65
defaultWizForm.22.0.36
goto.127
label.66
defaultWizForm.23.0.36
goto.127
label.67
defaultWizForm.24.0.36
goto.127
label.68
defaultWizForm.37.0.36
goto.127
label.69
defaultWizForm.40.0.36
goto.127
label.70
defaultWizForm.41.0.36
goto.127
label.71
defaultWizForm.50.0.36
goto.127
label.72
defaultWizForm.79.0.36
goto.127
label.73
defaultWizForm.21.0.35
goto.127
label.74
defaultWizForm.22.0.35
goto.127
label.75
defaultWizForm.23.0.35
goto.127
label.76
defaultWizForm.24.0.35
goto.127
label.77
defaultWizForm.37.0.35
goto.127
label.78
defaultWizForm.40.0.35
goto.127
label.79
defaultWizForm.41.0.35
goto.127
label.80
defaultWizForm.50.0.35
goto.127
label.81
defaultWizForm.79.0.35
goto.127
label.82
defaultWizForm.21.0.34
goto.127
label.83
defaultWizForm.22.0.34
goto.127
label.84
defaultWizForm.23.0.34
goto.127
label.85
defaultWizForm.24.0.34
goto.127
label.86
defaultWizForm.37.0.34
goto.127
label.87
defaultWizForm.40.0.34
goto.127
label.88
defaultWizForm.41.0.34
goto.127
label.89
defaultWizForm.50.0.34
goto.127
label.90
defaultWizForm.79.0.34
goto.127
label.91
defaultWizForm.21.0.33
goto.127
label.92
defaultWizForm.22.0.33
goto.127
label.93
defaultWizForm.23.0.33
goto.127
label.94
defaultWizForm.24.0.33
goto.127
label.95
defaultWizForm.37.0.33
goto.127
label.96
defaultWizForm.40.0.33
goto.127
label.97
defaultWizForm.41.0.33
goto.127
label.98
defaultWizForm.50.0.33
goto.127
label.99
defaultWizForm.79.0.33
goto.127
label.100
defaultWizForm.21.0.32
goto.127
label.101
defaultWizForm.22.0.32
goto.127
label.102
defaultWizForm.23.0.32
goto.127
label.103
defaultWizForm.24.0.32
goto.127
label.104
defaultWizForm.37.0.32
goto.127
label.105
defaultWizForm.40.0.32
goto.127
label.106
defaultWizForm.41.0.32
goto.127
label.107
defaultWizForm.50.0.32
goto.127
label.108
defaultWizForm.79.0.32
goto.127
label.109
defaultWizForm.21.0.31
goto.127
label.110
defaultWizForm.22.0.31
goto.127
label.111
defaultWizForm.23.0.31
goto.127
label.112
defaultWizForm.24.0.31
goto.127
label.113
defaultWizForm.37.0.31
goto.127
label.114
defaultWizForm.40.0.31
goto.127
label.115
defaultWizForm.41.0.31
goto.127
label.116
defaultWizForm.50.0.31
goto.127
label.117
defaultWizForm.79.0.31
goto.127
label.118
defaultWizForm.21.0.30
goto.127
label.119
defaultWizForm.22.0.30
goto.127
label.120
defaultWizForm.23.0.30
goto.127
label.121
defaultWizForm.24.0.30
goto.127
label.122
defaultWizForm.37.0.30
goto.127
label.123
defaultWizForm.40.0.30
goto.127
label.124
defaultWizForm.41.0.30
goto.127
label.125
defaultWizForm.50.0.30
goto.127
label.126
defaultWizForm.79.0.30
goto.127
label.127
gotoRandomLabel.63.128
label.128
defaultWizForm.21.1.36
goto.900
label.129
defaultWizForm.22.1.36
goto.900
label.130
defaultWizForm.23.1.36
goto.900
label.131
defaultWizForm.24.1.36
goto.900
label.132
defaultWizForm.37.1.36
goto.900
label.133
defaultWizForm.40.1.36
goto.900
label.134
defaultWizForm.41.1.36
goto.900
label.135
defaultWizForm.50.1.36
goto.900
label.136
defaultWizForm.79.1.36
goto.900
label.137
defaultWizForm.21.1.35
goto.900
label.138
defaultWizForm.22.1.35
goto.900
label.139
defaultWizForm.23.1.35
goto.900
label.140
defaultWizForm.24.1.35
goto.900
label.141
defaultWizForm.37.1.35
goto.900
label.142
defaultWizForm.40.1.35
goto.900
label.143
defaultWizForm.41.1.35
goto.900
label.144
defaultWizForm.50.1.35
goto.900
label.145
defaultWizForm.79.1.35
goto.900
label.146
defaultWizForm.21.1.34
goto.900
label.147
defaultWizForm.22.1.34
goto.900
label.148
defaultWizForm.23.1.34
goto.900
label.149
defaultWizForm.24.1.34
goto.900
label.150
defaultWizForm.37.1.34
goto.900
label.151
defaultWizForm.40.1.34
goto.900
label.152
defaultWizForm.41.1.34
goto.900
label.153
defaultWizForm.50.1.34
goto.900
label.154
defaultWizForm.79.1.34
goto.900
label.155
defaultWizForm.21.1.33
goto.900
label.156
defaultWizForm.22.1.33
goto.900
label.157
defaultWizForm.23.1.33
goto.900
label.158
defaultWizForm.24.1.33
goto.900
label.159
defaultWizForm.37.1.33
goto.900
label.160
defaultWizForm.40.1.33
goto.900
label.161
defaultWizForm.41.1.33
goto.900
label.162
defaultWizForm.50.1.33
goto.900
label.163
defaultWizForm.79.1.33
goto.900
label.164
defaultWizForm.21.1.32
goto.900
label.165
defaultWizForm.22.1.32
goto.900
label.166
defaultWizForm.23.1.32
goto.900
label.167
defaultWizForm.24.1.32
goto.900
label.168
defaultWizForm.37.1.32
goto.900
label.169
defaultWizForm.40.1.32
goto.900
label.170
defaultWizForm.41.1.32
goto.900
label.171
defaultWizForm.50.1.32
goto.900
label.172
defaultWizForm.79.1.32
goto.900
label.173
defaultWizForm.21.1.31
goto.900
label.174
defaultWizForm.22.1.31
goto.900
label.175
defaultWizForm.23.1.31
goto.900
label.176
defaultWizForm.24.1.31
goto.900
label.177
defaultWizForm.37.1.31
goto.900
label.178
defaultWizForm.40.1.31
goto.900
label.179
defaultWizForm.41.1.31
goto.900
label.180
defaultWizForm.50.1.31
goto.900
label.181
defaultWizForm.79.1.31
goto.900
label.182
defaultWizForm.21.1.30
goto.900
label.183
defaultWizForm.22.1.30
goto.900
label.184
defaultWizForm.23.1.30
goto.900
label.185
defaultWizForm.24.1.30
goto.900
label.186
defaultWizForm.37.1.30
goto.900
label.187
defaultWizForm.40.1.30
goto.900
label.188
defaultWizForm.41.1.30
goto.900
label.189
defaultWizForm.50.1.30
goto.900
label.190
defaultWizForm.79.1.30
goto.900
label.900"""
