UID = "9053B6A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.12.0
label.0
defaultWizForm.10.0.10
goto.20
label.1
defaultWizForm.10.0.9
goto.20
label.2
defaultWizForm.10.0.8
goto.20
label.3
defaultWizForm.10.0.7
goto.20
label.4
defaultWizForm.18.0.10
goto.20
label.5
defaultWizForm.18.0.9
goto.20
label.6
defaultWizForm.18.0.8
goto.20
label.7
defaultWizForm.18.0.7
goto.20
label.8
defaultWizForm.83.0.10
goto.20
label.9
defaultWizForm.83.0.9
goto.20
label.10
defaultWizForm.83.0.8
goto.20
label.11
defaultWizForm.83.0.7
goto.20
label.20"""
