UID = "9053C6A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.21.0
label.0
defaultWizForm.33.0.33
goto.30
label.1
defaultWizForm.33.0.34
goto.30
label.2
defaultWizForm.33.0.35
goto.30
label.3
defaultWizForm.33.0.36
goto.30
label.4
defaultWizForm.33.0.37
goto.30
label.5
defaultWizForm.33.0.38
goto.30
label.6
defaultWizForm.33.0.39
goto.30
label.7
defaultWizForm.34.0.33
goto.30
label.8
defaultWizForm.34.0.34
goto.30
label.9
defaultWizForm.34.0.35
goto.30
label.10
defaultWizForm.34.0.36
goto.30
label.11
defaultWizForm.34.0.37
goto.30
label.12
defaultWizForm.34.0.38
goto.30
label.13
defaultWizForm.34.0.39
goto.30
label.14
defaultWizForm.47.0.33
goto.30
label.15
defaultWizForm.47.0.34
goto.30
label.16
defaultWizForm.47.0.35
goto.30
label.17
defaultWizForm.47.0.36
goto.30
label.18
defaultWizForm.47.0.37
goto.30
label.19
defaultWizForm.47.0.38
goto.30
label.20
defaultWizForm.47.0.39
goto.30
label.30"""
