UID = "9023B5A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.28.0
label.0
defaultWizForm.1.0.22
goto.30
label.1
defaultWizForm.1.0.23
goto.30
label.2
defaultWizForm.1.0.24
goto.30
label.3
defaultWizForm.1.0.25
goto.30
label.4
defaultWizForm.1.0.26
goto.30
label.5
defaultWizForm.1.0.27
goto.30
label.6
defaultWizForm.1.0.28
goto.30
label.7
defaultWizForm.41.0.22
goto.30
label.8
defaultWizForm.41.0.23
goto.30
label.9
defaultWizForm.41.0.24
goto.30
label.10
defaultWizForm.41.0.25
goto.30
label.11
defaultWizForm.41.0.26
goto.30
label.12
defaultWizForm.41.0.27
goto.30
label.13
defaultWizForm.41.0.28
goto.30
label.14
defaultWizForm.38.0.22
goto.30
label.15
defaultWizForm.38.0.23
goto.30
label.16
defaultWizForm.38.0.24
goto.30
label.17
defaultWizForm.38.0.25
goto.30
label.18
defaultWizForm.38.0.26
goto.30
label.19
defaultWizForm.38.0.27
goto.30
label.20
defaultWizForm.38.0.28
goto.30
label.21
defaultWizForm.73.0.22
goto.30
label.22
defaultWizForm.73.0.23
goto.30
label.23
defaultWizForm.73.0.24
goto.30
label.24
defaultWizForm.73.0.25
goto.30
label.25
defaultWizForm.73.0.26
goto.30
label.26
defaultWizForm.73.0.27
goto.30
label.27
defaultWizForm.73.0.28
goto.30
label.30"""
