UID = "9053C1A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.20.0
label.0
defaultWizForm.41.0.22
goto.30
label.1
defaultWizForm.41.0.23
goto.30
label.2
defaultWizForm.41.0.24
goto.30
label.3
defaultWizForm.41.0.25
goto.30
label.4
defaultWizForm.41.0.26
goto.30
label.5
defaultWizForm.41.0.27
goto.30
label.6
defaultWizForm.41.0.28
goto.30
label.7
defaultWizForm.28.0.22
goto.30
label.8
defaultWizForm.28.0.23
goto.30
label.9
defaultWizForm.28.0.24
goto.30
label.10
defaultWizForm.28.0.25
goto.30
label.11
defaultWizForm.28.0.26
goto.30
label.12
defaultWizForm.28.0.27
goto.30
label.13
defaultWizForm.28.0.28
goto.30
label.14
defaultWizForm.12.0.22
goto.30
label.15
defaultWizForm.12.0.23
goto.30
label.16
defaultWizForm.12.0.24
goto.30
label.17
defaultWizForm.12.0.25
goto.30
label.18
defaultWizForm.12.0.26
goto.30
label.19
defaultWizForm.12.0.27
goto.30
label.20
defaultWizForm.12.0.28
goto.30
label.30"""
