UID = "9023A9A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.12.0
label.0
defaultWizForm.21.0.20
goto.20
label.1
defaultWizForm.21.0.19
goto.20
label.2
defaultWizForm.21.0.18
goto.20
label.3
defaultWizForm.21.0.17
goto.20
label.4
defaultWizForm.40.0.20
goto.20
label.5
defaultWizForm.40.0.19
goto.20
label.6
defaultWizForm.40.0.18
goto.20
label.7
defaultWizForm.40.0.17
goto.20
label.8
defaultWizForm.50.0.20
goto.20
label.9
defaultWizForm.50.0.19
goto.20
label.10
defaultWizForm.50.0.18
goto.20
label.11
defaultWizForm.50.0.17
goto.20
label.20"""
