UID = "9023A3A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.9.0
label.0
defaultWizForm.2.0.4
goto.10
label.1
defaultWizForm.6.0.4
goto.10
label.2
defaultWizForm.81.0.4
goto.10
label.3
defaultWizForm.2.0.3
goto.10
label.4
defaultWizForm.6.0.3
goto.10
label.5
defaultWizForm.81.0.3
goto.10
label.6
defaultWizForm.2.0.2
goto.10
label.7
defaultWizForm.6.0.2
goto.10
label.8
defaultWizForm.81.0.2
goto.10
label.10"""
