UID = "9053D2A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.60.0
label.0
defaultWizForm.16.0.45
goto.100
label.1
defaultWizForm.16.0.46
goto.100
label.2
defaultWizForm.16.0.47
goto.100
label.3
defaultWizForm.16.0.48
goto.100
label.4
defaultWizForm.16.0.49
goto.100
label.5
defaultWizForm.16.0.50
goto.100
label.6
defaultWizForm.16.0.51
goto.100
label.7
defaultWizForm.16.0.52
goto.100
label.8
defaultWizForm.16.0.53
goto.100
label.9
defaultWizForm.16.0.54
goto.100
label.10
defaultWizForm.16.0.55
goto.100
label.11
defaultWizForm.16.0.56
goto.100
label.12
defaultWizForm.35.0.45
goto.100
label.13
defaultWizForm.35.0.46
goto.100
label.14
defaultWizForm.35.0.47
goto.100
label.15
defaultWizForm.35.0.48
goto.100
label.16
defaultWizForm.35.0.49
goto.100
label.17
defaultWizForm.35.0.50
goto.100
label.18
defaultWizForm.35.0.51
goto.100
label.19
defaultWizForm.35.0.52
goto.100
label.20
defaultWizForm.35.0.53
goto.100
label.21
defaultWizForm.35.0.54
goto.100
label.22
defaultWizForm.35.0.55
goto.100
label.23
defaultWizForm.35.0.56
goto.100
label.24
defaultWizForm.54.0.45
goto.100
label.25
defaultWizForm.54.0.46
goto.100
label.26
defaultWizForm.54.0.47
goto.100
label.27
defaultWizForm.54.0.48
goto.100
label.28
defaultWizForm.54.0.49
goto.100
label.29
defaultWizForm.54.0.50
goto.100
label.30
defaultWizForm.54.0.51
goto.100
label.31
defaultWizForm.54.0.52
goto.100
label.32
defaultWizForm.54.0.53
goto.100
label.33
defaultWizForm.54.0.54
goto.100
label.34
defaultWizForm.54.0.55
goto.100
label.35
defaultWizForm.54.0.56
goto.100
label.36
defaultWizForm.55.0.45
goto.100
label.37
defaultWizForm.55.0.46
goto.100
label.38
defaultWizForm.55.0.47
goto.100
label.39
defaultWizForm.55.0.48
goto.100
label.40
defaultWizForm.55.0.49
goto.100
label.41
defaultWizForm.55.0.50
goto.100
label.42
defaultWizForm.55.0.51
goto.100
label.43
defaultWizForm.55.0.52
goto.100
label.44
defaultWizForm.55.0.53
goto.100
label.45
defaultWizForm.55.0.54
goto.100
label.46
defaultWizForm.55.0.55
goto.100
label.47
defaultWizForm.55.0.56
goto.100
label.48
defaultWizForm.67.0.45
goto.100
label.49
defaultWizForm.67.0.46
goto.100
label.50
defaultWizForm.67.0.47
goto.100
label.51
defaultWizForm.67.0.48
goto.100
label.52
defaultWizForm.67.0.49
goto.100
label.53
defaultWizForm.67.0.50
goto.100
label.54
defaultWizForm.67.0.51
goto.100
label.55
defaultWizForm.67.0.52
goto.100
label.56
defaultWizForm.67.0.53
goto.100
label.57
defaultWizForm.67.0.54
goto.100
label.58
defaultWizForm.67.0.55
goto.100
label.59
defaultWizForm.67.0.56
goto.100
label.100"""
