UID = "9053C2A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.20.0
label.0
defaultWizForm.30.0.22
goto.30
label.1
defaultWizForm.30.0.23
goto.30
label.2
defaultWizForm.30.0.24
goto.30
label.3
defaultWizForm.30.0.25
goto.30
label.4
defaultWizForm.30.0.26
goto.30
label.5
defaultWizForm.30.0.27
goto.30
label.6
defaultWizForm.30.0.28
goto.30
label.7
defaultWizForm.31.0.22
goto.30
label.8
defaultWizForm.31.0.23
goto.30
label.9
defaultWizForm.31.0.24
goto.30
label.10
defaultWizForm.31.0.25
goto.30
label.11
defaultWizForm.31.0.26
goto.30
label.12
defaultWizForm.31.0.27
goto.30
label.13
defaultWizForm.31.0.28
goto.30
label.14
defaultWizForm.58.0.22
goto.30
label.15
defaultWizForm.58.0.23
goto.30
label.16
defaultWizForm.58.0.24
goto.30
label.17
defaultWizForm.58.0.25
goto.30
label.18
defaultWizForm.58.0.26
goto.30
label.19
defaultWizForm.58.0.27
goto.30
label.20
defaultWizForm.58.0.28
goto.30
label.30"""
