UID = "9053C9A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.35.0
label.0
defaultWizForm.79.0.33
goto.40
label.1
defaultWizForm.79.0.34
goto.40
label.2
defaultWizForm.79.0.35
goto.40
label.3
defaultWizForm.79.0.36
goto.40
label.4
defaultWizForm.79.0.37
goto.40
label.5
defaultWizForm.79.0.38
goto.40
label.6
defaultWizForm.79.0.39
goto.40
label.7
defaultWizForm.41.0.33
goto.40
label.8
defaultWizForm.41.0.34
goto.40
label.9
defaultWizForm.41.0.35
goto.40
label.10
defaultWizForm.41.0.36
goto.40
label.11
defaultWizForm.41.0.37
goto.40
label.12
defaultWizForm.41.0.38
goto.40
label.13
defaultWizForm.41.0.39
goto.40
label.14
defaultWizForm.22.0.33
goto.40
label.15
defaultWizForm.22.0.34
goto.40
label.16
defaultWizForm.22.0.35
goto.40
label.17
defaultWizForm.22.0.36
goto.40
label.18
defaultWizForm.22.0.37
goto.40
label.19
defaultWizForm.22.0.38
goto.40
label.20
defaultWizForm.22.0.39
goto.40
label.21
defaultWizForm.9.0.33
goto.40
label.22
defaultWizForm.9.0.34
goto.40
label.23
defaultWizForm.9.0.35
goto.40
label.24
defaultWizForm.9.0.36
goto.40
label.25
defaultWizForm.9.0.37
goto.40
label.26
defaultWizForm.9.0.38
goto.40
label.27
defaultWizForm.9.0.39
goto.40
label.28
defaultWizForm.51.0.33
goto.40
label.29
defaultWizForm.51.0.34
goto.40
label.30
defaultWizForm.51.0.35
goto.40
label.31
defaultWizForm.51.0.36
goto.40
label.32
defaultWizForm.51.0.37
goto.40
label.33
defaultWizForm.51.0.38
goto.40
label.34
defaultWizForm.51.0.39
goto.40
label.40"""
