UID = "9053C8A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.35.0
label.0
defaultWizForm.11.0.33
goto.40
label.1
defaultWizForm.11.0.34
goto.40
label.2
defaultWizForm.11.0.35
goto.40
label.3
defaultWizForm.11.0.36
goto.40
label.4
defaultWizForm.11.0.37
goto.40
label.5
defaultWizForm.11.0.38
goto.40
label.6
defaultWizForm.11.0.39
goto.40
label.7
defaultWizForm.53.0.33
goto.40
label.8
defaultWizForm.53.0.34
goto.40
label.9
defaultWizForm.53.0.35
goto.40
label.10
defaultWizForm.53.0.36
goto.40
label.11
defaultWizForm.53.0.37
goto.40
label.12
defaultWizForm.53.0.38
goto.40
label.13
defaultWizForm.53.0.39
goto.40
label.14
defaultWizForm.56.0.33
goto.40
label.15
defaultWizForm.56.0.34
goto.40
label.16
defaultWizForm.56.0.35
goto.40
label.17
defaultWizForm.56.0.36
goto.40
label.18
defaultWizForm.56.0.37
goto.40
label.19
defaultWizForm.56.0.38
goto.40
label.20
defaultWizForm.56.0.39
goto.40
label.21
defaultWizForm.27.0.33
goto.40
label.22
defaultWizForm.27.0.34
goto.40
label.23
defaultWizForm.27.0.35
goto.40
label.24
defaultWizForm.27.0.36
goto.40
label.25
defaultWizForm.27.0.37
goto.40
label.26
defaultWizForm.27.0.38
goto.40
label.27
defaultWizForm.27.0.39
goto.40
label.28
defaultWizForm.32.0.33
goto.40
label.29
defaultWizForm.32.0.34
goto.40
label.30
defaultWizForm.32.0.35
goto.40
label.31
defaultWizForm.32.0.36
goto.40
label.32
defaultWizForm.32.0.37
goto.40
label.33
defaultWizForm.32.0.38
goto.40
label.34
defaultWizForm.32.0.39
goto.40
label.40"""
