UID = "9023B2A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.12.0
label.0
defaultWizForm.9.0.16
goto.20
label.1
defaultWizForm.9.0.15
goto.20
label.2
defaultWizForm.9.0.14
goto.20
label.3
defaultWizForm.9.0.13
goto.20
label.4
defaultWizForm.41.0.16
goto.20
label.5
defaultWizForm.41.0.15
goto.20
label.6
defaultWizForm.41.0.14
goto.20
label.7
defaultWizForm.41.0.13
goto.20
label.8
defaultWizForm.38.0.16
goto.20
label.9
defaultWizForm.38.0.15
goto.20
label.10
defaultWizForm.38.0.14
goto.20
label.11
defaultWizForm.38.0.13
goto.20
label.20"""
