UID = "9023A8A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.12.0
label.0
defaultWizForm.2.0.10
goto.20
label.1
defaultWizForm.2.0.9
goto.20
label.2
defaultWizForm.2.0.8
goto.20
label.3
defaultWizForm.2.0.7
goto.20
label.4
defaultWizForm.23.0.10
goto.20
label.5
defaultWizForm.23.0.9
goto.20
label.6
defaultWizForm.23.0.8
goto.20
label.7
defaultWizForm.23.0.7
goto.20
label.8
defaultWizForm.81.0.10
goto.20
label.9
defaultWizForm.81.0.9
goto.20
label.10
defaultWizForm.81.0.8
goto.20
label.11
defaultWizForm.81.0.7
goto.20
label.20"""
