UID = "9023C9A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.12.0
label.0
defaultWizForm.25.0.33
goto.20
label.1
defaultWizForm.25.0.32
goto.20
label.2
defaultWizForm.25.0.31
goto.20
label.3
defaultWizForm.25.0.30
goto.20
label.4
defaultWizForm.25.0.29
goto.20
label.5
defaultWizForm.64.0.33
goto.20
label.6
defaultWizForm.64.0.32
goto.20
label.7
defaultWizForm.64.0.31
goto.20
label.8
defaultWizForm.64.0.30
goto.20
label.9
defaultWizForm.64.0.29
goto.20
label.10
defaultWizForm.48.0.33
goto.20
label.11
defaultWizForm.48.0.32
goto.20
label.12
defaultWizForm.48.0.31
goto.20
label.11
defaultWizForm.48.0.30
goto.20
label.11
defaultWizForm.48.0.29
goto.20
label.20"""
