UID = "9023B2A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.12.0
label.0
defaultWizForm.9.0.36
goto.20
label.1
defaultWizForm.9.0.35
goto.20
label.2
defaultWizForm.9.0.34
goto.20
label.3
defaultWizForm.9.0.33
goto.20
label.4
defaultWizForm.41.0.36
goto.20
label.5
defaultWizForm.41.0.35
goto.20
label.6
defaultWizForm.41.0.34
goto.20
label.7
defaultWizForm.41.0.33
goto.20
label.8
defaultWizForm.24.0.36
goto.20
label.9
defaultWizForm.24.0.35
goto.20
label.10
defaultWizForm.24.0.34
goto.20
label.11
defaultWizForm.24.0.33
goto.20
label.20"""
