UID = "CD6BA214"
Name = "6E781E01"
TriggerScript = """
setCamera.1002
playAnimation.13.-1
gotoRandomLabel.3.10
label.10
say.<
    {4*Тиралин} обладает весьма богатой историей, уходящей далеко в старые времена.
    Изначально это было всего лишь небольшое поселение, основанное людьми, но, к сожалению, оно было полностью разрушено во время событий {4*Чёрного Солнца}.
    Тогда один из огромных вулканов, существующих в {4*Занзаре}, внезапно проснулся, и он уничтожил часть земель, полностью изменив их облик.
>.0
goto.13
label.11
say.<Основание Тиралина>.0
goto.13
label.12
say.<
    Вместе с этим закончилась {4*эпоха Драконов} и началась {4*эпоха Друидов}.
    Тем, кто был магически одарён, {4*феи} дали возможность помочь им в восстановлении природы, и таким образом появились {4*Карты Стихий}.
    За долгие годы своей непрерывной работы {4*Друиды} смогли превратить эти пепельные степи в {4*Зачарованный Лес}, удивительное и волшебное место.
>.0
goto.13
label.13
waitForUser
label.0
say.<Загадочные Руины>.1
choice.1.<
    Я не знаю точного предназначения этих строений, и у меня не было достаточно времени, чтобы лучше их изучить.
    Моё предположение состоит в том, что некогда это был храм, построенный людьми, чтобы поддерживать магию {4*Друидов} для произрастания {4*Зачарованного Леса}.
    Конечно, после {4*Раскола} и исчезновения {4*Друидов} от некогда величественных строений не осталось практически ничего.
>
choice.2.<
    Говорят, в {4*Эндеве} видели {4*Тёмного Эльфа}...
    это не может быть правдой, верно?
>
choice.3.<
    Когда-то богатые зелёные луга, окружающие эти горы, исчезли и стали выжженной пустошью.
    Реки полностью пересохли, а гигантское море, из которого они происходили, постепенно превратилось в болото, где сейчас обитают {4*Болотные Гоблины}.
    Это была огромная трагедия для всех, включая {4*фей}, которые тоже потеряли свои дома.
>
waitForUser
label.1
setTalkLabels.-1.-1.0
talk.<
    За железными вратами, которые ты можешь найти напротив моего дома, находится путь к таинственным руинам.
    Они являются свидетельством когда-то великой {4*эпохи Друидов}, наследия которой практически не осталось во всей {4*Занзаре}.
    Это очень грустно видеть, что теперь в этих местах обитают лишь только дикие феи.
>
waitForUser
goto.0
label.2
setTalkLabels.-1.-1.2
talk.<
    {4*Тиралин} был отстроен заново объединёнными усилиями людей и эльфов, чтобы стать центром новой жизни для всех жителей {4*Сада фей} и их окрестностей.
    Но мы практически ничего не знаем, что происходило после этого, — множество документов и книг было уничтожено людьми во время {4*Раскола}, и всё, что осталось, до сих пор хранится в {4*архиве Тиралина}, вдали от большинства посторонних глаз.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Если ты захочешь посетить это место, то я советую быть осторожной, там обитают очень опасные {4*феи Света и Энергии}.
    Возможно, руины хранят в себе немало секретов, но без каких-либо подсказок о том, где их найти, всё, что нам остаётся, так это надеяться, что когда-то мы узнаем о них что-либо.
    Или пока не найдётся тот, кто сможет найти {4*сокровище}, о котором ходят легенды.
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.g202s22m
movementSpeed.10
defaultWizForm.2.0.4"""
UpdateScript = """
label.0
moveSystem.1.2
gotoRandomLabel.2.0
goto.0
label.1
playAnimation.0.-1
lookAtPlayer.90.1
goto.0"""
