UID = "D2600234"
Name = "5B6A3F31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.15.-1
say.<Эмми, рад тебя видеть.>.0
waitForUser
ifNpcModifierHasValue.1
setTalkLabels.-1.-1.2
talk.<
    Добро пожаловать в небольшую деревню Эндева.
    Как видишь, она населена мирными {4*Лесными Эльфами}, хотя в последнее время они немного взволнованны.
    Эндева идеальное место для начала путешествия.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Этот дружелюбный лесной эльф, стоящий рядом со мной, идеально подходит для обучения неопытных фей.
    Ты найдешь полезные предметы в нашем магазине.
    Перед началом путешествия хорошенько вооружись.
>
waitForUser
exit
else
setTalkLabels.-1.-1.2
talk.<
    Мы давно тебя ждем.
    {4*Филины} отправились в разные места {4*Занзары}, чтобы помочь тебе в поисках.
    Если ты когда-нибудь нас встретишь, то, не медля, задавай нам вопросы.
    
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Но помни, что никто из нас не знает всей правды.
    Наши знания ограничены — каждый из нас знает только о той местности, в которую нас послали.
>
waitForUser
setNpcModifier.-1.-1.1
endIf"""
InitScript = "setModel.w003s03m"
UpdateScript = "lookAtPlayer.0.0"
