UID = "915CBBB4"
Name = "5B6A3F31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.15.-1
say.<Эми, рад тебя видеть.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Тебе нравится {4*Сад Фей}?
    Действительно, приятное место.
    Однако {4*феи}, живущие здесь, последнее время агрессивны, и везде бегают противные {4*пикси}.
>
waitForUser
talk.<
    Если ты хочешь поймать фею, тебе необходим {4*магический шар}.
    Существуют три разных вида шаров: из {4*серебра}, из {4*золота} и из {4*хрусталя}.
>
waitForUser
talk.<
    Перед тем, как с помощью шара поймать фею, она должен быть ослаблена в поединке фей и схвачена вашей феей.
    Только тогда Фея будет захвачена магическим шаром и отправлена к месту вашего рождения.
>
waitForUser
talk.<
    В зависимости от {4*опыта} феи, которую ты хочешь поймать, тебе понадобиться более мощный шар.
    Ты можешь ловить фей до {4*20-го} уровня с помощью {4*серебряного шара}.
    Для поимки более сильных фей необходимо использовать {4*золотой шар} или даже редкий {4*хрустальный}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<Приходи ко мне в любое время, Эми.>
waitForUser"""
InitScript = "setModel.w003s03m"
UpdateScript = "lookAtPlayer.0.0"
