UID = "15F94A04"
Name = "5B6A3F31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.15.-1
say.<Эми, рад тебя видеть.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Рад тебя видеть, Эми.
    Перед тобой город {4*Монагам}, дом {4*гномов}.
    Гномы не особенно любят чужеземцев, но им очень нужна помощь, особенно сейчас.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<Их кузнечное искусство всегда было причиной подозрений и недоверия со стороны {4*эльфов} и {4*гоблинов}, и многие находят странным, что им нравится жить в тёмных пещерах.>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Многие {4*эльфы} даже верят, что {4*Монагам} находится в легендарном {4*Царстве Тьмы}.
    Конечно, они ошибаются, но ты же знаешь, какими глупыми иной раз бывают сплетни...
>
waitForUser"""
InitScript = "setModel.w003s03m"
UpdateScript = "lookAtPlayer.0.0"
