UID = "6A0F3E34"
Name = "17D17BA1"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Ты пришла сюда в поисках новых фей?>.0
waitForUser
label.0
say.<
    Я давно не видела путешественников в Монагаме.
    Надеюсь, тебе здесь понравится.
>.1
choice.3.<Диалог>
choice.4.<Обмен>
choice.5.<До встречи>
waitForUser
label.3
say.<
    Я могу тебе рассказать об {4*искуственном} разведении фей.
    Это всё, что я знаю.
>.1
choice.6.<Селекция фей>
choice.7.<Семейство Орнеллы>
choice.8.<Старый Отшельник>
choice.9.<Назад>
waitForUser
label.6
setTalkLabels.-1.-1.2
talk.<
    В Книге фей перечислены только дикие феи, встречающиеся в {4*Занзаре}.
    Причина этому — многообразие эволюционных форм, которые можно получить экспериментальным путём.
    Никто не знает, насколько их много и какие феи ещё могут существовать.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Немногие селекционеры фей пытаются понять закономерности, при которых возможно появление новых форм, но пока что никто в этом не преуспел.
    Поэтому мы больше занимаемся сохранением тех видов, что нам удалось найти, например, {4*cемейства Орнеллы}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Нет универсального способа для выведения новых форм фей: гномы пытаются проводить эксперименты на феях, используя посторонние {4*источники энергии}.
    Также этим занимаются и {4*Тёмные Эльфы}, но, полагаю, ты сможешь узнать подробности, только если встретишь одного из них.
    И если он согласится рассказать об этом.
>
waitForUser
goto.3
label.7
setTalkLabels.-1.-1.2
talk.<
    {4*Семейство Орнеллы} уникально: его представители редко встречаются в дикой природе, гораздо чаще их можно найти прирученными.
    Давным-давно нашли способ их искусственного выведения, и с тех пор у каждой из рас {4*Занзары} появилась своя уникальная форма этого вида фей.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Родоначальником этой семьи является {4*Блумелла}.
    Эти феи, живущие в деревьях, кустах и растениях были одними из первых, что вступили в симбиоз с эльфами.
    К сожалению, после того, как большинство фей стали агрессивными, {4*Блумеллу} практически никто не видел в дикой форме.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Болотные Гоблины вывели {4*Камиллу}, чтобы облегчить ловлю {4*фей Воды}.
    Не всем нравится непривлекательный внешний вид {4*Камиллы}, но они гораздо легче переносят влажную атмосферу болот, чем обычная {4*Блумелла}.
    Ведь природный вариант этой феи предпочитает жить в среде, где больше растений.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    {4*Орнелла} — результат экспериментов гномов для выведения более доступных {4*фей Огня}.
    Они хорошо переносят высокие температуры, но предпочитают тёмные места с умеренным количеством света, что идеально для нашего {4*Монагама}.
    Именно поэтому они не так распространены по сравнению с другими видами.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Также существует {4*Изабелла}, но о ней известно немногое.
    Она встречается лишь у {4*Тёмных Эльфов}, и кто знает, как они получили этих фей... 
	Тебе стоит опасаться их, ведь {4*феи Тьмы} остаются одними из самых опасных и редких во всей {4*Занзаре}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я практически забыла рассказать о {4*Стелле}, фее Льда, которая изредка встречается в дикой природе.
    Когда-то они селились на вершинах холодных гор, однако сейчас {4*Стеллу} нигде невозможно найти.
    Редкие экземпляры этого вида ценятся среди {4*Коллекционеров} больше всего.
>
waitForUser
goto.3
label.8
setTalkLabels.-1.-1.2
talk.<
    Неподалеку от {4*Башни Гномов}, в горах, живёт старый гном-отшельник.
    Он один из немногих, кто изучает возможные эволюционные формы, и его основной интерес сосредоточен на {4*семействе Тайнфолов}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Всю свою жизнь гном искал способы трансформировать {4*Тайнфола} в другие формы, чтобы позволить ему овладеть остальными стихиями.
    В отличие от других фей, {4*Тайнфол} обладает уникальной способностью подчинять дикую природу стихий {4*Занзары}.
    Но, чтобы раскрыть его потенциал, требуются годы, а то и десятилетия.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    В лучшие времена этот гном был одним из сильнейших {4*Коллекционеров}, которые путешествовали по всей {4*Занзаре}.
    Возможно, он также был одним из немногих, кто отважился спуститься в само {4*Царство Тьмы}, чтобы найти там {4*фей Хаоса} и {4*Тьмы}.
    Если тебе хотелось бы услышать об этом больше, то, возможно, тебе стоит расспросить его самого.
>
waitForUser
goto.3
label.9
goto.0
label.4
setTalkLabels.1.2.1
talk.<
    Вижу, ты увлеченный {4*Коллекционер фей}.
    Эта фея — одна из немногих {4*фей Огня}, которые остались у нас, {4*гномов}.
    Я готова обменять её на {4*Эволюционный камень Огня}.
    Ты согласна?
>
waitForUser
label.1
ifPlayerHasCards.1.0.52
removePlayerCards.1.0.52
givePlayerCards.1.2.90
exit
else
setTalkLabels.-1.-1.0
talk.<
    Извини, но у тебя нет {4*Эволюционного Камня Огня}.
    Возвращайся, как он будет у тебя.
>
waitForUser
exit
label.2
goto.0
label.5
exit"""
InitScript = """
setModel.b026s00m
defaultWizForm.90.0.9"""
UpdateScript = "lookAtPlayer.0.1"
