UID = "9023D4A4"
Name = "79110B91"
#Electra (43), Callisto (16), Clum (29)
#From 35 to 29
InitScript = """
setNpcType.3
gotoRandomLabel.30.0
label.0
defaultWizForm.43.0.36
goto.1000
label.1
defaultWizForm.43.0.35
goto.1000
label.2
defaultWizForm.43.0.34
goto.1000
label.3
defaultWizForm.43.0.33
goto.1000
label.4
defaultWizForm.43.0.32
goto.1000
label.5
defaultWizForm.43.0.31
goto.1000
label.6
defaultWizForm.43.0.30
goto.1000
label.7
defaultWizForm.16.0.36
goto.1000
label.8
defaultWizForm.16.0.35
goto.1000
label.9
defaultWizForm.16.0.34
goto.1000
label.10
defaultWizForm.16.0.33
goto.1000
label.11
defaultWizForm.16.0.32
goto.1000
label.12
defaultWizForm.16.0.31
goto.1000
label.13
defaultWizForm.16.0.30
goto.1000
label.14
defaultWizForm.29.0.36
goto.1000
label.15
defaultWizForm.29.0.35
goto.1000
label.16
defaultWizForm.29.0.34
goto.1000
label.17
defaultWizForm.29.0.33
goto.1000
label.18
defaultWizForm.29.0.32
goto.1000
label.19
defaultWizForm.29.0.31
goto.1000
label.20
defaultWizForm.29.0.30
goto.1000
label.21
defaultWizForm.43.0.33
defaultWizForm.16.1.33
goto.1000
label.22
defaultWizForm.43.0.33
defaultWizForm.29.1.33
goto.1000
label.23
defaultWizForm.43.0.33
defaultWizForm.43.1.33
goto.1000
label.24
defaultWizForm.16.0.33
defaultWizForm.43.1.33
goto.1000
label.25
defaultWizForm.16.0.33
defaultWizForm.29.1.33
goto.1000
label.26
defaultWizForm.16.0.33
defaultWizForm.16.1.33
goto.1000
label.27
defaultWizForm.29.0.33
defaultWizForm.43.1.33
goto.1000
label.28
defaultWizForm.29.0.33
defaultWizForm.16.1.33
goto.1000
label.29
defaultWizForm.29.0.33
defaultWizForm.29.1.33
goto.1000
label.1000"""
