UID = "3E4CCC34"
Name = "31455C31"
TriggerScript = """
setCamera.1000
say.<Ты видишь перед собой пикси, сидящего на бочонке.>.0
waitForUser
label.0
say.<Пара зелёных глаз с интересом изучают тебя.>.1
choice.3.<Диалог>
choice.2.<Обмен>
choice.1.<Уйти>
waitForUser
label.2
say.<...>.1
choice.7.<Купить 1 кристалл по 5 монет>
choice.6.<Купить 10 кристаллов за 50 монет>
choice.5.<Купить 25 кристаллов за 125 монет>
choice.4.<Назад>
waitForUser
label.7
tradingCurrency.C564B4A3
tradingItem.5.BAA9B8A3
waitForUser
goto.0
label.6
ifPlayerHasCards.50.0.4
removePlayerCards.50.0.4
givePlayerCards.10.0.6
exit
else
setTalkLabels.-1.-1.0
talk.<Пикси недоумённо качает головой. Похоже, у тебя недостаточно денег для этой покупки.>
waitForUser
goto.0
label.5
ifPlayerHasCards.125.0.4
removePlayerCards.125.0.4
givePlayerCards.25.0.6
exit
else
setTalkLabels.-1.-1.0
talk.<Пикси недоумённо качает головой. Похоже, у тебя недостаточно денег для этой покупки.>
waitForUser
goto.0
label.4
goto.0
label.3
setTalkLabels.-1.-1.2
talk.<
    Пикси достаёт из соседней бочки монетку и показывает её тебе.
    В следующий момент он ловко вынимает кристалл из-под крышки бочки под собой, демонстрируя чудеса ловкости.
    Пикси попеременно перекладывает монетку и кристалл между своих двух лап, хитрым взглядом изучая тебя.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Похоже, он готов обменивать твои монеты на кристаллы.
    Впрочем, ты всё ещё не уверена, всегда ли пикси были такими умными...
>
waitForUser
goto.0
label.1
exit"""
InitScript = "setModel.p001s00m"
UpdateScript = "lookAtPlayer.-1.1"
