UID = "CC999B24"
Name = "24E3A591"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.1000
say.<Похоже, что Линнея погружена глубоко в раздумья, и не замечает тебя.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Определённо {4*Квинлин} будет расстроен, когда узнает, что здесь не осталось ничего о нужных ему исследованиях...
    и более того, мой эксперимент снова кончился неудачей...
    ох, ты все ещё здесь?
    Ты сможешь меня найти в главном здании {4*Монагама}, как только я закончу с делами здесь, а пока что ты не могла бы оставить меня одну?
>
waitForUser
exit
endIf
setNpcModifier.-1.-1.1000
setNpcModifier.3402.3.0
say.<
    С тобой всё в порядке?
    Ты уверена, что победила всех этих {4*фей}?
>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я надеялась, что кто-то заметит нашу пропажу, но не ожидала, что моим спасителем окажется человек...
    Меня зовут {4*Линнея}, и спасибо за твою помощь.
    Похоже, что наш эксперимент пошёл не по плану, и он случайно активировал систему сигнализации...
    неизвестным образом оставив меня здесь в одиночестве против всех этих фей! Это было чересчур даже для моих худших прогнозов!
>
waitForUser
talk.<
    Так или иначе, ты смогла отключить сигнализацию, и теперь всё в порядке.
     Надеюсь, что с остальными всё в порядке, и никто не умер в процессе...
    непредвиденных событий, встретившись с...
    очень непредвиденными последствиями телепортации...
    Кстати, если тебя интересует работа, то позже у меня найдётся задание для тебя.
>
waitForUser
talk.<
    Пока что мне нужно некоторое время, чтобы убедиться, что сигнализация точно отключена.
    Будь осторожно, здесь все ещё обитают дикие {4*феи Металла и Энергии}, иногда нападая в самый неподходящий момент...
    но ничего такого, с чем не смогла бы разобраться такой опытный {4*Коллекционер}, верно?
    
>
waitForUser
talk.<
    Подожди, наверняка я должна тебя отблагодарить как-то за своё спасение?
    Почему бы тебе не забрать эту уникальную фею?
    Она осталась здесь ещё с тех старых времён, когда {4*Квинлин} и {4*Магнус}...
    впрочем, я не буду тебе докучать деталями.
    Просто забери её с собой, здесь больше нечего охранять, кроме бесполезной кучи металлома и кусков камня...
>
waitForUser
givePlayerCards.1.2.139
exit"""
InitScript = """
setModel.b014s00m
defaultWizForm.209.0.4"""
UpdateScript = "lookAtPlayer.0.1"
