UID = "B7D0A034"
Name = "E95016B1"
TriggerScript = """
deployNpcAtTrigger.89.1
setCamera.3010
delay.5
setCamera.2000
changeWaypoint.-1.-1
playAnimation.13.-1
setCamera.3011
say.<
    Итак, ты – Эми из мира людей?
    Добро пожаловать к воротам {4*Тиралина}.
>.0
waitForUser
setCamera.1000
setTalkLabels.-1.-1.2
talk.<
    Я рад, что встретил тебя! {4*Рафи} сказал, что ты прибыла в {4*Занзару}, и я должен присмотреть за тобой.
    Но с тех пор произошло много ужасного.
>
waitForUser
talk.<
    Говорят, что ужасные, порочные существа, называемые {4*Тёмными Эльфами}, пришли сюда из {4*Царства тьмы}.
    Из клеток сбежали все {4*пикси}, и огромные {4*терновые кусты} распространяются быстрее огня.
>
waitForUser
talk.<
    И что хуже всего — мой отец, Гном {4*Квинлин}, пропал.
    Он видел, что наступают трудные времена, и теперь, когда он нам нужен, его нигде нет.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я надеюсь, ты понимаешь, что я должен идти искать своего отца.
    Он уже не молод, и ему нужна моя помощь.
    
>
waitForUser
delay.5
givePlayerCards.1.0.31
setCamera.3011
changeWaypoint.-1.1001
setTalkLabels.-1.-1.2
talk.<
    О, чуть не забыл: во время нашей последней встречи, {4*Рафи} попросил меня отдать тебе эту руну.
    Она перенесёт тебя в {4*Данмор}, деревню {4*Болотных Гоблинов}.
    Сейчас их дом находится в осаде {4*Тёмных Эльфов}, и возможно ты сможешь их прогнать оттуда.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Но будь осторожна, {4*Тёмные Эльфы} — непростые противники, и без сильной колоды фей ты не сможешь их победить.
    Прости, но мне действительно надо идти...
>
waitForUser
changeWaypoint.1001.1002
changeWaypoint.1002.1003
removeNpc
exit"""
InitScript = "setModel.d006s02m"
UpdateScript = """
label.0
ifPlayerIsClose.200
startPrelude
endIf
lookAtPlayer.10.1
goto.0"""
