UID = "1836E654"
Name = "6F1516A1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Хм...>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я знаю, что у тебя очень много вопросов, но позволь мне спросить тебя о кое-чём важном.
	Ты никогда не думала, почему ты смогла оказаться в мире {4*Занзары}?
	Почему {4*Страж}, который должен был закрыть все порталы в человеческий мир, не смог исполнить своё предназначение?
	Всё просто — {4*Страж} не был окончательно завершён, именно поэтому ты смогла проникнуть в этот мир.
>
waitForUser
talk.<
	Когда {4*Белый Друид} захотел отделить два мира от друг друга, у него было очень мало времени, чтобы сделать это.
	Если бы люди узнали об его плане, то они приложили бы все усилия, чтобы не позволить ему свершить задуманное.
	Именно тогда {4*Друид} обратился к {4*Квинлину}, — только гномы были способны создать полностью механическое и неуязвимое существо.
>
waitForUser
talk.<
	Но у {4*Квинлина} были другие планы на {4*Стража}.
	В конце концов, он должен был послужить совсем другим целям, — и сам {4*Квинлин} был в такой же опасности, как и сам {4*Белый Друид}.
	Они оба согласились, что защита {4*Занзары} стоит превыше всего, и поэтому они заключили соглашение
	— {4*Страж} станет временной защитой от человеческого мира, пока люди не будут готовы исправить свои ошибки.
>
waitForUser
talk.<
	Как только большинство порталов в человеческий мир оказались закрыты, наступили времена спокойствия...
	но знал ли кто-то о том, на какие жертвы пошёл {4*Квинлин}, чтобы создать {4*Стража}?
	Более того, было ли в его изначальных планах сделать {4*Стража} незавершённым?
	И самое главное, что является источником силы {4*Стража}?
	Я не знаю ответа ни на один из этих вопросов.
>
waitForUser
talk.<
	Послушай меня, ты не должна доверять {4*Квинлину}.
	И {4*Белому Друиду} тоже.
	Ты не можешь доверять даже мне, — меня не интересует ваш род и по большей части судьба {4*Занзары} тоже.
	Но я не хочу искать новое место взамен {4*Царства Тьмы}, когда {4*Тёмные Эльфы} готовы обеспечить меня всем, что мне необходимо для моих экспериментов.
	И это действительно важно для меня.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Ты должна что-то сделать со {4*Стражем}, пока не стало слишком поздно.
	Он превратился в опасное орудие, над которым больше никто из нас не в силах совладать.
	Никто не знает, на что способна сила {4*Стража} или что произойдёт, если...
	в любом случае, поторопись и заверши свою миссию, {4*Избранная}.
>
waitForUser
exit"""
InitScript = "setModel.e011s11m"
UpdateScript = "lookAtPlayer.0.1"
