UID = "ADDC0094"
Name = "BDE38F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.1
say.<Приветствую, гость.>.0
else
say.<О, чужеземец в нашем прекрасном городе!>.0
endIf
waitForUser
ifNpcModifierHasValue.0
setNpcModifier.-1.-1.1
setTalkLabels.-1.-1.2
talk.<
    В {4*Занзаре} настали тяжелые времена.
	Злобные {4*Темные Эльфы}, огромные {4*валуны}, перегораживающие дороги, и много-много других опасностей.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    То, что я разговариваю с огромным человеком, не облегчает мне жизнь!
	Но самое важное правило у нас — гостеприимство, так что если у тебя есть вопросы, то ты пришла по адресу.
>
waitForUser
endIf
label.10
say.<О чем ты хочешь узнать?>.1
choice.0.<Про Болотных Гоблинов>
choice.1.<О валунах и терновых кустах>
choice.2.<Сейчас ничего>
waitForUser
label.0
ifPlayerHasCards.1.0.15
setTalkLabels.-1.-1.0
talk.<
    Все говорят о твоих героических поступках в {4*Данморе}.
	Ты, должно быть, могущественный Повелитель фей, раз бросила вызов {4*Темным эльфам}.
>
waitForUser
else
setTalkLabels.-1.-1.2
talk.<
    О, болотные гоблины достаточно миролюбивы. Они живут в центре {4*Туманных Болот}.
	Их деревня называется {4*Данмор} и построена на деревянных сваях.
	Наверное, это очень шаткая конструкция.
>
waitForUser
talk.<
    Но они говорят, что сейчас здесь много {4*Темных эльфов}.
	Возможно, из-за близости к {4*Царству Тьмы}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Дорога в  {4*Данмор} долгая и опасная.
	Говорят, что пешком туда вообще не добраться.
	Тебе лучше поискать {4*какой-нибудь другой способ}, если хочешь туда попасть.
>
waitForUser
endIf
goto.10
label.1
setTalkLabels.-1.-1.0
talk.<
    Они появились ниоткуда, заблокировав дороги и проходы.
	Они – настоящее бедствие.
	Мы ничего не можем поделать, но я слышала, что можно как-то попросить {4*фей} помочь.
>
waitForUser
goto.10
label.2
exit"""
InitScript = """
setModel.g200s20m
movementSpeed.10"""
UpdateScript = """
label.0
moveSystem.1.3
gotoRandomLabel.3.0
goto.0
label.1
lookAtPlayer.10.1
goto.0
label.2
lookAtPlayer.20.1
goto.0"""
