UID = "9053C1A4"
Name = "79110B91"
#Gremor (7), Mencre (12), Tyberry (18), Mentaur (28), Pterik (62)
#From 35 to 29
InitScript = """
setNpcType.3
gotoLabelByRandom.50.35
gotoRandomLabel.35.0
label.0
defaultWizForm.7.0.36
goto.900
label.1
defaultWizForm.12.0.36
goto.900
label.2
defaultWizForm.18.0.36
goto.900
label.3
defaultWizForm.28.0.36
goto.900
label.4
defaultWizForm.62.0.36
goto.900
label.5
defaultWizForm.7.0.35
goto.900
label.6
defaultWizForm.12.0.35
goto.900
label.7
defaultWizForm.18.0.35
goto.900
label.8
defaultWizForm.28.0.35
goto.900
label.9
defaultWizForm.62.0.35
goto.900
label.10
defaultWizForm.7.0.34
goto.900
label.11
defaultWizForm.12.0.34
goto.900
label.12
defaultWizForm.18.0.34
goto.900
label.13
defaultWizForm.28.0.34
goto.900
label.14
defaultWizForm.62.0.34
goto.900
label.15
defaultWizForm.7.0.33
goto.900
label.16
defaultWizForm.12.0.33
goto.900
label.17
defaultWizForm.18.0.33
goto.900
label.18
defaultWizForm.28.0.33
goto.900
label.19
defaultWizForm.62.0.33
goto.900
label.20
defaultWizForm.7.0.32
goto.900
label.21
defaultWizForm.12.0.32
goto.900
label.22
defaultWizForm.18.0.32
goto.900
label.23
defaultWizForm.28.0.32
goto.900
label.24
defaultWizForm.62.0.32
goto.900
label.25
defaultWizForm.7.0.31
goto.900
label.26
defaultWizForm.12.0.31
goto.900
label.27
defaultWizForm.18.0.31
goto.900
label.28
defaultWizForm.28.0.31
goto.900
label.29
defaultWizForm.62.0.31
goto.900
label.30
defaultWizForm.7.0.30
goto.900
label.31
defaultWizForm.12.0.30
goto.900
label.32
defaultWizForm.18.0.30
goto.900
label.33
defaultWizForm.28.0.30
goto.900
label.34
defaultWizForm.62.0.30
goto.900
label.35
gotoRandomLabel.35.36
label.36
defaultWizForm.7.0.36
goto.71
label.37
defaultWizForm.12.0.36
goto.71
label.38
defaultWizForm.18.0.36
goto.71
label.39
defaultWizForm.28.0.36
goto.71
label.40
defaultWizForm.62.0.36
goto.71
label.41
defaultWizForm.7.0.35
goto.71
label.42
defaultWizForm.12.0.35
goto.71
label.43
defaultWizForm.18.0.35
goto.71
label.44
defaultWizForm.28.0.35
goto.71
label.45
defaultWizForm.62.0.35
goto.71
label.46
defaultWizForm.7.0.34
goto.71
label.47
defaultWizForm.12.0.34
goto.71
label.48
defaultWizForm.18.0.34
goto.71
label.49
defaultWizForm.28.0.34
goto.71
label.50
defaultWizForm.62.0.34
goto.71
label.51
defaultWizForm.7.0.33
goto.71
label.52
defaultWizForm.12.0.33
goto.71
label.53
defaultWizForm.18.0.33
goto.71
label.54
defaultWizForm.28.0.33
goto.71
label.55
defaultWizForm.62.0.33
goto.71
label.56
defaultWizForm.7.0.32
goto.71
label.57
defaultWizForm.12.0.32
goto.71
label.58
defaultWizForm.18.0.32
goto.71
label.59
defaultWizForm.28.0.32
goto.71
label.60
defaultWizForm.62.0.32
goto.71
label.61
defaultWizForm.7.0.31
goto.71
label.62
defaultWizForm.12.0.31
goto.71
label.63
defaultWizForm.18.0.31
goto.71
label.64
defaultWizForm.28.0.31
goto.71
label.65
defaultWizForm.62.0.31
goto.71
label.66
defaultWizForm.7.0.30
goto.71
label.67
defaultWizForm.12.0.30
goto.71
label.68
defaultWizForm.18.0.30
goto.71
label.69
defaultWizForm.28.0.30
goto.71
label.70
defaultWizForm.62.0.30
goto.71
label.71
gotoRandomLabel.35.72
label.72
defaultWizForm.7.1.36
goto.900
label.73
defaultWizForm.12.1.36
goto.900
label.74
defaultWizForm.18.1.36
goto.900
label.75
defaultWizForm.28.1.36
goto.900
label.76
defaultWizForm.62.1.36
goto.900
label.77
defaultWizForm.7.1.35
goto.900
label.78
defaultWizForm.12.1.35
goto.900
label.79
defaultWizForm.18.1.35
goto.900
label.80
defaultWizForm.28.1.35
goto.900
label.81
defaultWizForm.62.1.35
goto.900
label.82
defaultWizForm.7.1.34
goto.900
label.83
defaultWizForm.12.1.34
goto.900
label.84
defaultWizForm.18.1.34
goto.900
label.85
defaultWizForm.28.1.34
goto.900
label.86
defaultWizForm.62.1.34
goto.900
label.87
defaultWizForm.7.1.33
goto.900
label.88
defaultWizForm.12.1.33
goto.900
label.89
defaultWizForm.18.1.33
goto.900
label.90
defaultWizForm.28.1.33
goto.900
label.91
defaultWizForm.62.1.33
goto.900
label.92
defaultWizForm.7.1.32
goto.900
label.93
defaultWizForm.12.1.32
goto.900
label.94
defaultWizForm.18.1.32
goto.900
label.95
defaultWizForm.28.1.32
goto.900
label.96
defaultWizForm.62.1.32
goto.900
label.97
defaultWizForm.7.1.31
goto.900
label.98
defaultWizForm.12.1.31
goto.900
label.99
defaultWizForm.18.1.31
goto.900
label.100
defaultWizForm.28.1.31
goto.900
label.101
defaultWizForm.62.1.31
goto.900
label.102
defaultWizForm.7.1.30
goto.900
label.103
defaultWizForm.12.1.30
goto.900
label.104
defaultWizForm.18.1.30
goto.900
label.105
defaultWizForm.28.1.30
goto.900
label.106
defaultWizForm.62.1.30
goto.900
label.900"""
