UID = "9053C1A4"
Name = "79110B91"
#Mencre (12), Kunit (58), Tanzait (59), Ottis (62), Jina (85), Phaleon (88), Galeon (89)
#From 35 to 29
InitScript = """
setNpcType.3
gotoLabelByRandom.50.49
gotoRandomLabel.49.0
label.0
defaultWizForm.12.0.36
goto.900
label.1
defaultWizForm.58.0.36
goto.900
label.2
defaultWizForm.59.0.36
goto.900
label.3
defaultWizForm.62.0.36
goto.900
label.4
defaultWizForm.85.0.36
goto.900
label.5
defaultWizForm.88.0.36
goto.900
label.6
defaultWizForm.89.0.36
goto.900
label.7
defaultWizForm.12.0.35
goto.900
label.8
defaultWizForm.58.0.35
goto.900
label.9
defaultWizForm.59.0.35
goto.900
label.10
defaultWizForm.62.0.35
goto.900
label.11
defaultWizForm.85.0.35
goto.900
label.12
defaultWizForm.88.0.35
goto.900
label.13
defaultWizForm.89.0.35
goto.900
label.14
defaultWizForm.12.0.34
goto.900
label.15
defaultWizForm.58.0.34
goto.900
label.16
defaultWizForm.59.0.34
goto.900
label.17
defaultWizForm.62.0.34
goto.900
label.18
defaultWizForm.85.0.34
goto.900
label.19
defaultWizForm.88.0.34
goto.900
label.20
defaultWizForm.89.0.34
goto.900
label.21
defaultWizForm.12.0.33
goto.900
label.22
defaultWizForm.58.0.33
goto.900
label.23
defaultWizForm.59.0.33
goto.900
label.24
defaultWizForm.62.0.33
goto.900
label.25
defaultWizForm.85.0.33
goto.900
label.26
defaultWizForm.88.0.33
goto.900
label.27
defaultWizForm.89.0.33
goto.900
label.28
defaultWizForm.12.0.32
goto.900
label.29
defaultWizForm.58.0.32
goto.900
label.30
defaultWizForm.59.0.32
goto.900
label.31
defaultWizForm.62.0.32
goto.900
label.32
defaultWizForm.85.0.32
goto.900
label.33
defaultWizForm.88.0.32
goto.900
label.34
defaultWizForm.89.0.32
goto.900
label.35
defaultWizForm.12.0.31
goto.900
label.36
defaultWizForm.58.0.31
goto.900
label.37
defaultWizForm.59.0.31
goto.900
label.38
defaultWizForm.62.0.31
goto.900
label.39
defaultWizForm.85.0.31
goto.900
label.40
defaultWizForm.88.0.31
goto.900
label.41
defaultWizForm.89.0.31
goto.900
label.42
defaultWizForm.12.0.30
goto.900
label.43
defaultWizForm.58.0.30
goto.900
label.44
defaultWizForm.59.0.30
goto.900
label.45
defaultWizForm.62.0.30
goto.900
label.46
defaultWizForm.85.0.30
goto.900
label.47
defaultWizForm.88.0.30
goto.900
label.48
defaultWizForm.89.0.30
goto.900
label.49
gotoRandomLabel.49.50
label.50
defaultWizForm.12.0.36
goto.99
label.51
defaultWizForm.58.0.36
goto.99
label.52
defaultWizForm.59.0.36
goto.99
label.53
defaultWizForm.62.0.36
goto.99
label.54
defaultWizForm.85.0.36
goto.99
label.55
defaultWizForm.88.0.36
goto.99
label.56
defaultWizForm.89.0.36
goto.99
label.57
defaultWizForm.12.0.35
goto.99
label.58
defaultWizForm.58.0.35
goto.99
label.59
defaultWizForm.59.0.35
goto.99
label.60
defaultWizForm.62.0.35
goto.99
label.61
defaultWizForm.85.0.35
goto.99
label.62
defaultWizForm.88.0.35
goto.99
label.63
defaultWizForm.89.0.35
goto.99
label.64
defaultWizForm.12.0.34
goto.99
label.65
defaultWizForm.58.0.34
goto.99
label.66
defaultWizForm.59.0.34
goto.99
label.67
defaultWizForm.62.0.34
goto.99
label.68
defaultWizForm.85.0.34
goto.99
label.69
defaultWizForm.88.0.34
goto.99
label.70
defaultWizForm.89.0.34
goto.99
label.71
defaultWizForm.12.0.33
goto.99
label.72
defaultWizForm.58.0.33
goto.99
label.73
defaultWizForm.59.0.33
goto.99
label.74
defaultWizForm.62.0.33
goto.99
label.75
defaultWizForm.85.0.33
goto.99
label.76
defaultWizForm.88.0.33
goto.99
label.77
defaultWizForm.89.0.33
goto.99
label.78
defaultWizForm.12.0.32
goto.99
label.79
defaultWizForm.58.0.32
goto.99
label.80
defaultWizForm.59.0.32
goto.99
label.81
defaultWizForm.62.0.32
goto.99
label.82
defaultWizForm.85.0.32
goto.99
label.83
defaultWizForm.88.0.32
goto.99
label.84
defaultWizForm.89.0.32
goto.99
label.85
defaultWizForm.12.0.31
goto.99
label.86
defaultWizForm.58.0.31
goto.99
label.87
defaultWizForm.59.0.31
goto.99
label.88
defaultWizForm.62.0.31
goto.99
label.89
defaultWizForm.85.0.31
goto.99
label.90
defaultWizForm.88.0.31
goto.99
label.91
defaultWizForm.89.0.31
goto.99
label.92
defaultWizForm.12.0.30
goto.99
label.93
defaultWizForm.58.0.30
goto.99
label.94
defaultWizForm.59.0.30
goto.99
label.95
defaultWizForm.62.0.30
goto.99
label.96
defaultWizForm.85.0.30
goto.99
label.97
defaultWizForm.88.0.30
goto.99
label.98
defaultWizForm.89.0.30
goto.99
label.99
gotoRandomLabel.49.100
label.100
defaultWizForm.12.1.36
goto.900
label.101
defaultWizForm.58.1.36
goto.900
label.102
defaultWizForm.59.1.36
goto.900
label.103
defaultWizForm.62.1.36
goto.900
label.104
defaultWizForm.85.1.36
goto.900
label.105
defaultWizForm.88.1.36
goto.900
label.106
defaultWizForm.89.1.36
goto.900
label.107
defaultWizForm.12.1.35
goto.900
label.108
defaultWizForm.58.1.35
goto.900
label.109
defaultWizForm.59.1.35
goto.900
label.110
defaultWizForm.62.1.35
goto.900
label.111
defaultWizForm.85.1.35
goto.900
label.112
defaultWizForm.88.1.35
goto.900
label.113
defaultWizForm.89.1.35
goto.900
label.114
defaultWizForm.12.1.34
goto.900
label.115
defaultWizForm.58.1.34
goto.900
label.116
defaultWizForm.59.1.34
goto.900
label.117
defaultWizForm.62.1.34
goto.900
label.118
defaultWizForm.85.1.34
goto.900
label.119
defaultWizForm.88.1.34
goto.900
label.120
defaultWizForm.89.1.34
goto.900
label.121
defaultWizForm.12.1.33
goto.900
label.122
defaultWizForm.58.1.33
goto.900
label.123
defaultWizForm.59.1.33
goto.900
label.124
defaultWizForm.62.1.33
goto.900
label.125
defaultWizForm.85.1.33
goto.900
label.126
defaultWizForm.88.1.33
goto.900
label.127
defaultWizForm.89.1.33
goto.900
label.128
defaultWizForm.12.1.32
goto.900
label.129
defaultWizForm.58.1.32
goto.900
label.130
defaultWizForm.59.1.32
goto.900
label.131
defaultWizForm.62.1.32
goto.900
label.132
defaultWizForm.85.1.32
goto.900
label.133
defaultWizForm.88.1.32
goto.900
label.134
defaultWizForm.89.1.32
goto.900
label.135
defaultWizForm.12.1.31
goto.900
label.136
defaultWizForm.58.1.31
goto.900
label.137
defaultWizForm.59.1.31
goto.900
label.138
defaultWizForm.62.1.31
goto.900
label.139
defaultWizForm.85.1.31
goto.900
label.140
defaultWizForm.88.1.31
goto.900
label.141
defaultWizForm.89.1.31
goto.900
label.142
defaultWizForm.12.1.30
goto.900
label.143
defaultWizForm.58.1.30
goto.900
label.144
defaultWizForm.59.1.30
goto.900
label.145
defaultWizForm.62.1.30
goto.900
label.146
defaultWizForm.85.1.30
goto.900
label.147
defaultWizForm.88.1.30
goto.900
label.148
defaultWizForm.89.1.30
goto.900
label.900"""
