UID = "52107C84"
Name = "F566BE01"
TriggerScript = """
deployNpcAtTrigger.50.1
setCamera.3003
say.<
    Тревога! У нас незваный гость!
>.1
delay.20
deployNpcAtTrigger.42.39B7B084
startEffect.0.42
playSound.3
setCamera.3000
delay.10
deployNpcAtTrigger.43.54f25a04
startEffect.0.43
playSound.3
setCamera.3002
delay.10
deployNpcAtTrigger.45.52107c84
startEffect.0.45
playSound.3
setCamera.3001
delay.10
talk.<
    Никто не должен пройти на древний завод гномов! Поймайте её!
>
waitForUser
setCamera.1006
fight.1022.1"""
InitScript = """
ifNpcModifierHasValue.0
setNpcType.3
defaultWizForm.87.3.40
endIf
ifNpcModifierHasValue.1
setNpcType.3
defaultWizForm.139.0.19
defaultWizForm.12.1.18
defaultWizForm.129.2.19
defaultWizForm.28.3.17
defaultWizForm.130.4.16
endIf"""
UpdateScript = """
label.0
idle
ifPlayerIsClose.30
startPrelude
endIf
goto.0"""
DefeatedScript = """
removeNpcAtTrigger.49
removeNpcAtTrigger.41
removeNpc"""
