UID = "02989FB4"
Name = "05360321"
TriggerScript = """
playAmyVoice.4
say.<Пара красных глаз изучающе смотрят на тебя.>.0
setCamera.1000
waitForUser
talk.<Похоже, ты потревожила покой этой феи, и теперь боя не избежать...>
waitForUser
fight.-1.0"""
InitScript = """
setNpcType.3
defaultWizForm.132.0.30
defaultWizForm.86.1.31
defaultWizForm.89.2.27
defaultWizForm.63.3.29
defaultWizForm.13.4.27"""
DefeatedScript = """
talk.<
    После долгого боя фея больше не представляет никакой опасности.
    Ты решаешь забрать её с собой, чтобы она больше не стала причиной чьих-то неприятностей...
>
waitForUser
givePlayerCards.1.2.132
createDynamicItems.6.30.-1
startEffect.1.-1
removeNpc"""
