UID = "9171CF24"
Name = "2A28E891"
TriggerScript = """
playAmyVoice.5
say.<Пара красных глаз изучающе смотрят на тебя.>.0
setCamera.1000
waitForUser
talk.<Похоже, ты потревожила покой этой феи, и теперь боя не избежать...>
waitForUser
fight.-1.0"""
InitScript = """
setNpcType.3
defaultWizForm.208.0.19
defaultWizForm.40.1.19
defaultWizForm.23.2.22"""
DefeatedScript = """
talk.<
    После долгого боя фея больше не представляет никакой опасности.
    Ты решаешь забрать её с собой, чтобы она больше не стала причиной чьих-то неприятностей...
>
waitForUser
givePlayerCards.1.2.208
createDynamicItems.6.30.-1
startEffect.1.-1
removeNpc"""
