UID = "E3A72994"
Name = "05360321"
TriggerScript = """
playAmyVoice.5
say.<Пара красных глаз изучающе смотрят на тебя.>.0
setCamera.1000
waitForUser
talk.<Похоже, ты потревожила покой этой феи, и теперь боя не избежать...>
waitForUser
fight.-1.0"""
InitScript = """
setNpcType.3
defaultWizForm.133.0.41
defaultWizForm.7.1.36
defaultWizForm.61.2.40
defaultWizForm.29.3.40
defaultWizForm.49.4.41"""
DefeatedScript = """
talk.<
    После долгого боя фея больше не представляет никакой опасности.
    Ты решаешь забрать её с собой, чтобы она больше не стала причиной чьих-то неприятностей...
>
waitForUser
givePlayerCards.1.2.133
createDynamicItems.6.30.-1
startEffect.1.-1
removeNpc"""
