UID = "9053D1A4"
Name = "79110B91"
#Driane (75), Darbue (60), Pyphia (17)
#From 55 to 46
InitScript = """
setNpcType.3
gotoRandomLabel.59.0
label.0
defaultWizForm.75.0.56
goto.1000
label.1
defaultWizForm.75.0.55
goto.1000
label.2
defaultWizForm.75.0.54
goto.1000
label.3
defaultWizForm.75.0.53
goto.1000
label.4
defaultWizForm.75.0.52
goto.1000
label.5
defaultWizForm.75.0.51
goto.1000
label.6
defaultWizForm.75.0.50
goto.1000
label.7
defaultWizForm.75.0.49
goto.1000
label.8
defaultWizForm.75.0.48
goto.1000
label.9
defaultWizForm.60.0.56
goto.1000
label.10
defaultWizForm.60.0.55
goto.1000
label.11
defaultWizForm.60.0.54
goto.1000
label.12
defaultWizForm.60.0.53
goto.1000
label.13
defaultWizForm.60.0.52
goto.1000
label.14
defaultWizForm.60.0.51
goto.1000
label.15
defaultWizForm.60.0.50
goto.1000
label.16
defaultWizForm.60.0.49
goto.1000
label.17
defaultWizForm.60.0.48
goto.1000
label.18
defaultWizForm.60.0.47
goto.1000
label.19
defaultWizForm.17.0.56
goto.1000
label.20
defaultWizForm.17.0.55
goto.1000
label.21
defaultWizForm.17.0.54
goto.1000
label.22
defaultWizForm.17.0.53
goto.1000
label.23
defaultWizForm.17.0.52
goto.1000
label.24
defaultWizForm.17.0.51
goto.1000
label.25
defaultWizForm.17.0.50
goto.1000
label.26
defaultWizForm.17.0.49
goto.1000
label.27
defaultWizForm.17.0.48
goto.1000
label.28
defaultWizForm.17.0.47
goto.1000
label.29
defaultWizForm.75.0.52
defaultWizForm.60.1.52
goto.1000
label.30
defaultWizForm.75.0.52
defaultWizForm.17.1.52
goto.1000
label.31
defaultWizForm.75.0.52
defaultWizForm.75.1.52
goto.1000
label.32
defaultWizForm.60.0.52
defaultWizForm.75.1.52
goto.1000
label.33
defaultWizForm.60.0.52
defaultWizForm.17.1.52
goto.1000
label.34
defaultWizForm.60.0.52
defaultWizForm.60.1.52
goto.1000
label.35
defaultWizForm.17.0.52
defaultWizForm.75.1.52
goto.1000
label.36
defaultWizForm.17.0.52
defaultWizForm.60.1.52
goto.1000
label.37
defaultWizForm.17.0.52
defaultWizForm.17.1.52
goto.1000
label.38
defaultWizForm.60.0.52
defaultWizForm.75.1.52
defaultWizForm.75.2.52
goto.1000
label.39
defaultWizForm.60.0.52
defaultWizForm.75.1.52
defaultWizForm.17.2.52
goto.1000
label.40
defaultWizForm.60.0.52
defaultWizForm.17.1.52
defaultWizForm.75.2.52
goto.1000
label.41
defaultWizForm.60.0.52
defaultWizForm.17.1.52
defaultWizForm.17.2.52
goto.1000
label.42
defaultWizForm.60.0.52
defaultWizForm.60.1.52
defaultWizForm.75.2.52
goto.1000
label.43
defaultWizForm.60.0.52
defaultWizForm.60.1.52
defaultWizForm.17.2.52
goto.1000
label.44
defaultWizForm.60.0.52
defaultWizForm.60.1.52
defaultWizForm.60.2.52
goto.1000
label.45
defaultWizForm.75.0.52
defaultWizForm.60.1.52
defaultWizForm.60.2.52
goto.1000
label.46
defaultWizForm.75.0.52
defaultWizForm.60.1.52
defaultWizForm.17.2.52
goto.1000
label.47
defaultWizForm.75.0.52
defaultWizForm.17.1.52
defaultWizForm.60.2.52
goto.1000
label.48
defaultWizForm.75.0.52
defaultWizForm.17.1.52
defaultWizForm.17.2.52
goto.1000
label.49
defaultWizForm.75.0.52
defaultWizForm.75.1.52
defaultWizForm.60.2.52
goto.1000
label.50
defaultWizForm.75.0.52
defaultWizForm.75.1.52
defaultWizForm.17.2.52
goto.1000
label.51
defaultWizForm.75.0.52
defaultWizForm.75.1.52
defaultWizForm.75.2.52
goto.1000
label.52
defaultWizForm.17.0.52
defaultWizForm.75.1.52
defaultWizForm.75.2.52
goto.1000
label.53
defaultWizForm.17.0.52
defaultWizForm.75.1.52
defaultWizForm.60.2.52
goto.1000
label.54
defaultWizForm.17.0.52
defaultWizForm.60.1.52
defaultWizForm.75.2.52
goto.1000
label.55
defaultWizForm.17.0.52
defaultWizForm.60.1.52
defaultWizForm.60.2.52
goto.1000
label.56
defaultWizForm.17.0.52
defaultWizForm.17.1.52
defaultWizForm.75.2.52
goto.1000
label.57
defaultWizForm.17.0.52
defaultWizForm.17.1.52
defaultWizForm.60.2.52
goto.1000
label.58
defaultWizForm.17.0.52
defaultWizForm.17.1.52
defaultWizForm.17.2.52
goto.1000
label.1000"""
