UID = "9053D2A4"
Name = "79110B91"
#Gaer (35), Pix (54), Zana (67)
#From 55 to 46
TriggerScript = """
setNpcType.3
gotoRandomLabel.59.0
label.0
defaultWizForm.35.0.56
goto.1000
label.1
defaultWizForm.35.0.55
goto.1000
label.2
defaultWizForm.35.0.54
goto.1000
label.3
defaultWizForm.35.0.53
goto.1000
label.4
defaultWizForm.35.0.52
goto.1000
label.5
defaultWizForm.35.0.51
goto.1000
label.6
defaultWizForm.35.0.50
goto.1000
label.7
defaultWizForm.35.0.49
goto.1000
label.8
defaultWizForm.35.0.48
goto.1000
label.9
defaultWizForm.54.0.56
goto.1000
label.10
defaultWizForm.54.0.55
goto.1000
label.11
defaultWizForm.54.0.54
goto.1000
label.12
defaultWizForm.54.0.53
goto.1000
label.13
defaultWizForm.54.0.52
goto.1000
label.14
defaultWizForm.54.0.51
goto.1000
label.15
defaultWizForm.54.0.50
goto.1000
label.16
defaultWizForm.54.0.49
goto.1000
label.17
defaultWizForm.54.0.48
goto.1000
label.18
defaultWizForm.54.0.47
goto.1000
label.19
defaultWizForm.67.0.56
goto.1000
label.20
defaultWizForm.67.0.55
goto.1000
label.21
defaultWizForm.67.0.54
goto.1000
label.22
defaultWizForm.67.0.53
goto.1000
label.23
defaultWizForm.67.0.52
goto.1000
label.24
defaultWizForm.67.0.51
goto.1000
label.25
defaultWizForm.67.0.50
goto.1000
label.26
defaultWizForm.67.0.49
goto.1000
label.27
defaultWizForm.67.0.48
goto.1000
label.28
defaultWizForm.67.0.47
goto.1000
label.29
defaultWizForm.35.0.52
defaultWizForm.54.1.52
goto.1000
label.30
defaultWizForm.35.0.52
defaultWizForm.67.1.52
goto.1000
label.31
defaultWizForm.35.0.52
defaultWizForm.35.1.52
goto.1000
label.32
defaultWizForm.54.0.52
defaultWizForm.35.1.52
goto.1000
label.33
defaultWizForm.54.0.52
defaultWizForm.67.1.52
goto.1000
label.34
defaultWizForm.54.0.52
defaultWizForm.54.1.52
goto.1000
label.35
defaultWizForm.67.0.52
defaultWizForm.35.1.52
goto.1000
label.36
defaultWizForm.67.0.52
defaultWizForm.54.1.52
goto.1000
label.37
defaultWizForm.67.0.52
defaultWizForm.67.1.52
goto.1000
label.38
defaultWizForm.54.0.52
defaultWizForm.35.1.52
defaultWizForm.35.2.52
goto.1000
label.39
defaultWizForm.54.0.52
defaultWizForm.35.1.52
defaultWizForm.67.2.52
goto.1000
label.40
defaultWizForm.54.0.52
defaultWizForm.67.1.52
defaultWizForm.35.2.52
goto.1000
label.41
defaultWizForm.54.0.52
defaultWizForm.67.1.52
defaultWizForm.67.2.52
goto.1000
label.42
defaultWizForm.54.0.52
defaultWizForm.54.1.52
defaultWizForm.35.1.52
goto.1000
label.43
defaultWizForm.54.0.52
defaultWizForm.54.1.52
defaultWizForm.67.1.52
goto.1000
label.44
defaultWizForm.54.0.52
defaultWizForm.54.1.52
defaultWizForm.54.1.52
goto.1000
label.45
defaultWizForm.35.0.52
defaultWizForm.54.1.52
defaultWizForm.54.2.52
goto.1000
label.46
defaultWizForm.35.0.52
defaultWizForm.54.1.52
defaultWizForm.67.2.52
goto.1000
label.47
defaultWizForm.35.0.52
defaultWizForm.67.1.52
defaultWizForm.54.2.52
goto.1000
label.48
defaultWizForm.35.0.52
defaultWizForm.67.1.52
defaultWizForm.67.2.52
goto.1000
label.49
defaultWizForm.35.0.52
defaultWizForm.35.1.52
defaultWizForm.54.1.52
goto.1000
label.50
defaultWizForm.35.0.52
defaultWizForm.35.1.52
defaultWizForm.67.1.52
goto.1000
label.51
defaultWizForm.35.0.52
defaultWizForm.35.1.52
defaultWizForm.35.1.52
goto.1000
label.52
defaultWizForm.67.0.52
defaultWizForm.35.1.52
defaultWizForm.35.2.52
goto.1000
label.53
defaultWizForm.67.0.52
defaultWizForm.35.1.52
defaultWizForm.54.2.52
goto.1000
label.54
defaultWizForm.67.0.52
defaultWizForm.54.1.52
defaultWizForm.35.2.52
goto.1000
label.55
defaultWizForm.67.0.52
defaultWizForm.54.1.52
defaultWizForm.54.2.52
goto.1000
label.56
defaultWizForm.67.0.52
defaultWizForm.67.1.52
defaultWizForm.35.1.52
goto.1000
label.57
defaultWizForm.67.0.52
defaultWizForm.67.1.52
defaultWizForm.54.1.52
goto.1000
label.58
defaultWizForm.67.0.52
defaultWizForm.67.1.52
defaultWizForm.67.1.52
goto.1000
label.1000"""
