UID = "2476C9B4"
Name = "B18BDDB1"
TriggerScript = """
setCamera.3010
say.<О, это должно быть дом {4*Рафи} ...>.1
playAmyVoice.trg03a
delay.20
setCamera.3011
delay.20
say.<
    ...
    но что это за глупые создания?
>.1
playAmyVoice.trg03b
setCamera.3012
delay.20
removeNpc"""
InitScript = """
setNpcType.4
setCollision.0"""
UpdateScript = """
label.0
ifPlayerIsClose.155
startPrelude
endIf
idle
goto.0"""
