UID = "C598A334"
Name = "955FA731"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Ты тоже пришла из других земель?>.0
waitForUser
label.0
say.<Сейчас гномы как никогда нуждаются в чужой помощи, ты так не думаешь?>.1
choice.3.<Торговля>
choice.1.<До встречи>
waitForUser
label.4
setTalkLabels.-1.-1.2
talk.<
    В Книге фей перечислены только дикие феи, встречающиеся в {4*Занзаре}.
    Причина этому — многообразие эволюционных форм, которые можно получить экспериментальным путём.
    Никто не знает, насколько их много и какие феи ещё могут существовать.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Немногие селекционеры фей пытаются понять закономерности, при которых возможно появление новых форм, но пока что никто в этом не преуспел.
    Поэтому  мы больше занимаемся сохранением тех видов, что нам удалось найти, например, {4*cемейства Орнеллы}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Нет универсального способа для выведения новых форм фей: гномы пытаются проводить эксперименты на феях, используя посторонние {4*источники энергии}.
    Также этим занимаются и {4*Тёмные Эльфы}, но, полагаю, ты сможешь узнать подробности, только если встретишь одного из них.
    И если он согласится рассказать об этом.
>
waitForUser
goto.0
label.3
tradingCurrency.252A4FA3
tradingItem.5.4253C0A3
tradingItem.3.8B7A91A3
tradingItem.1.AC718B13
waitForUser
goto.0
label.1
exit"""
InitScript = """
setModel.b029s31m
defaultWizForm.151.0.0"""
UpdateScript = "lookAtPlayer.0.1"
