UID = "9053C5A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.21.0
label.0
defaultWizForm.65.0.33
goto.30
label.1
defaultWizForm.65.0.34
goto.30
label.2
defaultWizForm.65.0.35
goto.30
label.3
defaultWizForm.65.0.36
goto.30
label.4
defaultWizForm.65.0.37
goto.30
label.5
defaultWizForm.65.0.38
goto.30
label.6
defaultWizForm.65.0.39
goto.30
label.7
defaultWizForm.66.0.33
goto.30
label.8
defaultWizForm.66.0.34
goto.30
label.9
defaultWizForm.66.0.35
goto.30
label.10
defaultWizForm.66.0.36
goto.30
label.11
defaultWizForm.66.0.37
goto.30
label.12
defaultWizForm.66.0.38
goto.30
label.13
defaultWizForm.66.0.39
goto.30
label.14
defaultWizForm.70.0.33
goto.30
label.15
defaultWizForm.70.0.34
goto.30
label.16
defaultWizForm.70.0.35
goto.30
label.17
defaultWizForm.70.0.36
goto.30
label.18
defaultWizForm.70.0.37
goto.30
label.19
defaultWizForm.70.0.38
goto.30
label.20
defaultWizForm.70.0.39
goto.30
label.30"""
