UID = "9053C4A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.21.0
label.0
defaultWizForm.14.0.33
goto.30
label.1
defaultWizForm.14.0.34
goto.30
label.2
defaultWizForm.14.0.35
goto.30
label.3
defaultWizForm.14.0.36
goto.30
label.4
defaultWizForm.14.0.37
goto.30
label.5
defaultWizForm.14.0.38
goto.30
label.6
defaultWizForm.14.0.39
goto.30
label.7
defaultWizForm.15.0.33
goto.30
label.8
defaultWizForm.15.0.34
goto.30
label.9
defaultWizForm.15.0.35
goto.30
label.10
defaultWizForm.15.0.36
goto.30
label.11
defaultWizForm.15.0.37
goto.30
label.12
defaultWizForm.15.0.38
goto.30
label.13
defaultWizForm.15.0.39
goto.30
label.14
defaultWizForm.33.0.33
goto.30
label.15
defaultWizForm.33.0.34
goto.30
label.16
defaultWizForm.33.0.35
goto.30
label.17
defaultWizForm.33.0.36
goto.30
label.18
defaultWizForm.33.0.37
goto.30
label.19
defaultWizForm.33.0.38
goto.30
label.20
defaultWizForm.33.0.39
goto.30
label.30"""
