UID = "9023B4A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.16.0
label.0
defaultWizForm.1.0.16
goto.20
label.1
defaultWizForm.1.0.15
goto.20
label.2
defaultWizForm.1.0.14
goto.20
label.3
defaultWizForm.1.0.13
goto.20
label.4
defaultWizForm.18.0.16
goto.20
label.5
defaultWizForm.18.0.15
goto.20
label.6
defaultWizForm.18.0.14
goto.20
label.7
defaultWizForm.18.0.13
goto.20
label.8
defaultWizForm.37.0.16
goto.20
label.9
defaultWizForm.37.0.15
goto.20
label.10
defaultWizForm.37.0.14
goto.20
label.11
defaultWizForm.37.0.13
goto.20
label.12
defaultWizForm.73.0.16
goto.20
label.13
defaultWizForm.73.0.15
goto.20
label.14
defaultWizForm.73.0.14
goto.20
label.15
defaultWizForm.73.0.13
goto.20
label.20"""
