UID = "9053C7A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.35.0
label.0
defaultWizForm.19.0.33
goto.40
label.1
defaultWizForm.19.0.34
goto.40
label.2
defaultWizForm.19.0.35
goto.40
label.3
defaultWizForm.19.0.36
goto.40
label.4
defaultWizForm.19.0.37
goto.40
label.5
defaultWizForm.19.0.38
goto.40
label.6
defaultWizForm.19.0.39
goto.40
label.7
defaultWizForm.20.0.33
goto.40
label.8
defaultWizForm.20.0.34
goto.40
label.9
defaultWizForm.20.0.35
goto.40
label.10
defaultWizForm.20.0.36
goto.40
label.11
defaultWizForm.20.0.37
goto.40
label.12
defaultWizForm.20.0.38
goto.40
label.13
defaultWizForm.20.0.39
goto.40
label.14
defaultWizForm.13.0.33
goto.40
label.15
defaultWizForm.13.0.34
goto.40
label.16
defaultWizForm.13.0.35
goto.40
label.17
defaultWizForm.13.0.36
goto.40
label.18
defaultWizForm.13.0.37
goto.40
label.19
defaultWizForm.13.0.38
goto.40
label.20
defaultWizForm.13.0.39
goto.40
label.21
defaultWizForm.29.0.33
goto.40
label.22
defaultWizForm.29.0.34
goto.40
label.23
defaultWizForm.29.0.35
goto.40
label.24
defaultWizForm.29.0.36
goto.40
label.25
defaultWizForm.29.0.37
goto.40
label.26
defaultWizForm.29.0.38
goto.40
label.27
defaultWizForm.29.0.39
goto.40
label.28
defaultWizForm.41.0.33
goto.40
label.29
defaultWizForm.41.0.34
goto.40
label.30
defaultWizForm.41.0.35
goto.40
label.31
defaultWizForm.41.0.36
goto.40
label.32
defaultWizForm.41.0.37
goto.40
label.33
defaultWizForm.41.0.38
goto.40
label.34
defaultWizForm.41.0.39
goto.40
label.40"""
