UID = "0D55A334"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
gotoRandomLabel.3.0
label.0
say.<Человеческим духом пахнет?>.0
waitForUser
goto.3
label.1
say.<Человеческим духом пахнет?>.0
waitForUser
goto.3
label.2
say.<Человеческим духом пахнет?>.0
waitForUser
goto.3
label.3
setCamera.1006
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.66.0.12
defaultWizForm.62.1.10
defaultWizForm.68.2.12
defaultWizForm.87.3.12
goto.3
label.1
defaultWizForm.66.0.12
defaultWizForm.17.1.12
defaultWizForm.26.2.10
defaultWizForm.15.3.11
goto.3
label.2
defaultWizForm.66.0.12
defaultWizForm.47.1.11
defaultWizForm.6.2.10
defaultWizForm.74.3.10
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
