UID = "B517A5B4"
Name = "45E91F21"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Ох, дочь безграничной щедрости снова вернулась...>.0
waitForUser
ifPlayerHasCards.1.0.21
setTalkLabels.-1.-1.0
talk.<
    Ты можешь найти дверь, ведущую в царство бесчисленных богатств и чудес, прямо за моей спиной.
    Выбери правый путь, и ты обретёшь все сокровища мира.
    Выбери левый путь, и ты укротишь силу, способную изменить мир.
    Только ты можешь решить, какой путь стоит выбрать, о дочь нерешительности.
>
waitForUser
exit
endIf
setTalkLabels.1.2.1
talk.<
    За этот ключ, открывающий доступ в волшебный мир сокровищ, я прошу лишь жалкую {4*сотню монет}.
    Такая ничтожная сумма за врата к неуловимым богатствам и бесконечному могуществу, ты согласна на сделку?
>
waitForUser
setTalkLabels.0.0.0
label.1
ifPlayerHasCards.100.0.4
removePlayerCards.100.0.4
givePlayerCards.1.0.21
setTalkLabels.-1.-1.0
talk.<
    Прекрасный выбор, мой проницательный друг.
    С этим ключом двери к несметным богаствам теперь открыты перед тобой.
    Пусть на дорогах тебя не будет поджидать опасность, а твоё путешествие будет таким же успешным, как твои самые смелые мечты.
>
waitForUser
exit
else
setTalkLabels.-1.-1.0
talk.<
    О, дочь безграничной щедрости, похоже, что твои карманы недостаточно тяжелы для этой сделки.
    К сожалению, дверь к бесчисленному богатству недостижима без твёрдых намерений.
    Однако, как только я услышу звуки звенящей удачи, я буду всегда готов провести по этой тайной тропе.
>
waitForUser
exit
label.2
exit"""
InitScript = """
setModel.g300s30m
movementSpeed.15"""
UpdateScript = """
label.0
moveSystem.1.1
gotoRandomLabel.3.0
goto.0
label.1
playAnimation.0.30
goto.0
label.2
playAnimation.11.30
goto.0"""
