UID = "9C20B994"
Name = "45E91F21"
TriggerScript = """
setCamera.3001
changeWaypoint.5.6
playAnimation.13.-1
say.<
    Псс...
    Ты ищешь что-то особенное?
>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    У меня есть уникальный ключ от места, который открывает невероятный мир, полный самых ценных и дорогих сокровищ этого мира! Это место, где собираются хитрые торговцы и могущественные существа, готовые обменять свои секреты в обмен на горстку блестящих кристаллов...
>
waitForUser
talk.<
    Но берегись, мой друг, секретность превыше всего! Лишь самые могущественные {4*Коллекционеры} достойны познать тайные чудеса и удивительные дары, которые скрываются от взора неведующей толпы.
    Ты уже слышишь этот заманчивый шёпот удачи?
>
waitForUser
setTalkLabels.1.2.1
talk.<
    За этот ключ, открывающий доступ в волшебный мир сокровищ, я прошу лишь жалкую {4*сотню монет}.
    Такая ничтожная сумма за врата к неуловимым богатствам и бесконечному могуществу, ты согласна на сделку?
>
waitForUser
setTalkLabels.0.0.0
label.1
ifPlayerHasCards.100.0.4
removePlayerCards.100.0.4
givePlayerCards.1.0.21
setTalkLabels.-1.-1.0
talk.<
    Прекрасный выбор, мой проницательный друг.
    С этим ключом двери к несметным богаствам теперь открыты перед тобой.
    Пусть на дорогах тебя не будет поджидать опасность, а твоё путешествие будет таким же успешным, как твои самые смелые мечты.
>
waitForUser
goto.0
else
setTalkLabels.-1.-1.0
talk.<
    О, дочь безграничной щедрости, похоже, что твои карманы недостаточно тяжелы для этой сделки.
    К сожалению, дверь к бесчисленному богатству недостижима без твёрдых намерений.
    Однако, как только я услышу звуки звенящей удачи, я буду всегда готов провести по этой тайной тропе.
>
waitForUser
goto.0
label.2
setTalkLabels.-1.-1.0
talk.<
    Ах, я вижу...
    Ты решила отказаться от возможности всей своей жизни.
    Но не бойся, всегда есть другие, жаждущие необычного.
    Я продолжу поиски того, кто обладает достаточной храбростью, чтобы владеть этим бесценным сокровищем.
>
waitForUser
label.0
changeWaypoint.6.5
removeNpc"""
InitScript = """
setModel.g300s30m
movementSpeed.15"""
UpdateScript = """
label.0
idle
ifTriggerIsActive.9
startPrelude
endIf
goto.0"""
