UID = "36C11DB4"
Name = "DEE079A1"
TriggerScript = """
deployNpcAtTrigger.73.1
setCamera.3002
changeWaypoint.21.22
changeWaypoint.22.23
changeWaypoint.23.24
changeWaypoint.24.-1
playAnimation.13.-1
setCamera.1003
say.<Ты находишь внутри {4*Флакон Маны} (х2)!>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<Ты находишь внутри {4*Лекарство} (х2)!>
waitForUser
say.<...>.1
choice.1.<Ты находишь внутри {4*Чесночный Распылитель} (х1)!>
choice.2.<Ты находишь внутри {4*Лесные Травы} (х3)!>
waitForUser
label.1
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Лесные Травы} (х4)!>
waitForUser
setTalkLabels.-1.-1.2
talk.<Ты открываешь {4*Мистическую Шкатулку}...>
waitForUser
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Золотой Шар} (х1)!>
waitForUser
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х3)!>
waitForUser
setTalkLabels.2.3.1
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х4)!>
waitForUser
label.2
setCamera.1006
fight.-1.0
exit
label.3
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х5)!>
waitForUser
exit"""
InitScript = """
setModel.b002s20m
defaultWizForm.17.0.22
defaultWizForm.33.1.22
defaultWizForm.36.2.20
defaultWizForm.25.3.23
defaultWizForm.62.4.23"""
UpdateScript = """
label.0
idle
ifTriggerIsActive.69
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1003
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х6)!>
waitForUser
setTalkLabels.-1.-1.0
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х7)!>
waitForUser
givePlayerCards.1.0.51
givePlayerCards.1.0.107
setCamera.3003
changeWaypoint.-1.25
changeWaypoint.25.26
changeWaypoint.26.27
changeWaypoint.27.28
removeNpc"""
VictoriousScript = "killPlayer"
