UID = "05147314"
Name = "97688F91"
TriggerScript = """
setCamera.3000
playAnimation.13.-1
say.<Наконец-то, ты явилась сюда!>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Помнишь нашу первую встречу в {4*Тиралине}?
    Тогда я выглядела как уродливая {4*Болотная Гоблинша}, и ты победила меня в {4*дуэли фей}.
    Но всё это было несерьёзно, - и мы договорились встретить здесь снова?
    В первый раз я недооценила твою силу, но теперь всё будет по-другому!
>
waitForUser
fight.-1.0
exit"""
InitScript = """
setModel.b016s00m
defaultWizForm.27.0.21
defaultWizForm.69.1.21
defaultWizForm.28.2.23
defaultWizForm.85.3.21
defaultWizForm.150.4.20"""
UpdateScript = """
label.0
lookAtPlayer.1.1
ifPlayerIsClose.2
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
setTalkLabels.-1.-1.2
talk.<
    Как я могла проиграть такому ничтожному существу, как ты?! Будь прокляты {4*Эльфы, Гоблины, Гномы} и вы, {4*Люди}! {4*Тёмные Эльфы} заставят всех расплатиться за годы унижений и страданий, и вы будете молить о пощаде, как только мы сможем добраться до самого {4*Стража}! Ни {4*Белый Друид}, ни {4*Квинлин} не способны остановить нас в получении того, что мы заслуживаем!
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Это ещё не конец.
    {4*Королева} следит за каждым твоим шагом, {4*Избранная}!
>
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
