UID = "8C12D134"
Name = "389D7EB1"
TriggerScript = """
deployNpcAtTrigger.56.1
setCamera.3001
playAnimation.13.-1
say.<Повелительница фей из человеческого мира.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я слышал, что ты освободила {4*Данмор} от {4*Тёмных Эльфов}.
    Но это ещё только начало твоей битвы с ними, {4*Эми}.
    Они блокировали большинство дорог {4*Занзары}, и единственный проход в {4*Монагам} охраняет {4*элита Тёмных Эльфов}.
    Я не думаю, что кто-либо способен в одиночку противостоять им.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    К тому же, я уверен, что исчезновение {4*Квинлина} - их рук дело.
    Он был единственным, кто когда-либо выступал за перемирие с {4*Тёмными Эльфами} и пытался наладить с ними дипломатические связи.
    Но после того, как он ушёл к ним, чтобы мирно уладить конфликт, он бесследно исчез в {4*Царстве Тьмы}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Несомненно, во всём виноваты {4*Тёмные Эльфы}.
    Именно они затеяли коварный план по захвату всей {4*Занзары}, и долгое время они готовились, чтобы привести его в действие.
    Они вызвали {4*Терновык Кусты} и {4*Огромные Булыжники}, они захватили {4*Квинлина} и напали на {4*Данмор}.
>
waitForUser
setTalkLabels.10.11.1
talk.<
    Теперь мы должны решить, кто из нас отправится к {4*Белому Друиду} в {4*Царство Облаков}, чтобы сообщить ему о том, что творят Тёмные Эльфы! Ты готова к честному поединку?
>
waitForUser
label.10
setCamera.1006
fight.-1.0
exit
label.11
setTalkLabels.-1.-1.0
talk.<
    Сообщи мне, когда ты будешь к дуэли, {4*Эми}.
    Но ты должна поторопиться: у нас осталось не так много времени, чтобы успешно пытаться противостоять {4*Тёмным Эльфам}...
>
waitForUser
exit"""
InitScript = """
setModel.b012s00m
defaultWizForm.47.0.21
defaultWizForm.70.1.22
defaultWizForm.41.2.24
defaultWizForm.39.3.23
defaultWizForm.12.4.22"""
UpdateScript = """
label.0
lookAtPlayer.2.1
ifPlayerIsClose.4
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.3001
playAnimation.13.-1
setTalkLabels.-1.-1.2
talk.<
    Это была отличная битва.
    Таким образом, ты гораздо более подходящий кандидат для того, чтобы получить {4*Карту Воздуха}.
    Я надеюсь, ты сможешь дойти до самой вершины {4*Большого Дерева} и выиграть её: в отличие от остальных, ты единственная, кто может развеять эти нелепые слухи о {4*союзе Гномов и Тёмных Эльфов}...
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Напоследок я скажу тебе кое-что ещё.
    Я уверен, что {4*Тёмные Эльфы} ищут {4*магические Карты}, позволяющие управлять стихиями {4*Занзары}.
    И на твоём месте я был бы осторожнее - возможно, они ждут подходящего момента, чтобы сразиться за неё...
    А мне нужно вернуться в {4*Тиралин}.
    Я желаю тебе победы в этом {4*Турнире}.
>
waitForUser
givePlayerCards.1.0.107
changeWaypoint.7.6
changeWaypoint.6.5
changeWaypoint.5.4
changeWaypoint.4.3
removeNpc"""
VictoriousScript = "killPlayer"
