UID = "36C11DB4"
Name = "DEE079A1"
TriggerScript = """
deployNpcAtTrigger.73.1
setCamera.3002
changeWaypoint.21.22
changeWaypoint.22.23
changeWaypoint.23.24
changeWaypoint.24.-1
playAnimation.13.-1
setCamera.1003
say.<Разве я не говорила, что мы встретимся снова?>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Ты смогла победить двух {4*Коллекционеров} по пути сюда?
    Значит, я не ошиблась в тебе, и ты действительно имеешь потенциал стать гораздо более сильной.
    Но, возможно, ты пришла сюда не за этим?
    Мы можем начать нашу дуэль немедленно или я могу рассказать тебе немного больше о {4*Белом Друиде}, о которым ты наверняка уже неоднократно слышала до этого?
>
waitForUser
say.<...>.1
choice.1.<Диалог (Я хочу узнать больше о {4*Белом Друиде})>
choice.2.<Дуэль (Я готова к поединку)>
waitForUser
label.1
setTalkLabels.-1.-1.2
talk.<
    Ты наверняка слышала о {4*Великом Расколе}, верно?
    {4*Белый Друид} закрыл порталы, ведущие в {4*человеческий мир}, чтобы защитить магических существ от истребления руками людей?
    В этом ему помогал {4*Квинлин} - великий мастер гномов, кто создал первых {4*фей Металла}, а также самого {4*Стража}.
    Но долгое время он был против этой идеи, надеясь найти решение мирным путём.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Никто не знает, кто или что убедило {4*Квинлина} согласиться с этой идеей.
    Тем не менее, гораздо позже возникло {4*Предсказание}: легенда о том, что когда-то в {4*Занзару} придёт {4*Избранный} - или {4*Избранная} - кто снова откроет пути в {4*человеческий мир}.
    Но почему это должно произойти?
    Ведь люди не принесли для {4*Занзары} ничего, кроме разрушения?
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Правда в том, что тоже самое происходит и сейчас.
    {4*Тёмные Эльфы} обьявили войну всем, но наверняка причина этому страх перед чем-то...
    или кем-то.
    И так как они живут в том же мире, что и мы, после победы над ними никто не сможет магическим образом запечатать вход в {4*Царство Тьмы}.
    Они продолжат жить на той же земле, что и другие расы {4*Занзары}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я совсем забыла, я обещала рассказать тебе о {4*Белом Друиде}?
    Никто не видел {4*Белого Друида} после того, как произошёл {4*Великой Раскол}, и мало кто знает об его прошлом.
    Если ты задумаешься обо всём том, о чём я сказала, ты наверняка поймёшь, что я хотела донести до тебя.
    Мы имеем множество вопросов, но у нас нет ничего, кроме обычных предположений.
>
waitForUser
setTalkLabels.2.3.1
talk.<Ты готова к следующей битве за {4*Карту Воздуха}?>
waitForUser
label.2
setCamera.1006
fight.-1.0
exit
label.3
setTalkLabels.-1.-1.2
talk.<Возвращайся ко мне, как будешь готова.>
waitForUser
exit"""
InitScript = """
setModel.b002s20m
defaultWizForm.17.0.22
defaultWizForm.33.1.22
defaultWizForm.36.2.20
defaultWizForm.25.3.23
defaultWizForm.62.4.23"""
UpdateScript = """
label.0
idle
ifTriggerIsActive.69
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1003
setTalkLabels.-1.-1.2
talk.<
    У меня давно не было такой увлекательной дуэли фей! Большинство {4*Коллекционеров} давно забыли, что такое истинный дух {4*Коллекционера}...
    Твоя победа абсолютно заслужена.
    Но главные битвы все ещё ждут тебя впереди, и не стоит думать, что это будет также просто.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Возьми этот {4*Эволюционный Камень Воздуха}.
    При помощи него ты сможешь получить {4*фею Воздуха}, чтобы использовать её с {4*Картой Воздуха}.
    За западными воротами {4*Тиралина}, которые ведут в {4*Данмор}, находится ещё одна дорога, ведущая к обрыву, за которыми находятся {4*Тёмные Пещеры}.
    Воспользуйся этим путём, чтобы попасть горы и найти путь в {4*Царство Облаков}.
>
waitForUser
givePlayerCards.1.0.51
givePlayerCards.1.0.107
setCamera.3003
changeWaypoint.-1.25
changeWaypoint.25.26
changeWaypoint.26.27
changeWaypoint.27.28
removeNpc"""
VictoriousScript = "killPlayer"
