UID = "E1094DB4"
Name = "E95016B1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Ты не представляешь, как я рад тебя видеть здесь, Эми.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я все ещё продолжаю поиски своего отца, {4*Квинлина}.
    Я знаю, в {4*Занзаре} ходят слухи, что он спустился в {4*Царство Тьмы}, чтобы договориться с {4*Тёмными Эльфами}, но я ничего не слышал об этом от него самого.
    Но это неважно, - мы должны найти {4*Белого Друида} и рассказать о том, что происходит в {4*Занзаре}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Пока я путешествовал, я обнаружил этот {4*Стихийный Ключ Воздуха} - один из трёх, необходимых для запуска лифта в {4*Царство Облаков}, где обитает {4*Белый Друид}.
    Я бы мог отдать его тебе, но почему бы нам не провести дуэль фей?
    Мы должны быть уверены, что у тебя достаточно сил, чтобы противостоять {4*Тёмным Эльфам}, и маленькая тренировка этому не помешает?
>
waitForUser
setTalkLabels.10.11.1
talk.<Ты готова к битве за {4*Стихийный Ключ Воздуха}?>
waitForUser
label.10
setCamera.1006
fight.-1.0
exit
label.11
setTalkLabels.-1.-1.0
talk.<
    Хорошо.
    Скажи, когда ты будешь готова, но, пожалуйста, поторопись, - в этой пещере очень холодно даже для нас, {4*гномов}...
>
waitForUser
exit"""
InitScript = """
setModel.d006s02m
defaultWizForm.93.0.41
defaultWizForm.140.1.39
defaultWizForm.98.2.42
defaultWizForm.61.3.37
defaultWizForm.90.4.38
spell.0.0.21
spell.0.2.18
spell.1.0.51
spell.1.2.9
spell.2.2.42
spell.4.2.47"""
UpdateScript = "lookAtPlayer.0.1"
DefeatedScript = """
setTalkLabels.-1.-1.2
talk.<
    Твои способности продолжают расти, но в будущем тебе потребуется нечто большее, чем просто сильные феи.
    Тебе нужно понимать, кому ты готова доверять, {4*Эми}, потому что не все хотят, чтобы ты исполнила свою миссию...
    Это то, о чём мне рассказывал {4*Квинлин}, мой отец, до того, как он таинственным образом исчез.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Тебе нужно запустить лифт возле {4*Башни Мудрости}, используя {4*Стихийные Ключи Природы, Земли и Воздуха}.
    Именно так ты сможешь попасть в {4*Царство Облаков}.
    Я последую за тобой несколько позже, как я буду готов к тому, чтобы продолжить своё путешествие.
    Береги себя, {4*Эми}, и найди {4*Белого Друида} как можно скорее.
>
waitForUser
givePlayerCards.1.0.107
givePlayerCards.1.0.22
changeWaypoint.1.2
changeWaypoint.2.3
removeNpc"""
