UID = "ADDC0094"
Name = "DEE079A1"
TriggerScript = """
setCamera.1003
playAnimation.13.-1
say.<
    Я никогда не видела тебя до этого.
    Впервые в этом городе?
>.0
waitForUser
label.0
say.<
    Мне не нравится {4*Тиралин}, он слишком шумный.
    Однажды я всё же решусь найти более спокойное и уединённое место...
>.3
choice.1.<Обмен {4*Щепотки Пыльцы фей}>
choice.2.<Обмен {4*Горсти Пыльцы фей}>
choice.3.<До встречи>
waitForUser
label.1
tradingCurrency.23173793
tradingItem.2.99D2B4A3
tradingItem.4.AD58B4A3
waitForUser
goto.0
label.2
tradingCurrency.99D2B4A3
tradingItem.2.AD58B4A3
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.b002s20m
movementSpeed.10
defaultWizForm.180.0.0"""
UpdateScript = """
label.0
moveSystem.1.3
gotoRandomLabel.3.0
goto.0
label.1
lookAtPlayer.10.1
goto.0
label.2
lookAtPlayer.20.1
goto.0"""
