UID = "1D7435A4"
Name = "9F4416B1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.13.-1
say.<Хвала Друиду, так приятно тебя видеть, Эмми.>.0
waitForUser
ifPlayerHasSpecials.1.0
setTalkLabels.-1.-1.2
talk.<
    Перед тем как отправиться странствовать по Занзаре, тебе нужна собственная {4*фея}! Это единственное, что может защитить тебя от диких фей, живущих на деревьях, среди камней и в реке.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Тебе лучше пойти в {4*Эндеву}.
    Это недалеко отсюда и ее жители — миролюбивые {4*Лесные Эльфы}.
    Возможно, они тебе помогут.
>
waitForUser
exit
endIf
ifPlayerHasCards.0.0.16
setTalkLabels.-1.-1.2
talk.<
    Феи следуют за тобой, Эмми! Немногие люди, знаешь ли, встречают такое чудо в своей жизни!
>
waitForUser
talk.<
    Тренируй своих фей насколько возможно.
    Твой путь будет долог и опасен.
    Тебе стоит сходить к {4*Люциусу}.
    Он живет в маленьком домике на краю сада.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<Жители Занзара поручили {4*Люциусу} охранять всех {4*пикси}, запертых в его подвале, но кажется они сбежали ...>
waitForUser
exit
endIf
ifPlayerHasCards.0.0.31
setTalkLabels.-1.-1.2
talk.<
    С помощью своей феи ты сможешь теперь добраться до {4*волшебного города Тиралин}.
    {4*Тиралин} находится в самом сердце Занзары.
    На его узких улочках полно эльфов, гномов и гоблинов.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Ты встретишь много интересных существ, а также много узнаешь, но не задерживайся долго в этом великолепном городе! Твоя цель – это деревня Болотных Гоблинов {4*Данмор}.
    Ты легко доберешься туда из {4*Тиралина}.
>
waitForUser
exit
endIf
ifPlayerHasCards.0.0.47
setTalkLabels.-1.-1.2
talk.<
    Ты знаешь нашу игру в карты?
    Это таинственная игра силы и магии.
    Каждая карта в игре представляет собой такие стихии, как {4*Огонь}, {4*Воздух} или {4*Землю}.
    Сейчас самой важной картой для тебя является {4*Карта Природы}.
>
waitForUser
talk.<
    Вместе с {4*активной Феей Природы} ты можешь воспользоваться ей, чтобы уничтожить терновые кусты, покрывшие Занзару.
    Найди карту, это единственный способ продолжить поиски!
>
setTalkLabels.-1.-1.0
waitForUser
talk.<Как и все потерянные карты, она находится в  {4*магическом месте}, окруженном туманом, болотом и светящимися существами...>
waitForUser
exit
endIf
ifPlayerHasCards.0.0.45
setTalkLabels.-1.-1.2
talk.<
    {4*Карта Природы} – это только одна карта из колоды.
    Чтобы исследовать другие места в Занзаре, найди {4*Карту Земли}.
    Используй ее и {4*Фею Камня}, чтобы убрать большие валуны.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Мои сведения устарели, недоказаны и скорее легенда, чем правда...
    но ты, возможно, найдешь эту карту в забытом {4*Царстве Облаков}.
    В свое время гномы построили машины, чтобы достичь этих высот.
>
waitForUser
talk.<
    Сходи в их хранилище знаний, {4*Башню Гномов}.
    Она находится на краю обрыва в горах.
    Будь осторожна, гномы дружелюбны, но недоверчивы.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Следующий пункт твоего маршрута — уединенная {4*лесная хижина}.
    Ее обитатели  дружелюбны и смогут тебе помочь...
>
waitForUser
exit
endIf
ifPlayerHasCards.0.0.26
setTalkLabels.-1.-1.2
talk.<
    Я вижу, ты нашла {4*Карту Земли}.
    Это сильнодействующая карта.
    Используй ее вместе с Феей Камня, чтобы уничтожить валуны, завалившие дороги {4*Занзары}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Исследуй самые отдаленные уголки {4*Занзары}.
    Это единственный способ продолжить твое путешествие.
    Может ты даже найдешь дорогу к легендарным местам, таким как {4*арена} в Царстве Облаков...
>
waitForUser
exit
endIf
ifPlayerHasCards.0.0.44
setTalkLabels.-1.-1.2
talk.<
    Игра еще не закончена, Эмми.
    У тебя есть природа и земля, но ты должна найти {4*Карту Воздуха}.
    Она на дереве посреди {4*Туманного Болота}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Используй ее с {4*Феей Воздуха}, и ты сможешь использовать {4*вихри}, которые найдешь в Занзаре.
    Используй ее, чтобы преодолевать пропасти и возвышения!
>
waitForUser
exit
endIf
ifPlayerHasCards.0.0.22
setTalkLabels.-1.-1.2
talk.<
    К сожалению, кузнечное ремесло гномов часто неправильно использовалось, и многие важные волшебные места в Занзаре закрыты нерушимыми железными воротами.
    Здесь тебе не поможет ни карта фей, ни заклинания.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Тебе надо найти ключ от этих ворот.
    Боюсь, что я не знаю, где его можно найти, но почему бы тебе не зайти в {4*Белый Собор}?
    Я давно подозреваю, что существует какая-то связь между силой неба и земли.
>
waitForUser
exit
endIf
ifPlayerHasCards.0.0.52
setTalkLabels.-1.-1.0
talk.<
    Вот тебе небольшая, но полезная подсказка, Эмми: во время своих странствий по Занзаре я слышал о магическом камне, спрятанном за красивым водопадом.
    Может его можно как-нибудь использовать...
>
waitForUser
exit
endIf
ifPlayerHasCards.-1.2.31
setTalkLabels.-1.-1.0
talk.<
    Эмми, ты хорошо подготовлена к последней великой {4*битве фей}.
    Выполни предсказание и докажи, что ты самый лучший коллекционер фей.
    Открой вновь {4*древние пути}!
>
waitForUser
exit
endIf
setTalkLabels.-1.-1.2
talk.<
    Боюсь, что почти ничем не могу тебе сейчас помочь, Эмми.
    Вход в ужасное {4*Царство Тьмы} открыт.
    Он находится на Туманном болоте за старым деревом.
>
waitForUser
talk.<
    Но не торопись, ты еще не знаешь всех секретов {4*Занзары}.
    Сначала попробуй найти потерянную Карту Огня и открой дверь в огненные глубины Занзары.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    И еще: с помощью редких и ценных {4*Эволюционных Камней} ты сможешь менять стихийную принадлежность некоторых фей.
    Тебе обязательно стоит это попробовать!
>
waitForUser
exit"""
InitScript = """
movementSpeed.10
setModel.g000s00m"""
UpdateScript = """
lookAtPlayer.35.1
label.0
moveSystem.0.0
gotoRandomLabel.3.0
goto.0
label.1
lookAtPlayer.30.1
goto.0
label.2
lookAtPlayer.60.1
goto.0"""
