UID = "453A1534"
Name = "7B2D8F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
ifPlayerHasCards.1.0.22
say.<Список наград>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<{4*Загадочная Шкатулка} может содержать: {4*Щепотка Пыльцы фей} (х10), {4*Горсть Пыльцы фей} (x5), {4*Малый Лечебный Бальзам} (x5), {4*Средний Лечебный Бальзам} (x3), {4*Лекарственные Травы} (x6), {4*Флакон Маны} (x3), {4*Лекарство} (x3), {4*Чесночный Распылитель} (x2), {4*Серебрянный Шар} (х1)>
waitForUser
goto.0
endIf
say.<Тёмный Союз>.0
waitForUser
label.0
setTalkLabels.1.2.1
talk.<
    Но если тебе интересно, то ты можешь найти моих друзей в {4*Данморе} и {4*Монагаме}.
    У них также есть {4*призмы}, и они в гораздо лучшем состоянии, нежели моя.
    Я думаю, они не будут против помочь тебе в тренировке твоих фей, и возможно, вместе вы сможете узнать что-то больше об этом?
    Я буду рад узнать, каким образом {4*Тёмным Эльфам} удалось создать что-то подобное.
>
waitForUser
label.1
ifPlayerHasCards.7.0.4
removePlayerCards.7.0.4
setTalkLabels.-1.-1.0
talk.<
    Мне сложно поверить, что {4*Тёмные Эльфы} смогли накопить столько сил без чужой помощи.
    И {4*эльфы} обвиняют нас, {4*гномов}, в помощи этим созданиям, потому что мы живём в {4*Тёмных Пещерах}...
    Что за абсурд! Если бы не {4*мастер Квинлин}, то {4*Страж} никогда бы не защитил нас от {4*человеческого мира}, и {4*эльфы} были бы непременно первыми, на кого бы охотились {4*люди}!
>
waitForUser
givePlayerCards.2.0.6
changeDatabase.72861934
exit
endIf
setTalkLabels.-1.-1.0
talk.<
    Вход в {4*Царство Тьмы} расположен глубоко в {4*болотах Данмора}, но изначально эти ворота были запечатаны.
    Я не знаю, какая злая магия в этом замешана, но каким-то образом {4*Тёмные Эльфы} смогли прорваться сквозь них и вторгнулись в наш мир.
    Уверен, всему виной их эксперименты с магией, и во всех бедах, случившившихся с {4*Занзарой}, виноваты именно они!
>
waitForUser
exit
label.2
exit"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
