UID = "8EC38334"
Name = "21791F31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifPlayerHasCards.1.0.22
setTalkLabels.-1.-1.2
talk.<
    Какое несчастье! Друид врал нам все это время?
    Он призвал {4*Темных Эльфов} и поддерживает {4*Стража}?
>
waitForUser
talk.<
    Как он мог быть таким самонадеянным?
    Как он мог взять судьбу {4*Занзары} в свои руки! Должно быть, он сошел с ума от старости и злобы...
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Эмми, ты должна следовать предсказанию! Найди вход в {4*Царство Тьмы}.
    Там, в темноте, ты найдешь {4*Стража}.
>
waitForUser
exit
endIf
ifPlayerHasCards.1.0.44
setTalkLabels.-1.-1.0
talk.<
    Я поражен.
    Ты выиграла турнир на Старом Дереве! С помощью{4* Карты Воздуха} ты теперь можешь использовать все воздушные вихри.
    Они даже помогут тебе добраться до {4*Белого Собора}...
>
waitForUser
exit
endIf
ifPlayerHasCards.1.0.26
setTalkLabels.-1.-1.2
talk.<
    Ты нашла {4*доказательства} в {4*Царстве Облаков}?
    Наконец, мы узнаем, кто виноват в том, что случилось в нашей любимой {4*Занзаре}.
>
waitForUser
talk.<Хммм...>
waitForUser
talk.<Как такое может быть?>
waitForUser
talk.<
    Этот предмет - {4*Посох Квинлина}, несомненно! Это он -  {4*предатель}, который призвал Темных Эльфов! Мы должны найти и покарать его.
>
waitForUser
talk.<Мы организуем турнир Повелителей фей на {4*Большом Дереве} на болоте.>
waitForUser
talk.<
    Таким образом, мы определим лучшего Повелителя фей в {4*Занзаре} и пошлем его искать предателя.
    Гномы должны быть остановлены.
>
waitForUser
setTalkLabels.20.21.1
talk.<
    Ты должна принять в этом участие.
    Ты знаешь, как добраться до Большого Дерева?
>
waitForUser
label.20
setTalkLabels.-1.-1.0
talk.<Что ж, удачи на турнире.>
waitForUser
exit
label.21
setTalkLabels.-1.-1.0
talk.<
    Ты должна пройти через {4*Данмор} и идти по узким мостикам до {4*Большого Дерева}.
    Удачи на турнире.
>
waitForUser
exit
endIf
ifPlayerHasCards.1.0.15
gotoRandomLabel.2.80
label.80
say.<Добро пожаловать.>.0
goto.90
label.81
say.<Приятно тебя видеть.>.0
label.90
waitForUser
label.0
say.<Чем могу помочь?>.1
choice.1.<Закрытые западные ворота>
choice.2.<Торговля и обмен>
choice.3.<Не сейчас.>
waitForUser
label.1
setTalkLabels.-1.-1.2
talk.<
    Западные ворота?
    Гномы заперли их давным-давно с помощью{4* железного замка}.
    С тех пор все, что находится за ними, является тайной.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<Легенды говорят о загадочных руинах за воротами, но мы больше не знаем ничего, кроме того, что это место очень опасно для нас, эльфов.>
waitForUser
goto.0
label.2
setTalkLabels.-1.-1.0
talk.<
    Тебе везет! У нас есть большой магазин, где можно купить магические зелья и другие предметы.
    Его владелец известный коллекционер фей.
    Ты можешь пойти туда и купить себе что-нибудь полезное.
>
waitForUser
goto.0
label.3
exit
endIf
ifNpcModifierHasValue.0
setNpcModifier.-1.-1.1
say.<Во имя всех магических существ в Занзаре!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    В нашем городе человек! Вы можете в это поверить?! Похоже, что предсказание все-таки больше, чем просто легенда.
>
waitForUser
talk.<
    Действительно я должен был это ожидать.
    {4*Совы} пролетели над нашими домами и полетели в разные стороны...
>
waitForUser
talk.<
    С Болот идут тревожные слухи.
    Говорят, что {4*Темные Эльфы} вышли из своего царства.
    А {4*Квинлин}, вождь гномов, исчез.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    А теперь появилась ты — человек.
    Действительно настали времена перемен.
>
waitForUser
exit
else
say.<Добро пожаловать в Мэрию.>.0
waitForUser
setNpcModifier.-1.-1.1
gotoRandomLabel.3.100
label.100
talk.<Куда мог деться {4*Квинлин}?>
goto.200
label.101
talk.<
    С Болот идут тревожные слухи.
    Говорят, что {4*Темные Эльфы} вышли из своего царства.
    А {4*Квинлин}, вождь гномов, исчез.
>
goto.200
label.102
talk.<
    Беспокойные времена.
    Что еще произойдет?
>
goto.200
endIf
label.200
waitForUser"""
InitScript = "setModel.b005s32m"
UpdateScript = """
label.0
lookAtPlayer.20.1
moveSystem.1.1
goto.0"""
