UID = "72861934"
Name = "7B2D8F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
ifPlayerHasCards.1.0.22
say.<Список наград>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<{4*Загадочная Шкатулка} может содержать: {4*Щепотка Пыльцы фей} (х8-12), {4*Горсть Пыльцы фей} (x4-6), {4*Малый Лечебный Бальзам} (x2-4), {4*Средний Лечебный Бальзам} (x2-3), {4*Лесные Травы} (x3-4), {4*Флакон Маны} (x2), {4*Лекарство} (x2), {4*Чесночный Распылитель} (x1), {4*Серебрянный Шар} (х1)>
waitForUser
goto.0
endIf
say.<
    Это пугает меня больше всего.
    Вместо того, чтобы иметь храбрость взглянуть в глаза своему прошлому и тому, что оно хранит, мы пытаемся спрятаться от него, притворяясь, будто у нас всё в порядке.
    Для нас, {4*эльфов}, нет ничего важнее преемственности наших традиций и семейной истории.
    И что о нас будут думать наши покойные предки, если они узнают, как мы относимся к их наследию?
>.0
waitForUser
label.0
setTalkLabels.1.2.1
talk.<
    Когда {4*Тёмные Эльфы} заблокировали горный тракт, ведущий к {4*Монагаму}, мы лишились последних связей с внешним миром.
    Это произошло практически сразу, как {4*Тёмные Эльфы} осадили {4*Данмор}.
    И я решил остаться здесь, чтобы следить за тем, чтобы {4*Тёмные Эльфы} не добрались до {4*Тиралина}.
>
waitForUser
label.1
ifPlayerHasCards.10.0.4
removePlayerCards.10.0.4
setTalkLabels.-1.-1.0
talk.<
    В любом случае, {4*Камеи Коллекционеров} являются важным напоминанием о тех событиях, когда все {4*расы} на время забыли о своих разногласиях.
    Сейчас многие думают о существовании {4*Коллекционеров} как о пережитке прошлого, как о чём-то, что стало причиной всех наших бед.
    Но возможно ты сможешь показать своим примером, насколько глубоко они ошибаются в этом.
>
waitForUser
givePlayerCards.2.0.6
changeDatabase.837B7934
exit
endIf
setTalkLabels.-1.-1.0
talk.<
    Но ты должна понимать, что это не была просто война фей против людей.
    Ни одна из книг не может тебе рассказать о том, сколько было жертв на самом деле или насколько долго длились события, предшествующие {4*Расколу}.
    Даже сам {4*Квинлин} избегает любых вопросов, связанных с теми событиями.
    Что об этом могут думать остальные?
    Только самое худшее, что они могли услышать.
>
waitForUser
exit
label.2
exit"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
