UID = "A8325D24"
Name = "7B2D8F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
ifPlayerHasCards.1.0.22
say.<Список наград>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<{4*Загадочная Шкатулка} может содержать: {4*Щепотка Пыльцы фей} (х10), {4*Горсть Пыльцы фей} (x5), {4*Малый Лечебный Бальзам} (x5), {4*Средний Лечебный Бальзам} (x3), {4*Лекарственные Травы} (x6), {4*Флакон Маны} (x3), {4*Лекарство} (x3), {4*Чесночный Распылитель} (x2), {4*Серебрянный Шар} (х1)>
waitForUser
goto.0
endIf
say.<{4*Мистическая Шкатулка} может содержать: {4*Пригорошня Пыльцы фей} (x6), {4*Очищенный Нектар} (x2), {4*Большой Лечебный Бальзам} (x7), {4*Эликсир Маны} (x3), {4*Медный Редис} (x5), {4*Серебрянный Лук} (x4), {4*Золотая Морковь} (x3), {4*Золотой Шар} (x1)>.0
waitForUser
label.0
setTalkLabels.1.2.1
talk.<
    Сейчас мало кто верит в это, однако {4*Культ Друидов} пришёл в упадок ещё задолго до событий {4*Раскола}.
    Когда-то {4*Друиды} были служителями равновесия и гармонии в {4*Занзаре}, но большинство из них исчезло, и никто не знает точных причин этого.
    {4*Белый Друид} — один из последних, кто ещё жив, но даже он решил уйти в самовольное отшельничестве.
>
waitForUser
label.1
ifPlayerHasCards.5.0.4
removePlayerCards.5.0.4
setTalkLabels.-1.-1.0
talk.<{4*Магическая Шкатулка} может содержать: {4*Насыщенный Нектар} (x1), {4*Концентрированный Нектар} (x1), {4*Лечебный Эликсир} (x5), {4*Большой Эликсир Маны} (x4), {4*Медовый Эликсир} (x6), {4*Большой Медовый Эликсир} (x4), {4*Эликсир Природы} (x3), {4*Хрустальный Шар} (x1)>
waitForUser
givePlayerCards.1.0.6
changeDatabase.453A1534
exit
endIf
setTalkLabels.-1.-1.0
talk.<О чём ты хочешь узнать?>
waitForUser
exit
label.2
exit"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
