UID = "9E31E034"
Name = "BDE38F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.0
setNpcModifier.-1.-1.1
say.<Итак, ты тот человек, о котором все говорят.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я храню истории и легенды ушедших дней.
    Почти ни в одной из них не  говорится о хороших и добрых людях ...
>
waitForUser
else
say.<Человек вернулся.>.0
waitForUser
endIf
label.0
say.<Что я должна тебе сказать?>.1
choice.1.<Три мира>
choice.2.<Вина людей>
choice.3.<Сейчас ничего>
waitForUser
label.1
setTalkLabels.-1.-1.2
talk.<Были времена, когда все миры были объединены, когда люди и эльфы уважали друг друга и жили в мире.>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Всегда существовали человеческий мир, мир эльфов и наш мир, {4*Занзара}.
    Но вы уже не помните, что миры были объединены, только в ваших легендах и мифах остались намеки на правду.
>
waitForUser
goto.0
label.2
setCamera.2003
setTalkLabels.-1.-1.2
talk.<
    Люди! Чудовища! Много веков назад вы начали свою \"Великую Охоту\" – вы преследовали магических существ.
    Мы обязаны {4*Белому Друиду} тем, что все еще живы.
    
>
waitForUser
talk.<
    Все, что вы не могли объяснить, было для вас странным, а все странное должно было преследоваться.
    Вы прогнали эльфов и волшебников и запретили их по всему миру.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    {4*Белый Друид }отделил Занзару от мира людей и закрыл древние пути.
    Но сейчас вы, люди, нашли вход в наш мир.
    Я боюсь, что миру между нами пришел конец.
>
waitForUser
setCamera.1006
goto.0
label.3
exit"""
InitScript = "setModel.b004s21m"
UpdateScript = "lookAtPlayer.0.1"
