UID = "900FC934"
Name = "389D7EB1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<
    Интересно...
    Повелитель фей из человеческого мира?
>.0
waitForUser
ifPlayerHasCards.1.0.22
setTalkLabels.-1.-1.2
talk.<
    Я все еще не могу поверить, что {4*Друид} принес хаос в Занзару! Так это он запер нашего Гнома-Мастера Квинлина и обвиняет нас?
>
waitForUser
goto.0
endIf
ifPlayerHasCards.1.0.38
setTalkLabels.-1.-1.2
talk.<
    Ты нашла артефакт гномов у вождя {4*Темных Эльфов}?
    Теперь все в Занзаре поверят, что это мы вызвали Темных Эльфов.
>
waitForUser
endIf
label.0
setTalkLabels.1.2.1
talk.<
    Я вижу, ты собрала интересную коллекцию фей.
    Ты готова на поединок со мной, {4*Эйриком}-Повелителем фей?
>
waitForUser
label.1
setCamera.1006
fight.-1.0
label.2
setTalkLabels.-1.-1.0
talk.<Жаль, Я все еще ищу достойного соперника.>
waitForUser"""
InitScript = """
setModel.b012s00m
defaultWizForm.88.0.8
defaultWizForm.8.1.9
defaultWizForm.4.2.9
defaultWizForm.81.3.7"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
setCamera.3005
givePlayerCards.1.0.33
givePlayerCards.1.0.107
setTalkLabels.1.2.1
talk.<
    Ты хорошо сражалась! Наконец-то я нашел равного себе Повелителя фей.
    Я много путешествовал.
    Хочешь узнать побольше о  {4*редких феях}?
>
waitForUser
label.1
setTalkLabels.-1.-1.2
talk.<
    У нас есть легенда об {4*\"Идеальном Сочетании Фей\"}.
    Я все еще ищу эту непобедимую комбинацию фей.
    
>
waitForUser
setTalkLabels.-1.-1.0
talk.<Каждая фея обладает собственными {4*достоинствами} и {4*недостатками}, но только в правильной комбинации их способности приобретают важное значение.>
waitForUser
label.2
changeDatabase.5AC06084
exit"""
VictoriousScript = "killPlayer"
