UID = "E3A72994"
Name = "F655D391"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.0
say.<
    Я продаю весьма уникальный фей, которых ты не сможешь найти в другом месте - {4*драконов}.
    Они очень сложны для тренировки, и эволюционируют, лишь достигнув момента, когда они перестают получать всякий опыт...
    Но, в отличие от обычных фей, их {4*боевые возможности} намного {4*выше}.
>.0
else
say.<Диалог>.0
endIf
waitForUser
ifNpcModifierHasValue.0
setNpcModifier.-1.-1.1
setTalkLabels.-1.-1.2
talk.<Диалог>
waitForUser
endIf
setTalkLabels.0.1.1
talk.<Диалог>
waitForUser
label.1
exit
label.0
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.0.5
removePlayerCards.1.0.5
talk.<Диалог>
waitForUser
givePlayerCards.1.2.2
exit
else
talk.<{4*Очищенный Нектар} (x6)>
waitForUser
exit
endIf"""
InitScript = "setModel.w001s01m"
UpdateScript = "lookAtPlayer.0.1"
