UID = "7A2F0724"
Name = "2B4B0221"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Добро пожаловать в Павильон Облаков.>.0
waitForUser
label.4
say.<Чем могу помочь?>.1
choice.5.<Карта Земли>
choice.6.<Царство Облаков>
choice.7.<Не сейчас>
waitForUser
label.5
setTalkLabels.-1.-1.0
talk.<
    О, {4*Карта Земли} — сильнодействующее заклинание.
    Если у тебя есть эта карта и твоей активной феей является Фея Камня, ты сможешь преодолеть валуны, блокирующие дороги {4*Занзары}.
>
waitForUser
goto.4
label.6
setTalkLabels.-1.-1.0
talk.<
    Царство Облаков — мой новый дом.
    На севере находится {4*Белый Собор}, я там живу.
    В {4*Занзаре} нет другого такого чистого{4* }и волшебного места.
>
waitForUser
goto.4
label.7"""
InitScript = "setModel.v000s00"
UpdateScript = "lookAtPlayer.0.1"
