UID = "93624552"
Name = "0FDF8F91"
TriggerScript = """
setCamera.1000
playAnimation.12.-1
say.<
    Всё очень просто.
    Ты покупаешь один из моих товаров, а потом меняешь его на {4*случайную награду из списка}.
    Однако я не могу помочь тебе с оценкой {4*алхимических товаров}, для этого тебе лучше поискать кого-нибудь в {4*Данморе}.
>.0
waitForUser
gotoRandomLabel.2.5
label.5
setTalkLabels.1.2.1
talk.<У тебя нет никаких предметов, с оценкой которых я могу тебе помочь.>
waitForUser
label.6
setTalkLabels.1.2.1
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Деталь Дезинтеграции}!>
waitForUser
label.1
setTalkLabels.-1.-1.0
talk.<При ближайшем рассмотрении ты обнаруживаешь, что это {4*Рубиновая Деталь}!>
waitForUser
exit
label.2
setTalkLabels.-1.-1.0
talk.<
    Я могу открыть помочь тебе оценить все твои {4*Неизвестные Камни}, {4*Таинственные Камни} и {4*Магические Детали}.
    Ты хочешь сделать это?
>
waitForUser
exit"""
InitScript = "setModel.g003s03m"
UpdateScript = """
label.0
idle
moveSystem.1.3
gotoRandomLabel.2.0
goto.0
label.1
playAnimation.0.90
goto.0"""
