UID = "DCD4EF94"
Name = "C1BBEB91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
ifNumberOfNpcsIs.1.149DEE04
goto.100
else
goto.200
endIf
label.100
say.<Эмми, рад тебя видеть!>.0
waitForUser
ifNpcModifierHasValue.1
setTalkLabels.-1.-1.0
talk.<
    Это ужасно.
    Как мог {4*Белый Друид} похитить моего друга?
    Было смело с твоей стороны помешать ему.
    Прими эту ценную фею в знак моей благодарности.
>
waitForUser
givePlayerCards.1.2.45
removeWizForms
setNpcModifier.-1.-1.2
exit
else
setTalkLabels.-1.-1.0
talk.<
    Благодарю тебя за спасение моего друга {4*Лассе}.
    {4*Белому Друиду} точно нельзя верить.
>
waitForUser
exit
endIf
label.200
ifNpcModifierHasValue.0
say.<Подойди ближе!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Это {4*ты} та, которая сдвинула валун?
    Он закрывал проход в горы.
    Ужасный валун упал на дорогу, как только мой друг {4*Лассе} ушел из деревни.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    {4*Лассе} ушел на поиски своего отца {4*Квинлина}.
    Он пропал, и никто не знает куда.
    Мы все очень волнуемся.
>
waitForUser
setNpcModifier.-1.-1.1
exit
else
say.<Подойди ближе!>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Дела в нашей деревне идут все хуже.
    Наш мастер {4*Квинлин} пропал, и мы уже давно ничего не слышали о {4*Лассе}.
>
waitForUser
exit
endIf
ifPlayerHasCards.1.0.25
say.<Подойди ближе!>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я этому не верю! Мой {4*Лассе} – похищен Друидом?
    Ты должна его спасти!
>
waitForUser
exit
endIf"""
InitScript = """
setModel.d009s09
ifNpcModifierHasValue.2
else
defaultWizForm.45.0.20
endIf"""
UpdateScript = "lookAtPlayer.0.1"
