UID = "4D105FA4"
Name = "BDE38F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Ты находишь внутри {4*Горсть Пыльцы фей} (х4)!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х11)!>
waitForUser
setTalkLabels.0.1.1
talk.<
    Ох, ты пришла за {4*специальным меню}...
    Выбирай, что тебе больше нравится.
>
waitForUser
label.0
ifPlayerHasCards.10.0.4
removePlayerCards.10.0.4
subGame.1.2.10
waitForUser
else
setTalkLabels.-1.-1.0
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х12)!>
waitForUser
endIf
label.1
exit
label.10
setTalkLabels.-1.-1.0
talk.<
    Тебе интересно, как звучит моё настоящее имя?
    Это будет {4*Флавиус «Волк» Левин}.
    Слишком длинное и сложное, чтобы его запомнить, верно?
    Поэтому я обычно обхожусь только прозвищем — по крайней мере, оно не звучит, словно я какая-то далекая и глупая деревенщина из этих мест, тебе так не кажется?
>
waitForUser
playSound.0
givePlayerCards.15.0.4
exit"""
InitScript = "setModel.g300s30m"
UpdateScript = "lookAtPlayer.0.1"
