UID = "E12A0D14"
Name = "15A948B1"
TriggerScript = """
ifNpcModifierHasValue.1
say.<...>.0
waitForUser
exit
endIf
say.<...>.0
setTalkLabels.-1.-1.2
talk.<...>
waitForUser
talk.<...>
waitForUser
talk.<Скажи, все ли человеческие девушки также красивы, словно феи из сказок, или это только ты?>
waitForUser
setTalkLabels.-1.-1.0
talk.<Диалог>
waitForUser
setNpcModifier.-1.-1.1"""
InitScript = "setModel.x002s02"
UpdateScript = "lookAtPlayer.0.1"
