UID = "BFEF52B4"
Name = "C6446E91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifPlayerHasCards.1.0.25
say.<Приветствую, человек.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    С тех пор, как {4*Квинлин} исчез, {4*Тёмные Эльфы} пробираются всё дальше и дальше.
    Но даже они вряд ли смогут захватить {4*Тиралин}, место, где обитают множество {4* опытных Коллекционеров}, которые смогут дать им отпор.
    К сожалению, никто не готов в одиночку проучить {4*Тёмных Эльфов}, не говоря о том, чтобы спуститься в их логово в {4*Царстве Тьмы}.
>
waitForUser
exit
else
say.<
    Хм, чужеземец в нашем городе.
    Такое не часто увидишь!
>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Ты выглядишь как опытный {4*Коллекционер}, может ты поможешь мне с одним деликатным делом?
    После того, как {4*Тёмные Эльфы} заблокировали все пути из {4*Монагама}, мы послали наших немногих {4*Коллекционеров} на поиск помощи в {4*Тиралин} и {4*Данмор}.
    Поэтому мне больше некого попросить об этом.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Именно здесь, в {4*Монагаме}, Квинлин создал {4*Стража} - существо, которое было создано для того, чтобы отделить два мира друг от друга.
    Для этого гномы создали фабрику, где они неустанно работали над первыми прототипами {4*фей Металла}, но сейчас она является заброшенной, и поэтому мы используем её для некоторых...
    экспериментов.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Проблема в том, что я уже несколько дней ничего не слышал от них.
    Ты не могла бы проверить, всё ли с ними в порядке?
    Я буду тебе очень благодарен за это.
    Возьми этот ключ, ты найдёшь вход на фабрику прямо по дороге наверх, его сложно будет пропустить.
    И будь осторожна, там все ещё обитают {4*дикие феи Металла}, но я уверен, они не станут для тебя проблемой.
>
waitForUser
givePlayerCards.1.0.25
exit"""
InitScript = """
setModel.d002s02m
defaultWizForm.186.0.0"""
UpdateScript = "lookAtPlayer.0.1"
