UID = "11428094"
Name = "44EB3001"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Готовься к своей последней битве!>.0
waitForUser
changeWaypoint.-1.-1
talk.<
    Ты никогда не убежишь из этой ловушки.
    Наши {4*Феи Тьмы} легко уничтожат твоих!
>
waitForUser
setCamera.3000
deployNpcAtTrigger.82.6eceda24
startEffect.0.82
delay.10
playSound.5
setCamera.3001
delay.10
playSound.5
setCamera.3002
delay.10
playSound.5
setCamera.3003
delay.10
playSound.5
fight.-1.1"""
InitScript = """
setModel.u000s00m
defaultDeck.2.40.1"""
UpdateScript = """
label.0
lookAtPlayer.1.1
ifPlayerIsClose.15
startPrelude
endIf
goto.0"""
DefeatedScript = """
talk.<Друид, помоги нам, кто может ее остановить?!>
waitForUser
removeNpcAtTrigger.81
delay.10
startEffect.0.87
delay.1
setCamera.3001
startEffect.0.88
delay.1
startEffect.1.89
delay.1
setCamera.3000
startEffect.1.90
delay.1
startEffect.0.88
delay.1
startEffect.0.91
delay.1
setCamera.3003
startEffect.1.91
delay.1
startEffect.0.87
delay.1
setCamera.3002
startEffect.1.92
delay.1
startEffect.1.89
delay.1
startEffect.1.90
delay.1
startEffect.0.88
delay.1
removeNpc"""
