UID = "6FD7BD94"
Name = "7B2D8F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Что ты за жуткий призрак?>.0
waitForUser
label.10
say.<
    Не расстраивайся, не каждый может быть гномом.
    Могу я тебе помочь?
>.1
choice.0.<Происхождение и смысл этой странной тучи>
choice.1.<Купить что-нибудь>
choice.2.<Счастливого пути>
waitForUser
exit
label.0
setTalkLabels.-1.-1.2
talk.<
    Не спрашивай меня об этой дурацкой грозовой туче.
    Она льет на меня изо дня в день, и еще эти постоянные вспышки молнии...
>
waitForUser
talk.<
    Я хотел провести небольшой эксперимент.
    Поскольку я изобретатель, я хотел попробовать использовать энергию молнии, чтобы запустить наши старые машины.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    К сожалению, молния, на которую я рассчитывал, поразила меня.
    С тех пор я оказался здесь.
    Здесь, в этой пещере, я по крайней мере в безопасности...
>
waitForUser
goto.10
label.1
setTalkLabels.-1.-1.2
talk.<
    Я не крупный торговец, но мог бы продать тебе {4*фею}.
    Когда-то это была хорошая Фея Воды, но постоянные молнии как-то повлияли на ее волшебную сущность.
>
waitForUser
setTalkLabels.20.10.1
talk.<
    Я отдам тебе эту редкую фею за смешную цену в {4*100 кристаллов}.
    Согласна?
>
waitForUser
label.20
setTalkLabels.-1.-1.0
ifPlayerHasCards.100.0.6
removePlayerCards.100.0.6
givePlayerCards.1.2.141
talk.<
    Отлично, забирай фею.
    Она единственная в своём роде, так что хорошо заботься о ней! И будь аккуратна, а то закончишь с такой же тучей на голове...
>
waitForUser
removeWizForms
changeDatabase.df234a14
exit
endIf
talk.<
    О, у тебя недостаточно кристаллов.
    Приходи попозже.
    Я буду здесь...
    мокнуть...
>
waitForUser
exit
label.2
exit"""
InitScript = """
setModel.d000s00m
defaultWizForm.141.0.3
startActorEffect.0"""
UpdateScript = "lookAtPlayer.0.1"
