UID = "1900B294"
Name = "10E82091"
TriggerScript = """
setCamera.3001
deployNpcAtTrigger.36.1
playAnimation.13.-1
say.<Добро пожаловать в Башню Мудрости!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Вижу, ты пришла издалека.
    Но только тот, кто победит меня и моего старшего брата, достоин получить {4*Карту Земли}.
>
waitForUser
setTalkLabels.10.11.1
talk.<Ты готова участвовать в поединке фей?>
waitForUser
label.10
setCamera.1006
fight.-1.0
label.11
setTalkLabels.-1.-1.0
talk.<Я уверен, что выиграю!>
waitForUser"""
InitScript = """
setModel.b011s00m
defaultWizForm.131.0.39
defaultWizForm.17.1.38
defaultWizForm.132.2.36
defaultWizForm.118.3.37
defaultWizForm.48.4.37
spell.0.0.37
spell.0.2.22
spell.2.2.7
spell.3.2.3"""
UpdateScript = """
label.0
idle
ifPlayerIsClose.5
startPrelude
else
lookAtPlayer.5.1
endIf
goto.0"""
DefeatedScript = """
setTalkLabels.-1.-1.0
setCamera.3001
setTalkLabels.-1.-1.0
talk.<
    Твои феи хорошо подготовлены! Но одержат ли они победу над феями моего старшего брата?
    Приходи ко мне в библиотеку, если хочешь побольше узнать о {4*Царстве Облаков}.
>
waitForUser
givePlayerCards.1.0.107
changeWaypoint.-1.100
changeWaypoint.100.101
removeNpc
setCamera.1006"""
VictoriousScript = "killPlayer"
