UID = "E3843EB4"
Name = "0FDF8F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Добро пожаловать на Большое Дерево.>.0
waitForUser
setTalkLabels.5.6.1
talk.<Могу я предложить тебе немного {4*Концентрированного Нектара}, он может пригодиться в твоих путешествиях?>
waitForUser
label.5
givePlayerCards.3.0.9
changeDatabase.599E9214
exit
label.6
setTalkLabels.-1.-1.0
talk.<Хорошо.>
waitForUser
changeDatabase.599E9214
exit"""
InitScript = "setModel.g001s01m"
UpdateScript = "lookAtPlayer.-1.1"
