UID = "A8B22034"
Name = "5B6A3F31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.15.-1
say.<
    Но я никому не верю.
    {4*Белый Друид} давно запретил использовать {4*Карты Магии}, которые когда-то нам даровали феи.
    Мы бессильны что-то сделать без них, и обещания {4*Белого Друида}, что всё придёт к лучшему, оказались ложью.
    Если даже {4*Тёмные Эльфы} поняли это, теперь лишь вопрос времени, когда именно всё станет ещё хуже.
>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<...>
waitForUser
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Медовый Эликсир} (х2)!>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    И теперь, человек в нашем мире.
    Не волнуйся, ты не сможешь сделать наше положение ещё более невыносимым.
    Если не гоблины и гномы, так эльфы заставят вернуться нас во времена {4*Раскола}, — впрочем, даже тогда всё было не настолько плохо, как сейчас.
    Уж точно дороги не были перекрыты {4*Огромными Валунами}, {4*Терновыми Кустами} или отвратительными {4*Тёмными Эльфами}!
>
waitForUser"""
InitScript = "setModel.w003s03m"
UpdateScript = "lookAtPlayer.0.0"
