UID = "867BC434"
Name = "5B6A3F31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.15.-1
say.<Эмми, рад тебя видеть.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Ты проделала длинный путь, Эмми.
    Все, кто прошел глубокие каньоны и долины {4*Занзары}, должны быть опытными и обладать большой выносливостью.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Но поверь мне: даже если ты заберешься на самую высокую вершину местных гор, то все равно не увидишь настоящих высот Занзары! Туда нет обычного пути.
    Ты должна использовать  {4*лифты гномов}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<Управляемые магической силой легендарных  {4*Стихийных Ключей}, эти лифты привезут тебя в самые удивительные места {4*Занзары}.>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    В зависимости от маршрута, таким лифтам для работы необходимы различные {4*Стихийные Ключи}.
    Лифту за углом необходимы{4* Воздушный}, {4*Земляной} и {4*Природный} – их всегда должно быть три.
>
waitForUser"""
InitScript = "setModel.w003s03m"
UpdateScript = "lookAtPlayer.0.0"
