UID = "E8A1C684"
Name = "6E781E01"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Приветствую, Эми, охота на пикси была удачной?>.0
waitForUser
label.0
say.<Надеюсь, эти маленькие существа не доставляют слишком много проблем в твоём путешествии?>.3
choice.3.<Диалог>
choice.2.<Сдать пикси>
choice.1.<До встречи>
waitForUser
label.1
exit
label.3
say.<
    Говорят, в {4*Эндеве} видели {4*Тёмного Эльфа}...
    это не может быть правдой, верно?
>.3
choice.100.<Зловредные Пикси>
choice.101.<Волшебное Пугало>
choice.102.<Царство Тьмы>
choice.103.<Назад>
waitForUser
label.103
goto.0
label.100
setTalkLabels.-1.-1.2
talk.<
    {4*Пикси} являются существами, имеющими тёмное и таинственное происхождение.
    Кто-то считает их прислужниками злого волшебника из далёких земель, а кто-то думает, что за ними стоят {4*Тёмные Эльфы}, которые создали их, чтобы сеять хаос в {4*Занзаре}.
    Но на самом деле всё это лишь выдумки, далекие от настоящей правды.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    На самом деле {4*пикси} родом из заброшенной и мифической деревни {4*Грамайр}, которая находится по другую сторону снежных гор.
    Когда-то на {4*Грамайр} пало страшное проклятье, и с тех пор там царит вечная ночь.
    Это было наказанием {4*Нимиры}, одной из {4*Друидов}, за то, что жители деревни создали известных тебе пикси.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Когда-то пикси были мирным народом {4*Лиственников}, добродушными духами деревьев и растений.
    Но эксперименты с магией, для которых они были подопытными, изменил их облик и заставил полностью потерять свой разум.
    Когда {4*Нимира} узнала об этом, она укрыла всю деревню барьером, чтобы {4*пикси} не смогли выбраться оттуда во внешний мир.
    
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Но это всего лишь легенда.
    Я все ещё предпочитаю верить этому, хотя многие думают об этом как об обычной страшной сказке для детей.
    Но я не думаю, что {4*Тёмные Эльфы} обладали когда-либо силой, способной создать таких существ.
    В любом случае, мы не можем ничего сделать для {4*пикси}, кроме как не давать им создавать проблемы для всех окружающих.
>
waitForUser
goto.3
label.101
setTalkLabels.-1.-1.2
talk.<
    {4*Эндева} — мирная деревня, в которой поколениями занимаются фермерством и выращиванием овощей.
    Но, в отличие от остальных, у меня есть одна неприятная вещь, которая осложняет мою спокойную жизнь, — это {4*феи Хаоса}, обитающие в подвале моего дома.
    Поэтому, чтобы они не пытались испортить мой урожай, его охраняет специальное магическое пугало.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Он нелюдим и редко приветлив, но он все ещё незаменим, когда дело касается {4*фей Хаоса}.
    Видишь ли, это пугало зачаровано особыми чарами, позволяющими ему восполнять магические силы фей, и поэтому феи постоянно слетаются к нему...
    и с тех пор, что повсюду в {4*Саду фей} обитают {4*феи Природы}, то {4*феи Хаоса} не решаются уйти куда-либо отсюда.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Обычно я позволяю проходящим мимо путешественникам прогонять {4*фей Хаоса} в обмен на небольшую часть своего урожая.
    И этот случай не исключение.
    Если ты ещё не сделала этого, то ты можешь найти пугало прямо перед моим домом.
    Уверен, он будет весьма благодарен тебе за своё спасение и поможет восполнить магические силы твоих фей.
>
waitForUser
goto.3
label.102
setTalkLabels.-1.-1.2
talk.<
    Насколько тебе может показаться прекрасным мир {4*Занзары}, настолько же пугающей является его изнанка.
    {4*Царство Тьмы} - это ужасающее место, где обитают {4*феи Тьмы и Хаоса}, и вход в него находится глубоко в {4*болотах Данмора}, недалеко от поселения {4*Большого Дерева}.
    Ты легко можешь заметить его по огромным камням, похожим на открытую пасть неизвестного существа.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Глубоко под землёй {4*Тёмные Эльфы} поселились среди развалин некогда существовавший системы крепостей.
    В конце {4*эпохи Драконов} они использовались для защиты от {4*фей Тьмы и Хаоса}, которых пробудили многочисленные катаклизмы по всей {4*Занзаре}.
    Однако эти строения существовали ещё задолго до этого времени, но никто не знает, кто действительно был их строителем.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Теперь события прошлого повторяются снова, — на этот раз {4*Тёмные Эльфы} покинули свои жилища, как когда-то это сделали феи.
    Никто не может сказать, что стало причиной этого, но возможно это лишь указывает на очередные перемены, настигающие {4*Занзару}?
    {4*Эпоха Предсказания} приходит к концу, и вместе с ней наступит новое будущее, чтобы снова вернуть гармонию в этот мир.
>
waitForUser
goto.3
label.2
ifNpcModifierHasValue.0
goto.4
endIf
ifNpcModifierHasValue.1
goto.8
endIf
ifNpcModifierHasValue.2
goto.12
endIf
ifNpcModifierHasValue.3
goto.16
endIf
ifNpcModifierHasValue.4
goto.20
endIf
ifNpcModifierHasValue.5
goto.24
endIf
ifNpcModifierHasValue.6
goto.28
label.4
ifPlayerHasSpecials.0.10
setNpcModifier.-1.-1.1
say.<
    Прекрасно.
    Благодарю, что ты вернула этих негодников обратно.
    Вот твоя награда за {4*пять пикси}.
>.3
choice.5.<{4*Загадочная Шкатулка} (х2)>
choice.6.<{4*Горсть Пыльцы Фей (25 опыта)} (х8)>
choice.7.<{4*Рунический Свиток} (x3)>
waitForUser
endIf
setTalkLabels.-1.-1.0
talk.<
    Извини, но у тебя не достаточно пикси для обмена.
    Я дам тебе вознаграждение за каждых {4*пять пойманных пикси}.
>
waitForUser
goto.0
label.5
givePlayerCards.2.0.99
exit
label.6
givePlayerCards.8.0.1
exit
label.7
givePlayerCards.3.0.102
exit
label.8
ifPlayerHasSpecials.0.10
setNpcModifier.-1.-1.2
say.<
    Прекрасно.
    Благодарю, что ты вернула этих негодников обратно.
    Вот твоя награда за {4*пять пикси}.
>.3
choice.9.<{4*Загадочная Шкатулка} (х4)>
choice.10.<{4*Пригоршня Пыльцы Фей (50 опыта)} (х10)>
choice.11.<{4*Рунический Свиток} (x6)>
waitForUser
endIf
setTalkLabels.-1.-1.0
talk.<
    Извини, но у тебя не достаточно пикси для обмена.
    Я дам тебе вознаграждение за каждых {4*пять пойманных пикси}.
>
waitForUser
goto.0
label.9
givePlayerCards.4.0.99
exit
label.10
givePlayerCards.10.0.2
exit
label.11
givePlayerCards.6.0.102
exit
label.12
ifPlayerHasSpecials.0.10
setNpcModifier.-1.-1.3
say.<
    Прекрасно.
    Благодарю, что ты вернула этих негодников обратно.
    Вот твоя награда за {4*пять пикси}.
>.3
choice.13.<{4*Мистическая Шкатулка} (х3)>
choice.14.<{4*Очищенный Нектар} (x6)>
choice.15.<{4*Рунический Свиток} (x9)>
waitForUser
endIf
setTalkLabels.-1.-1.0
talk.<
    Извини, но у тебя не достаточно пикси для обмена.
    Я дам тебе вознаграждение за каждых {4*пять пойманных пикси}.
>
waitForUser
goto.0
label.13
givePlayerCards.3.0.100
exit
label.14
givePlayerCards.6.0.9
exit
label.15
givePlayerCards.9.0.102
exit
label.16
ifPlayerHasSpecials.0.10
setNpcModifier.-1.-1.4
say.<
    Прекрасно.
    Благодарю, что ты вернула этих негодников обратно.
    Вот твоя награда за {4*пять пикси}.
>.3
choice.17.<{4*Мистическая Шкатулка} (х7)>
choice.18.<{4*Насыщенный Нектар (1000 опыта)} (x1)>
choice.19.<{4*Рунический Свиток} (x15)>
waitForUser
endIf
setTalkLabels.-1.-1.0
talk.<
    Извини, но у тебя не достаточно пикси для обмена.
    Я дам тебе вознаграждение за каждых {4*пять пойманных пикси}.
>
waitForUser
goto.0
label.17
givePlayerCards.7.0.100
exit
label.18
givePlayerCards.1.0.88
exit
label.19
givePlayerCards.15.0.102
exit
label.20
ifPlayerHasSpecials.0.10
setNpcModifier.-1.-1.5
say.<
    Прекрасно.
    Благодарю, что ты вернула этих негодников обратно.
    Вот твоя награда за {4*пять пикси}.
>.3
choice.21.<{4*Магическая Шкатулка} (х8)>
choice.22.<{4*Концентрированный Нектар (2250 опыта)} (x1)>
choice.23.<{4*Рунический Свиток} (x25)>
waitForUser
endIf
setTalkLabels.-1.-1.0
talk.<
    Извини, но у тебя не достаточно пикси для обмена.
    Я дам тебе вознаграждение за каждых {4*пять пойманных пикси}.
>
waitForUser
goto.0
label.21
givePlayerCards.8.0.101
exit
label.22
givePlayerCards.1.0.89
exit
label.23
givePlayerCards.25.0.102
exit
label.24
ifPlayerHasSpecials.0.10
setNpcModifier.-1.-1.6
say.<
    Прекрасно.
    Благодарю, что ты вернула этих негодников обратно.
    Вот твоя награда за {4*пять пикси}.
>.3
choice.25.<{4*Магическая Шкатулка} (х15)>
choice.26.<{4*Концентрированный Нектар (2250 опыта)} (x4)>
choice.27.<{4*Рунический Свиток} (x40)>
waitForUser
endIf
setTalkLabels.-1.-1.0
talk.<
    Извини, но у тебя не достаточно пикси для обмена.
    Я дам тебе вознаграждение за каждых {4*пять пойманных пикси}.
>
waitForUser
goto.0
label.25
givePlayerCards.15.0.101
exit
label.26
givePlayerCards.4.0.89
exit
label.27
givePlayerCards.40.0.102
exit
label.28
say.<
    Ты уже собрала всех пикси, Эми.
    Теперь они все надежно заперты в своих клетках.
>.#
goto.0
label.1
exit"""
InitScript = """
setModel.g202s22m
defaultWizForm.194.0.0"""
UpdateScript = "lookAtPlayer.0.1"
