UID = "63D94324"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
gotoRandomLabel.3.0
label.0
say.<Человеческим духом пахнет?>.0
waitForUser
goto.3
label.1
say.<Человеческим духом пахнет?>.0
waitForUser
goto.3
label.2
say.<Человеческим духом пахнет?>.0
waitForUser
goto.3
label.3
setCamera.1006
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.122.0.43
defaultWizForm.57.1.41
defaultWizForm.104.2.40
defaultWizForm.64.3.40
defaultWizForm.116.4.43
spell.0.2.38
spell.2.2.48
spell.4.2.43
goto.3
label.1
defaultWizForm.122.0.43
defaultWizForm.126.1.42
defaultWizForm.95.2.40
defaultWizForm.13.3.41
defaultWizForm.38.4.43
spell.0.2.38
spell.1.2.42
spell.2.2.131
goto.3
label.2
defaultWizForm.122.0.43
defaultWizForm.109.1.41
defaultWizForm.121.2.42
defaultWizForm.28.3.41
defaultWizForm.5.4.41
spell.0.2.38
spell.1.0.37
spell.1.2.12
spell.2.2.56
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
