UID = "49F089B4"
Name = "6DDE8221"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<
    Никогда не видела никого, подобных тебе...
    ты пришла из другого мира?
>.0
waitForUser
label.0
say.<
    Тёмные Эльфы перекрыли все дороги между городами...
    чего они пытаются этим добиться?
>.1
choice.2.<Торговля>
choice.1.<До встречи>
waitForUser
label.2
tradingCurrency.C564B4A3
tradingItem.150.4D4A9913
tradingItem.250.CD73C313
tradingItem.150.9DAC42B3
tradingItem.250.8B7A91A3
tradingItem.500.4253C0A3
waitForUser
goto.0
label.1
exit"""
InitScript = """
setModel.g004s03m
movementSpeed.8
defaultWizForm.126.0.2"""
UpdateScript = """
label.0
moveSystem.1.4
gotoRandomLabel.3.0
goto.0
label.1
playAnimation.0.30
goto.0
label.2
playAnimation.11.30
goto.0"""
