UID = "55E534A4"
Name = "15A948B1"
TriggerScript = """
setCamera.1000
say.<Что ты ищешь в этом мрачном месте?>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Эти странные существа с крыльями заплатили много денег для того, чтобы выкупить это место.
    Похоже, со временем их станет здесь больше, но я боюсь, что мало кто оценит общество такого костлявого собеседника как я.
>
waitForUser"""
InitScript = "setModel.x002s02"
UpdateScript = "lookAtPlayer.-1.1"
