UID = "D2CB5434"
Name = "AC621EB1"
TriggerScript = """
setCamera.1003
say.<Приветствую.>.0
playAnimation.13.-1
waitForUser
label.0
say.<
    Если тебе нужны магические сферы или зелья, то это на первом этаже.
    Но ты здесь не за этим?
>.3
choice.1.<Диалог>
choice.2.<Торговля>
choice.3.<Обмен>
choice.4.<До встречи>
waitForUser
label.2
tradingCurrency.C564B4A3
tradingItem.25.99613EA3
tradingItem.50.2E2FB8A3
tradingItem.125.709DB4A3
waitForUser
goto.0
label.3
say.<С того времени, как этот эльф начал продавать {4*Эволюционные Камни}, все только и спрашивают об этих овощах...>.3
choice.5.<Обмен {4*Медного Редиса}>
choice.6.<Обмен {4*Серебрянного Лука}>
choice.7.<Обмен {4*Золотой Моркови}>
waitForUser
label.5
tradingCurrency.99613EA3
tradingItem.2.2E2FB8A3
tradingItem.6.709DB4A3
waitForUser
goto.0
label.6
tradingCurrency.2E2FB8A3
tradingItem.1.99613EA3
tradingItem.2.709DB4A3
waitForUser
goto.0
label.7
tradingCurrency.709DB4A3
tradingItem.1.99613EA3
tradingItem.1.2E2FB8A3
waitForUser
goto.0
label.1
say.<
    {4*Тиралин} прекрасен, не правда ли?
    Не видела ничего прекраснее него в своей жизни.
>.3
choice.8.<Фестиваль Весны>
choice.9.<Магические Овощи>
choice.10.<Семейное Дело>
choice.11.<Назад>
waitForUser
label.8
setTalkLabels.-1.-1.2
talk.<
    В {4*Занзаре} существует много праздников, но один из самых главных - это {4*Фестиваль Весны}.
    Все расы собираются вместе, чтобы отметить наступление нового года, в окружении своих семей и друзей.
    На время праздника стены {4*Тиралина} украшаются гербовыми знамёнами, горшками с цветами, а торговцы расставляют на улицах своих лавки, где продают сезонные товары.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Когда я была молодой, я всегда отпрашивалась у родителей, чтобы участвовать в {4*традиционном конкурсе} на лучший танец.
    На протяжении всего года я готовилась к этому, чтобы как-то отвлечься от ежедневной рутины, и завоевать главную награду.
    Отчего-то я была уверена, что если выиграю её, то смогу избавиться от постоянной необходимости помогать по магазину.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    А потом на одном из фестивалей я встретила своего будущего мужа, и ты сама можешь догадаться, чем всё это кончилось.
    Воспоминания об удивительно прожитых моментах не перестают вызывать у меня улыбку, но, к сожалению, тоже иногда напоминают мне о том, какая я стала сейчас.
    И я иногда просыпаюсь и с тоской думаю: а что, если бы я тогда сделала по-другому?
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Как бы то ни было, праздник бывает лишь один раз в году и нельзя постоянно жить только в его ожидании.
    Известная эльфийская поговорка гласит: \"{4*Если эльф отрастит себе крылья, как у феи, то первое, что он сделает - это перестанет работать}\".
    Праздники нужны для того, чтобы делиться горестями и радостями своей жизни с другими, а не только для того, чтобы забыть об ежедневной рутине.
>
waitForUser
goto.0
label.9
setTalkLabels.-1.-1.2
talk.<
    Тебе тоже интересно, почему фей так привлекают эти {4*овощи}?
    На самом деле, ответ прост: они выращены при помощи {4*магии}, и поэтому используются в {4*алхимии} и реже в {4*кулинарии} из-за необычных вкусовых качеств.
    Каждая раса выращивает свой {4*вид овоща}, пригодный для культивации в их среде обитания.
    
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    {4*Сок из Золотой моркови} обладает сильным тонизирующим эффектом, а также используется как средство для укрепления организма.
    {4*Зелень от Медного редиса} широко используется как приправа, а сами плоды могут нейтрализовывать слабые яды.
    Что же до {4*Серебряного лука}, то его сок является катализатором алхимических реакций и не только.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Возможно, тебе стоит когда-нибудь попробовать {4*эльфийское овощное рагу} или {4*форель, запечённую в листьях редиса} по традиционному рецепту {4*Болотных Гоблинов}.
    Я слышала, что {4*гномы} также выращивают в пещерах грибы, но я никогда не пробовала блюда из них.
    
>
waitForUser
goto.0
label.10
setTalkLabels.-1.-1.2
talk.<
    Держать свой магазин — это очень непростое дело, как ты понимаешь.
    Я здесь самая главная, и мне постоянно приходится за всем следить.
    Думаю, ты уже успела познакомится с моей непутёвой невесткой {4*Агатой} и моим сыном {4*Ларсом}.
    Если бы у {4*Агаты} не было такого таланта к алхимии, я никогда бы не позволила своему любимому сыну связать с ней свою жизнь.
    
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Поэтому когда {4*Ларс} обьявил о том, что он нашёл себе жену, я была вне себе от счастья: мы давно нуждались в лишней паре рук.
    Варка зелий требует очень много времени и умений, и я не могла одновременно стоять за прилавком и заниматься алхимией.
    Мне приходилось делать это ночью, и даже так мы были вынуждены покупать часть товаров у других алхимиков.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Всё бы ничего, но {4*Агата} постоянно думает, как заработать больше денег! Она настояла на повышении цен зелий, и из-за этого часть постоянных покупателей предпочитает теперь идти в {4*Эндеву}! И ещё она абсолютно отказывается покупать любые зелья у других торговцев, говоря, что мы должны готовить их только сами.
    Но у самой {4*Агаты} нет для этого времени!
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    И это ещё не всё.
    Она просто одержима экспериментированием! Насколько сильно мне нравится её преданность своему делу, она зачастую забывает о банальной безопасности окружающих! Просто постой здесь несколько минут, и ты сразу поймёшь, о чём я говорю.
>
waitForUser
goto.13
label.13
playAmyVoice.1
delay.5
goto.14
label.14
setTalkLabels.-1.-1.2
talk.<Через какое-то время тишину нарушил звук разбитой посуды.>
waitForUser
goto.15
label.15
playAmyVoice.2
delay.5
goto.16
label.16
setTalkLabels.-1.-1.2
talk.<И потом взрыв...>
waitForUser
goto.17
label.17
playAmyVoice.1
delay.5
goto.18
label.18
setTalkLabels.-1.-1.2
talk.<И снова что-то разбилось...>
waitForUser
goto.19
label.19
playAmyVoice.3
delay.5
goto.20
label.20
setTalkLabels.-1.-1.2
talk.<А это что было?..>
setTalkLabels.-1.-1.0
talk.<
    Вот именно об этом я и говорила! И так происходит каждый день! Я устала считать, сколько посуды уже было разбито, а от этих взрывов у меня уже болит голова! Если так продолжится, то скоро от этого магазина не останется ни одной досточки!
>
waitForUser
goto.0
label.11
goto.0
label.4
exit"""
InitScript = """
setModel.b024s21m
defaultWizForm.8.0.0"""
UpdateScript = "lookAtPlayer.0.1"
