UID = "B503A694"
Name = "5C9F1A31"
TriggerScript = """
setCamera.1003
say.<Добро пожаловать в таверну {4*\"Печальный Сатир\"}.>.0
playAnimation.13.-1
waitForUser
label.0
say.<Скажи, все ли человеческие девушки также красивы, словно феи из сказок, или это только ты?>.3
choice.1.<Диалог>
choice.2.<Обмен>
choice.3.<До встречи>
waitForUser
label.1
say.<Я наслаждаюсь каждой минутой нашего общения, и ты явно хочешь узнать больше о Занзаре, верно?>.3
choice.4.<Забытые Ритуалы>
choice.5.<Имена Эльфов>
choice.6.<Тревожные Знаки>
choice.7.<Назад>
waitForUser
label.4
setTalkLabels.-1.-1.2
talk.<
    Сейчас мало кто верит в это, однако {4*Культ Друидов} пришёл в упадок ещё задолго до событий {4*Раскола}.
    Когда-то {4*Друиды} были служителями равновесия и гармонии в {4*Занзаре}, но большинство из них исчезло, и никто не знает точных причин этого.
    {4*Белый Друид} — один из последних, кто ещё жив, но даже он решил уйти в самовольное отшельничестве.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Не только {4*эльфы}, но {4*гномы} и {4*гоблины} теперь пытаются вспомнить давние ритуалы и обряды, взывающие к первородным силам природы.
    Увы, этого недостаточно для того, чтобы заменить {4*Карты Магии} — мы даже не можем вызывать фей из их собственных миров, как когда-то это делали в прошлом.
    И похоже, что даже феи забыли, как когда-то они были совсем другими...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я сам принимал участие в некоторых обрядах, вместе с {4*эльфами из Тиралина}.
    Мы путешествовали к {4*кругу камней в болотах Данмора} — и хотя это было весело, а также таинственно, мы не смогли получить никаких результатов.
    Может, никто из нас не знал правильного ритуала?
    Но даже {4*гоблины} не помнят, для чего именно нужно было это место!
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Когда-то {4*Друиды} использовали свой уникальный дар, чтобы превратить это место в {4*Сад фей} — прекрасное царство тишины и спокойствия.
    И почему мы не можем этого сделать с {4*болотами Данмора}, которые некогда были огромным морем?
    Если мы смогли узнать секрет силы {4*Друидов}, я уверен, всё могло бы измениться к лучшему!
>
waitForUser
goto.1
label.5
setTalkLabels.-1.-1.2
talk.<
    Тебе интересно, как звучит моё настоящее имя?
    Это будет {4*Флавиус «Волк» Левин}.
    Слишком длинное и сложное, чтобы его запомнить, верно?
    Поэтому я обычно обхожусь только прозвищем — по крайней мере, оно не звучит, словно я какая-то далекая и глупая деревенщина из этих мест, тебе так не кажется?
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Если ты будешь обращать внимание на имена других {4*эльфов}, то можешь заметить, что у некоторых из них могут встречаться схожие окончания.
    По старой традиции, эти окончания указывают на место рождения, — деревню или город, — но среди богатых {4*эльфов} нередко имеются уникальные окончания, которые служат указанием на процветающую историю их семьи и рода.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    В настоящее время мало кто следует этим правилам.
    Окончание может наследоваться от мужской или женской линии рода, а иногда оно не связано ни с чем, и родители подбирают имя, исходя из собственных соображений.
    С большей вероятностью ты встретишь такие имена в городах, где традиции не так сильны, как в удаленных местах {4*Занзары}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Ах да, ты вероятно также будешь задаваться вопросом, как это работает у {4*Тёмных Эльфов}, — если тебе встретится один из них.
    Сказать по правде, я не имею ни малейшей идеи об этом.
    Хотя их язык очень похож на наш, я не хочу даже думать, кто или что могло породить на свет таких созданий...
    поэтому тебе лучше спросить об этом у кого-то другого.
>
waitForUser
goto.1
label.6
setTalkLabels.-1.-1.2
talk.<
    К сожалению, {4*Занзара} переживает не лучшие свои времена.
    Когда-то {4*Эндева} выглядела оживлённым местом, где собирались начинающие {4*Коллекционеры фей}, а на улицах {4*Тиралина} можно было увидеть бродячих музыкантов и поэтов.
    Сейчас это всё лишь тень былого прошлого.
    И даже не вздумай верить тем, кто говорит, что всё хорошо — они просто не желают замечать очевидного!
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Уже который год мы сталкиваемся с неурожаем, а {4*Зачарованный Лес} стал опасным местом, куда нельзя заходить, не имея верной феи за твоим плечом.
    {4*Тёмные Эльфы} покинули {4*Царство Тьмы}, чтобы объявить, что {4*Избранная} из {4*Предсказания} — это их {4*Королева}, ведь люди, ставшие причиной {4*Раскола}, не могут принести в {4*Занзару} ничего, кроме разрушения.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Но я никому не верю.
    {4*Белый Друид} давно запретил использовать {4*Карты Магии}, которые когда-то нам даровали феи.
    Мы бессильны что-то сделать без них, и обещания {4*Белого Друида}, что всё придёт к лучшему, оказались ложью.
    Если даже {4*Тёмные Эльфы} поняли это, теперь лишь вопрос времени, когда именно всё станет ещё хуже.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    И теперь, человек в нашем мире.
    Не волнуйся, ты не сможешь сделать наше положение ещё более невыносимым.
    Если не гоблины и гномы, так эльфы заставят вернуться нас во времена {4*Раскола}, — впрочем, даже тогда всё было не настолько плохо, как сейчас.
    Уж точно дороги не были перекрыты {4*Огромными Валунами}, {4*Терновыми Кустами} или отвратительными {4*Тёмными Эльфами}!
>
waitForUser
goto.1
label.2
tradingCurrency.8E0E9503
tradingItem.3.62689503
tradingItem.5.ADB09503
tradingItem.1.672642b3
tradingItem.1.1889A2B3
tradingItem.2.79064393
waitForUser
goto.0
label.7
goto.0
label.3
exit"""
InitScript = "setModel.b027s31m"
UpdateScript = "lookAtPlayer.0.1"
