UID = "D34025D4"
Name = "E11231A1"
TriggerScript = """
setCamera.1003
say.<Ещё одно существо, ищущее безграничную силу?>.0
playAnimation.13.-1
waitForUser
label.0
say.<Я могу исполнить все твои желания за соответствующую плату...>.3
choice.1.<Диалог>
choice.2.<Торговля>
choice.3.<Обмен>
choice.4.<До встречи>
waitForUser
label.2
tradingCurrency.BAA9B8A3
tradingItem.10.FA48BCA3
tradingItem.30.2F9B40A3
tradingItem.60.6D96A6A3
waitForUser
goto.0
label.3
setTalkLabels.10.11.1
talk.<
    Я могу открыть все имеющиеся у тебя шкатулки и отдать то, что в них лежит.
    Ты хочешь открыть их?
>
waitForUser
label.10
ifPlayerHasCards.1.0.99
removePlayerCards.1.0.99
goto.5
else
ifPlayerHasCards.1.0.100
removePlayerCards.1.0.100
goto.6
else
ifPlayerHasCards.1.0.101
removePlayerCards.1.0.101
goto.7
else
setTalkLabels.-1.-1.0
talk.<
    У тебя больше не осталось шкатулок для открытия...
    но ты можешь всегда купить их, когда у тебя появятся кристаллы, хе-хе.
>
waitForUser
goto.0
label.11
goto.0
label.1
say.<О чём ты хочешь узнать?>.3
choice.14.<Правила игры>
choice.13.<Список наград>
choice.12.<Назад>
waitForUser
label.14
setTalkLabels.-1.-1.0
talk.<
    Всё очень просто.
    Ты покупаешь одну из шкатулок за кристаллы, а потом меняешь его на {4*случайную награду}.
    Чем более дорогая шкатулка, тем выше шанс на большую награду...
    или меньшую, хе-хе.
    Поэтому ты можешь захотеть проверить, на твоей стороне сегодня удача или же нет.
>
waitForUser
goto.0
label.13
setTalkLabels.-1.-1.2
talk.<{4*Загадочная Шкатулка} может содержать: {4*Щепотка Пыльцы фей} (х8-12), {4*Горсть Пыльцы фей} (x4-6), {4*Малый Лечебный Бальзам} (x2-4), {4*Средний Лечебный Бальзам} (x2-3), {4*Лесные Травы} (x3-4), {4*Флакон Маны} (x2), {4*Лекарство} (x2), {4*Чесночный Распылитель} (x1), {4*Серебрянный Шар} (х1)>
waitForUser
setTalkLabels.-1.-1.2
talk.<{4*Мистическая Шкатулка} может содержать: {4*Пригорошня Пыльцы фей} (x3-9), {4*Очищенный Нектар} (x1-3), {4*Большой Лечебный Бальзам} (x3-7), {4*Эликсир Маны} (x1), {4*Медный Редис} (x3-9), {4*Серебрянный Лук} (x2-4), {4*Золотая Морковь} (x1), {4*Золотой Шар} (x1)>
waitForUser
setTalkLabels.-1.-1.0
talk.<{4*Магическая Шкатулка} может содержать: {4*Насыщенный Нектар} (x1), {4*Концентрированный Нектар} (x1), {4*Лечебный Эликсир} (x1-2), {4*Большой Эликсир Маны} (x1-3), {4*Медовый Эликсир} (x1-8), {4*Большой Медовый Эликсир} (x1-5), {4*Эликсир Стихий} (x1-7), {4*Хрустальный Шар} (x1)>
waitForUser
goto.0
label.12
goto.0
label.5
setTalkLabels.-1.-1.2
talk.<Ты открываешь {4*Загадочную Шкатулку}...>
waitForUser
gotoRandomLabel.26.50
label.50
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Серебряный Шар} (х1)!>
waitForUser
givePlayerCards.1.0.17
goto.10
label.51
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х8)!>
waitForUser
givePlayerCards.8.0.0
goto.10
label.52
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х9)!>
waitForUser
givePlayerCards.9.0.0
goto.10
label.53
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х10)!>
waitForUser
givePlayerCards.10.0.0
goto.10
label.54
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х11)!>
waitForUser
givePlayerCards.11.0.0
goto.10
label.55
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х12)!>
waitForUser
givePlayerCards.12.0.0
goto.10
label.56
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Горсть Пыльцы фей} (х4)!>
waitForUser
givePlayerCards.4.0.1
goto.10
label.57
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Горсть Пыльцы фей} (х5)!>
waitForUser
givePlayerCards.5.0.1
goto.10
label.58
setTalkLabels.-1.-1.2
talk.<Диалог>
waitForUser
givePlayerCards.6.0.1
goto.10
label.59
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Малый Лечебный Бальзам} (х2)!>
waitForUser
givePlayerCards.2.0.11
goto.10
label.60
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Малый Лечебный Бальзам} (х3)!>
waitForUser
givePlayerCards.3.0.11
goto.10
label.61
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Малый Лечебный Бальзам} (х4)!>
waitForUser
givePlayerCards.4.0.11
goto.10
label.62
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Средний Лечебный Бальзам} (х2)!>
waitForUser
givePlayerCards.2.0.12
goto.10
label.63
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Средний Лечебный Бальзам} (х3)!>
waitForUser
givePlayerCards.3.0.13
goto.10
label.64
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Флакон Маны} (х2)!>
waitForUser
givePlayerCards.2.0.61
goto.10
label.65
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Лекарство} (х2)!>
waitForUser
givePlayerCards.2.0.74
goto.10
label.66
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Чесночный Распылитель} (х1)!>
waitForUser
givePlayerCards.1.0.20
goto.10
label.67
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Лесные Травы} (х3)!>
waitForUser
givePlayerCards.3.0.5
goto.10
label.68
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Лесные Травы} (х4)!>
waitForUser
givePlayerCards.4.0.5
goto.10
label.6
setTalkLabels.-1.-1.2
talk.<Ты открываешь {4*Мистическую Шкатулку}...>
waitForUser
gotoRandomLabel.28.100
label.100
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Золотой Шар} (х1)!>
waitForUser
givePlayerCards.1.0.18
goto.10
label.101
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х3)!>
waitForUser
givePlayerCards.3.0.2
goto.10
label.102
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х4)!>
waitForUser
givePlayerCards.4.0.2
goto.10
label.103
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х5)!>
waitForUser
givePlayerCards.5.0.2
goto.10
label.104
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х6)!>
waitForUser
givePlayerCards.6.0.2
goto.10
label.105
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х7)!>
waitForUser
givePlayerCards.7.0.2
goto.10
label.106
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х8)!>
waitForUser
givePlayerCards.8.0.2
goto.10
label.107
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Пригоршня Пыльцы фей} (х9)!>
waitForUser
givePlayerCards.9.0.2
goto.10
label.108
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Очищенный Нектар} (х1)!>
waitForUser
givePlayerCards.1.0.9
goto.10
label.109
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Очищенный Нектар} (х2)!>
waitForUser
givePlayerCards.2.0.9
goto.10
label.110
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Очищенный Нектар} (х3)!>
waitForUser
givePlayerCards.3.0.9
goto.10
label.111
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Лечебный Бальзам} (х3)!>
waitForUser
givePlayerCards.3.0.13
goto.10
label.112
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Лечебный Бальзам} (х4)!>
waitForUser
givePlayerCards.4.0.13
goto.10
label.113
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Лечебный Бальзам} (х5)!>
waitForUser
givePlayerCards.5.0.13
goto.10
label.114
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Лечебный Бальзам} (х6)!>
waitForUser
givePlayerCards.6.0.13
goto.10
label.115
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Лечебный Бальзам} (х7)!>
waitForUser
givePlayerCards.7.0.13
goto.10
label.116
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Эликсир Маны} (х1)!>
waitForUser
givePlayerCards.1.0.90
goto.10
label.117
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Бронзовый Редис} (х3)!>
waitForUser
givePlayerCards.3.0.60
goto.10
label.118
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Бронзовый Редис} (х4)!>
waitForUser
givePlayerCards.4.0.60
goto.10
label.119
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Бронзовый Редис} (х5)!>
waitForUser
givePlayerCards.5.0.60
goto.10
label.120
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Бронзовый Редис} (х6)!>
waitForUser
givePlayerCards.6.0.60
goto.10
label.121
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Бронзовый Редис} (х7)!>
waitForUser
givePlayerCards.7.0.60
goto.10
label.122
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Бронзовый Редис} (х8)!>
waitForUser
givePlayerCards.8.0.60
goto.10
label.123
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Бронзовый Редис} (х9)!>
waitForUser
givePlayerCards.9.0.60
goto.10
label.124
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Серебряный Лук} (х2)!>
waitForUser
givePlayerCards.2.0.7
goto.10
label.125
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Серебряный Лук} (х3)!>
waitForUser
givePlayerCards.3.0.7
goto.10
label.126
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Серебряный Лук} (х4)!>
waitForUser
givePlayerCards.4.0.7
goto.10
label.127
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Золотая Морковь} (х1)!>
waitForUser
givePlayerCards.1.0.3
goto.10
label.7
setTalkLabels.-1.-1.2
talk.<Ты открываешь {4*Магическую Шкатулку}...>
waitForUser
gotoRandomLabel.28.500
label.500
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Хрустальный Шар} (х1)!>
waitForUser
givePlayerCards.1.0.19
goto.10
label.501
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Насыщенный Нектар} (х1)!>
waitForUser
givePlayerCards.1.0.88
goto.10
label.502
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Концентрированный Нектар} (х1)!>
waitForUser
givePlayerCards.1.0.89
goto.10
label.503
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Лечебный Эликсир} (х1)!>
waitForUser
givePlayerCards.1.0.14
goto.10
label.504
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Лечебный Эликсир} (х2)!>
waitForUser
givePlayerCards.2.0.14
goto.10
label.505
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Эликсир Маны} (х1)!>
waitForUser
givePlayerCards.1.0.91
goto.10
label.506
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Эликсир Маны} (х2)!>
waitForUser
givePlayerCards.2.0.92
goto.10
label.507
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Эликсир Маны} (х3)!>
waitForUser
givePlayerCards.3.0.92
goto.10
label.508
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Медовый Эликсир} (х1)!>
waitForUser
givePlayerCards.1.0.75
goto.10
label.509
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Медовый Эликсир} (х2)!>
waitForUser
givePlayerCards.2.0.75
goto.10
label.510
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Медовый Эликсир} (х3)!>
waitForUser
givePlayerCards.3.0.75
goto.10
label.511
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Медовый Эликсир} (х4)!>
waitForUser
givePlayerCards.4.0.75
goto.10
label.512
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Медовый Эликсир} (х5)!>
waitForUser
givePlayerCards.5.0.75
goto.10
label.513
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Медовый Эликсир} (х6)!>
waitForUser
givePlayerCards.6.0.75
goto.10
label.514
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Медовый Эликсир} (х7)!>
waitForUser
givePlayerCards.7.0.75
goto.10
label.515
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Медовый Эликсир} (х8)!>
waitForUser
givePlayerCards.8.0.75
goto.10
label.516
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Медовый Эликсир} (х1)!>
waitForUser
givePlayerCards.1.0.76
goto.10
label.517
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Медовый Эликсир} (х2)!>
waitForUser
givePlayerCards.2.0.76
goto.10
label.518
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Медовый Эликсир} (х3)!>
waitForUser
givePlayerCards.3.0.76
goto.10
label.519
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Медовый Эликсир} (х4)!>
waitForUser
givePlayerCards.4.0.76
goto.10
label.520
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Большой Медовый Эликсир} (х5)!>
waitForUser
givePlayerCards.5.0.76
goto.10
label.521
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Эликсир Стихий} (х1)!>
waitForUser
givePlayerCards.1.0.77
goto.10
label.522
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Эликсир Стихий} (х2)!>
waitForUser
givePlayerCards.2.0.77
goto.10
label.523
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Эликсир Стихий} (х3)!>
waitForUser
givePlayerCards.3.0.77
goto.10
label.524
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Эликсир Стихий} (х4)!>
waitForUser
givePlayerCards.4.0.77
goto.10
label.525
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Эликсир Стихий} (х5)!>
waitForUser
givePlayerCards.5.0.77
goto.10
label.526
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Эликсир Стихий} (х6)!>
waitForUser
givePlayerCards.6.0.77
goto.10
label.527
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Эликсир Стихий} (х7)!>
waitForUser
givePlayerCards.7.0.77
goto.10
label.4
exit"""
InitScript = "setModel.b007s02m"
UpdateScript = "lookAtPlayer.0.1"
