UID = "9A299BA4"
Name = "4963CC91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<О, ты тоже пришла сюда, чтобы поймать себе фею?>.0
waitForUser
label.0
ifPlayerHasCards.-1.2.121
setTalkLabels.-1.-1.0
talk.<
	Спасибо тебе за твою помощь, странница.
	Теперь у меня есть {4*Игуана}!
	Как у меня будет свободное время, я займусь её тренировкой!
	Уверен, что в ней есть некая скрытая сила!
>
waitForUser
exit
else
ifNpcModifierHasValue.1
goto.1
else
goto.2
label.1
setTalkLabels.10.11.1
talk.<
    Ты уже поймала {4*Игуану}?
	Мне не терпится увидеть её вживую!
	Я отдам тебе {4*Уиджи} в обмен на твою фею.
>
waitForUser
label.10
ifPlayerHasCards.1.2.74
removeWizForms
tradeWizform.121
else
setTalkLabels.-1.-1.0
talk.<
	У тебя нет с собой {4*Игуаны}...
	Ты можешь поймать её здесь, - так мне говорил мой друг.
	Но, возможно, это слишком трудная задача для тебя.
	Всё в порядке, я что-нибудь придумаю.
>
waitForUser
exit
label.11
exit
label.2
setTalkLabels.-1.-1.2
talk.<
	Я отправился сюда с моим другом, чтобы поймать редкую {4*фею Пси} - {4*Игуану}!
	Она водится только здесь, в самых далеких топях болота.
	Но я потерял своего друга из виду, когда заметил какую-то необычную фею.
	Это всё из-за того, что я совершенно забыл обо всём, как побежал следом за этой феей...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
	Но, ты знаешь что, теперь мы с феей стали большими друзьями!
	Я назвал его Уиджи.
	Никогда не слышал, что такие феи существуют в {4*Занзаре}, но он может делать "Вж-ж-ж-ж..."!
	Однако я все ещё хочу увидеть {4*Игуану}...
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Похоже, мой друг потерял меня, и решил вернуться обратно в деревню...
	Но я не хочу уходить отсюда, пока не смогу заполучить {4*Игуану}!
	Как насчёт того, чтобы ты поймала её, и тогда я отдам тебе свою фею?
	Он рассказал мне, что отправился в путешествие, потому что ему было очень скучно!
>
waitForUser
setNpcModifier.-1.-1.1
goto.0
label.3
setTalkLabels.-1.-1.2
talk.<
	Спасибо, что спасла моего друга, но я думаю, что пока что останусь здесь.
	Я не хочу снова оказаться бесполезным, если {4*Тёмные Эльфы} появятся снова, и поэтому я хочу немного потренировать своих фей.
	Но мне определённо нужны гораздо более лучшие феи, чем обитающие здесь...
>
waitForUser
goto.0
exit"""
InitScript = """
setModel.e002s02m
defaultWizForm.81.0.13"""
UpdateScript = "lookAtPlayer.0.0"
