UID = "A8B22034"
Name = "0FDF8F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Эм... привет.>.0
waitForUser
label.0
ifPlayerHasCards.1.0.56
goto.10
else
say.<Ты ведь пришла сюда, чтобы сразиться с {4*Генералом Тёмных Эльфов}? Он находится в каменном кругу к северо-западу отсюда...>.1
choice.2.<Диалог>
choice.1.<До встречи>
waitForUser
label.10
say.<Ты действительно смогла победить самого {4*Генерала}? Эм... ты выглядешь намного сильнее, чем кажешься на первый взгляд...>.1
choice.2.<Диалог>
choice.1.<До встречи>
waitForUser
label.2
ifPlayerHasCards.-1.2.121
goto.11
else
setTalkLabels.-1.-1.2
talk.<
	Видишь ли, я и мой друг решили пойти поймать одну из {4*фей Пси} в дальней части болот...
	У нас было не так много времени, чтобы нашу пропажу не заметили, и поэтому мы очень долго ждали этого шанса.
	Но когда мы зашли глубоко в болото, мы оказались отрезаны друг от друга из-за {4*Тёмного Эльфа}!
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
	Силы моих фей достаточно только для того, чтобы сражаться с {4*дикими феями}, у меня никогда не было серьёзной битвы с другими {4*Коллекционерами}.
	Именно поэтому я стою здесь и жду кого-нибудь, кто сможет прогнать {4*Тёмного Эльфа} с восточной стороны этого болота.
	Может, ты сможешь это сделать?
	Моему другу наверняка очень страшно и одиноко одному.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    У меня нет ничего, что я бы мог дать тебе за помощь, но...
	Пожалуйста, помоги ему!
	Это первый раз, когда мы пошли вместе ловить ему фею, и всё пошло совершенно неправильно!
	Я никогда не хотел, чтобы всё закончилось именно так...
>
waitForUser
goto.0
label.11
setTalkLabels.-1.-1.2
talk.<
	Спасибо, что спасла моего друга, но я думаю, что пока что останусь здесь.
	Я не хочу снова оказаться бесполезным, если {4*Тёмные Эльфы} появятся снова, и поэтому я хочу немного потренировать своих фей.
	Но мне определённо нужны гораздо более лучшие феи, чем обитающие здесь...
>
waitForUser
goto.0
exit"""
InitScript = """
setModel.e002s02m
defaultWizForm.81.0.13"""
UpdateScript = "lookAtPlayer.0.0"
