UID = "A5058034"
Name = "0FDF8F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Приветствую, путешественник.>.0
waitForUser
label.0
say.<
    Ты выглядишь как увлечённый {4*Коллекционер фей}...
    Может тебя заинтересует моё предложение?
>.1
choice.3.<Диалог>
choice.2.<Торговля>
choice.1.<До встречи>
waitForUser
label.3
setTalkLabels.-1.-1.2
talk.<
    Я продаю весьма уникальных фей, которых ты не сможешь найти в другом месте - {4*драконов}.
    Они очень сложны для тренировки, и эволюционируют, лишь достигнув момента, когда они перестают получать всякий опыт...
    Но, в отличие от обычных фей, их {4*боевые возможности} намного {4*выше}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Только из-за того, что их очень тяжело разводить, они будут стоить тебе {4*100 кристаллов}...
    или {4*500 монет}.
    Поэтому если ты захочешь собрать их полную коллекцию, тебе придётся потратить целых {4*5000 монет}! И возможно ты будешь первым человеком, кто соберёт их всех! Ох, извини, ты и так первый человек за столь долгое время...
>
waitForUser
goto.0
label.2
say.<
    Ты выглядишь как увлечённый {4*Коллекционер фей}...
    Может тебя заинтересует моё предложение?
>.3
choice.9.<Дракон Огня>
choice.10.<Дракон Природы>
choice.11.<Дракон Света>
choice.12.<Далее>
waitForUser
label.9
ifPlayerHasCards.100.0.6
removePlayerCards.100.0.6
givePlayerCards.1.2.189
exit
else
setTalkLabels.-1.-1.0
talk.<
    У тебя нет {4*100 кристаллов}...
    Я знаю, это достаточно дорого, но ты можешь вернуться в любой момент, когда сможешь накопить их! Хотя большинство не возвращается, но ты не выглядишь как кто-то бедный! Ведь так?
>
waitForUser
exit
label.10
ifPlayerHasCards.100.0.6
removePlayerCards.100.0.6
givePlayerCards.1.2.191
exit
else
setTalkLabels.-1.-1.0
talk.<
    У тебя нет {4*100 кристаллов}...
    Я знаю, это достаточно дорого, но ты можешь вернуться в любой момент, когда сможешь накопить их! Хотя большинство не возвращается, но ты не выглядишь как кто-то бедный! Ведь так?
>
waitForUser
exit
label.11
ifPlayerHasCards.100.0.6
removePlayerCards.100.0.6
givePlayerCards.1.2.193
exit
else
setTalkLabels.-1.-1.0
talk.<
    У тебя нет {4*100 кристаллов}...
    Я знаю, это достаточно дорого, но ты можешь вернуться в любой момент, когда сможешь накопить их! Хотя большинство не возвращается, но ты не выглядишь как кто-то бедный! Ведь так?
>
waitForUser
exit
label.12
say.<
    Ты выглядишь как увлечённый {4*Коллекционер фей}...
    Может тебя заинтересует моё предложение?
>.3
choice.15.<Дракон Тьмы>
choice.14.<Дракон Льда>
choice.13.<Назад>
waitForUser
label.15
ifPlayerHasCards.100.0.6
removePlayerCards.100.0.6
givePlayerCards.1.2.195
exit
else
setTalkLabels.-1.-1.0
talk.<
    У тебя нет {4*100 кристаллов}...
    Я знаю, это достаточно дорого, но ты можешь вернуться в любой момент, когда сможешь накопить их! Хотя большинство не возвращается, но ты не выглядишь как кто-то бедный! Ведь так?
>
waitForUser
exit
label.14
ifPlayerHasCards.100.0.6
removePlayerCards.100.0.6
givePlayerCards.1.2.197
exit
else
setTalkLabels.-1.-1.0
talk.<
    У тебя нет {4*100 кристаллов}...
    Я знаю, это достаточно дорого, но ты можешь вернуться в любой момент, когда сможешь накопить их! Хотя большинство не возвращается, но ты не выглядишь как кто-то бедный! Ведь так?
>
waitForUser
exit
label.13
goto.0
label.1
exit"""
InitScript = """
setModel.b017s00m
defaultWizForm.192.0.0"""
UpdateScript = """
label.0
lookAtPlayer.-1.1
moveSystem.1.1
gotoRandomLabel.2.0
goto.0
label.1
playAnimation.0.90
goto.0"""
