UID = "900FC934"
Name = "389D7EB1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<
    Гном {4*Эйрик} приветствует тебя, чужестранница.
>.0
waitForUser
ifPlayerHasCards.1.0.33
setTalkLabels.-1.-1.0
talk.<
    Я желаю, чтобы тебе в дороге сопутствовала удача, Эми.
>
waitForUser
goto.11
else
setTalkLabels.-1.-1.2
talk.<
	Ты уже знаешь о том, что в нашу {4*Занзару} вторглись {4*Тёмные Эльфы}?
	Не так давно они покинули {4*Царство Тьмы} и заблокировали все дороги, связывающие города между друг другом.
	{4*Монагам}, деревня гномов, оказалась первой, что стала отрезанной от остального мира.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я пришёл в {4*Тиралин} в поисках помощи, но никто не хочет помогать нам, {4*гномам}.
	Кто-то распускает грязные слухи о том, что {4*Квинлин}, один из трёх наших правителей, заключил тайный союз с {4*Тёмными Эльфами}.
	Но, конечно, это всё ложь.
	Он никогда бы не поступил так.
>
waitForUser
setTalkLabels.1.2.1
talk.<
    Итак, я предлагаю тебе сделку, странница.
	Дуэль!
	Если ты победишь меня, то получишь награду, – {4*руну телепортации, которая перенесёт тебя прямо в {4*Монагам}.
	Что скажешь?
	Рискнешь ли своим хрупким телом ради спасения гномьего народа?
>
waitForUser
label.1
setCamera.1006
fight.-1.0
label.2
setTalkLabels.-1.-1.0
talk.<Жаль, я всё ещё жду достойного соперника.>
waitForUser
label.11"""
InitScript = """
ifNpcModifierHasValue.0
setModel.b012s00m
gotoRandomLabel.18.50
label.50
defaultWizForm.4.0.10
goto.68
label.51
defaultWizForm.25.0.10
goto.68
label.52
defaultWizForm.37.0.10
goto.68
label.53
defaultWizForm.48.0.10
goto.68
label.54
defaultWizForm.64.0.10
goto.68
label.55
defaultWizForm.69.0.10
goto.68
label.56
defaultWizForm.4.0.11
goto.68
label.57
defaultWizForm.25.0.11
goto.68
label.58
defaultWizForm.37.0.11
goto.68
label.59
defaultWizForm.48.0.11
goto.68
label.60
defaultWizForm.64.0.11
goto.68
label.61
defaultWizForm.69.0.11
goto.68
label.62
defaultWizForm.4.0.12
goto.68
label.63
defaultWizForm.25.0.12
goto.68
label.64
defaultWizForm.37.0.12
goto.68
label.65
defaultWizForm.48.0.12
goto.68
label.66
defaultWizForm.64.0.12
goto.68
label.67
defaultWizForm.69.0.12
goto.68
label.68
gotoRandomLabel.18.69
label.69
defaultWizForm.4.2.10
goto.87
label.70
defaultWizForm.25.2.10
goto.87
label.71
defaultWizForm.37.2.10
goto.87
label.72
defaultWizForm.48.2.10
goto.87
label.73
defaultWizForm.64.2.10
goto.87
label.74
defaultWizForm.69.2.10
goto.87
label.75
defaultWizForm.4.2.11
goto.87
label.76
defaultWizForm.25.2.11
goto.87
label.77
defaultWizForm.37.2.11
goto.87
label.78
defaultWizForm.48.2.11
goto.87
label.79
defaultWizForm.64.2.11
goto.87
label.80
defaultWizForm.69.2.11
goto.87
label.81
defaultWizForm.4.2.12
goto.87
label.82
defaultWizForm.25.2.12
goto.87
label.83
defaultWizForm.37.2.12
goto.87
label.84
defaultWizForm.48.2.12
goto.87
label.85
defaultWizForm.64.2.12
goto.87
label.86
defaultWizForm.69.2.12
goto.87
label.87
gotoRandomLabel.18.88
label.88
defaultWizForm.4.4.10
goto.106
label.89
defaultWizForm.25.4.10
goto.106
label.90
defaultWizForm.37.4.10
goto.106
label.91
defaultWizForm.48.4.10
goto.106
label.92
defaultWizForm.64.4.10
goto.106
label.93
defaultWizForm.69.4.10
goto.106
label.94
defaultWizForm.4.4.11
goto.106
label.95
defaultWizForm.25.4.11
goto.106
label.96
defaultWizForm.37.4.11
goto.106
label.97
defaultWizForm.48.4.11
goto.106
label.98
defaultWizForm.64.4.11
goto.106
label.99
defaultWizForm.69.4.11
goto.106
label.100
defaultWizForm.4.4.12
goto.106
label.101
defaultWizForm.25.4.12
goto.106
label.102
defaultWizForm.37.4.12
goto.106
label.103
defaultWizForm.48.4.12
goto.106
label.104
defaultWizForm.64.4.12
goto.106
label.105
defaultWizForm.69.4.12
goto.106
label.106
endIf
ifNpcModifierHasValue.1
setModel.b012s00m
defaultWizForm.88.0.8
defaultWizForm.8.1.9
defaultWizForm.4.2.9
defaultWizForm.81.3.7
endIf"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
setCamera.3005
givePlayerCards.1.0.33
givePlayerCards.1.0.107
setTalkLabels.-1.-1.2
talk.<
    Ты выиграла.
	Вот твоя {4*руна Монагама}, - гномы всегда держат своё слово.
	Но будь осторожна, к сожалению ты не сможешь избежать битв с {4*Тёмными Эльфами}.
>
waitForUser
exit"""
VictoriousScript = "killPlayer"
