UID = "D7DF3704"
Name = "BDE38F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.6
goto.1
else
ifNpcModifierHasValue.5
goto.1
else
setTalkLabels.-1.-1.2
talk.<
    Долгое время я коллекционеровал редких фей, которые сейчас практически не встречаются в диком виде.
    Хотя они и не такие сильные, как большинство обычных фей, но я думаю, что, возможно, в них скрыт какой-то неизвестный потенциал...
    о котором ещё никто не знает.
>
waitForUser
setTalkLabels.10.11.1
talk.<
    Ты не хочешь помочь мне в этом?
    Я думаю, только в битвах феи могут показать свои скрытые стороны, и, возможно, тебе тоже не помешало бы узнать что-то большее об этих редких феях?
    Как тебе моя идея?
>
waitForUser
label.10
setCamera.1006
fight.-1.-1
exit
label.11
exit
label.1
say.<Ох, путешественник в таком месте...>.0
waitForUser
say.<
    Это снова ты?
    Если ты хочешь дружеский совет, то не советую пытаться изучить пещеру в другой стороне этого места - там обитают очень {4*опасные феи}...
>.0
waitForUser
exit"""
InitScript = """
ifNpcModifierHasValue.0
setModel.g300s30m
defaultWizForm.71.0.45
defaultWizForm.30.1.40
defaultWizForm.31.2.26
defaultWizForm.30.3.40
defaultWizForm.31.4.15
endIf
ifNpcModifierHasValue.1
setModel.g300s30m
defaultWizForm.123.0.28
defaultWizForm.127.1.27
defaultWizForm.130.2.26
defaultWizForm.125.3.30
defaultWizForm.124.4.29
endIf
ifNpcModifierHasValue.2
setModel.g300s30m
endIf
ifNpcModifierHasValue.3
setModel.g300s30m
endIf
ifNpcModifierHasValue.4
setModel.g300s30m
defaultWizForm.71.0.45
endIf
ifNpcModifierHasValue.5
setModel.g300s30m
defaultWizForm.123.0.28
endIf
ifNpcModifierHasValue.6
setModel.g300s30m
endIf
ifNpcModifierHasValue.7
setModel.g300s30m
endIf
ifNpcModifierHasValue.8
setModel.g300s30m
endIf
ifNpcModifierHasValue.9
setModel.g300s30m
endIf"""
UpdateScript = "lookAtPlayer.0.1"
DefeatedScript = """
ifNpcModifierHasValue.1
setNpcModifier.-1.-1.6
endIf
ifNpcModifierHasValue.0
setNpcModifier.-1.-1.5
endIf
setCamera.1000
setTalkLabels.-1.-1.2
talk.<
    Неплохо, совсем неплохо...
    Как ты видишь, эти феи имеют весьма ограниченные возможности в плане используемых стихий.
    Поэтому я думаю, мне нужно больше времени, чтобы изучить их возможности.
    Надеюсь, мы ещё как-нибудь встретимся.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Кстати, если ты случайно будешь проходить мимо {4*Мэрии Тиралина}, то не могла бы отдать им {4*мой ключ}?
	Я точно не собираюсь возвращаться к этой скучной и неинтересной работе, когда я могу коллекционировать фей!
	Так что забирай его себе, мне он больше не нужен.
>
waitForUser
givePlayerCards.1.0.27
givePlayerCards.1.0.107"""
