UID = "D7DF3704"
Name = "BDE38F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.0
say.<Ох, путешественник в таком месте...>.0
waitForUser
goto.0
else
say.<
    Это снова ты?
    Если ты хочешь дружеский совет, то не советую пытаться изучить пещеру в другой стороне этого места - там обитают очень {4*опасные феи}...
>.0
waitForUser
exit
endIf
label.0
setTalkLabels.-1.-1.2
talk.<
    Долгое время я коллекционеровал редких фей, которые сейчас практически не встречаются в диком виде.
    Хотя они и не такие сильные, как большинство обычных фей, но я думаю, что возможно в них скрыт какой-то неизвестный потенциал...
    о котором ещё никто не знает.
>
waitForUser
setTalkLabels.10.11.1
talk.<
    Ты не хочешь помочь мне в этом?
    Я думаю, только в битвах феи могут раскрыть свои скрытые стороны, и возможно тебе тоже не помешало узнать что-то большее об этих редких феях?
    Как тебе моя идея?
>
waitForUser
label.10
setCamera.1006
fight.-1.-1
exit
label.11
exit"""
InitScript = """
setModel.g300s30m
defaultWizForm.123.0.28
defaultWizForm.127.1.27
defaultWizForm.130.2.26
defaultWizForm.125.3.30
defaultWizForm.124.4.29"""
UpdateScript = "lookAtPlayer.0.1"
DefeatedScript = """
setCamera.1000
setTalkLabels.-1.-1.2
talk.<
    Неплохо, совсем неплохо...
    Как ты видишь, эти феи имеют весьма ограниченные возможности в плане используемых стихий.
    Поэтому я думаю, мне нужно больше времени, чтобы изучить их возможности.
    Надеюсь, мы ещё как-нибудь встретимся.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Кстати, если ты случайно будешь проходить мимо {4*Мэрии Тиралина}, то не могла бы отдать им {4*мой ключ}?
	Я точно не собираюсь возвращаться к этой скучной и неинтересной работе, когда я могу коллекционировать фей!
	Так что забирай его себе, мне он больше не нужен.
>
waitForUser
givePlayerCards.1.0.27
givePlayerCards.1.0.107
setNpcModifier.-1.-1.1"""
