UID = "1D5352B4"
Name = "BDE38F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.6
goto.1
else
ifNpcModifierHasValue.5
goto.1
else
label.0
say.<Что человек делает в лесу?>.0
waitForUser
setTalkLabels.10.11.1
talk.<
    Осторожно, феи в этой части {4*Занзары} очень агрессивны.
    Попробуй победить мою фею и тогда узнаешь, насколько ты опытна, хорошо?
>
waitForUser
label.10
setCamera.1006
fight.-1.0
exit
label.11
exit
label.1
say.<Опять ты...>.0
waitForUser
talk.<Оставь меня, мне хватит.>
waitForUser
exit"""
InitScript = """
ifNpcModifierHasValue.0
setModel.g300s30m
gotoRandomLabel.15.50
label.50
defaultWizForm.0.0.8
goto.65
label.51
defaultWizForm.8.0.8
goto.65
label.52
defaultWizForm.21.0.8
goto.65
label.53
defaultWizForm.50.0.8
goto.65
label.54
defaultWizForm.79.0.8
goto.65
label.55
defaultWizForm.0.0.9
goto.65
label.56
defaultWizForm.8.0.9
goto.65
label.57
defaultWizForm.21.0.9
goto.65
label.58
defaultWizForm.50.0.9
goto.65
label.59
defaultWizForm.79.0.9
goto.65
label.60
defaultWizForm.0.0.10
goto.65
label.61
defaultWizForm.8.0.10
goto.65
label.62
defaultWizForm.21.0.10
goto.65
label.63
defaultWizForm.50.0.10
goto.65
label.64
defaultWizForm.79.0.10
goto.65
label.65
gotoRandomLabel.18.66
label.66
defaultWizForm.4.1.10
goto.84
label.67
defaultWizForm.25.1.10
goto.84
label.68
defaultWizForm.37.1.10
goto.84
label.69
defaultWizForm.48.1.10
goto.84
label.70
defaultWizForm.64.1.10
goto.84
label.71
defaultWizForm.69.1.10
goto.84
label.72
defaultWizForm.4.1.11
goto.84
label.73
defaultWizForm.25.1.11
goto.84
label.74
defaultWizForm.37.1.11
goto.84
label.75
defaultWizForm.48.1.11
goto.84
label.76
defaultWizForm.64.1.11
goto.84
label.77
defaultWizForm.69.1.11
goto.84
label.78
defaultWizForm.4.1.12
goto.84
label.79
defaultWizForm.25.1.12
goto.84
label.80
defaultWizForm.37.1.12
goto.84
label.81
defaultWizForm.48.1.12
goto.84
label.82
defaultWizForm.64.1.12
goto.84
label.83
defaultWizForm.69.1.12
goto.84
label.84
gotoRandomLabel.18.85
label.85
defaultWizForm.4.2.10
goto.103
label.86
defaultWizForm.25.2.10
goto.103
label.87
defaultWizForm.37.2.10
goto.103
label.88
defaultWizForm.48.2.10
goto.103
label.89
defaultWizForm.64.2.10
goto.103
label.90
defaultWizForm.69.2.10
goto.103
label.91
defaultWizForm.4.2.11
goto.103
label.92
defaultWizForm.25.2.11
goto.103
label.93
defaultWizForm.37.2.11
goto.103
label.94
defaultWizForm.48.2.11
goto.103
label.95
defaultWizForm.64.2.11
goto.103
label.96
defaultWizForm.69.2.11
goto.103
label.97
defaultWizForm.4.2.12
goto.103
label.98
defaultWizForm.25.2.12
goto.103
label.99
defaultWizForm.37.2.12
goto.103
label.100
defaultWizForm.48.2.12
goto.103
label.101
defaultWizForm.64.2.12
goto.103
label.102
defaultWizForm.69.2.12
goto.103
label.103
gotoRandomLabel.15.104
label.104
defaultWizForm.0.3.8
goto.119
label.105
defaultWizForm.8.3.8
goto.119
label.106
defaultWizForm.21.3.8
goto.119
label.107
defaultWizForm.50.3.8
goto.119
label.108
defaultWizForm.79.3.8
goto.119
label.109
defaultWizForm.0.3.9
goto.119
label.110
defaultWizForm.8.3.9
goto.119
label.111
defaultWizForm.21.3.9
goto.119
label.112
defaultWizForm.50.3.9
goto.119
label.113
defaultWizForm.79.3.9
goto.119
label.114
defaultWizForm.0.3.10
goto.119
label.115
defaultWizForm.8.3.10
goto.119
label.116
defaultWizForm.21.3.10
goto.119
label.117
defaultWizForm.50.3.10
goto.119
label.118
defaultWizForm.79.3.10
goto.119
label.119
endIf
ifNpcModifierHasValue.1
setModel.g300s30m
defaultWizForm.23.0.13
defaultWizForm.47.1.14
defaultWizForm.73.2.14
defaultWizForm.43.3.15
endIf
ifNpcModifierHasValue.2
setModel.g300s30m
endIf
ifNpcModifierHasValue.3
setModel.g300s30m
endIf
ifNpcModifierHasValue.4
setModel.g300s30m
endIf
ifNpcModifierHasValue.5
setModel.g300s30m
defaultWizForm.0.0.9
endIf
ifNpcModifierHasValue.6
setModel.g300s30m
defaultWizForm.23.0.13
endIf
ifNpcModifierHasValue.7
setModel.g300s30m
endIf
ifNpcModifierHasValue.8
setModel.g300s30m
endIf
ifNpcModifierHasValue.9
setModel.g300s30m
endIf"""
UpdateScript = "lookAtPlayer.0.1"
DefeatedScript = """
ifNpcModifierHasValue.1
setNpcModifier.-1.-1.6
endIf
ifNpcModifierHasValue.0
setNpcModifier.-1.-1.5
endIf
setCamera.1000
setTalkLabels.-1.-1.0
talk.<
    Глазам своим не верю! Человек умудрился победить моих фей! Что дальше будет?!
>
waitForUser
givePlayerCards.1.0.107"""
