UID = "84E22024"
Name = "7B2D8F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Как приятно тебя видеть.>.0
waitForUser
ifNpcModifierHasValue.1
setTalkLabels.-1.-1.0
talk.<
    Ты уже поймала хоть одного {4*Тайнфола?}?
    Ты можешь использовать различные {4*эволюционные камни}, чтобы превратить его в другую форму.
    Правда, эти камни не так просто достать.
>
waitForUser
exit
endIf
setTalkLabels.-1.-1.2
talk.<
    Я давно не видел ни одного Повелителя фей.
    {4*Тёмные Эльфы} всех их выгнали! Поэтому я пришёл в эту пещеру.
    Мои любимые феи и я можем здесь спокойно жить.
>
waitForUser
setTalkLabels.0.1.1
talk.<
    Ох, уж очень здесь скучно.
    У нас давно не было поединков между феями, и мы действительно теряем свои навыки.
    Как насчет небольшого соревнования?
>
waitForUser
label.0
setCamera.1006
fight.-1.1
exit
label.1
exit"""
InitScript = """
setModel.d004s00m
defaultWizForm.147.0.45
defaultWizForm.148.2.43
defaultWizForm.149.4.47"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
setCamera.1000
setNpcModifier.-1.-1.1
setTalkLabels.-1.-1.2
talk.<
    Великолепно, твои феи действительно потрясающие! Ты оценила мою удивительную коллекцию?
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Все они были {4*Тайнфолы}, Феи Природы.
    Но я сумел превратить их в различные существа, используя {4*эволюционые камни}.
    Может, ты сама как-нибудь попробуешь мой метод?
>
waitForUser
givePlayerCards.1.0.107
exit"""
