UID = "84E22024"
Name = "7B2D8F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Как приятно тебя видеть.>.0
waitForUser
ifNpcModifierHasValue.6
goto.1
else
ifNpcModifierHasValue.5
goto.1
else
setTalkLabels.-1.-1.2
talk.<
    Я давно не видел ни одного Повелителя фей.
    {4*Тёмные Эльфы} всех их выгнали! Поэтому я пришёл в эту пещеру.
    Мои любимые феи и я можем здесь спокойно жить.
>
waitForUser
setTalkLabels.0.1.1
talk.<
    Ох, уж очень здесь скучно.
    У нас давно не было поединков между феями, и мы действительно теряем свои навыки.
    Как насчёт небольшого соревнования?
>
waitForUser
label.0
setCamera.1006
fight.-1.1
exit
label.1
exit
label.1
setTalkLabels.-1.-1.0
talk.<
    Ты уже поймала хоть одного {4*Тайнфола}?
    Ты можешь использовать различные {4*эволюционные камни}, чтобы превратить его в другую форму.
    Правда, эти камни не так просто достать.
>
waitForUser
exit"""
InitScript = """
ifNpcModifierHasValue.0
setModel.d004s00m
defaultWizForm.91.0.30
defaultWizForm.147.1.25
defaultWizForm.148.2.34
defaultWizForm.149.3.19
endIf
ifNpcModifierHasValue.1
setModel.d004s00m
defaultWizForm.147.0.15
defaultWizForm.148.2.13
defaultWizForm.149.4.17
endIf
ifNpcModifierHasValue.2
setModel.d004s00m
ifNpcModifierHasValue.3
setModel.d004s00m
ifNpcModifierHasValue.4
setModel.d004s00m
ifNpcModifierHasValue.5
setModel.d004s00m
defaultWizForm.91.0.30
ifNpcModifierHasValue.6
setModel.d004s00m
defaultWizForm.147.0.15
ifNpcModifierHasValue.7
setModel.d004s00m
ifNpcModifierHasValue.8
setModel.d004s00m
ifNpcModifierHasValue.9
setModel.d004s00m"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
ifNpcModifierHasValue.1
setNpcModifier.-1.-1.6
endIf
ifNpcModifierHasValue.0
setNpcModifier.-1.-1.5
endIf
setCamera.1000
setTalkLabels.-1.-1.2
talk.<
    Великолепно, твои феи действительно потрясающие!
	Ты оценила мою удивительную коллекцию?
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Все они были {4*Тайнфолы}, феи Природы.
    Но я сумел превратить их в различных существ, используя {4*эволюционые камни}.
    Может, ты сама как-нибудь попробуешь мой метод?
>
waitForUser
givePlayerCards.2.0.107
exit"""
