UID = "0D317E14"
Name = "8A0B7EB1"
TriggerScript = """
setCamera.1003
playAnimation.13.-1
say.<Рад тебя снова видеть, Эми.>.0
waitForUser
ifNpcModifierHasValue.6
goto.0
else
ifNpcModifierHasValue.5
goto.0
else
setCamera.3003
setTalkLabels.-1.-1.2
talk.<
    Ты уже пробовала {4*ловить новых фей} для своей колоды?
    Без этого ты не сможешь сражаться наравне с другими {4*Коллекционерами}.
    Ты можешь не использовать всех {4*пятерых фей} во время боя, но твои феи всегда должны быть готовы к любым неожиданным битвам.
>
waitForUser
setCamera.1006
setTalkLabels.10.11.1
talk.<
    Только в сражениях с другими {4*Коллекционерами} ты можешь получить бесценный {4*опыт} для своих фей.
    Ты не против {4*тренировочного боя}?
>
waitForUser
label.10
fight.-1.0
label.0
say.<{4*Эндева} может показаться скучным местом, однако многие находят здесь желанное уединение от остального мира.>.3
choice.1.<Диалог>
choice.11.<До встречи>
waitForUser
label.1
say.<
    Возможно, тебе будет интересно узнать больше об истории {4*Занзары}?
>.3
choice.2.<Облачная Арена>
choice.3.<Библиотека Тиралина>
choice.4.<Камеи Коллекционера>
choice.5.<Назад>
waitForUser
label.2
setTalkLabels.-1.-1.2
talk.<
    В старые времена, когда {4*Царство Облаков} ещё не стало заброшенным, каждую сотню лет на {4*Небесной Арене} проходил {4*Турнир}, наградой за который был титул и {4*легендарная карта Света}.
    К сожалению, история об этом оказалась забыта всеми, и сейчас мало кто верит, что такая {4*Карта} существовала.
    Но это предание переходило в моей семье из поколения в поколение.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Мой далекий предок был участником {4*Турнира}, на котором карту видели последний раз.
    Это был первый {4*Турнир} после {4*Великого Раздела}, когда {4*человеческий мир} стал отделён от нашего мира...
    и поэтому он был важен для всех {4*эльфов}, {4*болотных гоблинов} и {4*гномов} как символ единства рас в {4*Занзаре}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    История гласит, что победитель этого {4*Турнира} исчез вскоре после того, как получил {4*Карту Света}.
    К сожалению, история умалчивает о том, какими свойствами обладала {4*легендарная Карта}, ровно как и кем оказался победитель этого {4*Турнира}...
    Всё превратилось в малоизвестный миф, который сейчас мало кто помнит.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    В детстве {4*Сиамус} всегда любил эту легенду и очень расстраивался, когда никто не верил ему.
    За все годы {4*Магические Карты} были утеряны, и поэтому восстановление любой из них принесло бы мгновенную славу их обладателю.
    Но я думаю, что такие предания необходимы, даже если они окажутся не до конца правдивыми.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Множество {4*Коллекционеров} отправляются в путешествия, услышав о подобных преданиях.
    Даже если они не находят то, что они ищут, для них это становится бесценным опытом и важным уроком в жизни.
    Возможно, когда-то найдётся и тот, кто сможет выяснить всю правду об этой истории.
>
waitForUser
goto.1
label.3
setTalkLabels.-1.-1.2
talk.<
    {4*Тиралин} — самый крупный город эльфов в этой области {4*Занзары}, и он известен не только своим {4*магазином зелий}, но и {4*библиотекой}.
    Среди бесчисленных резных книжных шкафов здесь собраны {4*бесценные исторические труды}, {4*сведения о культурной жизни соседних регионов} и множество {4*древних мифов}.
    
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    А {4*Жизнь Тиралина} является самым полным и достоверным из сохранившихся исторических трудов {4*Тиралина}, который содержит огромное количество полезных сведений, касающихся повседневной жизни эльфов, вплоть до мельчайших деталей.
    Но самое главное, что там хранится — это {4*родословные древа всех эльфов}, имеющих связь с {4*Тиралином}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Если ты хочешь получить возможность работать в городе, то тебе нужно подтвердить, что кто-то в твоём роде уже был {4*гражданином Тиралина}.
    Иначе ты потратишь годы на знакомство с эльфийской бюрократией...
    И я надеюсь, что тебе никогда не придётся столкнуться с ней лично.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Последний раз, когда я пытался получить доступ к {4*библиотеке}, мне помешал этот гнусный эльф-секретарь, идиот, который повторял, что у него обеденный перерыв три часа кряду! Если бы в это не вмешалась сама дочь мэра — она прекрасный ангел, поверь мне, — я бы окончательно отчаялся добиться чего-либо.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    К сожалению, без {4*статуса гражданина} я не могу ознакомиться с документами лично, а подача запроса и его рассмотрение может длиться месяцами...
    и без {4*рекомендации} я не смогу устроиться работать в мэрию.
    Теперь ты понимаешь, в каком положении я нахожусь: я всего лишь хочу узнать больше о своей семье и о том, что произошло с другими семьями основателей {4*Тиралина}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я всё ещё надеюсь найти способ решить эту проблему.
    Тем более, {4*Эмили} — так зовут дочь мэра — пытается поддерживать {4*библиотеку} самостоятельно...
    но представь себе, насколько она одиноко себя чувствует, проводя день за днём с книгами.
    Не говоря о том, насколько это огромный труд для такой молодой эльфийки, как она.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Мы знаем очень мало о нашей {4*истории} и {4*происхождении}, и есть вещи, о которых среди эльфов не принято говорить вслух...
    и мне хотелось бы узнать больше о причинах этого.
>
waitForUser
goto.1
label.4
setTalkLabels.-1.-1.2
talk.<
    История {4*Камей Коллекционера} уходит во времена {4*Раскола}, когда {4*Занзара} была объята пламенем ненависти и страха {4*людей} перед магией и её могуществом.
    Все {4*Коллекционеры}, кто был готов выступить с их феями в борьбе с людьми, использовали камеи как знак различия и солидарности перед лицом общей опасности.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Насколько я знаю, подобную идею предложила {4*Тиралинская аристократия}.
    Чтобы подать пример для всех остальных, младшие по роду дети их семейств встали в один ряд вместе с обычными жителями {4*Тиралина} и всей {4*Занзары}.
    Под знаменем {4*Тиралина} они стали теми, кто защищали {4*Белого Друида} и {4*Квинлина}, пока те создавали {4*Стража}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Но ты должна понимать, что это не была просто война фей против людей.
    Ни одна из книг не может тебе рассказать о том, сколько было жертв на самом деле или насколько долго длились события, предшествующие {4*Расколу}.
    Даже сам {4*Квинлин} избегает любых вопросов, связанных с теми событиями.
    Что об этом могут думать остальные?
    Только самое худшее, что они могли услышать.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Это пугает меня больше всего.
    Вместо того, чтобы иметь храбрость взглянуть в глаза своему прошлому и тому, что оно хранит, мы пытаемся спрятаться от него, притворяясь, будто у нас всё в порядке.
    Для нас, {4*эльфов}, нет ничего важнее преемственности наших традиций и семейной истории.
    И что о нас будут думать наши покойные предки, если они узнают, как мы относимся к их наследию?
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    В любом случае, {4*Камеи Коллекционеров} являются важным напоминанием о тех событиях, когда все {4*расы} на время забыли о своих разногласиях.
    Сейчас многие думают о существовании {4*Коллекционеров} как о пережитке прошлого, как о чём-то, что стало причиной всех наших бед.
    Но возможно ты сможешь показать своим примером, насколько глубоко они ошибаются в этом.
>
waitForUser
goto.1
label.5
goto.0
label.11
exit"""
InitScript = """
ifNpcModifierHasValue.0
setModel.g207s23m
movementSpeed.10
gotoRandomLabel.15.50
label.50
defaultWizForm.0.0.4
goto.65
label.51
defaultWizForm.8.0.4
goto.65
label.52
defaultWizForm.21.0.4
goto.65
label.53
defaultWizForm.50.0.4
goto.65
label.54
defaultWizForm.79.0.4
goto.65
label.55
defaultWizForm.0.0.5
goto.65
label.56
defaultWizForm.8.0.5
goto.65
label.57
defaultWizForm.21.0.5
goto.65
label.58
defaultWizForm.50.0.5
goto.65
label.59
defaultWizForm.79.0.5
goto.65
label.60
defaultWizForm.0.0.6
goto.65
label.61
defaultWizForm.8.0.6
goto.65
label.62
defaultWizForm.21.0.6
goto.65
label.63
defaultWizForm.50.0.6
goto.65
label.64
defaultWizForm.79.0.6
goto.65
gotoRandomLabel.15.66
label.66
defaultWizForm.0.2.4
goto.81
label.67
defaultWizForm.8.2.4
goto.81
label.68
defaultWizForm.21.2.4
goto.81
label.69
defaultWizForm.50.2.4
goto.81
label.70
defaultWizForm.79.2.4
goto.81
label.71
defaultWizForm.0.2.5
goto.81
label.72
defaultWizForm.8.2.5
goto.81
label.73
defaultWizForm.21.2.5
goto.81
label.74
defaultWizForm.50.2.5
goto.81
label.75
defaultWizForm.79.2.5
goto.81
label.76
defaultWizForm.0.2.6
goto.81
label.77
defaultWizForm.8.2.6
goto.81
label.78
defaultWizForm.21.2.6
goto.81
label.79
defaultWizForm.50.2.6
goto.81
label.80
defaultWizForm.79.2.6
goto.81
label.81
gotoRandomLabel.15.82
label.82
defaultWizForm.0.4.4
goto.97
label.83
defaultWizForm.8.4.4
goto.97
label.84
defaultWizForm.21.4.4
goto.97
label.85
defaultWizForm.50.4.4
goto.97
label.86
defaultWizForm.79.4.4
goto.97
label.87
defaultWizForm.0.4.5
goto.97
label.88
defaultWizForm.8.4.5
goto.97
label.89
defaultWizForm.21.4.5
goto.97
label.90
defaultWizForm.50.4.5
goto.97
label.91
defaultWizForm.79.4.5
goto.97
label.92
defaultWizForm.0.4.6
goto.97
label.93
defaultWizForm.8.4.6
goto.97
label.94
defaultWizForm.21.4.6
goto.97
label.95
defaultWizForm.50.4.6
goto.97
label.96
defaultWizForm.79.4.6
goto.97
label.97
endIf
ifNpcModifierHasValue.1
setModel.g207s23m
movementSpeed.10
defaultWizForm.21.0.5
defaultWizForm.79.1.6
defaultWizForm.48.2.5
endIf
ifNpcModifierHasValue.2
setModel.g207s23m
movementSpeed.10
endIf
ifNpcModifierHasValue.3
setModel.g207s23m
movementSpeed.10
endIf
ifNpcModifierHasValue.4
setModel.g207s23m
movementSpeed.10
endIf
ifNpcModifierHasValue.5
setModel.g207s23m
movementSpeed.10
defaultWizForm.8.0.4
endIf
ifNpcModifierHasValue.6
setModel.g207s23m
movementSpeed.10
defaultWizForm.21.0.5
endIf
ifNpcModifierHasValue.7
setModel.g207s23m
movementSpeed.10
endIf
ifNpcModifierHasValue.8
setModel.g207s23m
movementSpeed.10
endIf
ifNpcModifierHasValue.9
setModel.g207s23m
movementSpeed.10
endIf"""
UpdateScript = """
label.0
moveSystem.1.2
gotoRandomLabel.3.0
goto.0
label.1
playAnimation.0.-1
lookAtPlayer.90.1
goto.0
label.2
playAnimation.0.-1
lookAtPlayer.20.1
goto.0"""
DefeatedScript = """
ifNpcModifierHasValue.1
setNpcModifier.-1.-1.6
endIf
ifNpcModifierHasValue.0
setNpcModifier.-1.-1.5
endIf
setTalkLabels.-1.-1.2
talk.<
    Это было не так уж и сложно, ведь правда?
    Ты встретишь намного более сильных {4*Коллекционеров}, чем я, выйдя за пределы {4*Эндевы}.
    Чем опытнее {4*Коллекционер}, тем свободнее он используют {4*заклинания других стихий}, и у него чаще встречаются {4*редкие феи}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    {4*Коллекционеры} используют {4*специальные камеи} для того, чтобы оценивать силу друг друга.
    Ты можешь получить их за {4*победу над любым Коллекционером}, и некоторые из них {4*не будут сражаться с тобой}, если у тебя не будет их {4*определённого количества}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    {4*Тёмные Эльфы} также используют {4*камеи}, но они имеют другой цвет.
    Не спрашивай, что тебе делать с ними, можешь считать это боевым трофеем...
    Немногие могут выйти победителями из {4*дуэли фей}, когда встретятся с кем-то из них.
    Не говоря уже о том, чтобы рассказать об этом вовсе.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    В любом случае, вот твоя награда.
    Не забывай {4*тренировать своих фей}, {4*экипировать их подходящими заклинаниями}, а также {4*следить за тем, чтобы здоровье было полным перед битвой}...
    О последнем я постоянно забываю сам, так что не повторяй моих ошибок.
>
waitForUser
givePlayerCards.1.0.107"""
VictoriousScript = "killPlayer"
