UID = "599E9214"
Name = "7066FC91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.2
goto.100
else
ifNpcModifierHasValue.1
label.100
say.<Я всегда рад видеть тебя, Эми.>.0
waitForUser
goto.101
else
ifNpcModifierHasValue.0
say.<Значит, это ты, Эми, человек из Предсказания?>.0
waitForUser
setNpcModifier.-1.-1.1
label.0
say.<Здесь так скучно... Не могу понять, что только Гоблины находят в этом месте.>.1
choice.3.<Диалог>
choice.2.<Дуэль>
choice.1.<До встречи>
waitForUser
label.101
say.<Здесь так скучно... Не могу понять, что только Гоблины находят в этом месте.>.1
choice.3.<Диалог>
choice.1.<До встречи>
waitForUser
label.3
setTalkLabels.-1.-1.2
talk.<
	Я был послан сюда, чтобы наблюдать за {4*Тёмными Эльфами} и их активностью возле {4*Царства Тьмы}.
	Но ты знаешь что?
	Здесь ничего не происходит.
	Я думаю, это была изначально плохая идея, но кто-то должен заниматься этим...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
	Мне все ещё тяжело поверить, как мы всё это время не знали ничего о {4*Тёмных Эльфах} и их коварных планах.
	Я давно знаю слухи о том, что {4*Тёмные Эльфы} способны менять свой облик, но я до последнего не верил в это.
	Сколько времени они скрывались среди нас?
	И что они хотят сделать с нами?
	
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
	И теперь, Павел постоянно говорит о том, что {4*Тёмные Эльфы} хотят повторить события {4*Чёрного Солнца}...
	Что за шутка!
	Это просто забытая сказка из прошлого, в которую уже никто не верит.
	Мы должны искать помощи у фей.
	Они всегда помогали нам, когда мы больше всего в них нуждались.
>
waitForUser
ifNpcModifierHasValue.2
goto.101
else
ifNpcModifierHasValue.1
goto.0
label.2
setTalkLabels.10.11.1
talk.<Ты хочешь вызвать меня на дуэль? Почему бы и нет. Ты определённо сильный {4*Коллекционер}, раз уж смогла добраться сюда. Просто скажи, как будешь готова.>
waitForUser
label.10
setCamera.1006
fight.-1.0
exit
label.11
goto.0
label.1
exit"""
InitScript = """
setModel.g301s31m
defaultWizForm.47.0.26
defaultWizForm.70.1.27
defaultWizForm.41.2.29
defaultWizForm.39.3.28
defaultWizForm.12.4.27"""
UpdateScript = "lookAtPlayer.0.1"
DefeatedScript = """
setCamera.1000
setNpcModifier.-1.-1.2
setTalkLabels.-1.-1.0
talk.<
    Это была отличная битва.
	Если ты будешь достаточно сильна, то ты сможешь изгнать {4*Тёмных Эльфов} туда, откуда они пришли!
	Только будь осторожней, ладно?
>
waitForUser
givePlayerCards.1.0.107"""
