UID = "B8FAD994"
Name = "6E781E01"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Итак, ты смогла добраться сюда.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    В своих путешествиях по Занзаре ты встретишь не только {4*диких фей}, но и {4*Коллекционеров фей}.
    В отличие от диких фей, которые редко нападают группами, при битве с {4*Коллекционером }тебе придётся сражаться с большим количеством фей.
    Ты готова показать своё мастерство владения феями?
>
waitForUser
setCamera.1006
fight.223.0"""
InitScript = """
setModel.g202s22m
wizform.0.62.0
wizform.2.35.0
wizform.4.73.0"""
UpdateScript = """
label.0
ifPlayerIsClose.11
startPrelude
else
lookAtPlayer.5.1
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
setTalkLabels.-1.-1.2
talk.<
    В битвах с {4*Коллекционерами} важно знать об {4*эффективностях} твоих фей.
    Например, {4*Природа} наносит увеличенный урон {4*Пси} и {4*Хаосу}, но также уязвима перед {4*Огнём}.
    Помни об этом каждый раз, как тебе придётся сражаться с кем-то из {4*Коллекционеров}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Иногда ты можешь оказаться пойманной в нежелательной битве с {4*дикой феей} — используй {4*Чесночный Распылитель}, чтобы отпугнуть её.
    Таким образом ты можешь исследовать самые опасные уголки {4*Занзары}, не боясь потерять всех своих фей.
    Но помни, что таким образом феи лишаются драгоценного для них опыта.
>
waitForUser
givePlayerCards.3.0.20
setCamera.3000
changeWaypoint.-1.100
removeNpc
setCamera.1006"""
