UID = "BD67EC84"
Name = "31CC2EC8"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.0
goto.1
endIf
say.<Ты всё ещё здесь?>.0
waitForUser
talk.<
    Как только я найду новых фей, я снова вызову тебя на бой, ты меня слышишь?! 
	И тогда я ни за что не проиграю тебе снова!>
waitForUser
exit
label.1
say.<Что человек делает в лесу?>.0
waitForUser
setTalkLabels.10.11.1
talk.<
    Человек? 
	Что ты забыла в {4*Занзаре} и каким образом ты сюда попала?
    Ничего, сейчас я тебе покажу, на что способна сила моих фей!
>
waitForUser
label.10
setCamera.1006
fight.-1.0
exit
label.11
exit"""
InitScript = """
setModel.g300s30m
defaultWizForm.89.0.19
defaultWizForm.54.1.17
defaultWizForm.28.2.17
defaultWizForm.5.3.19
defaultWizForm.19.4.18"""
UpdateScript = "lookAtPlayer.0.1"
DefeatedScript = """
setCamera.1000
setNpcModifier.-1.-1.1
setTalkLabels.-1.-1.0
talk.<
    Что? Как ты смогла меня победить?
	Ты сражалась нечестно! 
	Люди ничем не лучше {4*Тёмных Эльфов}, такие же трусливые и лживые!
	Забирай свою награду и убирайся с глаз моих!
>
waitForUser
givePlayerCards.2.0.107"""
VictoriousScript = "killPlayer"
