UID = "8C136A14"
Name = "10E82091"
TriggerScript = """
setCamera.3000
playAnimation.13.-1
ifNpcModifierHasValue.1
say.<О, опять ты!>.0
waitForUser
setTalkLabels.10.11.1
talk.<Ты хочешь сейчас сразиться с моими феями?>
waitForUser
exit
endIf
setNpcModifier.-1.-1.1
say.<
    Что?
    Люди в Занзаре?
    Это зло когда-нибудь закончится?
>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Вся земля идет прахом!
	Все дороги к нашему любимому дому, {4*Монагаму}, заполонили {4*Тёмные Эльфы}.
    {4*Квинлин} исчез, а теперь ещё в {4*Занзару} снова вернулись люди!
>
waitForUser
talk.<Один из них даже пытался попасть в нашу башню, потому что здесь я с братьями храню {4*Карту Магии Огня}.>
waitForUser
talk.<
	Используя {4*Карту Огня} ты сможешь спуститься в {4*Лавовые Пещеры}, где обитают редкие {4*феи Огня}.
	Но тебе всё ещё нужно найти подходящие {4*Элементальные Ключи} для запуска лифта.
>
waitForUser
setTalkLabels.10.11.1
talk.<
    Но с тех пор, как мы охраняем башню, ты должна победить каждого из нас в {4*поединке фей}, чтобы получить карту.
    Не хочешь попробовать?
>
waitForUser
exit
label.10
setCamera.1006
fight.-1.0
label.11
setTalkLabels.-1.-1.0
talk.<Хвала Друидам, а ведь я далеко не самый сильный {4*Повелитель фей}.>
waitForUser
exit"""
InitScript = """
ifNpcModifierHasValue.0
setModel.b009s00m
defaultWizForm.28.0.25
defaultWizForm.28.1.21
defaultWizForm.29.2.28
endIf
ifNpcModifierHasValue.1
setModel.b009s00m
defaultWizForm.103.0.48
defaultWizForm.77.1.49
defaultWizForm.114.2.48
defaultWizForm.138.3.46
defaultWizForm.11.4.47
endIf"""
UpdateScript = "lookAtPlayer.0.1"
DefeatedScript = """
setTalkLabels.-1.-1.0
setCamera.3000
talk.<
    Ладно, ты меня победила.
    Хм, но ты никогда не победишь моих трёх братьев.
    Иди за мной в комнату, если хочешь.
    Я достаточно много могу рассказать.
>
waitForUser
givePlayerCards.1.0.107
changeWaypoint.-1.0
changeWaypoint.0.1
removeNpc"""
VictoriousScript = "killPlayer"
