UID = "7982B534"
Name = "CE6DE2A1"
TriggerScript = """
deployNpcAtTrigger.51.1
setCamera.3004
changeWaypoint.1.2
changeWaypoint.2.3
playAnimation.12.-1
say.<
    Как это возможно?
    Как {4*человек} смог попасть в {4*Занзару}?
>.0
waitForUser
setTalkLabels.1.2.1
talk.<
    Ты пришла сюда, чтобы помочь {4*Тёмным Эльфам} разрушить наш мир?
    Я знаю вас, {4*людей}, в прошлом вы принесли только горе и разрушение! 
	Если ты не сможешь победить в этой дуэли, то немедленно вернись в своей {4*человеческий мир} и никогда оттуда не возвращайся!
>
waitForUser
label.1
setCamera.1006
fight.-1.0
label.2
setTalkLabels.-1.-1.0
talk.<Ты не сможешь победить меня!>
waitForUser
changeWaypoint.3.2
playAnimation.0.-1
exit"""
InitScript = """
ifNpcModifierHasValue.0
setModel.g004s03m
gotoRandomLabel.18.50
label.50
defaultWizForm.2.0.7
goto.68
label.51
defaultWizForm.6.0.7
goto.68
label.52
defaultWizForm.18.0.7
goto.68
label.53
defaultWizForm.40.0.7
goto.68
label.54
defaultWizForm.81.0.7
goto.68
label.55
defaultWizForm.88.0.7
goto.68
label.56
defaultWizForm.2.0.8
goto.68
label.57
defaultWizForm.6.0.8
goto.68
label.58
defaultWizForm.18.0.8
goto.68
label.59
defaultWizForm.40.0.8
goto.68
label.60
defaultWizForm.81.0.8
goto.68
label.61
defaultWizForm.88.0.8
goto.68
label.62
defaultWizForm.2.0.9
goto.68
label.63
defaultWizForm.6.0.9
goto.68
label.64
defaultWizForm.18.0.9
goto.68
label.65
defaultWizForm.40.0.9
goto.68
label.66
defaultWizForm.81.0.9
goto.68
label.67
defaultWizForm.88.0.9
goto.68
label.68
gotoRandomLabel.18.69
label.69
defaultWizForm.2.2.7
goto.87
label.70
defaultWizForm.6.2.7
goto.87
label.71
defaultWizForm.18.2.7
goto.87
label.72
defaultWizForm.40.2.7
goto.87
label.73
defaultWizForm.81.2.7
goto.87
label.74
defaultWizForm.88.2.7
goto.87
label.75
defaultWizForm.2.2.8
goto.87
label.76
defaultWizForm.6.2.8
goto.87
label.77
defaultWizForm.18.2.8
goto.87
label.78
defaultWizForm.40.2.8
goto.87
label.79
defaultWizForm.81.2.8
goto.87
label.80
defaultWizForm.88.2.8
goto.87
label.81
defaultWizForm.2.2.9
goto.87
label.82
defaultWizForm.6.2.9
goto.87
label.83
defaultWizForm.18.2.9
goto.87
label.84
defaultWizForm.40.2.9
goto.87
label.85
defaultWizForm.81.2.9
goto.87
label.86
defaultWizForm.88.2.9
goto.87
label.87
gotoRandomLabel.18.88
label.88
defaultWizForm.2.4.7
goto.106
label.89
defaultWizForm.6.4.7
goto.106
label.90
defaultWizForm.18.4.7
goto.106
label.91
defaultWizForm.40.4.7
goto.106
label.92
defaultWizForm.81.4.7
goto.106
label.93
defaultWizForm.88.4.7
goto.106
label.94
defaultWizForm.2.4.8
goto.106
label.95
defaultWizForm.6.4.8
goto.106
label.96
defaultWizForm.18.4.8
goto.106
label.97
defaultWizForm.40.4.8
goto.106
label.98
defaultWizForm.81.4.8
goto.106
label.99
defaultWizForm.88.4.8
goto.106
label.100
defaultWizForm.2.4.9
goto.106
label.101
defaultWizForm.6.4.9
goto.106
label.102
defaultWizForm.18.4.9
goto.106
label.103
defaultWizForm.40.4.9
goto.106
label.104
defaultWizForm.81.4.9
goto.106
label.105
defaultWizForm.88.4.9
goto.106
label.106
endIf
ifNpcModifierHasValue.1
setModel.g004s03m
defaultWizForm.50.0.8
defaultWizForm.25.2.10
defaultWizForm.40.4.7
endIf"""
UpdateScript = """
label.0
idle
ifTriggerIsActive.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
setTalkLabels.-1.-1.0
talk.<
    Это невозможно.
    Ты хочешь снова забрать у нас то, что когда-то вернул нам {4*Белый Друид}?
    Надеюсь, тебе не хватит наглости появиться в {4*Данморе}...
    Если {4*Белый Друид} узнает, что человек снова вступил в этот мир, он определённо изгонит тебя туда, откуда ты пришла!
>
waitForUser
givePlayerCards.1.0.107
changeWaypoint.3.4
removeNpc"""
VictoriousScript = "killPlayer"
