UID = "7982B534"
Name = "CE6DE2A1"
TriggerScript = """
deployNpcAtTrigger.51.1
setCamera.3004
changeWaypoint.1.2
changeWaypoint.2.3
playAnimation.12.-1
say.<
    Как это возможно?
    Как {4*человек} смог попасть в {4*Занзару}?
>.0
waitForUser
setTalkLabels.1.2.1
talk.<
    Ты пришла сюда, чтобы помочь {4*Тёмным Эльфам} разрушить наш мир?
    Я знаю вас, {4*людей}, в прошлом вы принесли только горе и разрушение! 
	Если ты не сможешь победить в этой дуэли, то немедленно вернись в своей {4*человеческий мир} и никогда оттуда не возвращайся!
>
waitForUser
label.1
setCamera.1006
fight.-1.0
label.2
setTalkLabels.-1.-1.0
talk.<Ты не сможешь победить меня!>
waitForUser
changeWaypoint.3.2
playAnimation.0.-1
exit"""
InitScript = """
ifNpcModifierHasValue.0
setModel.g004s03m
gotoRandomLabel.6.50
label.50
defaultWizForm.2.0.8
goto.56
label.51
defaultWizForm.6.0.8
goto.56
label.52
defaultWizForm.18.0.8
goto.56
label.53
defaultWizForm.40.0.8
goto.56
label.54
defaultWizForm.81.0.8
goto.56
label.55
defaultWizForm.88.2.8
goto.56
label.56
gotoRandomLabel.6.57
label.57
defaultWizForm.2.2.10
goto.63
label.58
defaultWizForm.6.2.10
goto.63
label.59
defaultWizForm.18.2.10
goto.63
label.60
defaultWizForm.40.2.10
goto.63
label.61
defaultWizForm.81.2.10
goto.63
label.61
defaultWizForm.88.2.10
goto.63
label.63
gotoRandomLabel.6.64
label.64
defaultWizForm.2.4.7
goto.70
label.65
defaultWizForm.6.4.7
goto.70
label.66
defaultWizForm.18.4.7
goto.70
label.67
defaultWizForm.40.4.7
goto.70
label.68
defaultWizForm.81.4.7
goto.70
label.69
defaultWizForm.88.4.7
goto.70
label.70
endIf
ifNpcModifierHasValue.1
setModel.g004s03m
defaultWizForm.50.0.8
defaultWizForm.25.2.10
defaultWizForm.40.4.7
endIf"""
UpdateScript = """
label.0
idle
ifTriggerIsActive.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
setTalkLabels.-1.-1.0
talk.<
    Это невозможно.
    Ты хочешь снова забрать у нас то, что когда-то вернул нам {4*Белый Друид}?
    Надеюсь, тебе не хватит наглости появиться в {4*Данморе}...
    Если {4*Белый Друид} узнает, что человек снова вступил в этот мир, он определённо изгонит тебя туда, откуда ты пришла!
>
waitForUser
givePlayerCards.1.0.107
changeWaypoint.3.4
removeNpc"""
VictoriousScript = "killPlayer"
