UID = "CDE4C534"
Name = "8959CAB1"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<
    Ох, человек?
    Я не видел ваш вид уже множество лет...
>.0
waitForUser
label.0
say.<
    Я могу помочь тебе с тренировкой твоих фей.
    Хотя мои феи не такие сильные, как у большинства Коллекционеров.
>.3
choice.3.<Диалог>
choice.2.<Тренировка>
choice.1.<До встречи>
waitForUser
label.1
exit
label.2
fight.-1.0
label.3
say.<
    Тебе тоже интересно, каким образом мои феи не нуждаются в лечении?
    Это интересная история.
>.3
choice.7.<Путешествие в Тиралин>
choice.6.<Мистическая Призма>
choice.5.<Тёмный Союз>
choice.4.<Назад>
waitForUser
label.7
setTalkLabels.-1.-1.2
talk.<
    Когда {4*Тёмные Эльфы} вышли на поверхность, все мы были очень встревожены этими событиями.
    Долгое время их никто не видел дальше их собственного {4*Царства Тьмы}, и никто не ожидал, что всё это время они упорно тренировали своих фей, чтобы использовать их против нас! Поэтому я был одним из первых, кто решил бросить им вызов.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я путешествовал по миру и сражался с каждым {4*Тёмным Эльфом}, которого я встречал на пути.
    Но, к сожалению, со временем это становилось всё труднее - {4*Терновые Кусты} и {4*Огромные Булыжники} заблокировали практически все пути сообщения между городами.
    К тому же, видя меня, многие {4*Тёмные Эльфы} спешили сбежать ещё до того, как я мог им преподать урок...
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Когда {4*Тёмные Эльфы} заблокировали горный тракт, ведущий к {4*Монагаму}, мы лишились последних связей с внешним миром.
    Это произошло практически сразу, как {4*Тёмные Эльфы} осадили {4*Данмор}.
    И я решил остаться здесь, чтобы следить за тем, чтобы {4*Тёмные Эльфы} не добрались до {4*Тиралина}.
>
waitForUser
goto.0
label.6
setTalkLabels.-1.-1.2
talk.<
    В одном из сражений с {4*Тёмным Эльфом} я получил очень странную вещь: призму, внутри которой, словно на звёздном небе, можно увидеть различных фей.
    Я долго изучал эту вещь, пока не сделал поразительное открытие: оно призывает иллюзии фей, которые ничем не отличимы от реальных! И именно так {4*Тёмные Эльфы} могли тренировать своих фей, не прибегая к сражениям с дикими феями...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Но, к сожалению, это штуковина была уже достаточно повреждённой после многократного использования, и поэтому эти феи настолько слабые.
    К тому же, оно может делать иллюзии немногих фей, хотя они все различаются по своим стихиям.
    Я все ещё не уверен, замешана ли здесь магия, и я даже не могу представить, кто смог бы изобрести нечто настолько уникальное!
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Но если тебе интересно, то ты можешь найти моих друзей в {4*Данморе} и {4*Монагаме}.
    У них также есть {4*призмы}, и они в гораздо лучшем состоянии, нежели моя.
    Я думаю, они не будут против помочь тебе в тренировке твоих фей, и возможно, вместе вы сможете узнать что-то больше об этом?
    Я буду рад узнать, каким образом {4*Тёмным Эльфам} удалось создать что-то подобное.
>
waitForUser
goto.0
label.5
setTalkLabels.-1.-1.2
talk.<
    Вход в {4*Царство Тьмы} расположен глубоко в {4*болотах Данмора}, но изначально эти ворота были запечатаны.
    Я не знаю, какая злая магия в этом замешана, но каким-то образом {4*Тёмные Эльфы} смогли прорваться сквозь них и вторгнулись в наш мир.
    Уверен, всему виной их эксперименты с магией, и во всех бедах, случившившихся с {4*Занзарой}, виноваты именно они!
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Мне сложно поверить, что {4*Тёмные Эльфы} смогли накопить столько сил без чужой помощи.
    И {4*эльфы} обвиняют нас, {4*гномов}, в помощи этим созданиям, потому что мы живём в {4*Тёмных Пещерах}...
    Что за абсурд! Если бы не {4*мастер Квинлин}, то {4*Страж} никогда бы не защитил нас от {4*человеческого мира}, и {4*эльфы} были бы непременно первыми, на кого бы охотились {4*люди}!
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Уверен, это именно {4*эльфы} в сговоре со своими тёмными собратьями, а всё для того, чтобы они не напали на {4*Тиралин}! Ты не думаешь, что это очень странно, что только здесь мы в безопасности, когда {4*Данмор} и {4*Монагам} полностью отрезаны от остального мира?
    Возможно, скоро настанет и наша очередь...
    и тогда я покажу этим {4*Тёмным Эльфам}, что им не стоило выходить на солнечный свет!
>
waitForUser
goto.0
label.4
goto.0"""
InitScript = """
setModel.b020s00m
defaultDeck.2.20.1"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
setTalkLabels.-1.-1.0
talk.<
    Неплохо.
    Возвращайся ко мне, если твои феи все ещё будут нуждаться в новых тренировках.
>
waitForUser
gotoRandomLabel.20.50
label.50
givePlayerCards.3.0.0
goto.70
label.51
givePlayerCards.3.0.0
goto.70
label.52
givePlayerCards.3.0.0
goto.70
label.53
givePlayerCards.3.0.0
goto.70
label.54
givePlayerCards.3.0.0
goto.70
label.55
givePlayerCards.3.0.0
goto.70
label.56
givePlayerCards.3.0.0
goto.70
label.57
givePlayerCards.3.0.0
goto.70
label.58
givePlayerCards.3.0.0
goto.70
label.59
givePlayerCards.3.0.0
goto.70
label.60
givePlayerCards.2.0.1
goto.70
label.61
givePlayerCards.2.0.1
goto.70
label.62
givePlayerCards.2.0.1
goto.70
label.63
givePlayerCards.2.0.1
goto.70
label.64
givePlayerCards.2.0.1
goto.70
label.65
givePlayerCards.2.0.1
goto.70
label.66
givePlayerCards.2.0.1
goto.70
label.67
givePlayerCards.1.0.2
goto.70
label.68
givePlayerCards.1.0.2
goto.70
label.69
givePlayerCards.1.0.2
goto.70
label.70"""
VictoriousScript =  """
setTalkLabels.-1.-1.0
talk.<
    Ты потеряла всех своих фей?
    Всё в порядке, парочка трав и несколько зелий приведут их обратно в порядок.
	Ты можешь попытаться сразиться со мной снова позже, если захочешь.
>
waitForUser"""
