UID = "CDE4C594"
Name = "6D58FDB1"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Добро пожаловать.>.0
waitForUser
label.0
say.<
    Если ты пришла ради тренировки своих фей, то тебе лучше быть готовой к вызову.
    С этими феями что-то не так...
>.3
choice.4.<Диалог>
choice.3.<Тренировка>
choice.2.<Торговля>
choice.1.<До встречи>
waitForUser
label.2
tradingCurrency.C564B4A3
tradingItem.10.21F89313
tradingItem.10.140F9713
tradingItem.15.A9C69713
tradingItem.25.761F9713
tradingItem.25.64979713
waitForUser
goto.0
label.3
fight.-1.0
label.4
say.<
    Тебе тоже нравится, как уютно выглядит мой дом?
	Мне нравится жить в комфорте.
>.3
choice.8.<Забытые Дороги>
choice.7.<Нравы Гоблинов>
choice.6.<Мистическая Призма>
choice.5.<Назад>
waitForUser
label.8
setTalkLabels.-1.-1.2
talk.<
    Если ты думаешь, что ты первая, кто заметил, что мои карты не до конца точные — нет, ты не была первой! 
	Они были нарисованы ещё кем-то во времена {4*Раскола}, и я не знаю, кто именно их нарисовал. 
	Однако если ты хочешь мой совет, то никогда не сходи с дороги и всегда иди направо или налево — и тебе не понадобится никакая карта.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Конечно, эти земли далеко не являются всеми землями {4*Занзары} — и в ней ещё много удивительных мест, о которых ты можешь узнать из чужих рассказов или книг. 
	Когда-то руны были у каждого, и они использовались для лёгкого перемещения по всем этим таинственным местам. 
	Но после {4*Раскола} многие из нас обнаружили, что большинство рун перестало работать — вероятно, закрытие порталов в человеческий мир всё-таки было не лучшей идеей…
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Но если {4*Предсказание} действительно является правдой, и ты пришла уничтожить {4*Стража}, тогда всё может измениться. 
	Хотя я уже слишком ленив для далеких путешествий, такой {4*Коллекционер фей} как ты всегда имеет возможность открыть для себя новые дороги. 
	Или, быть может, Гоблины найдут некоторые из малоизвестных порталов, ведущие на другие территории и места... кто знает.
>
waitForUser
goto.4
label.7
setTalkLabels.-1.-1.2
talk.<
    {4*Болотные Гоблины} сильно отличаются от других рас {4*Занзары}, — мы не любим использовать {4*золото} и {4*кристаллы} для торговли, предпочитая обмен.
	Также {4*гоблины} считают, что нельзя иметь слишком много вещей: чем у тебя их больше, тем сложнее будет покинуть этот мир, когда наступит твоё время.
	Но это просто пережитки прошлого, — они были выдуманы для того, чтобы все {4*гоблины} считали себя равными друг другу и не забывали помогать в трудную минуту.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Многие {4*гоблины} теперь живут в {4*Тиралине} или даже отправились в далекие путешествия, чтобы найти свой дом в другом месте.
	{4*Эльфы} не особенно жалуют нас: им не нравится, что мы не делаем различий между расами, и доверяем только собственным суждениям о других.
	Но {4*Тиралин} — единственный город в этой части {4*Занзары}, и поэтому многие стремятся туда, пускай он таит в себе много опасностей.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    К тому же, мы самые лучшие рассказчики историй, и зачастую мы путешествуем только для того, чтобы найти какую-нибудь новенькую байку.
	Но сколько бы мы не путешествовали, мы всегда помним о своём доме: И поэтому всегда возвращаемся туда, где находится наше место рождения.
	Иногда я хочу увидеть море, как и многие из нас, но всё, что у нас есть, это квакующие лягушки и булькающее болото...
>
waitForUser
goto.4
label.6
setTalkLabels.-1.-1.2
talk.<
    Ты можешь поверить в это?
	Я получил эту [4*призму} от одного из {4*Тёмных Эльфов}, в знак нашей дружбы.
	Именно благодаря ей я смог получить всё, то, что сейчас есть у меня, а именно: прекрасную мягкую кровать заместо травяной циновки!
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Меня не волнует, что думают об этом остальные, — эти двуличные {4*эльфы} ненавидят всех, кто не думает так же, как они!
	И {4*гоблины} ничем не лучше них: они все завидуют тем, кто имеет больше золота, чем в их собственных карманах!
	Но {4*Тёмные Эльфы} и {4*гномы} другие.
	Тебе не стоит доверять скверным слухам, которые распространяют о них в {4*Тиралине}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я слышал, что у кого-то есть совершенно невредимая {4*призма}...
	К сожалению, её магия постепенно угасает, поэтому эти феи уже не такие сильные, как были раньше.
    Я бы очень хотел найти способ восстановить её обратно.
	Не хотелось бы лишаться той вещи, которая сделала меня настолько счастливым.
>
waitForUser
goto.4
label.5
goto.0
label.1
exit"""
InitScript = """
setModel.g001s01m
gotoRandomLabel.10.12
label.10
defaultDeck.2.40.1
spell.0.2.0
spell.1.2.0
spell.2.2.0
spell.3.2.0
spell.4.2.0
goto.22
label.11
defaultDeck.2.40.1
spell.0.2.5
spell.1.2.5
spell.2.2.5
spell.3.2.5
spell.4.2.5
goto.22
label.12
defaultDeck.2.40.1
spell.0.2.10
spell.1.2.10
spell.2.2.10
spell.3.2.10
spell.4.2.10
goto.22
label.13
defaultDeck.2.40.1
spell.0.2.15
spell.1.2.15
spell.2.2.15
spell.3.2.15
spell.4.2.15
goto.22
label.14
defaultDeck.2.40.1
spell.0.2.20
spell.1.2.20
spell.2.2.20
spell.3.2.20
spell.4.2.20
goto.22
label.15
defaultDeck.2.40.1
spell.0.2.25
spell.1.2.25
spell.2.2.25
spell.3.2.25
spell.4.2.25
goto.22
label.16
defaultDeck.2.40.1
spell.0.2.30
spell.1.2.30
spell.2.2.30
spell.3.2.30
spell.4.2.30
goto.22
label.17
defaultDeck.2.40.1
spell.0.2.35
spell.1.2.35
spell.2.2.35
spell.3.2.35
spell.4.2.35
goto.22
label.18
defaultDeck.2.40.1
spell.0.2.40
spell.1.2.40
spell.2.2.40
spell.3.2.40
spell.4.2.40
goto.22
label.19
defaultDeck.2.40.1
spell.0.2.45
spell.1.2.45
spell.2.2.45
spell.3.2.45
spell.4.2.45
goto.22
label.20
defaultDeck.2.40.1
spell.0.2.50
spell.1.2.50
spell.2.2.50
spell.3.2.50
spell.4.2.50
goto.22
label.21
defaultDeck.2.40.1
spell.0.2.55
spell.1.2.55
spell.2.2.55
spell.3.2.55
spell.4.2.55
goto.22
label.22"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
setTalkLabels.-1.-1.0
talk.<
    Неплохо.
    Возвращайся ко мне, если твои феи все ещё будут нуждаться в новых тренировках.
>
waitForUser
givePlayerCards.1.0.162"""
