UID = "71063924"
Name = "B18BDDB1"
TriggerScript = """
ifNpcModifierHasValue.1
say.<К сожалению, этот ящик пуст!>.0
waitForUser
exit
endIf
say.<Открыть шкатулку?>.1
choice.0.<Да>
choice.1.<Нет>
waitForUser
label.0
setCamera.1007
playAnimation.14.0
playSound.1
createDynamicModel.0.-1.-1
givePlayerCards.1.0.62
setNpcModifier.-1.-1.1
delay.10
setCamera.1006
label.1"""
InitScript = """
setNpcType.4
setCollision.0
setModel.i003si03
ifNpcModifierHasValue.1
playAnimation.14.0
endIf"""
