UID = "55373434"
Name = "9F4416B1"
TriggerScript = """
setCamera.3001
deployNpcAtTrigger.99.1
delay.15
changeWaypoint.2.1
playSound.4
say.<
    ...
    эээ...
    кажется, вон один из них!
>.1
playAmyVoice.trg01d
playPlayerAnimation.34.-1
delay.15
setCamera.2000
changeWaypoint.1.3
setCamera.3003
playAnimation.13.-1
say.<Во имя Святого Друида!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<Наконец!>
waitForUser
talk.<
    Моя миссия выполнена.
    Я почти перестал надеяться.
    Люди такие недалекие во всем, что касается магии.
    Ты {4*единственная}, кто может использовать руну.
>
waitForUser
setCamera.3004
talk.<
    Я наблюдаю за вами, человекообразными, целую вечность, ожидая героиню из предсказания.
    Только она может пройти через древний портал.
>
waitForUser
talk.<
    Так написано.
    И теперь ты здесь.
    Я действительно это сделал - Я, Гоблин Рафи, {4*гений}!
>
waitForUser
talk.<
    Когда-то в Занзаре был настоящий мир – мир между гоблинами великого болота, эльфами в лесах и гномами в их горных пещерах.
    {4*Белый Друид}, наш страж, следил за этим.
>
waitForUser
talk.<
    Но теперь беды приходят одна за другой.
    {4*Феи} когда-то были опорой магии в Занзара.
    Но теперь они одичали, и вместо помощи нападают на нас.
>
waitForUser
talk.<
    Наши дороги завалены {4*огромными валунами} или заросли {4*терновыми кустами}.
    Жизнь стала тяжелой.
    И дела все ухудшаются! 
>
waitForUser
setTalkLabels.10.11.1
talk.<
    {4*Тёмные Эльфы} покинули свои тёмные дома и сеют хаос в Занзаре, никто не может противостоять им без помощи фей.
    Но теперь ты здесь, и у нас есть еще одна надежда! Ты поможешь нам, не так ли?
>
waitForUser
label.10
setTalkLabels.-1.-1.2
talk.<
    Конечно, так было написано! Я знаю.
    Никто не сможет остановить настоящую героиню.
>
goto.20
label.11
setTalkLabels.-1.-1.2
talk.<
    Возможно, ты еще не понимаешь, но твои поступки доказывают, что ты выбрана древними писаниями.
    Ты спасешь наш мир.
>
label.20
waitForUser
talk.<
    Существует древнее предсказание о герое – или героине.
    Ты выполнишь его.
    Никто не знает всего предсказания, даже Белый Друид из Царства Облаков.
>
waitForUser
talk.<
    И хотя никто не знает всех тайн Занзары, тебе везде помогут.
    Я всегда готов дать тебе совет.
    Совы тоже много знают о тайнах Занзары.
    Кто знает, может ты найдешь древние писания...
>
waitForUser
talk.<
    Настоящая героиня всегда найдет свой путь, не так ли?
    Тебе понадобится эта {4*эльфийская сумка}, если ты собираешься участвовать в поединках фей.
    Ты должна знать, как участвовать в этих поединках.
>
waitForUser
setCamera.1003
setTalkLabels.-1.-1.0
talk.<
    Только настоящая Повелительница фей сможет одержать победу.
    Там дальше есть деревня эльфов Эндева, и ты сможешь там узнать многое о феях.
>
waitForUser
changeWaypoint.3.4
givePlayerCards.1.0.59
changeDatabase.1D7435A4
exit"""
InitScript = """
movementSpeed.10
setModel.g000s00m"""
UpdateScript = """
deployNpcAtTrigger.59.0
label.0
lookAtPlayer.1.0
ifTriggerIsActive.13
startPrelude
endIf
goto.0"""
