UID = "2D354DB4"
Name = "6E781E01"
TriggerScript = """
playAnimation.13.-1
setCamera.3001
ifNpcModifierHasValue.1
say.<Разве ты не Эми, девушка из мира людей?>.0
waitForUser
else
setNpcModifier.-1.-1.1
say.<
    Человек! Такое не часто увидишь!
>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Человек?
    Я думал, что вы все давным-давно вымерли! Я {4*Руфус}, {4*Хранитель Пикси}.
    Кто ты?
    Ты пришла помочь нам сражаться с нашествием пикси?
>
waitForUser
endIf
ifPlayerHasSpecials.1.1
setTalkLabels.-1.-1.2
talk.<
    Прекрасно.
    Возьми этот {4*Мешок для Пикси}.
    При помощи него ты можешь ловить их, достаточно просто подойти к ним близко.
    Но не думай, что это будет просто, — даже если они глупые, они все ещё очень быстрые и ловкие.
>
waitForUser
setTalkLabels.10.11.1
talk.<Ты знаешь, как сражаться с феями?>
waitForUser
label.10
setTalkLabels.-1.-1.2
talk.<
    Один из {4*пикси} пробрался в {4*Эндеву} и прячется где-то в нашей деревне.
    Почему бы тебе не попытаться найти и поймать его?
    После этого ты можешь последовать за мной в {4*Сад фей}, но помни, что ты должна быть готова к битвам с {4*дикими феями}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Если тебе потребуется помощь в {4*тренировке феи}, обратись к тренеру, он находится около другого выхода из {4*Эндевы}.
    Береги себя.
>
waitForUser
givePlayerCards.1.0.16
changeWaypoint.10.11
removeNpc
exit
label.11
setCamera.1005
setTalkLabels.-1.-1.2
talk.<
    Ты можешь нести с собой в сумке {4*пять фей} за раз.
    Если на тебя нападут, они будут за тебя сражаться.
    Ты должна научиться использовать силу своей активной феи в бою.
>
waitForUser
talk.<
    Каждая фея может летать, пока у нее достаточно энергии.
    Во время сражения ты можешь видеть их энергию полета как {4*зеленую полоску}.
    К счастью, эта энергия  восстанавливается, когда фея стоит на земле.
    Тем не менее, ты должна расходовать ее разумно!
>
waitForUser
talk.<
    Ты можешь нападать, используя {4*атакующие} заклинания.
    Сила заклинания зависит от времени подготовки.
    Чем дольше ты его заряжаешь, тем мощнее будет его действие.
    Но не перестарайся, иначе заклинание нанесёт урон твоей же фее!
>
waitForUser
talk.<
    {4*Пассивные} заклинания поддерживают твою фею.
    Они защищают ее от повреждений, усиливают ее атаки или помогают тебе в чем–нибудь другом.
>
waitForUser
talk.<
    Ты можешь купить заклинания за золотые монеты, если повстречаешь {4*торговцев заклинаниями}.
    Эти магические торговцы сомнительные спекулянты, но тебе понадобится их помощь, чтобы усиливать своих фей.
    Ты можешь встретить одного из них в {4*таверне Эндевы} или в {4*моём доме}, который находится на другой стороне {4*Сада фей}.
>
waitForUser
setCamera.3001
talk.<
    Жизненная энергия твоей феи показана как {4*красная полоска}.
    Если твоя фея проиграла, то ее можно вернуть к жизни с помощью {4*лекарственных трав} и вылечить до полного здоровья {4*флаконами с бальзамом}.
>
waitForUser
setTalkLabels.11.10.1
talk.<Объяснить тебе эти правила еще раз?>
waitForUser
endIf
label.0
say.<У всех людей такие же странные манеры, как у тебя?>.1
choice.1.<Уйти из деревни>
choice.2.<Феи в Эндеве>
choice.3.<Не сейчас>
waitForUser
label.1
setTalkLabels.-1.-1.0
talk.<
    Ты, должно быть, недавно в {4*Занзаре}.
    Разве ты не знаешь, что без собственной {4*феи} ты будешь беспомощной перед {4*дикими феями}?
    Сначала найди себе фею, а потом сможешь уйти из деревни.
>
waitForUser
goto.0
label.2
setTalkLabels.-1.-1.0
talk.<
    Я думаю, {4*Люциус} может отдать одну из своих фей, которые хранятся у него дома.
    Найди его в таверне, и скажи, что ты пришла помочь с {4*нашествием пикси}.
>
waitForUser
setCamera.3002
delay.18
setTalkLabels.-1.-1.0
setCamera.3001
talk.<
    Как только у тебя будет собственная {4*фея}, возвращайся ко мне.
    Помни, что ты можешь выбрать только {4*одну} из них.
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.g202s22m
movementSpeed.11
defaultWizForm.194.0.2
endIf"""
UpdateScript = "lookAtPlayer.0.1"
