UID = "E1129734"
Name = "6E781E01"
TriggerScript = """
setCamera.3000
playAnimation.13.-1
say.<Надеюсь, тебе понравился наш {4*Сад Фей}, пока ты добиралась сюда?>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Надеюсь, ты не забыла поймать всех {4*пикси} по пути сюда?
    У тебя должно быть их достаточно, чтобы получить за них {4*награду}.
>
waitForUser
talk.<
    За этим проходом находится мой дом.
    Моей задачей было охранять этих вредных существ, но злобный {4*Тёмный Эльф} проникнул в подвал с клетками и открыл их.
    Теперь {4*пикси} разбежались по всем уголкам {4*Занзары}.
>
waitForUser
talk.<
    Я могу обменять каждых {4*пятерых пикси}, которых ты принесёшь мне, на {4*предметы}, которые тебе понадобятся для {4*фей}.
    Разумеется, чем больше пикси ты найдёшь, тем лучше будет награда за их сдачу.
>
waitForUser
talk.<
    Во время путешествий тебе не раз придётся ловить новых фей или же обменивать их у других {4*Коллекционеров}.
    Но чтобы узнать о сильных и слабых сторонах каждой из них, тебе потребуется {4*Книга фей}.
    Такая есть у каждого уважающего себя {4*Коллекционера}.
>
waitForUser
talk.<
    В ней ты найдёшь {4*описание характеристик}, {4*количество здоровья}, а также {4*уровень эволюции} любой феи.
    Не каждая фея имеет {4*эволюционные формы}, и к тому же здесь указаны не все существующие феи.
    Но ты найдёшь здесь большинство {4*фей}, которых можно обнаружить {4*в дикой природе}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Также существуют {4*особые формы} фей, которые можно получить при помощи {4*Эволюционных Камней} или {4*особых инструментов Гномов}, но тебе лучше попытаться узнать об этом в {4*Тиралине}, {4*Данморе} и {4*Монагаме}.
    А мне пора вернуться домой.
>
waitForUser
ifPlayerHasCards.1.0.58
setNpcModifier.2411.69.1
goto.0
else
setNpcModifier.2411.69.0
label.0
modifyTrigger.0.3202.7
givePlayerCards.1.0.58
changeWaypoint.10.11
removeNpc
exit"""
InitScript = """
setModel.g202s22m
defaultWizForm.194.0.2"""
UpdateScript = "lookAtPlayer.0.1"
