UID = "501F4684"
Name = "C82ECC31"
TriggerScript = """
setCamera.3000
playAnimation.12.-1
ifNpcModifierHasValue.1
say.<
    Ты ещё не вернулась в свой мир?
    Какая жалость.
>.0
waitForUser
else
setNpcModifier.-1.-1.1
say.<И что {4*человек} мог забыть в нашем мире?>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    {4*Рафи}, должно быть, совершенно выжил из ума, раз уж позволил {4*человеческому детенышу} проникнуть в {4*Занзару}.
    Благодаря {4*Великому Разделу}, мы наконец смогли изолировать наш мир от человеческой скверны, и теперь ты пришла, чтобы снова погрузить {4*Занзару} в хаос?
>
waitForUser
endIf
ifPlayerHasSpecials.2.2
setTalkLabels.-1.-1.2
talk.<
    Я не позволю тебе пройти, если у тебя с собой не будет как минимум {4* две феи}.
    Даже если ты сможешь получить свою {4*первую фею}, то вторую тебе придётся поймать самостоятельно...
    и если ты не способна на что-то настолько тривиальное, то тебе стоит вернуться в человеческий мир к своим куклам.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Пфф, ты смогла раздобыть {4*двух фей}.
    Возможно ты даже сможешь дойти до {4*Турнира} на {4*Великом Дереве}?
    Если ты сможешь это сделать, тогда мы сможем сразиться в {4*поединке фей}, и я наконец докажу, насколько {4*люди} существа, недостойные нашего доверия.
>
waitForUser
givePlayerCards.1.0.62
changeWaypoint.1.2
removeNpc
exit
endIf
label.0
say.<Я надеюсь, что после первой встречи с {4*Тёмным Эльфом} ты поймёшь, какой большой ошибкой было приходить в этот мир...>.1
choice.1.<Уйти из деревни>
choice.2.<Великий Раздел>
choice.3.<Пока ничего>
waitForUser
exit
label.1
setTalkLabels.-1.-1.0
talk.<
    Я не позволю тебе пройти, если у тебя с собой не будет как минимум {4* две феи}.
    Даже если ты сможешь получить свою {4*первую фею}, то вторую тебе придётся поймать самостоятельно...
    и если ты не способна на что-то настолько тривиальное, то тебе стоит вернуться в человеческий мир к своим куклам.
>
waitForUser
goto.0
label.2
setTalkLabels.-1.-1.2
talk.<
    Давным-давно три мира — {4*человеческий мир}, {4*Занзара} и {4*астральный мир фей} — были единым целым.
    Все расы: {4*эльфы}, {4*болотные гоблины}, {4*гномы} и {4*люди} жили в гармонии, и волшебные существа были также обычно для вашего мира, как для {4*Занзары}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Так продолжалось до тех пор, пока {4*люди} не объявили {4*Великую Охоту}: они начали уничтожать всех {4*магических существ}, и даже {4*людей}, из-за страха перед возможностями {4*магии}.
    Единственным, кто спас нас всех от уничтожения, был {4*Белый Друид}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    {4*Белый Друид} создал {4*Стража} — магическое создание, которое отделило {4*человеческий мир} от {4*Занзары}.
    Так или иначе, но я всё равно не доверяю {4*Белому Друиду} — он такой же {4*человек}, как и ты, и он ничего не сделал для {4*восстановления гармонии} после {4*Нарушения Баланса}.
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.g204s20m
defaultWizForm.135.0.2
endIf"""
UpdateScript = "lookAtPlayer.0.1"
