UID = "501F4684"
Name = "E95016B1"
TriggerScript = """
setCamera.3000
playAnimation.12.-1
ifNpcModifierHasValue.1
say.<О, это снова ты, Эми.>.0
waitForUser
else
setNpcModifier.-1.-1.1
say.<
	Итак, ты – Эми из мира людей?
    Добро пожаловать в {4*Эндеву}.
>.0
waitForUser
talk.<
    Я рад, что встретил тебя! {4*Рафи} сказал, что ты прибыла в {4*Занзару}, и я должен присмотреть за тобой.
    Но с тех пор произошло много ужасного.
>
waitForUser
talk.<
    Говорят, что ужасные, порочные существа, называемые {4*Тёмными Эльфами}, пришли сюда из {4*Царства Тьмы}.
    Из клеток сбежали все {4*пикси}, и теперь они сеят хаос всюду, где бы они не находились.
>
waitForUser
talk.<
    И что хуже всего — мой отец, гном {4*Квинлин}, пропал.
    Он видел, что наступают трудные времена, и теперь, когда он нам нужен, его нигде нет.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я надеюсь, ты понимаешь, что нам нужна твоя помощь.
    И не только мне, а также {4*Белому Друиду} и всей {4*Занзаре}.
>
waitForUser
ifPlayerHasSpecials.2.2
setTalkLabels.-1.-1.2
talk.<
    Значит, ты смогла раздобыть {4*двух фей}.
    Это хорошие новости, но тебе понадобится гораздо больше {4*фей}, если ты собираешься отправиться в серьёзное путешествие.
    Возможно ты захочешь поймать нескольких в {4*Саду Фей} или даже {4*Зачарованном Лесу}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Следуя этой дороге, ты сможешь дойти до {4*Тиралина} - города, некогда построенного в союзе людей и эльфов.
	Именно там тебе следует искать помощи в том, чтобы найти путь к {4*Белому Друиду}, который живёт в {4*Царстве Облаков}.
	Сейчас единственный путь к лифту в {4*Царство Облаков} отрезан {4*Тёмными Эльфами}, но может кто-то знает альтернативные пути.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Для запуска лифта тебе понадобятся {4*Элементальные Ключи Стихий}, - и я слышал, что один из них хранится в {4*Данморе}, поселении {4*Болотных Гоблинов}.
	Тебе стоит начать свои поиски оттуда.
	{4*Тёмные Эльфы} также заблокировали все пути к нему, но наверняка кто-то сможет поделиться своей руной, чтобы ты смогла безопасно добраться туда.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    И чуть не забыл: во время нашей последней встречи {4*Рафи} попросил меня отдать тебе эту карту.
	При помощи неё ты сможешь без проблем ориентироваться в {4*Саду фей}, а также {4*Зачарованном Лесу}.
	И если тебе понадобятся карты других земель {4*Занзары], то ищи {4*Заида} в {4*Данморе},он сможет помочь тебе с этим.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
	Я вернусь в {4*Монагам}, чтобы продолжить поиски {4*Элементального Ключа Воздуха}, утерянного давным-давно.
	Уверен, мы обязательно ещё встретимся в будущем, Эми.
	Прости, но мне действительно надо идти...
>
waitForUser
givePlayerCards.1.0.62
changeWaypoint.1.2
removeNpc
exit
endIf
label.0
say.<Тебе что-то нужно от меня?>.1
choice.1.<Диалог>
choice.2.<Уйти>
waitForUser
label.1
setTalkLabels.-1.-1.0
talk.<
	Извини, Эми, но я не позволить тебе пройти, если у тебя с собой не будет как минимум {4*две феи}.
	{4*Дикие феи}, обитающие за пределами {4*Сада Фей}, гораздо агрессивнее и опаснее, нежели те, что обитают здесь.
	Тебе стоит позаботиться о том, чтобы не попасть в неприятности, так как только твои {4*феи} могут защитить тебя в путешествии.
>
waitForUser
goto.0
label.2
exit"""
InitScript = """
setModel.d006s02m
defaultWizForm.189.0.2"""
UpdateScript = "lookAtPlayer.0.1"
