UID = "70B749B4"
Name = "F655D391"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifPlayerHasCards.1.0.10
goto.10
endIf
ifNumberOfNpcsIs.1.5AB6E504
setTalkLabels.-1.-1.0
talk.<Остался последний терновый куст на нашей земле.>
waitForUser
exit
endIf
ifNumberOfNpcsIs.2.5AB6E504
setTalkLabels.-1.-1.0
talk.<На нашей земле осталось ещё два терновых куста.>
waitForUser
exit
endIf
ifNumberOfNpcsIs.3.5AB6E504
setTalkLabels.-1.-1.0
talk.<Тебе надо найти и уничтожить ещё три терновых куста.>
waitForUser
exit
endIf
ifNumberOfNpcsIs.4.5AB6E504
setTalkLabels.-1.-1.0
talk.<В нашей долине растут четыре терновых куста.>
waitForUser
exit
endIf
ifNumberOfNpcsIs.0.5AB6E504
setTalkLabels.-1.-1.0
talk.<
    Спасибо, что освободила наш дом от кустов.
    {4*Стихийный Ключ Воздуха} хранится в Мэрии Тиралина, и для этого тебе потребуется {4*ключ}. Возьми эту вещь в качестве моей благодарности.
>
waitForUser
givePlayerCards.1.0.10
exit
endIf
ifNumberOfNpcsIs.5.5AB6E504
say.<Добро пожаловать в нашу лесную хижину.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    {4*Терновые кусты} заполонили всю нашу землю так, что мы больше не можем здесь жить.
    Мой муж отправился {4*за помощью} на болото.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Найди все терновые кусты на нашей земле и уничтожь их.
    За это я подскажу, где стоит искать {4*Стихийный Ключ Воздуха}.
>
waitForUser
exit
endIf
label.10
ifNumberOfNpcsIs.1.E3A72994
say.<Спасибо, что освободила наш дом от этих кустов.>.0
waitForUser
exit
endIf
say.<Добро пожаловать в нашу лесную хижину.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Мой муж отправился в {4*Данмор}, чтобы найти способ избавиться от этих кустов.
    Я надеюсь, что с ним всё в порядке, и он скоро вернётся домой.
>
waitForUser
exit"""
InitScript = """
setModel.w000s00m
movementSpeed.13"""
UpdateScript = "lookAtPlayer.0.1"
