UID = "6E238F04"
Name = "97688F91"
TriggerScript = """
setCamera.1000
setTalkLabels.5.10.1
talk.<
    Принеси мне {4*три Камеи Коллекционера и три Камеи Тёмных Эльфов}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
label.5
setCamera.1006
fight.-1.0
label.10
setTalkLabels.-1.-1.0
talk.<Прочесть>
waitForUser"""
InitScript = """
setModel.u003s03m
defaultDeck.2.35.1"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
setCamera.1000
say.<
    Принеси мне {4*девять Камей Тёмных Эльфов}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>.0
waitForUser
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
