UID = "4C505E04"
Name = "E95016B1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Я рад тебя снова видеть, {4*Эми}.>.0
waitForUser
ifNpcModifierHasValue.0
setTalkLabels.-1.-1.0
talk.<
    Ох, ты все ещё здесь, {4*Эми}.
    Я надеюсь, {4*Тёмные Эльфы} больше не отважатся напасть на {4*Царство Облаков} после того, что ты устроила здесь! Ты должна гордиться собой и тем, насколько сильны твои феи.
    Ты определённо сможешь помочь {4*Белому Друиду} в его задании по сохранению {4*Занзары}.
>
waitForUser
goto.1
endIf
ifPlayerHasCards.1.0.26
setTalkLabels.-1.-1.2
talk.<
    {4*Тёмный Эльф} отдал тебе этот посох?
    Он принадлежит моему отцу, {4*Квинлину}.
    Я не знаю, каким образом они смогли получить его, потому что только сам {4*Квинлин} мог знать об его месте хранении.
    Если только он сам не сказал им об этом?
    Но это невозможно! Он никогда бы не стал отдавать им что-то настолько ценное...
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я думаю, мне нужно какое-то время, чтобы внимательно обдумать всё, что произошло здесь.
    Ты должна встретиться с {4*Белым Друидом} в {4*Соборе}, и обсудить с ним всё, что ты увидела здесь.
    Мы встретимся с тобой там позже.
>
waitForUser
setNpcModifier.-1.-1.0
goto.1
else
setTalkLabels.-1.-1.0
talk.<
    Пока {4*Тёмные Эльфы} находятся на {4*Небесной Арене}, мы не можем уйти отсюда.
    Они определённо что-то скрывают, и ты должна узнать, какой их настоящий план.
>
waitForUser
label.1
exit"""
InitScript = """
setModel.d006s02m
defaultWizForm.93.0.60"""
UpdateScript = """
deployNpcAtTrigger.43.0
lookAtPlayer.0.1"""
