UID = "5A886314"
Name = "2B4B0221"
TriggerScript = """
ifTriggerIsActive.34
deployNpcAtTrigger.12.1
setCamera.3001
playAnimation.13.-1
say.<Для нашей любимой Занзары наступили тяжелые времена.>.0
waitForUser
goto.10
endIf
ifTriggerIsActive.33
goto.20
endIf
label.10
say.<Мы должны быть стойкими в это тяжёлое время.>.1
choice.12.<Вина гномов>
choice.13.<Собор>
choice.14.<До встречи>
waitForUser
label.12
setTalkLabels.15.16.1
talk.<
    Будь проклят {4*Квинлин, Гном Мастер}! Этот предатель поддерживает Тёмных Эльфов! Мы должны его остановить.
    Или у тебя есть сомнения в виновности гномов?
>
waitForUser
label.15
setTalkLabels.-1.-1.0
talk.<
    Ты сама завоевала {4*гномий артефакт} на моей арене.
    Очевидно, что он пришёл от Гнома-Мастера.
>
waitForUser
goto.10
label.16
setTalkLabels.-1.-1.0
talk.<
    Ты права.
    Гномам больше нельзя верить, они предали нас, заключив союз с {4*Тёмными Эльфами}.
>
waitForUser
goto.10
label.13
setTalkLabels.-1.-1.2
talk.<
    Разве это не прекрасно?
    Такой непорочный и мирный.
    Никто, ни {4*гном}, ни {4*Тёмный Эльф}, ни даже человек не сможет это изменить.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    В предсказании говорится о переменах, но я не позволю никому разрушить наш мир.
    Запомни мои слова!
>
waitForUser
goto.10
label.14
exit
label.20
deployNpcAtTrigger.10.1
setCamera.3005
setTalkLabels.-1.-1.0
talk.<
    Счастливого пути.
    Но помни: гномы виноваты в наших бедах.
    
>
waitForUser"""
InitScript = "setModel.v000s00"
UpdateScript = """
deployNpcAtTrigger.15.0
label.0
lookAtPlayer.2.0
ifTriggerIsActive.33
startPrelude
endIf
ifTriggerIsActive.34
startPrelude
endIf
goto.0"""
