UID = "C04B4184"
Name = "2B4B0221"
TriggerScript = """
deployNpcAtTrigger.12.1
setCamera.3001
changeWaypoint.1.2
playAnimation.13.-1
say.<Ты как раз вовремя, Эми.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Вот еще одно доказательство вины гномов.
    Этот хитрый гном пробрался в мой дворец и пытался меня {4*обокрасть}!
>
waitForUser
setCamera.3020
delay.20
setCamera.3001
setTalkLabels.-1.-1.0
talk.<Но я поймал его и поместил за этот непробиваемый волшебный барьер.>
waitForUser
changeDatabase.5A886314
exit"""
InitScript = "setModel.v000s00"
UpdateScript = """
label.0
idle
ifTriggerIsActive.33
startPrelude
endIf
goto.0"""
