UID = "285EB684"
Name = "2B4B0221"
TriggerScript = """
delay.15
setCamera.3002
say.<Ужасно, что все это произошло.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Ты спасла {4*Квинлина} со старой фабрики?
    Тогда ты, несомненно, поняла, что {4*гномы} тебе не враги.
    Они никогда не имели дел с {4*Тёмными Эльфами}.
>
waitForUser
setCamera.3003
startEffect.1.36
delay.3
deployNpcAtTrigger.36.ABF0DA04
talk.<
    Это именно я призвал {4*Тёмных Эльфов} из Царства Тьмы.
    Предсказание никогда не должно сбыться.
    {4*Страж} не должен быть повержен!
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я оставлю твоего друга {4*Лассе} на попечение моего союзника.
    Он о нем хорошо позаботятся.
    Возвращайся, Эми.
    Уходи из {4*Занзары}, или ты вынуждена будешь узнать, что я единственный настоящий {4*Повелитель Фей}.
>
waitForUser
startEffect.0.-1
delay.2
removeNpc
exit"""
InitScript = "setModel.v000s00"
UpdateScript = "startPrelude"
