UID = "1E3B48B4"
Name = "60D826B1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.1
say.<...>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<...>
waitForUser
exit
endIf
setNpcModifier.3600.40.1
setNpcModifier.3600.43.1
setNpcModifier.3600.54.1
setNpcModifier.3600.21.1000
setNpcModifier.3600.7.1000
setNpcModifier.-1.-1.1
say.<Человек из предсказания!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
	Я практически потерял надежду, что кто-то найдёт меня здесь.
    Мне удалось пробраться в {4*Царство Тьмы}, чтобы разузнать, что планируют {4*Тёмные Эльфы}, но, как ты видишь, я был не настолько успешен в этом...
    Раз уж ты здесь, то они не стали для тебя большой проблемой...
    и теперь ты наверняка захочешь узнать всю правду о {4*Страже}.
>
waitForUser
setCamera.2003
talk.<
	В далёком прошлом именно я создал {4*Стража}, — существо, наполовину принадлежащее этому миру и наполовину астральному миру фей.
	Его предназначением было защитить {4*Занзару} от людей, но это должно было стать временной мерой.
	Именно поэтому возникло {4*Предсказание}: легенда о человеке, который однажды объединит два разделённых мира.
>
waitForUser
talk.<
	Но до того, как это произойдёт, кто-то должен был защищать {4*Стража}...
	в конце концов, весь этот план держался в секрете ото всех остальных рас, и мы боялись, что никто не примет его.
	Поэтому {4*Белый Друид} и я заключили союз с {4*Тёмными Эльфами}, и таким образом они стали защитниками {4*Стража}.
	Или я надеялся, что это будет так...
	если бы ты только знала, насколько я ошибался.
>
waitForUser
talk.<
	Магия {4*Стража} должна была поддерживаться {4*Белым Друидом}.
	Именно его заклинание позволило закрыть порталы в человеческий мир.
	Но было слишком поздно, когда я понял, что {4*Белый Друид} всё это время лгал нам всем.
	Это была не его магия, что поддерживала существования {4*Стража}, это была магия самой {4*Занзары}.
>
waitForUser
talk.<
    {4*Тёмные Эльфы} были первыми, кто заметил это, и когда они сообщили мне об этом, я не поверил им.
	Долгое время {4*Белый Друид} служил во имя блага всей {4*Занзары}, и что могло заставить измениться его?
	И тогда я понял.
	Всё это время он боялся смерти, — и он решил использовать {4*Стража}, чтобы обрести бессмертие!
>
waitForUser
talk.<
	В отличие от рас, населяющих {4*Занзару}, вы, люди, имеете самую худшую склонность к магии.
	Именно по этой причине ваш жизненный цикл настолько короток.
	Но в то же время {4*Друиды} были другими.
	Они были способны пропускать магию через себя, управляя окружающими их стихиями.
	Как ты можешь предположить, {4*Белый Друид} был одним из них.
>
waitForUser
setCamera.1000
talk.<
	Если бы всё пошло так, как я изначально предполагал, {4*Белому Друиду} пришлось бы пожертвовать своей жизнью ради существования {4*Стража}.
	Но он нашёл другой способ, и связал {4*Стража} с самой {4*Занзарой}, и теперь этот мир страдает из-за моей глупости и недальновидности.
	Тем не менее, все ещё не поздно исправить мою ошибку.
	Мы должны уничтожить {4*Стража}, и я помогу тебе в этом.
>
waitForUser
talk.<
	Но до этого...
	мне нужно о кое о чём тебя попросить.
	Мой сын, {4*Лассе}, должен был отвлечь {4*Белого Друида}, пока я искал способ получить доступ к {4*Стражу}.
	К сожалению, мы можем только полагаться на помощь {4*Тёмных Эльфов} — только у них есть ключ от двери, ведущей к {4*Стражу}.
	Именно тебе нужно вернуться обратно в {4*Белый Собор}.
>
waitForUser
talk.<
	Возьми это кольцо, и передай его ...
	Он должен был украсть ключ из {4*Белого Собора}, но наверняка {4*Друид} узнал об этом плане и теперь держит его в плену. 
	И заодно расскажи {4*Лассе} обо всём, что ты узнала от меня...
	а также, что я очень сожалею, что я втянул его в это.
	Он все ещё молодой гном, и не понимает всю опасность сил {4*Белого Друида}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    У нас осталось не так много времени.
	Пожалуйста, поспеши в {4*Белый Собор} и передай это кольцо.
    В это время я пока останусь здесь.
	У меня есть некоторые неоконченные дела.
>
waitForUser
givePlayerCards.1.0.73
exit"""
InitScript = "setModel.d005s01m"
UpdateScript = "lookAtPlayer.0.1"
