UID = "83908DB4"
Name = "0FDF8F91"
TriggerScript = """
setCamera.1000
ifPlayerHasCards.1.0.15
deployNpcAtTrigger.24.1
deployNpcAtTrigger.17.0
playAnimation.0.-1
playAnimation.13.-1
say.<Ты прогнала {4*Тёмных Эльфов}?>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Ох и битва это, наверное, была...
    Хорошо, что меня там не было.
    Но ты действительно заслужила награду.
>
waitForUser
say.<Что ты хочешь?>.1
choice.5.<Три {4*Очищенных нектара}>
choice.6.<Три {4*Медных редиса}>
choice.7.<Золотой шар>
waitForUser
label.5
givePlayerCards.3.0.9
changeDatabase.B2EE3B04
exit
label.6
givePlayerCards.3.0.60
changeDatabase.B2EE3B04
exit
label.7
givePlayerCards.1.0.18
changeDatabase.B2EE3B04
exit
endIf
gotoRandomLabel.3.1
label.1
playAnimation.0.-1
say.<
    Помогите! Почему мне никто не поможет бороться с Тёмными Эльфами?
>.0
waitForUser
exit
label.2
playAnimation.0.-1
say.<
    Они хотят меня ограбить! Сделайте что-нибудь!
>.0
waitForUser
exit
label.3
playAnimation.0.-1
say.<
    Тёмные Эльфы! Они хотят украсть мои сокровища!
>.0
waitForUser
exit"""
InitScript = """
movementSpeed.19
setModel.g002s02m"""
UpdateScript = """
label.0
moveSystem.1.2
goto.0"""
