UID = "B2EE3B04"
Name = "0FDF8F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Привет, Повелительница фей.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<Надеюсь, больше никогда не увижу этих {4*ужасных Темных Эльфов}!>
waitForUser"""
InitScript = """
movementSpeed.2
setModel.g002s02m"""
UpdateScript = "lookAtPlayer.0.1"
