UID = "C5552784"
Name = "BDE38F91"
TriggerScript = """
gotoRandomLabel.10.0
label.0
say.<Я в это не верю, он — мошенник!>.0
goto.100
label.1
say.<Лучше это увидеть, его фокусы хороши.>.0
goto.100
label.2
say.<Положить карты на стол?>.0
goto.100
label.3
say.<Он блефует, я в этом уверен...>.0
goto.100
label.4
say.<
    Что за болван! Он когда-нибудь собирается положить карту?
>.0
goto.100
label.5
say.<Еще две карты, и я победил...>.0
goto.100
label.6
say.<Пожалуйста, не мешай, я делаю это не ради забавы!>.0
goto.100
label.7
label.8
label.9
say.<
    Убирайся! Забери монету и иди!
>.0
createDynamicItems.4.1.-1
goto.100
label.100
waitForUser"""
InitScript = """
setNpcType.4
setModel.g306s36m"""
UpdateScript = """
lookAtPlayer.0.-1
label.10
idle
idle
idle
gotoRandomLabel.6.0
goto.10
label.0
label.4
label.5
playAnimation.11.90
playAnimation.0.20
goto.10
label.1
playAnimation.12.20
playAnimation.0.20
goto.10
label.2
idle
idle
goto.10
label.3
idle
idle
idle
idle
goto.10"""
