UID = "D5C56E04"
Name = "C86EAF91"
TriggerScript = """
setCamera.1000
say.<О, опять ты!>.0
waitForUser
label.10
say.<Чем могу помочь?>.1
choice.0.<Пополнить ману>
choice.1.<Информация о магии фей>
choice.2.<Не сегодня>
waitForUser
label.0
setCamera.3000
delay.1
startEffect.2.27
delay.1
setCamera.3001
startEffect.2.28
delay.1
startEffect.2.29
delay.1
startEffect.2.30
delay.1
setCamera.3002
startEffect.2.31
delay.1
startEffect.2.32
delay.1
setCamera.3000
startEffect.2.35
delay.1
startEffect.2.33
delay.1
startEffect.2.34
revive
goto.10
label.1
talk.<
    Только фея с достаточным количеством{4*маны} может использовать заклинания в поединке.
    Каждое заклинание забирает одну {4*единицу маны}.
    Будь осторожна, так как если вся мана кончится, то фея будет использовать свою {4*жизненную энергию} для заклинания!
>
waitForUser
goto.10
label.2
exit"""
InitScript = """
setNpcType.4
setModel.v001s01"""
