UID = "599E9214"
Name = "0FDF8F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Как тебе наше дерево?>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    После {4*Данмора}, находящегося на севере, Большое Дерево это второе поселение Болотных Гоблинов в {4*Занзаре}.
    Это очень уютное место, не так ли?
>
waitForUser
exit"""
InitScript = "setModel.g001s01m"
UpdateScript = "lookAtPlayer.0.1"
VictoriousScript = "killPlayer"
