UID = "0A1E3314"
Name = "10E82091"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Добро пожаловать в мою библиотеку.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    О, {4*Царство Облаков}.
    Легендарное место.
    Нет другого такого сверкающего и красивого места во всей {4*Занзаре}! В облаках много непревзойдённых мест.
>
waitForUser
talk.<
    Это {4*Белый Собор}, дом {4*Друида}; великая {4*Арена}, место, где когда-то повелители фей проверяли свои силы; белый {4*Павильон}, где проводились богатые празднества...
    но это всё было очень давно.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    С тех пор, как платформа перестала функционировать, никто не может добраться до облаков.
    Многие даже забыли о существовании {4*Царства Облаков}.
>
waitForUser
exit"""
InitScript = """
setModel.b011s00m
defaultWizForm.32.0.8"""
UpdateScript = "lookAtPlayer.0.1"
