UID = "B6A31714"
Name = "10E82091"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Добро пожаловать в мой скромный дом.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Книги сильно помогают в {4*Занзаре}.
    В них содержатся легенды о наших предках.
    Одна из легенд говорит о герое, который спасёт наш мир.
    Должно быть, это {4*Белый Друид}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    К сожалению, в книгах не говорится, как именно он сможет спасти {4*Занзару}.
    Посмотри вокруг.
    Может, ты найдешь ниточку, которую мы упустили.
>
waitForUser"""
InitScript = """
setModel.b010s00m
defaultWizForm.29.0.2"""
UpdateScript = "lookAtPlayer.0.1"
