UID = "07953694"
Name = "10E82091"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Это была честная битва.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Давным-давно {4*Квинлин} попросил нас охранять {4*Магическую Карту Огня}.
    Она была создана гномами, чтобы защитить себя от пылающего жара {4*Лавовых Пещер}.
>
waitForUser
talk.<
    Единственный лифт, через который ты можешь спуститься в {4*Лавовые Пещеры}, находится в {4*Монагаме}, в доме {4*Квинлина}.
    Но для его запуска тебе понадобятся {4*Стихийные Ключи Воздуха, Камня и Огня}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я не знаю, где ты можешь их найти, но {4*Стихийный Ключ Земли} все ещё находится во владении {4*гномов}.
    Также существуют и другие лифты, которым нужны другие комбинации ключей.
    Боюсь, это все, что я знаю.
>
waitForUser"""
InitScript = """
setModel.b009s00m
defaultWizForm.47.0.24"""
UpdateScript = "lookAtPlayer.0.1"
