UID = "F8F6E424"
Name = "7B2D8F91"
TriggerScript = """
ifNumberOfNpcsIs.0.7EDC6334
goto.10
endIf
say.<Наконец-то кто-то нашёл нас в этом забытом месте!>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Ты должна победить этих агрессивных фей, чтобы освободить меня из плена.
    Но будь осторожна, их много, и они очень опасны!
>
waitForUser
exit
label.10
endActorEffect
setTalkLabels.-1.-1.2
talk.<
    Спасибо, что освободила меня из плена.
    Я уже потерял надежду, что кто-то найдёт меня, и моя голова кружится от этого ослепительного света...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Во время одного из наших экспериментов что-то пошло не так, и я оказался здесь.
    Наши феи обратились против нас, заперев меня в этой энергетической тюрьме.
    Я не знаю, сколько прошло времени, но мне кажется, что я здесь нахожусь уже целую вечность.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Теперь я могу вернуться домой.
    Возьми эти {4*детали гномов}, которые я нашёл здесь.
    Надеюсь, моя {4*Руна Возвращения} всё ещё работает...
>
waitForUser
givePlayerCards.3.0.108
delay.10
startEffect.0.-1
removeNpc"""
InitScript = """
setModel.d000s00m
startActorEffect.1"""
UpdateScript = "lookAtPlayer.-1.1"
