UID = "9053B6A4"
Name = "79110B91"
#Rasrow (10), Tyberri (18), Strix (83)
#From 19 to 16
InitScript = """
setNpcType.3
gotoRandomLabel.12.0
label.0
defaultWizForm.10.0.20
goto.20
label.1
defaultWizForm.10.0.19
goto.20
label.2
defaultWizForm.10.0.18
goto.20
label.3
defaultWizForm.10.0.17
goto.20
label.4
defaultWizForm.18.0.20
goto.20
label.5
defaultWizForm.18.0.19
goto.20
label.6
defaultWizForm.18.0.18
goto.20
label.7
defaultWizForm.18.0.17
goto.20
label.8
defaultWizForm.83.0.20
goto.20
label.9
defaultWizForm.83.0.19
goto.20
label.10
defaultWizForm.83.0.18
goto.20
label.11
defaultWizForm.83.0.17
goto.20
label.20"""
