UID = "95FBD3A4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.158.0.30
defaultWizForm.120.1.27
defaultWizForm.67.2.27
defaultWizForm.162.3.28
defaultWizForm.23.4.26
goto.3
label.1
defaultWizForm.158.0.30
defaultWizForm.208.1.29
defaultWizForm.27.2.26
defaultWizForm.62.3.28
defaultWizForm.106.4.30
goto.3
label.2
defaultWizForm.158.0.30
defaultWizForm.29.1.28
defaultWizForm.63.2.28
defaultWizForm.166.3.29
defaultWizForm.119.4.27
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
