UID = "F9B3D3A4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.u002s02m
defaultDeck.2.45.1
exit
endIf
ifNpcModifierHasValue.1
setModel.u002s02m
gotoRandomLabel.3.0
label.0
defaultWizForm.104.0.31
defaultWizForm.157.1.30
defaultWizForm.42.2.31
defaultWizForm.76.3.27
defaultWizForm.209.4.27
goto.3
label.1
defaultWizForm.104.0.31
defaultWizForm.70.1.27
defaultWizForm.59.2.27
defaultWizForm.86.3.29
defaultWizForm.98.4.26
goto.3
label.2
defaultWizForm.104.0.31
defaultWizForm.114.1.29
defaultWizForm.115.2.29
defaultWizForm.72.3.28
defaultWizForm.57.4.26
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
