UID = "95FBD3A4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.120.0.38
defaultWizForm.129.1.39
defaultWizForm.110.2.39
defaultWizForm.56.3.39
defaultWizForm.96.4.37
goto.3
label.1
defaultWizForm.120.0.38
defaultWizForm.114.1.39
defaultWizForm.66.2.36
defaultWizForm.133.3.37
defaultWizForm.93.4.38
goto.3
label.2
defaultWizForm.120.0.38
defaultWizForm.137.1.37
defaultWizForm.131.2.39
defaultWizForm.70.3.38
defaultWizForm.136.4.38
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
