UID = "B503A794"
Name = "5C9F1A31"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.u002s02m
defaultDeck.2.45.1
exit
endIf
ifNpcModifierHasValue.1
setModel.u002s02m
gotoRandomLabel.3.0
label.0
defaultWizForm.186.0.30
defaultWizForm.168.1.26
defaultWizForm.178.2.29
defaultWizForm.181.3.27
defaultWizForm.107.4.28
goto.3
label.1
defaultWizForm.186.0.30
defaultWizForm.174.1.31
defaultWizForm.91.2.28
defaultWizForm.151.3.26
defaultWizForm.117.4.28
goto.3
label.2
defaultWizForm.186.0.30
defaultWizForm.101.1.29
defaultWizForm.100.2.31
defaultWizForm.109.3.27
defaultWizForm.173.4.30
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
