UID = "6C605F04"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.152.0.44
defaultWizForm.90.1.42
defaultWizForm.122.2.44
defaultWizForm.126.3.41
defaultWizForm.202.4.43
goto.3
label.1
defaultWizForm.152.0.44
defaultWizForm.183.1.42
defaultWizForm.123.2.42
defaultWizForm.156.3.44
defaultWizForm.127.4.42
goto.3
label.2
defaultWizForm.152.0.44
defaultWizForm.124.1.43
defaultWizForm.164.2.43
defaultWizForm.128.3.44
defaultWizForm.99.4.43
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
