UID = "1F4D22A4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.143.0.19
defaultWizForm.13.1.17
defaultWizForm.112.2.16
defaultWizForm.20.3.16
defaultWizForm.30.4.19
goto.3
label.1
defaultWizForm.143.0.19
defaultWizForm.75.1.18
defaultWizForm.55.2.16
defaultWizForm.100.3.17
defaultWizForm.39.4.19
goto.3
label.2
defaultWizForm.143.0.19
defaultWizForm.111.1.17
defaultWizForm.56.2.18
defaultWizForm.15.3.17
defaultWizForm.26.4.17
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
