UID = "C5B14EB4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.u007s07m
defaultDeck.1.25.1
exit
endIf
ifNpcModifierHasValue.1
setModel.u007s07m
gotoRandomLabel.3.0
label.0
defaultWizForm.18.0.18
defaultWizForm.86.1.17
defaultWizForm.39.2.15
defaultWizForm.7.3.15
goto.3
label.1
defaultWizForm.18.0.18
defaultWizForm.84.1.18
defaultWizForm.16.2.17
defaultWizForm.12.3.15
goto.3
label.2
defaultWizForm.18.0.18
defaultWizForm.49.1.18
defaultWizForm.51.2.16
defaultWizForm.28.3.15
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
