UID = "7266B9B4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.u002s02m
defaultDeck.2.35.1
exit
endIf
ifNpcModifierHasValue.1
setModel.u002s02m
gotoRandomLabel.3.0
label.0
defaultWizForm.161.0.44
defaultWizForm.151.1.46
defaultWizForm.172.2.46
defaultWizForm.98.3.45
defaultWizForm.167.4.44
goto.3
label.1
defaultWizForm.161.0.44
defaultWizForm.149.1.46
defaultWizForm.178.2.46
defaultWizForm.148.3.44
defaultWizForm.119.4.43
goto.3
label.2
defaultWizForm.161.0.44
defaultWizForm.181.1.44
defaultWizForm.102.2.46
defaultWizForm.159.3.46
defaultWizForm.150.4.44
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
