UID = "0B68DE34"
Name = "97688F91"
TriggerScript = """
setCamera.1000
changeWaypoint.-1.-1
say.<Человеческим духом пахнет?>.0
waitForUser
setCamera.1006
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.g004s03m
defaultWizForm.10.0.5
defaultWizForm.54.1.10
defaultWizForm.53.2.8
endIf
ifNpcModifierHasValue.1
setModel.u003s03m
gotoRandomLabel.3.0
label.0
defaultWizForm.74.0.7
defaultWizForm.10.1.7
defaultWizForm.50.2.8
goto.3
label.1
defaultWizForm.74.0.7
defaultWizForm.88.1.7
defaultWizForm.52.2.8
goto.3
label.2
defaultWizForm.74.0.7
defaultWizForm.79.1.7
defaultWizForm.6.2.7
goto.3
label.3
endIf"""
UpdateScript = """
label.0
idle
ifPlayerIsClose.40
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
