UID = "A51A47A4"
Name = "97688F91"
TriggerScript = """
setCamera.1000
changeWaypoint.-1.-1
say.<Человеческим духом пахнет?>.0
waitForUser
setCamera.1006
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.g004s03m
defaultWizForm.10.0.5
defaultWizForm.54.1.10
defaultWizForm.53.2.8
endIf
ifNpcModifierHasValue.1
setModel.u003s03m
gotoRandomLabel.3.0
label.0
defaultWizForm.36.0.7
defaultWizForm.83.1.8
defaultWizForm.25.2.8
goto.3
label.1
defaultWizForm.36.0.7
defaultWizForm.37.1.9
defaultWizForm.21.2.7
goto.3
label.2
defaultWizForm.36.0.7
defaultWizForm.81.1.7
defaultWizForm.4.2.8
goto.3
label.3
endIf"""
UpdateScript = """
label.10
idle
ifPlayerIsClose.40
startPrelude
endIf
goto.10"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
