UID = "193341B4"
Name = "97688F91"
TriggerScript = """
setCamera.1000
changeWaypoint.-1.-1
say.<Человеческим духом пахнет?>.0
waitForUser
setCamera.1006
fight.-1.0"""
InitScript = """
setModel.u003s03m
gotoRandomLabel.3.0
label.0
defaultWizForm.61.0.9
defaultWizForm.48.1.9
defaultWizForm.41.2.7
goto.3
label.1
defaultWizForm.61.0.9
defaultWizForm.9.1.8
defaultWizForm.64.2.9
goto.3
label.2
defaultWizForm.61.0.9
defaultWizForm.69.1.8
defaultWizForm.32.2.8
goto.3
label.3"""
UpdateScript = """
label.10
idle
ifPlayerIsClose.40
startPrelude
endIf
goto.10"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
