UID = "205BCC34"
Name = "B18BDDB1"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.u002s02m
defaultDeck.1.25.1
exit
endIf
ifNpcModifierHasValue.1
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.46.0.25
defaultWizForm.54.1.26
defaultWizForm.78.2.24
defaultWizForm.14.3.27
defaultWizForm.23.4.24
goto.3
label.1
defaultWizForm.46.0.25
defaultWizForm.19.1.22
defaultWizForm.12.2.24
defaultWizForm.22.3.23
defaultWizForm.39.4.27
goto.3
label.2
defaultWizForm.46.0.25
defaultWizForm.73.1.25
defaultWizForm.60.2.26
defaultWizForm.35.3.24
defaultWizForm.18.4.25
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
