UID = "7266B9B4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.u002s02m
gotoRandomLabel.3.0
label.0
defaultWizForm.161.0.47
defaultWizForm.151.1.49
defaultWizForm.172.2.49
defaultWizForm.98.3.48
defaultWizForm.167.4.47
goto.3
label.1
defaultWizForm.161.0.47
defaultWizForm.149.1.49
defaultWizForm.178.2.49
defaultWizForm.148.3.47
defaultWizForm.119.4.46
goto.3
label.2
defaultWizForm.161.0.47
defaultWizForm.181.1.47
defaultWizForm.102.2.49
defaultWizForm.159.3.49
defaultWizForm.150.4.47
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
