UID = "B8F89614"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.200.0.48
defaultWizForm.103.1.47
defaultWizForm.99.2.46
defaultWizForm.105.3.48
defaultWizForm.90.4.49
goto.3
label.1
defaultWizForm.200.0.48
defaultWizForm.120.1.48
defaultWizForm.158.2.46
defaultWizForm.113.3.49
defaultWizForm.177.4.49
goto.3
label.2
defaultWizForm.200.0.48
defaultWizForm.119.1.49
defaultWizForm.203.2.47
defaultWizForm.176.3.48
defaultWizForm.159.4.49
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
