UID = "8C14D234"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.u002s02m
gotoRandomLabel.3.0
label.0
defaultWizForm.97.0.44
defaultWizForm.113.1.44
defaultWizForm.187.2.42
defaultWizForm.107.3.42
defaultWizForm.188.4.43
goto.3
label.1
defaultWizForm.97.0.44
defaultWizForm.206.1.43
defaultWizForm.160.2.41
defaultWizForm.116.3.42
defaultWizForm.157.4.41
goto.3
label.2
defaultWizForm.97.0.44
defaultWizForm.155.1.44
defaultWizForm.153.2.42
defaultWizForm.199.3.43
defaultWizForm.59.4.41
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
