UID = "6C605F04"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.132.0.44
defaultWizForm.121.1.42
defaultWizForm.141.2.44
defaultWizForm.82.3.41
defaultWizForm.93.4.43
goto.3
label.1
defaultWizForm.132.0.44
defaultWizForm.108.1.42
defaultWizForm.28.2.42
defaultWizForm.119.3.44
defaultWizForm.92.4.42
goto.3
label.2
defaultWizForm.132.0.44
defaultWizForm.30.1.43
defaultWizForm.115.2.43
defaultWizForm.49.3.44
defaultWizForm.111.4.43
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
