UID = "3C07D7A4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.96.0.40
defaultWizForm.118.1.39
defaultWizForm.106.2.41
defaultWizForm.99.3.38
defaultWizForm.93.4.39
goto.3
label.1
defaultWizForm.96.0.40
defaultWizForm.105.1.39
defaultWizForm.108.2.40
defaultWizForm.129.3.40
defaultWizForm.57.4.38
goto.3
label.2
defaultWizForm.96.0.40
defaultWizForm.95.1.41
defaultWizForm.130.2.39
defaultWizForm.147.3.40
defaultWizForm.148.4.38
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
