UID = "C5B14EB4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.u002s02m
gotoRandomLabel.3.0
label.0
defaultWizForm.87.0.18
defaultWizForm.48.1.17
defaultWizForm.87.2.15
defaultWizForm.86.3.15
defaultWizForm.13.4.18
goto.3
label.1
defaultWizForm.87.0.18
defaultWizForm.84.1.18
defaultWizForm.39.2.17
defaultWizForm.16.3.15
defaultWizForm.65.4.17
goto.3
label.2
defaultWizForm.87.0.18
defaultWizForm.61.1.18
defaultWizForm.67.2.16
defaultWizForm.2.3.15
defaultWizForm.49.4.18
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
