UID = "8C14D234"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.u002s02m
gotoRandomLabel.3.0
label.0
defaultWizForm.100.0.44
defaultWizForm.142.1.44
defaultWizForm.95.2.42
defaultWizForm.90.3.42
defaultWizForm.42.4.43
goto.3
label.1
defaultWizForm.100.0.44
defaultWizForm.54.1.43
defaultWizForm.138.2.41
defaultWizForm.118.3.42
defaultWizForm.131.4.41
goto.3
label.2
defaultWizForm.100.0.44
defaultWizForm.99.1.44
defaultWizForm.56.2.42
defaultWizForm.139.3.43
defaultWizForm.133.4.41
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
