UID = "B8F89614"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.b016s00m
defaultDeck.2.35.1
exit
endIf
ifNpcModifierHasValue.1
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.200.0.45
defaultWizForm.103.1.44
defaultWizForm.99.2.43
defaultWizForm.105.3.45
defaultWizForm.90.4.46
goto.3
label.1
defaultWizForm.200.0.45
defaultWizForm.120.1.45
defaultWizForm.158.2.43
defaultWizForm.113.3.46
defaultWizForm.177.4.46
goto.3
label.2
defaultWizForm.200.0.45
defaultWizForm.119.1.46
defaultWizForm.203.2.44
defaultWizForm.176.3.45
defaultWizForm.159.4.46
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
