UID = "0D55A334"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.12.0.12
defaultWizForm.1.1.10
defaultWizForm.62.2.12
defaultWizForm.67.3.12
goto.3
label.1
defaultWizForm.12.0.12
defaultWizForm.65.1.12
defaultWizForm.17.2.10
defaultWizForm.3.3.11
goto.3
label.2
defaultWizForm.12.0.12
defaultWizForm.87.1.11
defaultWizForm.47.2.10
defaultWizForm.53.3.10
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
