UID = "0F96CC34"
Name = "B18BDDB1"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.u008s08m
defaultDeck.1.15.1
exit
endIf
ifNpcModifierHasValue.1
setModel.u008s08m
gotoRandomLabel.3.0
label.0
defaultWizForm.72.0.24
defaultWizForm.1.1.22
defaultWizForm.62.2.23
defaultWizForm.67.3.24
defaultWizForm.67.4.24
goto.3
label.1
defaultWizForm.72.0.24
defaultWizForm.65.1.25
defaultWizForm.17.2.23
defaultWizForm.3.3.26
defaultWizForm.67.4.26
goto.3
label.2
defaultWizForm.72.0.24
defaultWizForm.87.1.24
defaultWizForm.47.2.23
defaultWizForm.53.3.26
defaultWizForm.67.4.23
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
