UID = "1F4D22A4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.b016s00m
defaultDeck.1.25.1
exit
endIf
ifNpcModifierHasValue.1
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.143.0.14
defaultWizForm.13.1.13
defaultWizForm.112.2.11
defaultWizForm.20.3.11
defaultWizForm.30.4.14
goto.3
label.1
defaultWizForm.143.0.14
defaultWizForm.75.1.13
defaultWizForm.55.2.11
defaultWizForm.100.3.12
defaultWizForm.39.4.14
goto.3
label.2
defaultWizForm.143.0.14
defaultWizForm.111.1.12
defaultWizForm.56.2.13
defaultWizForm.15.3.12
defaultWizForm.26.4.12
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
