UID = "6A91CC34"
Name = "B18BDDB1"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.b016s00m
defaultDeck.1.25.1
exit
endIf
ifNpcModifierHasValue.1
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.34.0.27
defaultWizForm.80.1.26
defaultWizForm.49.2.23
defaultWizForm.38.3.23
defaultWizForm.68.4.26
goto.3
label.1
defaultWizForm.34.0.27
defaultWizForm.55.1.24
defaultWizForm.81.2.23
defaultWizForm.44.3.27
defaultWizForm.29.4.25
goto.3
label.2
defaultWizForm.34.0.27
defaultWizForm.5.1.24
defaultWizForm.24.2.25
defaultWizForm.11.3.24
defaultWizForm.63.4.27
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
