UID = "1F4D22A4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.143.0.19
defaultWizForm.36.1.17
defaultWizForm.74.2.16
defaultWizForm.65.3.16
defaultWizForm.130.4.19
goto.3
label.1
defaultWizForm.143.0.19
defaultWizForm.20.1.18
defaultWizForm.64.2.16
defaultWizForm.158.3.17
defaultWizForm.54.4.19
goto.3
label.2
defaultWizForm.143.0.19
defaultWizForm.38.1.17
defaultWizForm.14.2.18
defaultWizForm.13.3.17
defaultWizForm.61.4.17
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
