UID = "69108AB4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.u002s02m
gotoRandomLabel.3.0
label.0
defaultWizForm.31.0.25
defaultWizForm.70.1.22
defaultWizForm.94.2.25
defaultWizForm.29.3.24
defaultWizForm.16.4.24
goto.3
label.1
defaultWizForm.31.0.25
defaultWizForm.24.1.21
defaultWizForm.87.2.23
defaultWizForm.96.3.22
defaultWizForm.27.4.23
goto.3
label.2
defaultWizForm.31.0.25
defaultWizForm.92.1.24
defaultWizForm.68.2.23
defaultWizForm.45.3.23
defaultWizForm.44.4.26
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
