UID = "5A2476B4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.u002s02m
defaultDeck.2.35.1
exit
endIf
ifNpcModifierHasValue.1
setModel.u002s02m
gotoRandomLabel.3.0
label.0
defaultWizForm.48.0.18
defaultWizForm.19.1.16
defaultWizForm.28.2.17
defaultWizForm.35.3.15
defaultWizForm.77.4.19
goto.3
label.1
defaultWizForm.48.0.18
defaultWizForm.87.1.19
defaultWizForm.14.2.18
defaultWizForm.2.3.19
defaultWizForm.85.4.17
goto.3
label.2
defaultWizForm.48.0.18
defaultWizForm.73.1.18
defaultWizForm.8.2.17
defaultWizForm.43.3.16
defaultWizForm.54.4.17
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
