UID = "59FA5CB4"
Name = "B18BDDB1"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.163.0.19
defaultWizForm.155.1.17
defaultWizForm.165.2.16
defaultWizForm.187.3.16
defaultWizForm.205.4.19
goto.3
label.1
defaultWizForm.163.0.19
defaultWizForm.90.1.18
defaultWizForm.176.2.16
defaultWizForm.175.3.17
defaultWizForm.156.4.19
goto.3
label.2
defaultWizForm.163.0.19
defaultWizForm.153.1.17
defaultWizForm.179.2.18
defaultWizForm.172.3.17
defaultWizForm.182.4.17
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
