UID = "1E12D3B4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
ifNpcModifierHasValue.0
setModel.b016s00m
defaultDeck.2.35.1
exit
endIf
ifNpcModifierHasValue.1
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.22.0.24
defaultWizForm.32.1.21
defaultWizForm.67.2.22
defaultWizForm.39.3.25
defaultWizForm.33.4.21
goto.3
label.1
defaultWizForm.22.0.24
defaultWizForm.45.1.26
defaultWizForm.38.2.22
defaultWizForm.50.3.24
defaultWizForm.12.4.24
goto.3
label.2
defaultWizForm.22.0.24
defaultWizForm.54.1.23
defaultWizForm.58.2.26
defaultWizForm.65.3.21
defaultWizForm.18.4.26
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
