UID = "86DB0D34"
Name = "B18BDDB1"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.204.0.19
defaultWizForm.169.1.17
defaultWizForm.203.2.16
defaultWizForm.161.3.16
defaultWizForm.202.4.19
goto.3
label.1
defaultWizForm.204.0.19
defaultWizForm.150.1.18
defaultWizForm.177.2.16
defaultWizForm.171.3.17
defaultWizForm.154.4.19
goto.3
label.2
defaultWizForm.204.0.19
defaultWizForm.108.1.17
defaultWizForm.180.2.18
defaultWizForm.202.3.17
defaultWizForm.185.4.17
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
