UID = "84FAE734"
Name = "7B2D8F91"
TriggerScript = """
ifPlayerHasCards.1.0.102
removePlayerCards.1.0.102
deployNpcAtTrigger.44.0
exit
else
deployNpcAtTrigger.44.0
exit
"""
InitScript = """
setNpcType.4
setCollision.0"""
UpdateScript = """
label.0
ifPlayerIsClose.11
startPrelude
endIf
idle
goto.0"""
