UID = "1E12D3B4"
Name = "97688F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1006
say.<Человеческим духом пахнет?>.0
waitForUser
fight.-1.0"""
InitScript = """
setModel.b016s00m
gotoRandomLabel.3.0
label.0
defaultWizForm.122.0.33
defaultWizForm.57.1.31
defaultWizForm.104.2.30
defaultWizForm.64.3.30
defaultWizForm.116.4.33
goto.3
label.1
defaultWizForm.122.0.33
defaultWizForm.126.1.32
defaultWizForm.95.2.30
defaultWizForm.13.3.31
defaultWizForm.38.4.33
goto.3
label.2
defaultWizForm.122.0.33
defaultWizForm.121.2.32
defaultWizForm.28.3.31
defaultWizForm.5.4.31
goto.3
label.3"""
UpdateScript = """
label.0
lookAtPlayer.10.1
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
givePlayerCards.1.0.106
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
