UID = "8C12D134"
Name = "389D7EB1"
TriggerScript = """
deployNpcAtTrigger.56.1
setCamera.3001
playAnimation.13.-1
say.<...>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Горсть Пыльцы фей} (х5)!>
waitForUser
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Горсть Пыльцы фей} (х6)!>
waitForUser
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Малый Лечебный Бальзам} (х2)!>
waitForUser
setTalkLabels.10.11.1
talk.<Ты находишь внутри {4*Малый Лечебный Бальзам} (х3)!>
waitForUser
label.10
setCamera.1006
fight.-1.0
exit
label.11
setTalkLabels.-1.-1.0
talk.<Ты находишь внутри {4*Малый Лечебный Бальзам} (х4)!>
waitForUser
exit"""
InitScript = """
setModel.b012s00m
defaultWizForm.47.0.21
defaultWizForm.70.1.22
defaultWizForm.41.2.24
defaultWizForm.39.3.23
defaultWizForm.12.4.22"""
UpdateScript = """
label.0
lookAtPlayer.2.1
ifPlayerIsClose.4
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.3001
playAnimation.13.-1
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Средний Лечебный Бальзам} (х2)!>
waitForUser
setTalkLabels.-1.-1.0
talk.<Ты находишь внутри {4*Средний Лечебный Бальзам} (х3)!>
waitForUser
givePlayerCards.1.0.107
changeWaypoint.7.6
changeWaypoint.6.5
changeWaypoint.5.4
changeWaypoint.4.3
removeNpc"""
VictoriousScript = "killPlayer"
