UID = "B263B5F1"
Name = "23D47EB1"
TriggerScript = """
deployNpcAtTrigger.65.1
setCamera.3000
playAnimation.13.-1
say.<Ты открываешь {4*Загадочную Шкатулку}...>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х9)!>
waitForUser
setTalkLabels.10.11.1
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х10)!>
waitForUser
label.10
setCamera.1006
fight.-1.0
exit
label.11
setTalkLabels.-1.-1.0
talk.<Ты находишь внутри {4*Серебряный Шар} (х1)!>
waitForUser
exit"""
InitScript = """
setModel.g204s20m
defaultWizForm.1.0.53
defaultWizForm.11.1.52
defaultWizForm.11.2.50
defaultWizForm.11.3.51"""
UpdateScript = """
label.0
lookAtPlayer.1.1
ifPlayerIsClose.2
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.3000
setTalkLabels.-1.-1.0
talk.<Ты находишь внутри {4*Щепотка Пыльцы фей} (х8)!>
waitForUser
changeWaypoint.30.31
setCamera.3004
changeWaypoint.31.32
changeWaypoint.32.33
removeNpc"""
