name: "Build Pre-Release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre-Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"

      - name: "Setup feezfuzz"
        run: "python -m pip install feezfuzz"

      - name: "Validate using feezfuzz"
        run: "python -m feezfuzz --test"

      - name: "Cleanup after validation"
        run: "rm -rf /build"

      - name: "Build using feezfuzz"
        run: "python -m feezfuzz --fbs"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/_fb0x05.fbs
            build/_fb0x06.fbs
