UID = "9023B4A4"
Name = "79110B91"
#Worgot (0), Phoe (37), Tyberry (18), Guana (73), Mykory (40)
#From 19 to 16
InitScript = """
setNpcType.3
gotoRandomLabel.20.0
label.0
defaultWizForm.0.0.20
goto.20
label.1
defaultWizForm.37.0.20
goto.20
label.2
defaultWizForm.18.0.20
goto.20
label.3
defaultWizForm.73.0.20
goto.20
label.4
defaultWizForm.40.0.20
goto.20
label.5
defaultWizForm.0.0.19
goto.20
label.6
defaultWizForm.37.0.19
goto.20
label.7
defaultWizForm.18.0.19
goto.20
label.8
defaultWizForm.73.0.19
goto.20
label.9
defaultWizForm.40.0.19
goto.20
label.10
defaultWizForm.0.0.18
goto.20
label.11
defaultWizForm.37.0.18
goto.20
label.12
defaultWizForm.18.0.18
goto.20
label.13
defaultWizForm.73.0.18
goto.20
label.14
defaultWizForm.40.0.18
goto.20
label.15
defaultWizForm.0.0.17
goto.20
label.16
defaultWizForm.37.0.17
goto.20
label.17
defaultWizForm.18.0.17
goto.20
label.18
defaultWizForm.73.0.17
goto.20
label.19
defaultWizForm.40.0.17
goto.20
label.20"""
