UID = "390F9484"
Name = "46FFDE21"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Коллекционер фей.>.0
waitForUser
label.0
say.<
    У меня огромный выбор {4*активных} и {4*пассивных} заклинаний.
    Чем могу помочь?
>.1
choice.3.<Диалог>
choice.2.<Торговля>
choice.1.<До встречи>
waitForUser
label.3
setTalkLabels.-1.-1.2
talk.<
    Это довольно просто.
    У меня большое количество различных заклинаний для твоих фей.
    Но я их не просто продаю...
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Для торговли со мной тебе необходимо получить {4*специальные камеи}.
    Ты можешь добыть их, если выиграешь в {4*дуэли фей} с другим {4*Коллекционером} или {4*Тёмным Эльфом}.
    Но будь внимательна, каждый торговец будет спрашивать разное количество камей, и чем сильнее заклинания, тем больше тебе их потребуется.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Ты можешь найти торговцев в основных крупных поселениях - {4*Тиралине}, {4*Данморе} и {4*Монагаме} - а также в доме {4*Руфуса, Хранителя Пикси из Эндевы}.
    Также в мире существует особый {4*четырёхлистный клевер}, знак самых выдающихся {4*Коллекционеров}, и если ты сможешь заполучить один из них, то это значительно упростит торговлю с нами, хе-хе.
>
waitForUser
goto.0
label.2
ifPlayerHasCards.1.0.107
say.<
    У меня огромный выбор {4*активных} и {4*пассивных} заклинаний.
    Чем могу помочь?
>.1
choice.8.<Камень>
choice.7.<Огонь>
choice.6.<Металл>
choice.5.<Назад>
waitForUser
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*одну Камею Коллекционера}, чтобы доказать, что ты являешься {4*Коллекционером}.
    Только после этого я смогу предложить тебе какие-либо заклинания.
>
waitForUser
goto.0
label.8
setupGambling.1.1.33
setupGambling.1.1.34
setupGambling.1.1.131
setupGambling.1.1.130
setupGambling.1.1.32
setupGambling.1.1.31
setupGambling.1.1.30
setupGambling.1.1.59
setupGambling.1.1.92
setupGambling.1.1.93
setupGambling.1.1.94
setupGambling.1.1.141
setupGambling.1.1.91
setupGambling.1.1.90
setupGambling.15.3.0
waitForUser
goto.1
label.7
ifPlayerHasCards.3.0.107
goto.10
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*три Камеи Коллекционера и три Камеи Тёмных Эльфов}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.10
ifPlayerHasCards.3.0.106
setupGambling.1.1.103
setupGambling.1.1.102
setupGambling.1.1.104
setupGambling.1.1.101
setupGambling.1.1.100
setupGambling.1.1.40
setupGambling.1.1.44
setupGambling.1.1.41
setupGambling.1.1.42
setupGambling.1.1.43
setupGambling.10.3.0
waitForUser
goto.1
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*три Камеи Коллекционера и три Камеи Тёмных Эльфов}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.6
ifPlayerHasCards.6.0.106
setupGambling.1.1.59
setupGambling.1.1.58
setupGambling.1.1.57
setupGambling.1.1.56
setupGambling.1.1.55
setupGambling.1.1.118
setupGambling.1.1.119
setupGambling.1.1.116
setupGambling.1.1.115
setupGambling.1.1.117
setupGambling.10.3.0
waitForUser
goto.1
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*шесть Камей Тёмных Эльфов}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.5
goto.0
label.1
exit"""
InitScript = """
setCollision.0
setModel.w002s02m"""
UpdateScript = "lookAtPlayer.0.1"
