UID = "1EB60484"
Name = "342ACD21"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Коллекционер фей.>.0
waitForUser
label.0
say.<
    У меня огромный выбор {4*активных} и {4*пассивных} заклинаний.
    Чем могу помочь?
>.1
choice.3.<Диалог>
choice.2.<Торговля>
choice.1.<До встречи>
waitForUser
label.3
say.<Что ты хочешь узнать?>.1
choice.103.<Где можно найти других торговцев?>
choice.102.<Где мне добыть Камеи?>
choice.101.<Как я могу получить Четырёхлистный Клевер?>
choice.100.<Назад>
waitForUser
label.103
setTalkLabels.-1.-1.2
talk.<
    Ты можешь найти других торговцев в основных крупных поселениях — {4*Тиралине}, {4*Данморе} и {4*Монагаме}.
	Но будь осторожна, они все требуют разное количество {4*Камей} для торговли с ними.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    В {4*Тиралине}, городе {4*эльфов}, ты можешь приобрести заклинания {4*Природы, Воздуха и Света}.
	А в {4*Данморе}, деревне {4*Болотных Гоблинов}, ты можешь найти заклинания {4*Воды, Пси и Льда}.
	Наконец, в {4*Монагаме}, деревне {4*гномов}, ты можешь купить заклинания {4*Хаоса, Огня и Металла}.
>
waitForUser
goto.3
label.102
setTalkLabels.-1.-1.2
talk.<
    Это не так сложно, правда.
	Ты можешь получить {4*Камеи Коллекционера} после победы над любым {4*Коллекционером}.
	Обычно их можно найти в {4*деревнях и городах}, но более опытные {4*Коллекционеры} зачастую путешествуют по {4*Занзаре} в поисках новых фей...
	или противников.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    До недавнего времени найти {4*Тёмных Эльфов} было крайне тяжелой задачей, но теперь многое изменилось.
	Ты можешь наткнуться на них, путешествуя по всей {4*Занзаре}, — но если ты хочешь моего совета...
	Просто поброди в окрестностях {4*Данмора} или {4*Монагама}.
	Или ты можешь отправиться напрямую в их дом, в {4*Царство Тьмы}, но мало кто знает, как именно туда попасть.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Так или иначе, но {4*Тёмные Эльфы} гораздо более опасные противники, чем большинство {4*Коллекционеров}.
	Если тебя заметит один из {4*Тёмных Эльфов}, то сражения будет не избежать.
	Поэтому прежде чем вызвать одного из них на дуэль, лучше набраться опыта в сражениях с другими {4*Коллекционерами}.
>
waitForUser
goto.3
label.101
setTalkLabels.-1.-1.0
talk.<
    Если ты действительно готова посвятить свою жизнь {4*дуэлям фей}, то награда обязательно найдёт свой путь к тебе.
	Путешествуй по {4*Занзаре}, знакомься с другими {4*Коллекционерами} и выигрывай в дуэлях с {4*Тёмными Эльфами}...
	И в один день ты сможешь получить {4*Четырёхлистный Клевер}.
>
waitForUser
goto.3
label.100
goto.0
label.2
ifPlayerHasCards.1.0.210
say.<
    У меня огромный выбор {4*активных} и {4*пассивных} заклинаний.
    Чем могу помочь?
>.1
choice.12.<Вода>
choice.11.<Пси>
choice.10.<Лёд>
choice.9.<Назад>
waitForUser
else
say.<
    У меня огромный выбор {4*активных} и {4*пассивных} заклинаний.
    Чем могу помочь?
>.1
choice.8.<Вода>
choice.7.<Пси>
choice.6.<Лёд>
choice.5.<Назад>
waitForUser
label.12
ifPlayerHasCards.1.0.107
setupGambling.1.1.10
setupGambling.1.1.11
setupGambling.1.1.12
setupGambling.1.1.13
setupGambling.1.1.14
setupGambling.1.1.70
setupGambling.1.1.71
setupGambling.1.1.72
setupGambling.1.1.73
setupGambling.1.1.74
setupGambling.15.3.0
waitForUser
goto.1
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*одну Камею Коллекционера}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.11
ifPlayerHasCards.3.0.107
setupGambling.1.1.25
setupGambling.1.1.26
setupGambling.1.1.27
setupGambling.1.1.28
setupGambling.1.1.29
setupGambling.1.1.85
setupGambling.1.1.86
setupGambling.1.1.87
setupGambling.1.1.88
setupGambling.1.1.89
setupGambling.15.3.0
waitForUser
goto.1
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*три Камеи Коллекционера}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.10
ifPlayerHasCards.6.0.106
goto.51
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*три Камеи Коллекционера и шесть Камей Тёмных Эльфов}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.51
ifPlayerHasCards.3.0.107
setupGambling.1.1.35
setupGambling.1.1.36
setupGambling.1.1.37
setupGambling.1.1.38
setupGambling.1.1.39
setupGambling.1.1.95
setupGambling.1.1.96
setupGambling.1.1.97
setupGambling.1.1.98
setupGambling.1.1.99
setupGambling.15.3.0
waitForUser
goto.1
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*три Камеи Коллекционера и шесть Камей Тёмных Эльфов}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.9
goto.0
label.8
setupGambling.1.1.10
setupGambling.1.1.11
setupGambling.1.1.12
setupGambling.1.1.13
setupGambling.1.1.14
setupGambling.1.1.70
setupGambling.1.1.71
setupGambling.1.1.72
setupGambling.1.1.73
setupGambling.1.1.74
setupGambling.10.3.0
waitForUser
goto.1
label.7
ifPlayerHasCards.3.0.107
setupGambling.1.1.25
setupGambling.1.1.26
setupGambling.1.1.27
setupGambling.1.1.28
setupGambling.1.1.29
setupGambling.1.1.85
setupGambling.1.1.86
setupGambling.1.1.87
setupGambling.1.1.88
setupGambling.1.1.89
setupGambling.10.3.0
waitForUser
goto.1
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*три Камеи Коллекционера}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.6
ifPlayerHasCards.3.0.106
goto.50
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*три Камеи Коллекционера и три Камеи Тёмных Эльфов}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.50
ifPlayerHasCards.3.0.107
setupGambling.1.1.35
setupGambling.1.1.36
setupGambling.1.1.37
setupGambling.1.1.38
setupGambling.1.1.39
setupGambling.1.1.95
setupGambling.1.1.96
setupGambling.1.1.97
setupGambling.1.1.98
setupGambling.1.1.99
setupGambling.10.3.0
waitForUser
goto.1
else
setTalkLabels.-1.-1.0
talk.<
    Принеси мне {4*три Камеи Коллекционера и три Камеи Тёмных Эльфов}, чтобы доказать, что ты являешься опытным {4*Коллекционером}.
    Только после этого я смогу предложить тебе более сильные заклинания.
>
waitForUser
goto.0
label.5
goto.0
label.1
exit"""
InitScript = """
setCollision.0
setModel.w002s02m"""
UpdateScript = "lookAtPlayer.0.1"
